### ISSUE TITLE
database "postgres" does not exist

### ISSUE THREAD

**Issue by JulyYin** [goharbor/harbor-helm#100]
![image](https://user-images.githubusercontent.com/8434933/49211269-24d34800-f3fa-11e8-9bc0-b77cf4aec6e3.png)

**Comment by JulyYin** [comment]
I am using version master

**Comment by ywk253100** [comment]
What image are you using? Did you change the database image?

**Comment by JulyYin** [comment]
> What image are you using? Did you change the database image?

没有修改过镜像，镜像版本是dev的

**Comment by ywk253100** [comment]
Closing this issue, feel free to reopen it if the issue still exists.
