### ISSUE TITLE
Overriding harborAdminPassword isn't honored

### ISSUE THREAD

**Issue by jmaaks** [goharbor/harbor-helm#1000]
When I specify a new value for harborAdminPassword it isn't honored -- accessing Harbor via the UI still requires using the "Harbor12345" default password.

I'm specifying it on the command line (along with other overrides of values.yaml) as follows:

--set harborAdminPassword="Admin123" \

**Comment by ninjadq** [comment]
this value only works when you first time installs Harbor.

**Comment by jmaaks** [comment]
Why is this, and where can the previous configuration be cleared out?  

It appears this value is stored in the harbor-harbor-core secret under HARBOR_ADMIN_PASSWORD, and that secret is deleted when I run a helm delete on the installation.

**Comment by jmaaks** [comment]
OK, silly error on my part.  It appears harbor-core only reads that environment variable the first time it runs, then it's stored in the back-end database.  If you re-install Harbor, but keep the existing back-end storage/databases, then that value is still there and won't be read again.

**Comment by sathieu** [comment]
See the following KB to reset the pwd: https://kb.vmware.com/s/article/76289

**Comment by timbrown5** [comment]
+1. Is it possible to add an `init` step that sets the password to `HARBOR_ADMIN_PASSWORD` each time a pod is deployed. Seems like that would allow updating the password in the K8 config would work?

**Comment by thiDucTran** [comment]
wondering if the `bitnami` chart has this issue or would the harbor operator has this issue
