### ISSUE TITLE
How to generate the index-cache.yaml file of chartmuseum

### ISSUE THREAD

**Issue by CharesLee** [goharbor/harbor-helm#1002]
After I deleted the index-cache.yaml in my chart directory, I restarted my chartmuseum and found that index-cache.yaml was not regenerated, but it is good to access the chart file of the project through harborUI and can also be downloaded

helm install harbor version 2.2.1

**Comment by ninjadq** [comment]
Could you provide more context related to this issue. like logs and env info

**Comment by CharesLee** [comment]
Thank you, I have found the corresponding method. After deleting the corresponding index-cache.yaml file under the chart project, clear the redis data.
kubectl exec -it harbor-harbor-redis-0 -- redis-cli flushall
