### ISSUE TITLE
Database Pod doesn't start on NFS backed storage

### ISSUE THREAD

**Issue by cferber** [goharbor/harbor-helm#1010]
I configured a PV for NFS backed storage and related PVC. Modified values.yaml to use the mentioned PVC and related storage class for the database.
Database container hangs in init stage with below error message. The same configuration works fine with local storage.

Normal   Scheduled    107s                default-scheduler  Successfully assigned default/harbortest-database-0 to kubepht02
  Warning  FailedMount  37s (x8 over 101s)  kubelet            MountVolume.SetUp failed for volume "harbornfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o hard 172.16.111.73:/data /var/lib/kubelet/pods/67785706-7cd9-4599-8413-1ea2c96a73a0/volumes/kubernetes.io~nfs/harbornfs
Output: mount: /var/lib/kubelet/pods/67785706-7cd9-4599-8413-1ea2c96a73a0/volumes/kubernetes.io~nfs/harbornfs: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.

**Comment by zyyw** [comment]
how to you provision the NFS? could it be the NFS driver issue?
