### ISSUE TITLE
v1.7.1 is not available through the Helm repo

### ISSUE THREAD

**Issue by immanuelfodor** [goharbor/harbor-helm#1025]
It seems v1.7.1 is still not available in the Helm repo. It is usually there soon after a new release is published on Github.

```bash
helm repo add harbor https://helm.goharbor.io
helm repo update
helm pull harbor/harbor
# 48691 Jul 27 19:50 harbor-1.7.0.tgz
```

Related to https://github.com/goharbor/harbor-helm/pull/1022 and https://github.com/goharbor/harbor-helm/releases/tag/1.7.1

**Comment by ninjadq** [comment]
Are you still can not download it?

**Comment by immanuelfodor** [comment]
I've just tried it again and it's working now, thanks for the update!
