### ISSUE TITLE
configure imageChartStorage s3 find this  nil pointer error

### ISSUE THREAD

**Issue by grexkin** [goharbor/harbor-helm#1027]
helm version: v3.6.3
kubernetes: v1.21.2
helm-harbor: 2.3.0
Error: template: harbor/templates/registry/registry-dpl.yaml:100:31: executing "harbor/templates/registry/registry-dpl.yaml" at <.Values.persistence.imageChartStorage.filesystem.rootdirectory>: nil pointer evaluating interface {}.rootdirectory

**Comment by ninjadq** [comment]
Could provide more context and logs for this error?
