### ISSUE TITLE
Some questions about my Traefik-ingress-controller 

### ISSUE THREAD

**Issue by tianxuanling** [goharbor/harbor-helm#103]
I deployed the Traefik in my K8S cluster,But when I deploy this harbor with helm,The default domain URL (https://core.harbor.domain) is  connection refused,But all of my pods,services and ingress are successfull running.
But I create another one traefik ingress xxx.xxx.xxx in http on traefik,I visit the URL http://xxx.xxx.xxx successfull.
Why the default URL is connection refused (https://core.harbor.domain)

Any advice?

**Comment by pedroparraortega** [comment]
> I deployed the Traefik in my K8S cluster,But when I deploy this harbor with helm,The default domain URL (https://core.harbor.domain) is connection refused,But all of my pods,services and ingress are successfull running.
> But I create another one traefik ingress xxx.xxx.xxx in http on traefik,I visit the URL http://xxx.xxx.xxx successfull.
> Why the default URL is connection refused (https://core.harbor.domain)
> 
> Any advice?

That is the example value for your domain. You need to modify it for the one which apply to your cluster

**Comment by aaahrens** [comment]
^
