### ISSUE TITLE
Metrics are not exposed when enabling `metrics.enabled: true`

### ISSUE THREAD

**Issue by steffenb91** [goharbor/harbor-helm#1031]
I couldn´t get the metrics exposed for harbor, maybe someone here can help me (could be a bug as well?)

After setting `metrics.enabled: true`, when calling https://<harbor_host>/metrics i get an error 404 and am redirected to the main portal page of harbor. So according to the harbor docs the metrics should be available under `/metrics` (https://goharbor.io/docs/2.3.0/administration/metrics/). This did not work for me.

I then tried adding a new route to the harbor-ingress to redirect to the harbor-exporter service, but that did not work, since the harbor-exporter has his metrics exposed on the path /metrics per default. result: the added ingress route redirected me to the index page of the harbor-exporter, containing only a link to https://<harbor_host>/metrics. (which is incorrect in this context)

what helped was to instruct the ingress to rewrite the url (with the annotation nginx.ingress.kubernetes.io/rewrite-target: /$2) . but this annotation will of course break the routing for the rest of the application. so only possible options that worked for me was to specify a completely new ingress rule with a different host, and pointing to harbor-exporter/metrics/metrics:

```kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/app-root: /metrics/metrics
  name: harbor-ingress-exporter
spec:
  rules:
  - host: <HARBOR_HOST_METRICS>
    http:
      paths:
      - backend:
          service:
            name: harbor-exporter
            port:
              number: 8001
        path: /metrics(/|$)(.*)
        pathType: Prefix
```

please tell me, were i somewhere heading in the wrong direction? if so, additional documentation about how to access exposed metrics would be fine!

**Comment by ninjadq** [comment]
Currently, we only can collector metrics via service monitor

**Comment by hrr888** [comment]
According to this: https://github.com/goharbor/harbor-helm/blob/32e0df98a4718f074fc4fe3d39a89fc34c46defe/templates/core/core-dpl.yaml#L98 metric port is not exposed in pod. So service monitor will not work either.

**Comment by zyyw** [comment]
https://github.com/goharbor/harbor-helm/issues/959#issuecomment-957347560

it's been added to service, so it must be added to the pod as well

**Comment by zyyw** [comment]
it's by design to use service monitor to collect metrics data. if you want get metrics data out of cluster 
```when calling https://<harbor_host>/metrics i get an error 404```, you may need to customize service monitor.
And if you don't want to service monitor to collect metrics data, there may be security concerns.

**Comment by ottramst** [comment]
Why was this issue closed? There is no `http-metrics` port with the assigned value of 8001 on the harbor-core Pod when `metrics.enabled: true`
