### ISSUE TITLE
unable to download helm chart from harbor

### ISSUE THREAD

**Issue by obeyler** [goharbor/harbor-helm#1034]
I upload into test project an helm chart `generate-secret-0.1.6.tgz`
I can check inside harbor-chartmuseum pod that the file is well uploaded:
```
ls /chart_storage/test/
generate-secret-0.1.6.tgz
```
I can see everything inside harbor about this chart (value, read.md)
```
helm repo add te https://harbor.XXXX/chartrepo/test  --insecure-skip-tls-verify
helm search repo te
NAME               	CHART VERSION	APP VERSION	DESCRIPTION                                       
te/generate-secret 	0.1.6        	1.0.0      	A Helm chart for Kubernetes 
```
If I call api to retrieve affected label to this chart it works fine:
```
curl https://harbor.XXXX/api/v2.0/chartrepo/test/charts/generate-secret/0.1.6/labels
[
  {
    "id": 1,
    "name": "internal",
    "description": "",
    "color": "#9B0D54",
    "scope": "g",
    "project_id": 0,
    "creation_time": "2021-08-19T15:50:21.964915Z",
    "update_time": "2021-08-19T15:50:21.964916Z",
    "deleted": false
  }
]
```

but why when I try to download the helm chart from the harbor UI it always failed with HTTP404 error
`Http failure response for https://harbor.XXXX/api/chartrepo/test/charts/generate-secret-0.1.6.tgz`

Harbor-helm chart version  1.7.1
any idea who can cause this pb? 
no log except 404 :-(

**Comment by obeyler** [comment]
I also try to replace local storage by s3. 
I can see on my bucket all file, but I still not enable to download chart by harbor ui

**Comment by obeyler** [comment]
The downloaf url given by harbor api is different from the downlod url used by ui: 
```
https://harbor.XXXX/chartrepo/test/charts/generate-secret-0.1.6.tgz
```
 versus
```
https://harbor.XXXX/api/chartrepo/test/charts/generate-secret-0.1.6.tgz
```

**Comment by obeyler** [comment]
see https://github.com/goharbor/harbor/issues/15228

**Comment by ninjadq** [comment]
hi, this issue is fixed in the harbor. we will deliver it in harbor-helm in the next patch release

**Comment by zyyw** [comment]
close it, as it is resolve in harbor 2.3.3.
reference: https://github.com/goharbor/harbor/issues/15737
