### ISSUE TITLE
Not able to push image to the Registry - Retrying after transferred the data (for several layers)

### ISSUE THREAD

**Issue by invy** [goharbor/harbor-helm#1040]
I have similar problem to the one described in #578 
I'm trying to configure Harbor in HA cluster.

I've specified FSGID for nfs provisioner (this one: https://github.com/openebs/dynamic-nfs-
provisioner/blob/develop/docs/intro.md ) to be 10000. This fsGroup/runAsUser are specified in securityContext for the registry pod. But push still returns with error code 500, except in my case upload process finishes and I'm able to see the transferred data under /storage, when I login in one of the replicas containers.

I suppose it's similar problem, but I'm not able to find what causes my error.

**Comment by ninjadq** [comment]
#578 is caused by a permission issue, in some provisioned it may not compatible with securityContext, you need to fix the permission by yourself

**Comment by invy** [comment]
@ninjadq I'm not sure now whether it's actually permission problem. It could be that something else in my cluster is misbehaving.
I'm getting now sporadic retries on push, but in the end I'm able to push an image. So I guess, permissions is not an issue for me anymore. Could you point me in the right direction? Not that my HA redis oder HA postgres setup is broken.

**Comment by invy** [comment]
Ok, I think my problem is not correctly installed HA redis. Are there any recommendations from Harbor regarding how HA Redis should be configured?
