### ISSUE TITLE
Extend Chart to Support additional Trivy Storage on Redis

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-helm#1042]
Trivy supports using Redis as a cache storage option. See https://aquasecurity.github.io/trivy/v0.19.2/vulnerability/examples/cache/

This Helm chart should support similar to the jobservice (joblogs) configuration.

**Comment by ninjadq** [comment]
the harbor didn't support this feature currently, you can open a issue on harbor repo
