### ISSUE TITLE
Frequently restart the harbor-clair container

### ISSUE THREAD

**Issue by lluqqikkai** [goharbor/harbor-helm#1046]
Log：error: a container name must be specified for pod harbor-harbor-clair-6f6f86799-bxfxj, choose one of: [clair adapter]
event：Warning  BackOff  9m55s (x1230 over 3d23h)  kubelet, “IP”  Back-off restarting failed containe
Please advise thanks

**Comment by ninjadq** [comment]
what version of the harbor are you running? currently, the Clair is not officially supported by harbor, you can try trivy instead
