### ISSUE TITLE
Doesn't create harbor service when type is ingress

### ISSUE THREAD

**Issue by rlewkowicz-rcd** [goharbor/harbor-helm#1047]
I have this deployed in 2 different environments. One with istio routing to cluster ip harbor service. This works great. With type ingress in another environment, I don't get a harbor service at all. I get harbor core, but I can't really tell what I'm supposed to be doing with it. It listens, but throws a 404 for everything.

**Comment by ninjadq** [comment]
what kind of ingress controller are you using? could you provide the logs of the ingress controller, harbor-core, and other related pod ?
