### ISSUE TITLE
Which deployments make use of storage backends?

### ISSUE THREAD

**Issue by darend** [goharbor/harbor-helm#105]
I am looking at configuring harbor to use AWS S3 and RDSfor storage. Id like to narrow down which pods actually require access to these resources in order manage permissions, but its not clear which ones need it. 

Is there a list of which pods make use of storage so that I could manage access?

**Comment by darend** [comment]
Looking at [docs/High Availability.md](https://github.com/goharbor/harbor-helm/blob/b5b422f91b8a574762ac980737a65fb2690bc98e/docs/High%20Availability.md#configuration) I believe I can infer that the access is only required by the following pods:

- chartmuseum
- registry
- jobservice

**Comment by ywk253100** [comment]
Only registry and chartmuseum are supported to used s3 directly to store images and charts.

**Comment by darend** [comment]
Thanks @ywk253100 

Is the plan to keep jobservice using a PV?

**Comment by ywk253100** [comment]
The job logs can be stored in PV or database, this can be configured.

**Comment by darend** [comment]
Thanks, closing
