### ISSUE TITLE
Harbor connection limit

### ISSUE THREAD

**Issue by WenwuPeng** [goharbor/harbor-helm#1052]
Hi All, 

There are two questions about Harbor connection limit, in the https://github.com/goharbor/harbor/wiki/Harbor-FAQs#modify-the-max-connections-of-database 
1. suggests deleting the harbor database pod after making the change. Is this recommended to do on a live env which has lot of images and charts in harbor repo?
2  the 1000 is the recommendation from Harbor team then can propose to customer?

**Comment by sunielm7** [comment]
ny updates on this? I found multiple issues with the documentation for this change. This is the cmdlet to be run for increasing the max connections for harbor database.
 
kubectl -n $NAMESPACE exec $POD_NAME -- cat /var/lib/postgresql/data/postgresql.conf | sed 's/max_connections = .*/max_connections = 1000/g' | kubectl -n $NAMESPACE exec $POD_NAME -i -- tee /var/lib/postgresql/data/postgresql.conf
 
Here, ‘sed’ editor doesn’t exist on postgres container with harbor 1.10.2 version. Second part of the command which reads empty standard in and writes to postgresql.conf which makes the file content void. This will result in issues when re-starting harbor pod. Please fix the documentation and provide correct steps to modify the max connections as early as possible.
 
Upgrading harbor to a higher version will be a long term solution but Dish won’t be able to do that now. Hence, we need the short term solution to fix the connection limit on 1.10.2 for this customer.

**Comment by ywk253100** [comment]
@WenwuPeng The data of the database is persistent in the PV, so just deleting the database pod will not cause data loss.
For the `1000`, it's just the default value, and it should be changed according to the usage and deployment
BTW, please open issues on the main repository of harbor https://github.com/goharbor/harbor which responses more quickly if it's not the bug or doesn't any change for the Harbor chart

**Comment by ywk253100** [comment]
@sunielm7 Is the [FAQ](https://github.com/goharbor/harbor/wiki/Harbor-FAQs#modify-the-max-connections-of-the-database-for-versions-less-than-v202) the documentation you refer to? I don't see any `sed` in the command
