### ISSUE TITLE
How to clean harbor running in k8s?

### ISSUE THREAD

**Issue by Ryanbeta** [goharbor/harbor-helm#106]
If I docker-compose up a harbor, I could clean it by typing:
```shell
docker-compose down
docker run -it --name gc --rm --volumes-from registry vmware/registry:2.6.2-photon garbage-collect --dry-run /etc/registry/config.yml
```
When it comes to harbor-helm, how could I clean those deleted images to save my disk? 
Do I have to execute "helm delete" before performing garbage-collect?

**Comment by ywk253100** [comment]
The online GC is introduced in Harbor 1.7 (RC release will be available soon), so if you are using the chart on master branch, you can already do the GC on the web portal by login with system admin user.
