### ISSUE TITLE
Migrate to another authz system

### ISSUE THREAD

**Issue by brackend** [goharbor/harbor-helm#1069]
Is it possible to migrate from, say ldap to OIDC?  It looks like its locked in once configured - drop down is greyed out.

My deployment is through Helm.  If a straight forward migration is not possible.  Is there another approach to for example, maintain all the libraries and potentially the group permissions.

**Comment by brackend** [comment]
thank you

**Comment by lethargosapatheia** [comment]
I don't really understand that argument. User information doesn't become invalid, you have many of the same details, including the email address when switching from LDAP to OIDC, for example.
Moreover, if you have the same groups when switching from LDAP to OIDC (this is our case and it's a valid, relatively common case), then you can definitely keep the permissions. You manually update group_type from 1 (LDAP) to 3 (OIDC) in the `user_group` table and you delete the `ldap_group_dn` fields. And it works just fine and the group permissions will be kept as long as (in this case) the same group names show up in the OIDC group claim for each user. Harbor doesn't keep an associating between groups and users in the database. It will just read and use whatever the IdP provides.

Not supporting remapping the users (like gitlab does without any issues) it's one thing, but _not understanding_ why people would need this is just weird.
