### ISSUE TITLE
Registry Secret causes changes on every apply

### ISSUE THREAD

**Issue by darend** [goharbor/harbor-helm#107]
## issue

Every time `helm diff` or `helm sync` is run changes are shown even if no config changes we made

## background

The registry secret generates a random password inline: https://github.com/goharbor/harbor-helm/blob/b5b422f91b8a574762ac980737a65fb2690bc98e/templates/registry/registry-secret.yaml#L9

Similarly with the notary certificates: https://github.com/goharbor/harbor-helm/blob/b5b422f91b8a574762ac980737a65fb2690bc98e/templates/notary/notary-cm.yaml#L11

**Comment by ywk253100** [comment]
Yes, the secret and certificate are used to secure the communication between the internal components, they are both generated automatically.

**Comment by ywk253100** [comment]
Any side effect do you get with them?

**Comment by darend** [comment]
> Any side effect do you get with them?

We use `helm diff` to show changes that would be applied and have automation to roll things out. It just makes the diff a little harder to parse as you need to know to ignore these changes.

As a feature request, perhaps allow these to be provided when installing the chart
