### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by bellcprimer** [goharbor/harbor-helm#1078]
Hi all

I cannot for the life of me get username and password working when logging into portal.

Ive set the password with harborAdminPassword value for the helm chart.

I am using version 1.7.2 and I tried 1.7.2

there arent many google searches on it so I assumed im doing something wrong.

I havent made any changes apart from the password and there is nothing in the logs

**Comment by QiuToo** [comment]
我使用helm  install harbor  version2.4.2也出现这个问题，我使用的是NodePort的访问方式。

**Comment by zyyw** [comment]
@QiuToo , are you using internal ip or public ip for nodePort.

I deployed harbor 2.4.2 via nodePort with a public IP and it can be logged in successfully. If you are using an internal ip, it could be a problem:
* https://github.com/goharbor/harbor-helm/issues/485#issuecomment-573495240
