### ISSUE TITLE
Cannot change external redis user

### ISSUE THREAD

**Issue by aldiserg** [goharbor/harbor-helm#1087]
i am using external redis service and have to change username for connect to it (not redis)
https://github.com/goharbor/harbor-helm/blob/master/templates/_helpers.tpl#L175

**Comment by ywk253100** [comment]
Let's support configuring the username for Redis once this is done in Harbor core: https://github.com/goharbor/harbor/issues/15895

**Comment by zyyw** [comment]
submit a PR for this, but it only works with "default" redis username + customized redis password, as it tested on redis-server 6.2.6. This might be a limitation of redis-server?

**Comment by zyyw** [comment]
due to dependency on goharbor/harbor, this will not be shipped out in release-1.9.0
