### ISSUE TITLE
Use recommended labels in helm and kubernetes

### ISSUE THREAD

**Issue by ese** [goharbor/harbor-helm#109]
Follow current guidelines in label definition.

https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by ywk253100** [comment]
@ese As I know, if the version is set as a label, the following upgrade will fail https://github.com/goharbor/harbor-helm/issues/30. Any advice?
