### ISSUE TITLE
database supports mysql?

### ISSUE THREAD

**Issue by zhijiangwang** [goharbor/harbor-helm#110]
In config of values.yaml，Can I use Mysql?
`
database:
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db
      tag: dev
    # The initial superuser password for internal database
    password: "root123"
    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    nodeSelector: {}
    tolerations: []
    affinity: {}
  external:
    host: "192.168.0.1"
    port: "5432"
    username: "user"
    password: "password"
    coreDatabase: "registry"
    clairDatabase: "clair"
    notaryServerDatabase: "notary_server"
    notarySignerDatabase: "notary_signer"
    sslmode: "disable"
`

**Comment by ywk253100** [comment]
No, only supports PostgreSQL
