### ISSUE TITLE
Ingress name changed

### ISSUE THREAD

**Issue by mohit94614** [goharbor/harbor-helm#1100]
Hello team,

We recently upgraded from harbor 2.1.3 to 2.3.3 and we observed that ingress got recreated due to a change in name of ingress. 

this resulted in a change on IP on ingress and which caused the service disruption for over environment, since on over environment we are having a corporate firewall and this broke our entire harbor setup.
Request you either document these kinda breaking changes or possible not change the ingress setup or naming convention.

**Comment by ninjadq** [comment]
hi, you can work around it using the method in https://github.com/goharbor/harbor-helm/issues/987#issuecomment-882338034
