### ISSUE TITLE
possibility to set portal settings.json

### ISSUE THREAD

**Issue by PaulusTM** [goharbor/harbor-helm#1108]
The `settings.json` from the portal controls some style options. I'd like these to be set by using a configmap, but in the current setup this is not possible.

If I contribute this, would it be something you'd be interested in?

**Comment by ninjadq** [comment]
Hi, you can use [post rendering](https://helm.sh/docs/topics/advanced/#post-rendering) to customize `settings.json` 
currently, we didn't have a plan to expose this kind of setting in value.yaml
