### ISSUE TITLE
when harbor-helm first install, report error: "Multi-Attach error for volume "xxx" Volume is already used by pod(s)"

### ISSUE THREAD

**Issue by lynn447742** [goharbor/harbor-helm#1109]
**Hi harbor-helm team:**
@jessehu    @paulczar 
Use rook as the storage engine to create a storageclass of ceph-rbd type, and configure the helm file values.yaml: set the number of copies of chartmuseum, jobservice, and registry to 2. **After helm install is installed, the pod runs as follows:**
![image](https://user-images.githubusercontent.com/87010472/145602753-317c7ee2-d525-438d-97c7-0acffdba717a.png)

**Run "kubectl describe po myharbor-jobservice-5895d94d64-mvtfd -n harbor-helm" as follows:**
![image](https://user-images.githubusercontent.com/87010472/145603201-2e3b83a5-bf16-41b1-b5f9-da07826fd907.png)

**The automatically created pvc is as follows：**
![image](https://user-images.githubusercontent.com/87010472/145604129-922bf0c4-ec63-4905-bc8f-5152cf7b003d.png)

**All resources created in the harbor-helm namespace are as follows：**
![image](https://user-images.githubusercontent.com/87010472/145604310-27245eae-af93-41bd-88ab-46386b714cc3.png)
![image](https://user-images.githubusercontent.com/87010472/145604348-571f8c59-ee82-4d98-be10-ec7d7b8b4dee.png)

**Chartmuseum and jobservice are in the same configuration, Why Chartmuseum is running normally，but jobservice is reported that pvc has been used by another replica?**

**Comment by patsevanton** [comment]
@lynn447742  How are fixed issue ?
