### ISSUE TITLE
Database password is stored in Configmap as clear text

### ISSUE THREAD

**Issue by darend** [goharbor/harbor-helm#111]
The password for the clair and notary databases are stored in a Configmap as clear text. It should be stored as Secret for security.

A template is used to construct the postgres URL with the password:
https://github.com/goharbor/harbor-helm/blob/c263ec91c71067565317bf08aa212989d6a156ca/templates/_helpers.tpl#L133-L143

Its then used in the configmaps:
https://github.com/goharbor/harbor-helm/blob/c263ec91c71067565317bf08aa212989d6a156ca/templates/clair/clair-cm.yaml#L15
https://github.com/goharbor/harbor-helm/blob/c263ec91c71067565317bf08aa212989d6a156ca/templates/notary/notary-cm.yaml#L35
https://github.com/goharbor/harbor-helm/blob/c263ec91c71067565317bf08aa212989d6a156ca/templates/notary/notary-cm.yaml#L59

**Comment by draeron** [comment]
this is critical security issue, on our cluster, all pod's stdout get collected and sent to a elasticsearch cluster which means the value of our password get indexed.

**Comment by ywk253100** [comment]
@darend Thanks for your feedback, we'll fix it.

**Comment by ywk253100** [comment]
@darend The issue of password leaking is tracked by https://github.com/goharbor/harbor/issues/7510.

**Comment by darend** [comment]
> The issue of password leaking is tracked by goharbor/harbor#7510.

@ywk253100 Thanks. That issue tracks logging of passwords, there is still the issue that the password is stored in a ConfigMap vs Secret
