### ISSUE TITLE
add feature HPA on core and registry pods 

### ISSUE THREAD

**Issue by Tejuvmware** [goharbor/harbor-helm#1112]
Hello Team, 

We are going to receive a huge traffic soon with an application release. Could you please include HPA feature as soon as possible or is there a workaround to implement/ include HPA to the k8s cluster along by using the existing harbor-helm ? 

Please guide as soon as possible.. 

Thanks in advance..!!

**Comment by Tejuvmware** [comment]
Any update on this issue ?

**Comment by ninjadq** [comment]
you can try to manually scale it, we didn't have a plan to support HPA recently.
