### ISSUE TITLE
Cannot modify the annotations of ingress through helm --set

### ISSUE THREAD

**Issue by fengzhibin** [goharbor/harbor-helm#1129]
kubectl version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

helm version:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

When I execute the following command：
helm install harbor harbor/harbor --set expose.ingress.annotations."nginx\.ingress\.kubernetes\.io/ssl-redirect"="false"

I got the following error：
`
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found f, error found in #10 byte of ...|edirect":false},"lab|..., bigger context ...|":"0","nginx.ingress.kubernetes.io/ssl-redirect":false},"labels":{"app":"harbor","chart":"harbor","h|...
`

If I change "false" to other characters, such as "ABC", no error message will be generated
helm install harbor harbor/harbor --set expose.ingress.annotations."nginx\.ingress\.kubernetes\.io/ssl-redirect"="abc"

`NAME: harbor
LAST DEPLOYED: Thu Dec 30 17:26:43 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Please wait for several minutes for Harbor deployment to complete.
Then you should be able to visit the Harbor portal at https://core.harbor.domain
For more details, please visit https://github.com/goharbor/harbor`

**Comment by zyyw** [comment]
@fengzhibin the error message 
```
ReadString: expects " or n, but found f, error found in #10 byte of ...|edirect":false},"lab|..., bigger context ...|":"0","nginx.ingress.kubernetes.io/ssl-redirect":false}
```
essentially requires the value of assigned to `nginx.ingress.kubernetes.io/ssl-redirect` to be a string value of "false".
But somehow, the command you run `helm install harbor harbor/harbor --set expose.ingress.annotations."nginx.ingress.kubernetes.io/ssl-redirect"="false"` wasn't interpreted to be a string value of "false" but a boolean value of false.

**Comment by pvdputte** [comment]
You can use `--set-string` instead of `--set` so it won't try to interpret it as a boolean. See https://stackoverflow.com/a/61905861

**Comment by fengzhibin** [comment]
> You can use `--set-string` instead of `--set` so it won't try to interpret it as a boolean. See https://stackoverflow.com/a/61905861

The right solution，

`helm install harbor harbor/harbor --set-string expose.ingress.annotations."nginx\.ingress\.kubernetes\.io/ssl-redirect"="false"`

**Comment by fengzhibin** [comment]
> @fengzhibin the error message
> 
> ```
> ReadString: expects " or n, but found f, error found in #10 byte of ...|edirect":false},"lab|..., 
> bigger context ...|":"0","nginx.ingress.kubernetes.io/ssl-redirect":false}
> ```
> 
> essentially requires the value assigned to `nginx.ingress.kubernetes.io/ssl-redirect` to be a string value of "false". But somehow, the command you run `helm install harbor harbor/harbor --set expose.ingress.annotations."nginx.ingress.kubernetes.io/ssl-redirect"="false"` wasn't interpreted to be a string value of "false", which was expected, but actually being interpreted as a boolean value of false. Noticed that the value `false` is not surrounded by quotes in the error message, in another words, the error message is `"nginx.ingress.kubernetes.io/ssl-redirect":false`; if the false interpreted as expected, it should be `"nginx.ingress.kubernetes.io/ssl-redirect":"false"`. That could be the reason why it errors out.

Thank you for your answer. I found that using --set, whether = false or = "false", will be regarded as false of Boolean value. When I use  --set-string, I can use false string
