### ISSUE TITLE
Pods with PVC-s should be StatefulSets instead of Deployments

### ISSUE THREAD

**Issue by laurivosandi** [goharbor/harbor-helm#1137]
We're running Harbor from Helm with storage on top of Longhorn. PVC-s are correctly created and attached during first run but any attempts to roll out updates end with:

```
harbor-jobservice-695db976-x2tdl     1/1     Running             1          22h
harbor-jobservice-85b8fc4658-csdkk   0/1     ContainerCreating   0          22h
harbor-registry-768c966-8qd4l        0/2     ContainerCreating   0          22h
harbor-registry-79c65bcfb7-r5t6v     2/2     Running             0          22h
```
This seems to be because jobservice and registry both use Deployment kind, in which case new pod is started before old one is teared down during rollout. This presumably works fine with external storage such as S3 but with PVC-s this does not, as PVC will be locked by the previously running pod preventing the new one from starting up:

```
./harbor.yml-# Source: harbor/templates/jobservice/jobservice-dpl.yaml
./harbor.yml-apiVersion: apps/v1
./harbor.yml:kind: Deployment
./harbor.yml-metadata:
./harbor.yml-  name: "k6-harbor-jobservice"
./harbor.yml----
./harbor.yml-# Source: harbor/templates/registry/registry-dpl.yaml
./harbor.yml-apiVersion: apps/v1
./harbor.yml:kind: Deployment
./harbor.yml-metadata:
./harbor.yml-  name: "k6-harbor-registry"
```
The more correct way to do this would be:
* Use StatefulSet if PVC is involved
* Use Deployment otherwise

**Comment by bnapalm** [comment]
I've also run into this, however, it is worth mentioning that the existing strategy should work fine if your volumes are ReadWriteMany, so there could be cases when Deployment is still preferred.

For the common ReadWriteOnce volumes, you should change the update strategy to "Recreate" as commented here: https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L346-L350

I would, however, argue that the defaults in values.yaml could be better, as they use RWO volumes and RollingUpdate strategy by default.

**Comment by laurivosandi** [comment]
Please do NOT recommend ReadWriteMany as solution, this implies the application is actually designed to handle multiple processes writing into the same filesystem. At best it will work without issues, but more likely that will cause inconsistencies or even worse data corruption. Harbor devs could confirm whether this is a suitable workaround for the problem.

I went thru the [statefulset](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) and the update strategy policy docs and I'm sticking to what I originally wrote above.

**Comment by bnapalm** [comment]
Fair point. I was basing my comment on this line in the `values.yaml`

`# Set it as "Recreate" when "RWM" for volumes isn't supported`

but that does not really mean that these components support RWM.

After some testing, I also don't like the approach of setting UpdateStrategy.type to "Recreate", as this applies to multiple deployments. In my case, I would only want this for jobservice. If the application does not specifically support RWM volumes, then StatefulSet is indeed the recommended approach when using persistent volumes.

**Comment by ywk253100** [comment]
They cannot be `StatefulSets` as we discussed [here]{https://github.com/goharbor/harbor-helm/pull/410#issuecomment-558900322}

**Comment by laurivosandi** [comment]
@ywk253100 can you confirm that jobservice and registry behaviour remains correct with ReadWriteMany access mode?

**Comment by ywk253100** [comment]
@laurivosandi Yes, I can confirm that. Our internal Harbor instance deploys multiple registry pods with NFS as the underlying storage system

**Comment by laurivosandi** [comment]
Note that when running on Longhorn you can't actually use ReadWriteMany access mode because Longhorn volume can be mounted at time only on one worker node

**Comment by blackliner** [comment]
> I've also run into this, however, it is worth mentioning that the existing strategy should work fine if your volumes are ReadWriteMany, so there could be cases when Deployment is still preferred.
> 
> For the common ReadWriteOnce volumes, you should change the update strategy to "Recreate" as commented here: https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L346-L350
> 
> I would, however, argue that the defaults in values.yaml could be better, as they use RWO volumes and RollingUpdate strategy by default.

I tried to solve this issue here: https://github.com/goharbor/harbor-helm/pull/1334 but @zyyw seemed to not understand the issue :-/
