### ISSUE TITLE
horizon cannot login

### ISSUE THREAD

**Issue by SUMMERLm** [goharbor/harbor-helm#1149]
![image](https://user-images.githubusercontent.com/92348982/155058738-ccac18d0-0091-4cbd-8f43-64eaf81a4f07.png)

![image](https://user-images.githubusercontent.com/92348982/155058074-00739076-45b4-47c3-85a1-4a7535003303.png)
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/92348982/155058251-b45cd8c7-12ed-4cef-baf0-81aaf6e475c1.png">
![image](https://user-images.githubusercontent.com/92348982/155058320-f5b2ca03-8cf2-4111-b1a8-441b3d90639e.png)
![image](https://user-images.githubusercontent.com/92348982/155058425-2ad39c10-6c25-4276-b834-1e8468abf7a4.png)
![image](https://user-images.githubusercontent.com/92348982/155058597-eb16a192-10a6-4b9a-bca8-4f61a538334e.png)

**Comment by zyyw** [comment]
tried install harbor via harbor-helm with nodePort on my vm, I am able to login harbor portal without any problem. Can't reproduce this error.

@SUMMERLm could you please share your full value.yaml and helm install/upgrade(if you ran helm upgrade) commands ?

**Comment by zyyw** [comment]
pls make sure the password for admin is not reset to a new password or the password of admin exists in database. this `harborAdminPassword` setting only works when admin password is not set in database.

**Comment by withlin** [comment]
@zyyw same issue

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
khub-harbor     harbor          10              2022-03-14 10:24:12.231491 +0800 CST    deployed        harbor-1.8.1    2.4.1    
```
![image](https://user-images.githubusercontent.com/22409551/158096005-6c1be074-8a96-4cdf-85f1-791f9ca102e4.png)

**Comment by kevinlmadison** [comment]
@withlin Were you able to resolve this issue? I'm experiencing the same thing.

**Comment by withlin** [comment]
@kevinlmadison   i am use v2.4.0 version which is reslove it.
