### ISSUE TITLE
Upgraded recently, any reason to NOT use the dev release for registryctl and photon

### ISSUE THREAD

**Issue by webdz9r** [goharbor/harbor-helm#1150]
We've upgrade from 2.2.0 to 2.4.1 and we set our values for the photon and registryctl version to 2.1.1

I noticed in the defaults have it set to dev

Anyone reason we should use the dev tag vs the version set by our previous install? There was no reason we used the 2.1.1 we just typically set the values when doing deployments to release versions 

Thanks

**Comment by zyyw** [comment]
Hi @webdz9r why would you want to set registryctl and etc version to 2.1.1 when upgrading from 2.2.0 to 2.4.1?

You may probably do a `git checkout tags/<tag> -b <branch>` and do a deployment based on the code base checked out.
BTW the dev is a placeholder of image version to be replace with an specific image version when we make a release of harbor-helm.

**Comment by zyyw** [comment]
the reason of `dev` tag is that we have harbor images pushed to dockerhub periodically tagged with `dev` and conceptually, the latest codebase of harbor-helm should use the images built against the latest codebase of goharbor/harbor, which is tagged as `dev`.
