### ISSUE TITLE
Harbor Helm 1.8.1 HA with external backing services

### ISSUE THREAD

**Issue by aceeric** [goharbor/harbor-helm#1153]
I'm using the 1.8.1 helm charts to stand up an HA Harbor registry on Kubernetes. To integrate with an external database it looks like the chart `values.yaml` wants an in-lined password. Is there any consideration being given to the idea of supporting templating for that so I can define the password with a Helm lookup function to get the password from a Secret provisioned by an external Postgres operator? Similarly, the S3 integration would benefit from the access key and secret key supporting this. (Potentially the Redis integration as well...) Thank you.

**Comment by xzizka** [comment]
Hello, we are trying to achieve nearly the same in our project. We are using ArgoCD fro deployment. The way we are trying now is to define the base of the deployment in one Git repo (same for all deployments) and in another repo linked with the ArgoCD we use kustomize to customize all necessary values, but maybe this is overcomplicated for your situation.

**Comment by sylvainOL** [comment]
fyi, I've created https://github.com/goharbor/harbor-helm/pull/1244 in order to help on that.
If it doesn't pass (because it's rather big), my plan was to start with database external first
