### ISSUE TITLE
docker login failed

### ISSUE THREAD

**Issue by jiangxuhui** [goharbor/harbor-helm#1156]
my harbor expose  is nodePort，i can open web in chrome ,but when i 

docker login -u admin -p Harbor12345 https://139.9.162.134:30043

response: Error response from daemon: Get "https://139.9.162.134:30043/v2/": x509: cannot validate certificate for 139.9.162.134 because it doesn't contain any IP SANs

i try every method on the internet, but failed

**Comment by jiangxuhui** [comment]
also, i don't think close http is a good idea , harbor only use in  Local Area Network

**Comment by jmozd** [comment]
what's in the SAN field of the certificate used by Harbor? One way to check is via 
`openssl s_client -connect 139.9.162.134:30043 2>/dev/null | openssl x509 -inform pem -noout -text`
Clients will check the SAN field (subject alternative names) and in your case, the client reports that no IP entries are in the SAN field (needed as you use an IP in the URL, "139.9.162.134" in your case).

Likely, you'll need to use the formal host name (as given in the cert's SAN field) to properly access the registry.

**Comment by zyyw** [comment]
similar to this issue: https://github.com/goharbor/harbor-helm/issues/852

**Comment by zyyw** [comment]
Could you please set IP to commonName: https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L25
and try again?
