### ISSUE TITLE
Change comment typo in Values file around Jaeger Tracing

### ISSUE THREAD

**Issue by ChrisJBurns** [goharbor/harbor-helm#1164]
So I am setting up the Distributed tracing aspect for Harbor and I have followed the helm chart and it was slightly misleading.

The below is the yaml that can be found here:
https://github.com/goharbor/harbor-helm/blob/6a52e9a35ddcffb268aea688766a1a2cff2286da/values.yaml#L910-L919

However i think the `agent mode` and `collector mode` comments are the wrong way around. I have tested this because when I point my `endpoint` at my jaeger collector: `endpoint: http://jaeger-collector.jaeger:14268/api/traces`, I can the traces showing up. However when putting the agent details in the `endpoint` value, I get nothing. I also think the fact that in the `collector mode` it has `agent_host` and `agent_port` which is also a bit of a give away to why I believe it's a typo.

Should be a quick fix, just wanted to double check with someone first.

**Comment by zyyw** [comment]
Hi @ChrisJBurns , you mean the comment should be updated from 
```
 jaeger: 
   # jaeger supports two modes: 
   #   agent mode(uncomment endpoint and uncomment username, password if needed) 
   #   collector mode(uncomment agent_host and agent_port) 
```
to 
```
 jaeger: 
   # jaeger supports two modes: 
   #   collector mode(uncomment endpoint and uncomment username, password if needed) 
   #   agent mode(uncomment agent_host and agent_port) 
```
If so, I agree with you on that. Could you please open a PR for this fix? Thank you.

**Comment by ChrisJBurns** [comment]
@zyyw  PR raised: https://github.com/goharbor/harbor-helm/pull/1167
