### ISSUE TITLE
怎么还没有发布正式版本啊

### ISSUE THREAD

**Issue by lanmingle** [goharbor/harbor-helm#118]
怎么还没有发布正式版本啊！！！什么时候发布正式版呀。

**Comment by ywk253100** [comment]
Very soon

**Comment by lanmingle** [comment]
@ywk253100 就刚才是不是打算发布1.0.0了？我刚才安装了最新的master分支（即1.0.0这个分支），正常跑起来了，忽然之间不想折腾了。😝
