### ISSUE TITLE
Add optional PodDisruptionBudget to chart

### ISSUE THREAD

**Issue by slushysnowman** [goharbor/harbor-helm#1181]
Currently, there is no option to create PodDisruptionBudget in the chart. It would be very handy to have the option to do this from within the chart, so that users who require a PodDisruptionBudget don't have to maintain this separately.

**Comment by zyyw** [comment]
Since the PDB is a relatively independent resource. We would suggest you manage PBD separately instead of incorporating with harbor-helm.

**Comment by robinkb** [comment]
I disagree with this conclusion. I consume a lot of Helm charts in my environments, and most Helm charts which can setup highly-available applications include PDBs in the chart. Having to configure all of the matchLabels and such is a hassle that I would expect the Helm chart to do for me.

Having said that, I do think that the proposed PR (#1182) was not very elegant. My favorite implementation that I've seen so far is in the [chart for oauth2-proxy](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/poddisruptionbudget.yaml). The PDBs are enabled by default, but only when the replicaCount is > 1.

PodDisruptionBudgets are essential to ensure that applications don't go down during normal cluster operations, like rolling restarts of nodes.
