### ISSUE TITLE
Add option to set pod securityContext runAsNonRoot

### ISSUE THREAD

**Issue by slushysnowman** [goharbor/harbor-helm#1183]
Currently the only way to set this is to patch the manifests (either via postrender, or after deployment).

For clusters with policy enforcement, where `runAsNonRoot` must be set to true, not being able to configure this is troublesome.

It would be great if we could configure this via the chart, rather than having to patch this in separately.

**Comment by zyyw** [comment]
Essentially, there are two to set user `runAsNonRoot` and `runAsUser` with a numeric UID. It is by design to use `runAsUser`. Maybe you should update the policy instead of checking `runAsNonRoot`.
