### ISSUE TITLE
How Registry Image Backup - Harbor (v2.4.x) / Harbor Helm (1.8.0)

### ISSUE THREAD

**Issue by namgonkim** [goharbor/harbor-helm#1186]
hi

Currently, Harbor (v2.4.x) / Harbor Helm (1.8.0) deployed to k8s as Harbor Helm, and chartmuseum, registry, database, redis, trivy, and job-service are using nfs as pv and pvc. thank you. :) (rook-ceph is also under consideration)

However, in case of an emergency, I searched for a periodic backup of the harbor, but there was no document about the backup in the situation of distribution with Helm, so I asked a question.

No matter how much I looked at the issues and discussions of the harbor, harbor-helm git repository, there was no clear answer.

Metadata stored in the database can be processed using db export backup, but I am curious how to back up the artifacts (images) stored in the registry.

**Can you provide a guide for backing up the image layers in the registry container of harbour, deployed by k8s with harbour helm, without using a third party (velero, minio)?**

Here's what I was thinking of:
1. Connect to any Docker registry using replication and periodically back up images there.
  - If I load a backup image in this way, the image digest value will be different, so it is likely to conflict with the metadata stored in the database.
2. Connect to the registry container of the deployed harbor, bind the ```/storage``` directory with ```tar``` and send it to the outside.
  - I tried the method, but it fails because there is no root, and the ```scp``` command that can be transmitted to the outside cannot be performed.

Thank you for reading this long post, and thank you for your reply.

**Comment by zyyw** [comment]
Thanks for bringing this up! We are actively investigating backup harbor with Velero. 
More ideas/suggestion are very welcome!

**Comment by namgonkim** [comment]
Is there any way to back up the harbor deployed with helm itself without using a third party tool like Velero? Please guide. thank you.

**Comment by djpbessems** [comment]
I'm curious about an answer to this question too; could this be achieved with a tool like skopeo or crane? Maybe with a script that also queries the REST API to get a full list of all images?
