### ISSUE TITLE
Internal Redis component not Highly available

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor-helm#1190]
Hi,

Due to the issue I am facing with the external Redis component, in case of Harbor Helm Chart 2.5.0. Issue link : [https://github.com/goharbor/harbor/issues/16777]

I am trying to use the internal Redis component provided by the Harbor Helm chart, but I am observing that it creates only 1 replica. If I try to scale up the stateful set, 3 replicas are created which are each individual masters, not master-replica-replica set.

Is it the expected behaviour or is there a way to make this Internal Redis HA?

**Comment by zyyw** [comment]
It is by design not supporting redis HA with internal redis.
