### ISSUE TITLE
How deploy Harbor chart on EKS with ALB Controler ?

### ISSUE THREAD

**Issue by agaillar** [goharbor/harbor-helm#1193]
Hello, 

I would like to deploy Harbor (v2.5.0) on an AWS EKS cluster (v1.20) with an ALB ingress controller (v2.3).

With the default controller (`expose.ingress.controller`), the error `Failed deploy model due to InvalidParameter: 1 validation error(s) found. - minimum field value of 1, CreateTargetGroupInput.Port` occurs, and the services are not accessible. 

Indeed, with an ALB controller, the services must be of type NodePort (see. https://coresolutions.ltd/blog/kubernetes-aws-load-balancer-controller/)

Switching to the gce controller, I don't get the previous error. The services are accessible. 
However, switching to the controller has changed the input rules by adding wildcards. This causes an error because the ALB controller no longer accepts wildcards: `prefix path shouldn't contain wildcards: /api/*`

Would you have an idea on the right method to implement ?
thanks in advance, best regards

**Comment by agaillar** [comment]
a workaround, using kustomize to modify services in the post-rendering : 
(https://github.com/thomastaylor312/advanced-helm-demos/tree/master/post-render)

**Comment by zyyw** [comment]
Hi @agaillar , the ALB is currently not supported. You can refer to this PR to work with ALB controller:
* https://github.com/goharbor/harbor-helm/pull/295

**Comment by zyyw** [comment]
Hi @agaillar , you are very welcome to try this PR, and please submit a PR for ALB controller if it's verified working.

**Comment by jamesglennan** [comment]
This is fixed now- i assume itll be available in the next release, you can specify ingress type `alb`, you will obviously need to add annotations to configure the LB yourself

**Comment by sidewinder12s** [comment]
Note this might be missing this bit of configuration: https://github.com/goharbor/harbor-helm/issues/474

I only noticed it when I tried to enable podReadinessGate and then rollouts failed because the core service health checks were failing.
