### ISSUE TITLE
How to use external redis?

### ISSUE THREAD

**Issue by andyzheung** [goharbor/harbor-helm#1194]
I am try to use external redis, but it seem that can't start up..
values like this:
![image](https://user-images.githubusercontent.com/22912347/166928973-3d744b9d-a0c4-42e9-9124-9daef1498c80.png)

redis:
![image](https://user-images.githubusercontent.com/22912347/166929095-57facb9f-f811-4a79-a33f-51f244da773d.png)

**Comment by zyyw** [comment]
Hi @andyzheung , could you please try the scenario of installing standalone redis instead of installing redis in k8s env?
for example: https://redis.io/docs/getting-started/installation/
