### ISSUE TITLE
The LDAP option cannot be selected except for the database

### ISSUE THREAD

**Issue by yangqi766** [goharbor/harbor-helm#1198]
![企业微信截图_20220510105219](https://user-images.githubusercontent.com/13087771/167533303-5a3db032-e668-44d2-b571-f4a1976ebe20.png)

The LDAP option cannot be selected except for the database.

why ??

**Comment by zyyw** [comment]
This is not a harbor-helm issue. please feel free to open an issue in goharbor/harbor.
It's very likely that there are some users existing in database and thus preventing you switching to LDAP authentication.
