### ISSUE TITLE
Ability to add hostAliases through values yaml file

### ISSUE THREAD

**Issue by Shashankft9** [goharbor/harbor-helm#1204]
I have couple of harbor registry endpoints which are not discoverable over public internet, and hence in order to do replication I want to ensure that the remote endpoint is discoverable in the local endpoint, for which I am using `hostAliases` in the deployments and statefulsets, so that the pod host entries are updated accordingly - currently I have to add it manually in all the k8s resources, meaning if I upgrade or reinstall, my changes will be lost. 

So, would it be possible to add a field for `hostAliases` in values.yaml? Or if you think there is a better alternative for this, please do suggest. 

ref: https://cloud-native.slack.com/archives/CC1E09J6S/p1652187516779859?thread_ts=1652178247.337329&cid=CC1E09J6S

cc @chlins

**Comment by zyyw** [comment]
@Shashankft9 thanks for using harbor-helm. the `hostAliases` might be an ad-hoc user scenario, not a general use case. I'm afraid we may not add this config in values.yaml.

**Comment by outofrange** [comment]
Could this be reconsidered?
We would like to use hostAliases as well!
