### ISSUE TITLE
When operating harbor core with multiple replicas, 401 Unauthorized occurs intermittently during docker login

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor-helm#1205]
hello
When running harbor-core as multiple instead of replica 1, it seems that a 401 Unauthorized error occurs intermittently (1 or 2 out of 10) during docker login.

`echo "password" | docker login $REGISTRY_HOST --username $REGISTRY_USER --password-stdin
Error response from daemon: login attempt to $REGISTRY_HOST/v2/ failed with status: 401 Unauthorized`

harbor-core log
`2022-05-19T08:57:54Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is not valid yet`

If harbor-core is operated with 1 replica, no error occurs.

Shouldn't the harbor core be operated with multiple replicas? Please answer
I'm using version 1.9.0 and if you have any info I need for debugging please tell me

thanks.

**Comment by kkacsh321** [comment]
@derekcha we had this issue also, and what it came down to was time syncs between the nodes that were running core/registry. Once we fixed the NTP time issues problems went away. Key to this error is in the message that the token is not valid yet..... "yet".

**Comment by InderpreetSaini** [comment]
[https://github.com/goharbor/harbor/issues/16942](url)
