### ISSUE TITLE
Harbor 2.6 from Helm chart?

### ISSUE THREAD

**Issue by MallocArray** [goharbor/harbor-helm#1208]
My first experience using helm was to deploy Harbor to an OpenShift cluster.

As far as I can tell, I used the same helm chart and values.yaml file and deployed it to 3 different Openshift clusters using only slightly different domain names.

In one cluster it deployed Harbor 2.5 and after doing `helm upgrade harbor harbor/harbor -f values.yaml -n harbor` recently, the About page is showing `Version v2.5.0-74d26706`

On two other clusters that I deployed a few days later, it is showing a version of Harbor 2.6 which I can't find a reference to on the official Harbor page at all.  As a test I tried doing an upgrade, and this other cluster went from running `Version v2.6.0-f78047f1` to now showing `Version v2.6.0-d26b5792`

Is 2.6 even a valid version and why would using the same computer to log into the different OCP clusters and using the same helm command and values result in different versions of Harbor?

**Comment by zyyw** [comment]
@MallocArray None of the three version `Version v2.5.0-74d26706`, `v2.6.0-f78047f1`, or `Version v2.6.0-d26b5792` are official release harbor. I guess you just cloned `https://github.com/goharbor/harbor-helm.git` and deployed harbor via harbor-helm master branch. Please **download the released harbor helm** of your choice here: 
* https://github.com/goharbor/harbor-helm/releases
If you are deploying harbor via harbor-helm master branch, the version will be the next version of harbor release + the (relatively) latest commit from goharbor/harbor. For example, currently we have harbor 2.5.x released, if you deploy harbor through harbor-helm master branch, the version will be 2.6.0-commit, where `commit` is the relatively latest commit in goharbor/harbor.

**Comment by zyyw** [comment]
alternative, you can refer this guideline to install harbor via harbor-helm:
* https://github.com/goharbor/harbor-helm#installation

**Comment by MallocArray** [comment]
I didn't clone a repo, but I did follow most of this guide, since I'm installing into OpenShift
https://computingforgeeks.com/install-harbor-image-registry-on-kubernetes-openshift-with-helm-chart/

So basically I did:
```bash
helm repo add harbor https://helm.goharbor.io
helm repo update
wget https://raw.githubusercontent.com/goharbor/harbor-helm/master/values.yaml
# Edited values to have expose.type=ingress and my DNS names, increased registry database size and changed upgradeStrategy to Recreate
helm install harbor harbor/harbor -f values.yaml -n harbor
```
I used a different command to fix the root user issue in OCP
```
oc adm policy add-scc-to-user anyuid system:serviceaccount:harbor:default
```

And that is it.  So I'm not sure where I would specify a version to install.  From the link @zyyw provided, I saw the command
``` 
helm install my-release harbor/harbor
```
but if I tried to replace my-release with a release number like
```
helm install v1.9.0 harbor/harbor -f values.yaml -n harbor
```

That didn't work.  Do I need to add  `--version 1.9.0 ` to the command line? Or what am I missing?

**Comment by zyyw** [comment]
I installed harbor v2.5.1-b0506782 successfully by following the step below:
```
1. helm repo add harbor https://helm.goharbor.io
2. helm install my-release harbor/harbor --version v1.9.1 --set persistence.enabled=false,externalURL=https://x.x.x.x:30003,expose.type=nodePort,expose.tls.auto.commonName=x.x.x.x,imagePullSecrets[0].name=dockerhub-cred
```

In your case, if you want to install harbor-helm v1.9.0, you can do the following:
```
1. helm repo add harbor https://helm.goharbor.io
2. wget https://raw.githubusercontent.com/goharbor/harbor-helm/v1.9.0/values.yaml (not master, but v1.9.0)
# edit values.yaml as you want
3. helm install my-release harbor/harbor --version v1.9.0 -f values.yaml
```
