### ISSUE TITLE
State mismatch error for OIDC integration

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor-helm#1213]
Hi,
I have enabled OIDC Integration for Harbor HA Setup deployed using helm chart v2.5.0. For the setup, I have used a core URL say www.abc.com using which helm chart was deployed. Additionally I have added an additional domain say www.xyz.com as an ingress rule, post harbor setup.

For the OIDC integration, at the OIDC provider side, I gave both the redirect URI i.e. https://www.xyz.com/c/oidc/callback and https://www.abc.com/c/oidc/callback

After the setup and OIDC integration, I was able to login to the primary URL www.abc.com, but getting a status mismatch error for the second domain www.xyz.com and the URL in the browser after OIDC authentication redirects to https://www.abc.com/c/oidc/callback

{"errors":[{"code":"BAD_REQUEST","message":"State mismatch"}]}

In the core pod logs, I see the below error:

2022-06-01T12:41:17Z [ERROR] [/core/controllers/oidc.go:75]: State mismatch, in session: %!s(<nil>), in url: w3hn0KgXLLO7WHqRgW3gTsrAZM7dlRoL
2022-06-01T13:32:13Z [ERROR] [/core/controllers/oidc.go:75]: State mismatch, in session: %!s(<nil>), in url: lbJm9jc0cqxFbvIsBIThXpQ3NvKmHoAC

Could you please advise, if there is a way to make this setup work for OIDC based login for both URLs?

**Comment by zyyw** [comment]
this doesn't look like a harbor helm issue, please open a issue under github.com/goharbor/harbor

**Comment by InderpreetSaini** [comment]
[https://github.com/goharbor/harbor/issues/16942](url)
