### ISSUE TITLE
Support for Adding Non Selector Pod Labels to Every Component

### ISSUE THREAD

**Issue by vinayan3** [goharbor/harbor-helm#1220]
The chart should be able to add new labels for each of the components that create pods. Some orgs put policies or admission controllers in place on the Kube Cluster for enforcement of having certain labels on pods. The labels often are used for cost accounting and for points of contacts.

The labels that are added to pods should not be added to the service selector. The label selectors for services are immutable.

**Comment by zyyw** [comment]
This might be an ad-hoc requirement. We'll watch the demand of community of this requirement.

**Comment by jsalatiel** [comment]
Also needing this. Our global security policies are completely based on pod labels.
So database access , ingress access requires podLabels to work.

**Comment by sylvainOL** [comment]
fyi, I've created #1244 in order to help on that.
If it doesn't pass (because it's rather big), my plan was to start with database external first

**Comment by boniek83** [comment]
I would like to have this as well. Using it for ownership (to attach costs and to integrate with chats for incident response)

**Comment by wilddeuces** [comment]
Our company would like to integrate labels for cost accounting too

**Comment by SQUIDwarrior** [comment]
We also need this ability
