### ISSUE TITLE
Disabling Cert check (trivy.insecure) doesn't seem to work

### ISSUE THREAD

**Issue by prom3theu5** [goharbor/harbor-helm#1221]
Hi

I'm getting this error when trying to scan

```
022-06-25T16:07:41.901Z	[34mINFO[0m	DB Repository: ghcr.io/aquasecurity/trivy-db
2022-06-25T16:07:41.901Z	[34mINFO[0m	Downloading DB...
2022-06-25T16:07:42.148Z	[31mFATAL[0m	DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get "https://ghcr.io/v2/": x509: certificate signed by unknown authority
: general response handler: unexpected status code: 500, expected: 200
```

I've set the value `trivy.insecure` to true, and can see that that has been passed through here:

![image](https://user-images.githubusercontent.com/1518610/175782153-effa7b12-c1ec-46d7-9bf4-e4aec625d97b.png)

Am I missing something?

**Comment by prom3theu5** [comment]
Seems like it was recently addressed by Trivy
https://github.com/aquasecurity/trivy/pull/2140

Does this mean the binary in the photon adapter needs updating?

**Comment by zyyw** [comment]
the trivy version and trivyadapter version has been updated recently in goharbor/harbor main branch and release-2.5.0 branch. 
* https://github.com/goharbor/harbor/pull/17071
* https://github.com/goharbor/harbor/pull/17072

@prom3theu5 please stay tuned and try Harbor v2.6.0 / v2.5.2 (both of which are going to be release in the near future)
