### ISSUE TITLE
Harbor >= 1.9.2 external Redis Trivy auth failure

### ISSUE THREAD

**Issue by HammerNL89** [goharbor/harbor-helm#1231]
We upgraded to Harbor 1.9.2 (v2.5.2) and noticed that Trivy wasn't working anymore. When inspecting the logs of the Trivy pod it's spammed with: 
```ERROR: worker.fetch - WRONGPASS invalid username-password pair or user is disabled.
ERROR: worker.fetch - WRONGPASS invalid username-password pair or user is disabled.
ERROR: worker.fetch - WRONGPASS invalid username-password pair or user is disabled.
ERROR: worker.fetch - WRONGPASS invalid username-password pair or user is disabled.
```

We use an external Redis cache (AWS elasticache), but it's failing to connect. When we started debugging we noticed that in the Helm chart helper template a hardcoded redis user is [configured](https://github.com/goharbor/harbor-helm/blob/3bb3ee7fc5195fadaf994511f71cb27f1527f8f7/templates/_helpers.tpl#L175)
This seems to apply to all urls for harbor components that connect to Redis, however only the Trivy component seems to be effected. Looking at the changelog of Harbor v2.5.2 the Trivy/adapter version is bumped.

It looks like Trivy (redigo) is now respecting the username:password entry and is therefore failing in our setup, because we don't have a  user called 'redis' defined in our elasticache, only user 'default'.

Why is the the Redis username hardcoded in the helper template? Imo this should be default or empty if certain components don't support it, or when there is no option in the values.yaml to configure it.

**Comment by arjunprasad2143** [comment]
I have the same issue

**Comment by zyyw** [comment]
we have an issue to track supporting username for external redis:
* https://github.com/goharbor/harbor-helm/issues/1087

And there is a PR (on-hold) to resolve this issue:
* https://github.com/goharbor/harbor-helm/pull/1143

**Comment by arjunprasad2143** [comment]
Any kind of work around for this? This is a breaking change for us. As we only use trivy we dont have any other scanning tool

**Comment by HammerNL89** [comment]
> Any kind of work around for this? This is a breaking change for us. As we only use trivy we dont have any other scanning tool

For our Elasticache we moved to [RBAC ](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.RBAC.html)and created a usergroup and users: default, redis. 

> we have an issue to track supporting username for external redis:
> 
> * [Cannot change external redis user #1087](https://github.com/goharbor/harbor-helm/issues/1087)
> 
> And there is a PR (on-hold) to resolve this issue:
> 
> * [feat: add username support for external redis #1143](https://github.com/goharbor/harbor-helm/pull/1143)

This is not a feature request, it's a breaking issue. I don't see a reason for the redis username being hardcoded, because before this releases it was ignored anyway.

Either document that the redis cache should be configured with user redis, or remove the hardcoded username in the redis urls.

**Comment by arjunprasad2143** [comment]
I still get the error . 

`ERROR: worker.fetch - ERR wrong number of arguments for 'auth' command`

can this be reopened?

**Comment by icassano** [comment]
Hello, I am facing same issue with external redis.
What can I do, please ?
Ignazio

**Comment by arjunprasad2143** [comment]
Even I am not sure why it was closed as completed.

**Comment by mwhcp** [comment]
... same problem with `trivy` scans (full a/o image scans) in one of our environments and with externel redis (Azure PaaS) v6.0.14. 
Same error message as above.  Any workarounds or help how to fix this problem are welcome.

**Comment by keliansb** [comment]
Same issue for me, your workaround works @mwhcp, thank you!
