### ISSUE TITLE
docker push fails with 403 -error parsing HTTP 403 response body: invalid character 

### ISSUE THREAD

**Issue by Pradeepkarthi** [goharbor/harbor-helm#1261]
Hi all,

I have deployed 1.9.0 branch of goharbor and via UI its working fine.. docker login also works well, however when I do a docker push its throwing the below error. Any clue or help will be appreciated. Its infact showing the msg that its pushed but not actually getting pushed and returns a forbidden error.

# docker push <hostname.domainname.com/library/alpine:latest
The push refers to repository [<hostname.domainname.com/library/alpine]
ec34fcc1d526: Pushed
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"

I am using Kong ingress and hence during the install, values.yaml  modified to have expose.type as clusterIP. Then created an ingress with the following config

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ingress
  namespace: harbor
  labels:
    AllowInsecureIngress: "true"
spec:
  rules:
  - host: <hostname.domainname>.com
    http:
      paths:
      - backend:
          service:
            name: harbor
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific

Thanks,
pmk

**Comment by zyyw** [comment]
@Pradeepkarthi there is a `<` character in `docker push <hostname.domainname.com/library/alpine:latest`, which looks odd to me. Do you want to try push without the `<` character

**Comment by zyyw** [comment]
@Pradeepkarthi what's your configuration in values.yaml for `externalURL`.
Please refer to this issue for additional information: 
* https://github.com/goharbor/harbor/issues/13224

**Comment by Pradeepkarthi** [comment]
@zyyw , it was infact tried without any special characters, the "<" accidently got added while I was changing the host and domain name due to compliance before pasting it as reference.

docker push myhost.mydomain.com_/library/alpine:latest
The push refers to repository [myhost.mydomain.com/library/alpine]
ec34fcc1d526: Pushed
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "\r\n<title>403 Forbidden</title>\r\n\r\n

external URL name is set as follows
externalURL: https://myhost.mydomain.com

Thanks and Regards,
Pradeep

**Comment by Pradeepkarthi** [comment]
Hi there, 

any one has faced the issue..I have tried so many options including the new stable version and also changing the ingress config etc, now it seems there is a new error with 405.

Harbor is exposed using clusterIP and then there is an ingress which is configured using kong. If any one has any clue with this, it would be really helpful. Everything works in the harbor UI and I am able to create projects/libraries/user, execute the api calls etc, however when it comes to docker push it fails with below error (docker login also succeeds)
====================
# docker push harbor.test.com/harbor/library/alpine:latest
The push refers to repository [harbor.test.com/harbor/library/alpine]
994393dc58e7: Layer already exists
error parsing HTTP 405 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.22.0</center>\r\n</body>\r\n</html>\r\n"
#
====================
