### ISSUE TITLE
Getting  x509: certificate signed by unknown authority while pushing images to harbor with registry storage minio s3

### ISSUE THREAD

**Issue by smanikkara** [goharbor/harbor-helm#1285]
We set up Harbor using helm top of openshift and backend registry storage as minio s3
while pushing image getting below error

2Faws4_request&X-Amz-Date=20220904T061252Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=3416adeb6cbf562b90af1183643c98e3057f37928118303f6ecdd19fc92ccd99": x509: certificate signed by unknown authority

it seems some certificate issue between harbor and s3 endpoint any idea to fix?

**Comment by smanikkara** [comment]
We use that values.yaml only but we have updated some values like
#regionendpoint: http://myobjects.local (as per this code)
we use https so that this issue occurs...

looks like issue

https://github.com/goharbor/harbor/issues/16437

but not sure how to use ca_bundle in harbor running on openshift

**Comment by haminhcong** [comment]
> We use that values.yaml only but we have updated some values like #regionendpoint: http://myobjects.local (as per this code) we use https so that this issue occurs...
> 
> looks like issue
> 
> [goharbor/harbor#16437](https://github.com/goharbor/harbor/issues/16437)
> 
> but not sure how to use ca_bundle in harbor running on openshift

Did you try to use this config?


```yaml
# The custom ca bundle secret, the secret must contain key named "ca.crt"
# which will be injected into the trust store for chartmuseum, core, jobservice, registry, trivy components
# caBundleSecretName: ""
```

**Comment by smanikkara** [comment]
Yes this issue happening when we use https to the endpoint
