### ISSUE TITLE
PVC configuration docs are mixed up

### ISSUE THREAD

**Issue by immanuelfodor** [goharbor/harbor-helm#1287]
The README says at https://github.com/goharbor/harbor-helm#configuration that `trivy` has 2 new PVCs:
- `persistence.persistentVolumeClaim.trivy.jobLog`
- `persistence.persistentVolumeClaim.trivy.scanDataExports`

But this is not true, `jobservice` has these new PVCs:
- `persistence.persistentVolumeClaim.jobservice.jobLog`
- `persistence.persistentVolumeClaim.jobservice.scanDataExports`

Just take a look at the templates: https://github.com/goharbor/harbor-helm/tree/master/templates/jobservice

If you're upgrading to Harbor OSS v2.6.0 via Helm, please beware of these new PVC configs! :warning:

**Comment by zyyw** [comment]
Thank you for reporting this issue! This PR will resolve this issue:
* https://github.com/goharbor/harbor-helm/pull/1280
