### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [goharbor/harbor-helm#1313]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by zyyw** [comment]
@nate-double-u Anything we need to do from our side?

**Comment by nate-double-u** [comment]
Hi @zyyw, it looks like there are several Helm maintainers on the Netlify team with access to make the build image change. 

If the folks on that list aren't able to do it I'd be happy to help out, but would prefer to make sure that the list of Netlify Team members is correct and up to date with folks able to make these kinds of changes.

The folks currently on the list:
* @OrlinVasilev
* @a-mccarthy
* @jonasrosland 
* @ywk253100 
* @stuclem

**Comment by OrlinVasilev** [comment]
Hi @nate-double-u all links that you have provided are for site I cannot check :( 
For harbor.io we have updated the image:
![image](https://user-images.githubusercontent.com/7236111/197529299-39f248a5-0944-47a6-acf0-3890ad7002db.png)
for helm.harbor.io as well
![image](https://user-images.githubusercontent.com/7236111/197529435-216210bd-6954-41e6-ab12-16962405e208.png)

**Comment by nate-double-u** [comment]
Hi @OrlinVasilev, i was looking at the https://app.netlify.com/teams/harbor/overview team, and it looks like both sites hosted there are correct now.

I think we can close this issue.

**Comment by OrlinVasilev** [comment]
@nate-double-u Nice thank you!
