### ISSUE TITLE
Define external URL for docker registry

### ISSUE THREAD

**Issue by jkroepke** [goharbor/harbor-helm#132]
Hi,

in some setups the Forwarded Headers of the ssl offloading proxy are not well defined. In this case the registry return Locations headers with http:// instead https:// . 

To workaround this behavior its possible to configure the correct external url inside the registry:

https://github.com/goharbor/harbor-helm/blob/1fb73b17f8705d41d55acae85c753fcdbc673a13/templates/registry/registry-cm.yaml#L145

```
http:
  host: {{ .Value.externalURL }}
```

See also: https://docs.docker.com/registry/configuration/#http

**Comment by ywk253100** [comment]
The configuration option `relativeurls ` is provided to fix this: https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L381
