### ISSUE TITLE
Using the robot account to call the vulnerability api.

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor-helm#1333]
We want to use the robot account to call the vulnerability api.
So I created a system robot account with the following permission.
```
{
   "level":"system",
   "permissions": [
      {
         "kind":"system",
         "namespace":"/",
         "access":[
            {
               "resource":"*",
               "action":"list"
            }
         ]
      }
   ]
}
```
But when I call the api(`/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}/additions/vulnerabilities`) I get a FORBIDDEN error.

What permission do I need to give so that the error doesn't occur?

Please answer.  :)

**Comment by zyyw** [comment]
This issue is tracked here:
* https://github.com/goharbor/harbor/issues/17703

Closing it now.
