### ISSUE TITLE
notary server and signer start error

### ISSUE THREAD

**Issue by songchaoqiang** [goharbor/harbor-helm#1335]
Whether it is internal or external postgresql, when the notary service starts, if the db password is wrong, it will output "Failed to Ping DB, sleep for 1 second".
<img width="469" alt="image" src="https://user-images.githubusercontent.com/109948570/198020159-d25b0e73-c4d7-4f26-89ab-0dec0b4bf266.png">

But if the password is correct, it will report an error and exit "Error starting postgres driver: pq: password authentication failed for user". why?
<img width="792" alt="image" src="https://user-images.githubusercontent.com/109948570/198020380-51d11eb6-4243-4dcc-9a8d-10cb0790449d.png">

**Comment by shanaider** [comment]
As workaround me, we using postgres-ha(bitnami) <=13 is working.

```
pgpool:
  authenticationMethod: md5
```

related: (https://github.com/goharbor/harbor/issues/16135)
