### ISSUE TITLE
Extra Volume definition for usage with Hashicorp Vault CSI

### ISSUE THREAD

**Issue by rgarcia89** [goharbor/harbor-helm#1336]
In order to you the Vault CSI SecretStoreDriver I need to add an extra Volume and VolumeMount to the chart.
However, this doesn't seem to be possible right now.

I have seen the following MR (https://github.com/goharbor/harbor-helm/pull/911) and would like to ask if someone has found an alternative solution for this case, or how this merge can be advanced?

Thanks

**Comment by rgarcia89** [comment]
@golgoth31

**Comment by zyyw** [comment]
Regarding this MR:
* https://github.com/goharbor/harbor-helm/pull/911

it depends on the demand of community. If there are a lot of community users asking for it, we will consider to get the MR into master branch.

**Comment by kyue1005** [comment]
this would be great as we are utilizing csi secrets store in our cluster

**Comment by Freydiere** [comment]
That would be a great feature as I need to mount extra volumes as well. If this could even be done for every microservice, it would be even greater
