### ISSUE TITLE
templates/database/database-ss.yaml is missing imagePullingPolicy on a initContainer

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor-helm#134]
version: 0.3.0
the same imagePullPolicy should be added to the initContainer for consistency
in templates/database/database-ss.yaml

**Comment by ywk253100** [comment]
@wu105 Any interests to open a PR for the fix?

**Comment by wu105** [comment]
I tried but not authorized to push.  it is real simple: copy the imagePullPolicy line from the containers section to the initContainers section.

**Comment by ywk253100** [comment]
OK, we'll fix it later.

**Comment by phenixblue** [comment]
@ywk253100 I submitted PR #139 to fix this

**Comment by ywk253100** [comment]
Closing this issue as the fix has been merged.
