### ISSUE TITLE
How to solve x509 certificate problem

### ISSUE THREAD

**Issue by l1douhua** [goharbor/harbor-helm#1346]
nerdctl build --insecure-registry -t xxxx:30003/zikayou/springboot-demo:v0.0.4 .
-----------------------------------------------------------------------------------------
Dockerfile:1

1 | >>> FROM xxxx:30003/zikayou/serverjre:v1
2 | RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
3 | ADD target/springboot-demo-0.0.1-SNAPSHOT.jar /springboot-demo-0.0.1-SNAPSHOT.jar

error: failed to solve: xxxx:30003/zikayou/serverjre:v1: failed to do request: Head "https://xxxx:30003/v2/zikayou/serverjre/manifests/v1": x509: cannot validate certificate for xxxx because it doesn't contain any IP SANs
time="2022-09-06T11:00:36Z" level=fatal msg="unrecognized image format"

-----------------------------------------------------------------------------------------

**Comment by zyyw** [comment]
If your harbor instance is installed via docker-compose, please try the following method to generate the certificates for harbor - ca.crt, server.crt, server.key:
```
  ### Create CA certificate
  openssl req \
      -newkey rsa:4096 -nodes -sha256 -keyout harbor_ca.key \
      -x509 -days 3650 -out harbor_ca.crt -subj '/C=CN/ST=PEK/L=BeiJing/O=VMware/CN=HarborCA'
  
  ### Generate a Certificate Signing Request
  openssl req \
      -newkey rsa:4096 -nodes -sha256 -keyout $harbor_hostname_value.key \
      -out $harbor_hostname_value.csr -subj "/C=CN/ST=PEK/L=BeiJing/O=VMware/CN=$harbor_hostname_value"
  
  ### Generate the certificate of local registry host
  if [ -n "$HARBOR_HOSTNAME" ]; then
    echo subjectAltName = DNS.1:$HARBOR_HOSTNAME > extfile.cnf
  else
    echo subjectAltName = IP:$ip_address > extfile.cnf
  fi
  openssl x509 -req -sha256 -days 3650 \
      -extfile extfile.cnf \
      -CA harbor_ca.crt -CAkey harbor_ca.key -CAcreateserial \
      -in $harbor_hostname_value.csr \
      -out $harbor_hostname_value.crt
```
where `HARBOR_HOSTNAME` is the FQDN value if you are using a domain name (if using IP instead of domain name, then `HARBOR_HOSTNAME=""`), `ip_address` is the IP value if you are using IP address instead of domain name to access harbor, and `harbor_hostname_value` is equal to HARBOR_HOSTNAME if domain name is used, otherwise it equals to `ip_address`. 
And then `harbor_ca.crt` is the `ca.crt`; $harbor_hostname_value.crt is the `server.crt`; $harbor_hostname_value.key is the `server.key`.

If your harbor instance is installed via harbor-helm, you'll need to install cert-manager to take care of the certificates.

**Comment by l1douhua** [comment]
> If your harbor instance is installed via docker-compose, please try the following method to generate the certificates for harbor - ca.crt, server.crt, server.key:
> 
> ```
>   ### Create CA certificate
>   openssl req \
>       -newkey rsa:4096 -nodes -sha256 -keyout harbor_ca.key \
>       -x509 -days 3650 -out harbor_ca.crt -subj '/C=CN/ST=PEK/L=BeiJing/O=VMware/CN=HarborCA'
>   
>   ### Generate a Certificate Signing Request
>   openssl req \
>       -newkey rsa:4096 -nodes -sha256 -keyout $harbor_hostname_value.key \
>       -out $harbor_hostname_value.csr -subj "/C=CN/ST=PEK/L=BeiJing/O=VMware/CN=$harbor_hostname_value"
>   
>   ### Generate the certificate of local registry host
>   if [ -n "$HARBOR_HOSTNAME" ]; then
>     echo subjectAltName = DNS.1:$HARBOR_HOSTNAME > extfile.cnf
>   else
>     echo subjectAltName = IP:$ip_address > extfile.cnf
>   fi
>   openssl x509 -req -sha256 -days 3650 \
>       -extfile extfile.cnf \
>       -CA harbor_ca.crt -CAkey harbor_ca.key -CAcreateserial \
>       -in $harbor_hostname_value.csr \
>       -out $harbor_hostname_value.crt
> ```
> 
> where `HARBOR_HOSTNAME` is the FQDN value if you are using a domain name (if using IP instead of domain name, then `HARBOR_HOSTNAME=""`), `ip_address` is the IP value if you are using IP address instead of domain name to access harbor, and `harbor_hostname_value` is equal to HARBOR_HOSTNAME if domain name is used, otherwise it equals to `ip_address`. And then `harbor_ca.crt` is the `ca.crt`; $harbor_hostname_value.crt is the `server.crt`; $harbor_hostname_value.key is the `server.key`.
> 
> If your harbor instance is installed via harbor-helm, you'll need to install cert-manager to take care of the certificates. And also set `externalURL=https://harbor.<harbor-ip>.nip.io` and if using ingress, also set `expose.ingress.hosts.core=harbor.<harbor-ip>.nip.io`

Thanks for putting my mind at ease , I'll try what you say @zyyw

**Comment by l1douhua** [comment]
@zyyw  i have another problem now

**Comment by l1douhua** [comment]
[root@k8s-control-plane-01 certs.d]# nerdctl login  https://douhua.com:30003
Enter Username: admin
Enter Password: 
ERRO[0006] failed to call tryLoginWithRegHost            error="failed to call rh.Client.Do: Get \"https://douhua.com:30003/v2/\": x509: certificate signed by unknown authority" i=0
FATA[0006] failed to call rh.Client.Do: Get "https://douhua.com:30003/v2/": x509: certificate signed by unknown authority

**Comment by zyyw** [comment]
@l1douhua the `x509: certificate signed by unknown authority `essentially means the vm where you run the `nerdctl login https://douhua.com:30003/` doesn't trust the ca.crt of the harbor instance. You will need to make change to make the vm trust this ca.crt of your harbor instance.

Are you able to login via `docker` cli, say `docker login https://douhua.com:30003`. If it also reports the same message as following:
```
x509: certificate signed by unknown authority
```
Please  create this folder `sudo mkdir -p /etc/docker/certs.d/douhua.com:30003` and `cd /etc/docker/certs.d/douhua.com:30003` and then 
```
sudo wget https://douhua.com:30003/api/v2.0/systeminfo/getcert --no-check-certificate
sudo mv getcert ca.crt
# restart docker (optional)
```
And then run `docker login https://douhua.com:30003` again
