### ISSUE TITLE
Add option to disallow privilegeEscalation

### ISSUE THREAD

**Issue by relief-melone** [goharbor/harbor-helm#1348]
currently there is no option to edit the securityContext of containers inside of the various deployments of helm. It would be nice if this could be added. Would gladly add a PR if there are no objections to that option. Of course if there is no valid reason to enable privilegeEscalation the best thing would be to disable it in every container that could get started.

**Comment by relief-melone** [comment]
https://github.com/goharbor/harbor-helm/pull/1349

I took the freedom to just create a PR. Feel free to reject or ask for any changes (The contributing guide was more on the acutal application so I am not sure if all here is correct)

**Comment by zyyw** [comment]
thanks for contributing to Harbor-helm, unfortunately we have no plan to support `allowPrivilegeEscalation` so far.

**Comment by relief-melone** [comment]
well the problem is you currently are. allowPrivilegeEscalation needs to be disabled explicitly and this prevents clusters which are safe by design and have policies in place to prevent pods that could "escalate" from running to being unable to run this chart
