### ISSUE TITLE
Chart cannot be installed with Helm 2.7.2 

### ISSUE THREAD

**Issue by gyuuu** [goharbor/harbor-helm#135]
Using **helm v2.7.2** `helm install --dry-run .` fails with 
Error: error validating "": error validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required

After upgrading helm to **v2.12.1** everything works just fine.

I'm not sure this should be fixed or not. The main reason I opened this issue is to provide some search results for those who face the same problem.

**Comment by ywk253100** [comment]
@gyuuu Thanks for your feedback. Harbor chart needs helm 2.8.0+ as mentioned here https://github.com/goharbor/harbor-helm#prerequisites.

**Comment by gyuuu** [comment]
I missed that, it was my fault. No changes needed, thanks.
