### ISSUE TITLE
AWS role assuming with service account missing from chart for imageChartStorage -> s3 

### ISSUE THREAD

**Issue by rzvn2600** [goharbor/harbor-helm#1353]
Hi All,

I cannot find any documentation about s3 storage for Harbor images and charts. I would like to ask if you can direct me to any suitable documentation that will explain how to use key features of the EKS cluster like roleassuming together with s3 storage for storing harbor images successfully on s3 for the registry POD.

The only specific documentation I have found was this: https://github.com/docker/docs/blob/main/registry/storage-drivers/s3.md

Thanks in advance.

**Comment by zyyw** [comment]
please take a look at this doc:
https://github.com/goharbor/harbor-helm#configuration , about this `persistence.imageChartStorage.type` section

**Comment by zyyw** [comment]
btw, if you are trying to install harbor with docker-compose, then please navigate to this page for more details:
* https://goharbor.io/docs/main/install-config/configure-yml-file/
the `Optional Parameters` section, and the `storage_service` row.

**Comment by rzvn2600** [comment]
Thanks a lot
