### ISSUE TITLE
Chart does not allow Postgresql secret instead of password

### ISSUE THREAD

**Issue by redbelow** [goharbor/harbor-helm#1358]
https://github.com/goharbor/harbor-helm/blob/185354a01bc00fb9db5943dfd331128fbcd149d8/templates/_helpers.tpl#L138

Hi, the current chart (1.11.0) does not allow secret instead of postgres password to be used (for either internal or external db). Attempting to deploy without the password for postgres will cause service failure.

I think fixing this will require changes to the harbor image itself as well as the chart.

**Comment by torsten-online** [comment]
Yes, I have the same problem. The existing secret is not used for the password of notary-server and notary-signer database, the default value "password" is used.

**Comment by figaw** [comment]
Ideally it would be possible to use an `existingSecret`, to configure both 

`NOTARY_SERVER_DB_URL` and `NOTARY_SIGNER_DB_URL` inside the pods.

---

If you need it "right now" you can specify the password under `database.external.password` in the `values.yaml`-file. 

The helm chart uses this value in the `_helpers.tpl` to generate the db_url:

`_helpers.tpl`: 
```helm
{{- define "harbor.database.notaryServer" -}}
postgres://{{ template "harbor.database.username" . }}:{{ template "harbor.database.escapedRawPassword" . }}@{{ template "harbor.database.host" . }}:{{ template "harbor.database.port" . }}/{{ template "harbor.database.notaryServerDatabase" . }}?sslmode={{ template "harbor.database.sslmode" . }}
{{- end -}}
```

where `harbor.database.escapedRawPassword` comes from `Values.database.external.password`:

```helm
{{- define "harbor.database.rawPassword" -}}
  {{- if eq .Values.database.type "internal" -}}
    {{- .Values.database.internal.password -}}
  {{- else -}}
    {{- .Values.database.external.password -}}
  {{- end -}}
{{- end -}}

{{- define "harbor.database.escapedRawPassword" -}}
  {{- include "harbor.database.rawPassword" . | urlquery | replace "+" "%20" -}}
{{- end -}}
```

The `harbor.database.notaryServer` is used by the `templates/notary/notary-secret.yaml` in both:

```yaml
  server.json: {{ tpl (.Files.Get "conf/notary-server.json") . | b64enc }}
  ...
  NOTARY_SERVER_DB_URL: {{ include "harbor.database.notaryServer" . | b64enc }}
```

And the `conf/notary-server.json` (inside the secret):

```
{ 
  ...
  "storage": {
    "backend": "postgres",
    "db_url": "{{ template "harbor.database.notaryServer" . }}"
  },
}
```

**Comment by haribtw** [comment]
Same issue here. kinda beats the point of using `existingSecret` now
