### ISSUE TITLE
Unable to start harbor-trivy due to invalid redis URL: bad escape in Go?

### ISSUE THREAD

**Issue by PentheusLennuye** [goharbor/harbor-helm#1359]
Good evening!

I've attempted to install Harbor using Terraform's "helm_release" resource.
- Helm Chart = v1.11.0
- Harbor = 12.7.0. 
 
On `kubectl -n harbor get pods`, the harbor-core, harbor-trivy-0, and harbor-jobservice pods go to CrashLoopBackoff. Chart Museum, Notary*, Portal, and Registry are just dandy. JobService and Core I need to dig further.

The `kubectl -n harbor logs harbot-trivy-0` command give this little tidbit:
`
{"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2022-12-29T21:33:40Z","version":"dev"}
{"level":"fatal","msg":"Error: constructing connection pool: invalid redis URL: parse \"redis://:PASSWORDREDACTED@redis-headless.redis.svc.cluster.local:6379/%!s(float64=5)?idle_timeout_seconds=30\": invalid URL escape \"%!s\"","time":"2022-12-29T21:33:40Z"}
`
Note the \"**%!s**\" in the escape. There appears to be an exclamation mark in between % and s which appears odd to me. I'm not a Go guy by any stretch of the imagination (Python's still my game), so your expertise on this matter is appreciated!  I tested connectivity to redis:latest with that URL and it works.

I suspect the errors noted below are in Harbor (I grepped your source for that string and came up zilch), but since I'm using Helm, I wanted to check here first before going upstream.

The relevant section of the values.yaml is:
`redis:
  type: external
  external:
    addr: redis-headless.redis.svc.cluster.local:6379
    coreDatabaseIndex: 0
    jobserviceDatabaseIndex: 1
    registryDatabaseIndex: 2
    chartmuseumDatabaseIndex: 3
    trivyAdapterIndex: 5
    password: PASSWORDREDACTED
`
Thank you!

**Comment by zyyw** [comment]
please make sure that, in your values.yaml file, it should be 
```
trivyAdapterIndex: "5"
```
and NOT
```
trivyAdapterIndex: 5
```
