### ISSUE TITLE
Disable default ingress

### ISSUE THREAD

**Issue by rakeshreddyrg09** [goharbor/harbor-helm#1366]
How can we help you?
Hi Team,

is it possible to disable default ingress in values file?
or is there any way I can override the values file..! for ingress annotations.

Thank you.

**Comment by zyyw** [comment]
Hi @rakeshreddyrg09 , assuming you are installing harbor using harbor-helm. You can do
```
git clone https://github.com/goharbor/harbor-helm.git
cd harbor-helm
```
and update/edit the values.yaml as you like, for example, updating the expose.type and expose.ingress.annotations.
And the run the following command to install harbor via harbor-helm:
```
helm install my-release --set imagePullSecrets[0].name=dockerhub-cred .
```
where you should create a docker-registry secret called dockerhub-cred, with the command below, for authorization and authentication when pulling images from DockerHub to avoid
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. 
```
kubectl create secret docker-registry dockerhub-cred \
  --docker-username=tiger \                   # replace "tiger" with your DockerHub username
  --docker-password=pass113 \              # replace "pass113" with your DockerHub password
  --docker-email=tiger@acme.com        # replace "tiger@acme.com" with the email address you used for sign-up DockerHub
```

**Comment by rakeshreddyrg09** [comment]
Hi @zyyw ,
Yeah, I am installing harbor using the helm chart.

In my case, the installation automatically uses the Gitops approach (using flux & helemrelese).
In annotations, I have to add a cider block range for AWS env and for local installation it should not append.
For that, if I have the option to create external ingress that would be better I feel.
