### ISSUE TITLE
Upgrade version from v2.2.0

### ISSUE THREAD

**Issue by itsecforu** [goharbor/harbor-helm#1371]
How to update the helm chart correctly ? 
I am currently running version 2.2.0. 
I read that there are peculiarities because of the database. 
I did not find any specific instructions. 
Maybe someone has already done it painlessly? 
Wouldn't want to lose data

Now I see theese steps:

```
1. helm pull harbor/harbor
2. helm repo update
3. helm show chart harbor/harbor:
apiVersion: v1
appVersion: 2.7.0
4. helm upgrade harbor
```

**Comment by itsecforu** [comment]
no ideas?

**Comment by zyyw** [comment]
please refer to this doc:
