### ISSUE TITLE
expose.tls.auto.commonName must set in any expose.type

### ISSUE THREAD

**Issue by willzhang** [goharbor/harbor-helm#1374]
## what happend
harbor version v2.7.0

expose.tls.auto.commonName must set in any expose.type

here say:  [     # The common name used to generate the certificate, it's necessary](https://github.com/goharbor/harbor-helm/blob/a658bcafeb6e4e9797763171fd0c8a0dc2c43d2b/values.yaml#L21)
      # The common name used to generate the certificate, it's necessary
      # when the type isn't "ingress"

Even if the type is ingress, this parameter must be set too.

## example

most is default values, but `expose.tls.auto.commonName` can not be ignore, otherwise login harbor UI will failed.This should be noted for users.

```
helm upgrade --install harbor harbor/harbor --namespace harbor --create-namespace \
  --set expose.type=ingress \
  --set expose.ingress.className=nginx \
  --set expose.ingress.hosts.core=core.harbor.domain \
  --set expose.ingress.hosts.notary=notary.harbor.domain \
  --set externalURL=https://core.harbor.domain \
  --set expose.tls.auto.commonName=core.harbor.domain \
  --set harborAdminPassword="Harbor12345"
```

**Comment by zyyw** [comment]
It may not be sure that helm install Harbor in `ingress` expose type requiring `expose.tls.auto.commonName`
example:
```
helm install harbor-t2 --set persistence.enabled=false,externalURL=https://harbor.10.92.93.131.nip.io,expose.ingress.hosts.core=harbor.10.92.93.131.nip.io,imagePullSecrets[0].name=dockerhub-cred  .
```
