### ISSUE TITLE
Add a global registry address

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-helm#1381]
Currently no registry definition in the values.yaml, so user needs to update all the components image value if they want to pull images from self registry in the private environment, it would be great if user can just override one global registry for all deployment images.

**Comment by zyyw** [comment]
example:
```
 image: {{ .Values.pliant.addon_ansible.image.registry }}/{{ .Values.pliant.addon_ansible.image.repository }}:{{ .Values.pliant.addon_ansible.image.tag }}
```
