### ISSUE TITLE
New charts are not visible in the Harbor GUI after being pushed with helm-cm but the chart is visible in the s3 bucket

### ISSUE THREAD

**Issue by EnriqueAlmanza** [goharbor/harbor-helm#1393]
**Expected behavior and actual behavior:**
Pushed helmcharts are not visibile in the Harbor GUI.
The persistent is configured with s3 bucket and there you can see the pushed charts only.
the index.yaml file is not updated (currently more than 100K entries)

**Steps to reproduce the problem:**
Helms are pushed to harbor using helm cm-push . harbor
The chart is pushed and appears in the s3 bucket correctly, nevertheless the chart is not visible in the Harbor GUI
the index.yaml file is as well not updated. 

The workaround is to delete the index.yaml file and push again, then the index.yaml is regenerated and chart appears in Harbor

Another workaround I found in the chartmuseum documentation can be seen here (https://github.com/helm/chartmuseum#cache-interval), but I dont find how to set up that paratmeter using the helm chart (is there a way? and if so, is that the right way to solve the problem?)

**Versions:**
- Helm harbor version 1.10.3
- harbor version: Version v2.6.3-1297af6c

**Comment by zyyw** [comment]
Hi @EnriqueAlmanza , the chartmuseum is going to be deprecated in harbor oss v2.8.0. The support for using chartmuseum with harbor is limited. Please try to use OCI compatible chart with Harbor.

**Comment by EnriqueAlmanza** [comment]
Hi @zyyw thank you for the information, is there a way to pass a environment variable (--cache-interval=<interval>) to chartmuseum which is currently in support?
