### ISSUE TITLE
Update Helm Chart to match the config change in storage_service.redirect.disabled in harbor.yml.tmpl to storage_service.redirect.deactivate

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-helm#1408]
related to https://github.com/goharbor/harbor/pull/14615

**Comment by zyyw** [comment]
@Vad1mo the PR you mentioned just change `disabled` to `disable`, not `deactivate`. 
In harbor-helm, I believe it's:
* https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L276
