### ISSUE TITLE
Default Admin Password invalid 

### ISSUE THREAD

**Issue by ray2211** [goharbor/harbor-helm#1414]
![2023-02-21_18h18_35](https://user-images.githubusercontent.com/73368915/220317164-9339aec0-050d-459e-a558-b38bb0b8e9af.png)

Everything up and running normally:
![2023-02-21_18h19_22](https://user-images.githubusercontent.com/73368915/220317420-ae05901f-6b1d-45a6-b493-d2d34bb0fd24.png)

i use nodeport and my externalURL is 
externalURL: http://10.2.166.109:30002

when i login fail
there is no any  error logs in core 

please help me...

**Comment by zyyw** [comment]
Hi @ray2211 , please check it following suggestions:
1. is this a fresh installed harbor instance without reset password? or did you update the admin password
2. could you please check the log in nginx pod to trace the network traffic
3. which harbor-helm version are you using?

**Comment by fengshunli** [comment]
@ray2211 update harbor_user set password_version='sha1' where user_id=1;

**Comment by fengshunli** [comment]
After updating the harborAdminPassword password, I can’t log in. This needs to be fixed. @zyyw 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/18587688/221153289-cbf567c2-229a-4f47-b00b-765c22c32bc2.png">


<img width="491" alt="image" src="https://user-images.githubusercontent.com/18587688/221153569-acf073ce-f711-4643-a8a1-26321921fb8c.png">

**Comment by stone-xzt** [comment]
I encountered the same problem

**Comment by stone-xzt** [comment]
harbor-helm-1.10.4
v2.6.4

**Comment by stone-xzt** [comment]
@zyyw

**Comment by stone-xzt** [comment]
![1677306318036](https://user-images.githubusercontent.com/83194479/221342278-9e2ba042-de16-4b58-8d7e-7377a8aed4f8.png)

**Comment by stone-xzt** [comment]
![1677306318036](https://user-images.githubusercontent.com/83194479/221342301-99ededd6-07e6-49b2-ac36-7f47dd451c06.png)

**Comment by stone-xzt** [comment]
@ray2211 You need to specify the "externalURL"

**Comment by MinerYang** [comment]
by settting the admin harbor paasword, you need to either through the UI or modify the db manually.
please refer to [How to reset admin password?](https://github.com/goharbor/harbor/wiki/Harbor-FAQs)
Will close this issue for now, if you any any further question feel free to reopen it.
