### ISSUE TITLE
index.yaml file is not updated after pushing new chart

### ISSUE THREAD

**Issue by EnriqueAlmanza** [goharbor/harbor-helm#1418]
Expected behavior and actual behavior:

The persistency is configured with s3 bucket and there you can see the pushed charts only BUT the index.yaml file is not updated (currently more than 100K entries) hence pushed new charts are also not visibile in the Harbor GUI.

Steps to reproduce the problem:
Helms are pushed to harbor using helm cm-push . harbor
The chart is pushed and appears in the s3 bucket correctly, nevertheless the chart is not visible in the Harbor GUI
the index.yaml file is as well not updated.

If I delete the index.yaml manually and push again the index.yaml is regenerated and the new charts appears in harbor.

Question:
I want to manually set the "--cache-interval=1m" so that the index.yaml is always up to date, is there a way to do so with the current helm chart?

Versions:

Helm-chart harbor version 1.10.3

**Comment by EnriqueAlmanza** [comment]
issue is still present. The Index file does not update when pushing new charts hence the new charts are not visible in harbor :(

**Comment by EnriqueAlmanza** [comment]
any suggestion?

**Comment by EnriqueAlmanza** [comment]
still the issue

**Comment by EnriqueAlmanza** [comment]
?

**Comment by zyyw** [comment]
As chartmuseum is deprecated and removed in Harbor oss v2.8.0 (harbor-helm v1.12.0), the support of it is limited. 
Please try to convert them into OCI-compatible artifacts and then push them to Harbor afterwards.

How to convert charts to OCI-compatible artifacts?
* https://github.com/goharbor/harbor/wiki/Migrate-helm-chart-to-oci-registry-in-Harbor
