### ISSUE TITLE
enable persistence per volume

### ISSUE THREAD

**Issue by Brice187** [goharbor/harbor-helm#1424]
currently the helmchart only allows to globally enable persistence for the harbor volumes.

**Comment by zyyw** [comment]
normally users just want to configure the persistence in one place for all of registry, jobservice, redis, database, and trivy.
May i know what your use case is?

**Comment by Brice187** [comment]
* registry is saved on s3
* database is a longhorn pvc
* redis/jobservice do not have to be a pvc at all
