### ISSUE TITLE
existingSecretAdminPassword is not working

### ISSUE THREAD

**Issue by hashanmp** [goharbor/harbor-helm#1429]
Hello!
I am using helm chart version 1.11.1 to deploy harbor on our EKS cluster using argoCD but for some reason even when I use existingSecretAdminPassword parameter it won't pick up the Kubernetes secret for admin user. 
also I am using `existingSecret` for external database it works without an issue.
can someone help me here? 🙏 

here is my value file looks like
```
harbor:
  ---
  existingSecretAdminPassword: "harbor-creds"
  existingSecretAdminPasswordKey: "HARBOR_ADMIN_PASSWORD"
  --
```

_Originally posted by @hashanmp in https://github.com/goharbor/harbor-helm/discussions/1428_

**Comment by zyyw** [comment]
As one community user mentioned in the following discussion thread, the feature of existingSecretAdminPassword is in master branch and tagged to be released in the future version of 1.12.0: 
* https://github.com/goharbor/harbor-helm/discussions/1428

PR related to this existingSecretAdminPassword topic:
https://github.com/goharbor/harbor-helm/pull/1274
