### ISSUE TITLE
Make the Repo to be indicated as the "Official" repo for Harbor

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-helm#1433]
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/1492007/222788144-0dcce463-910f-4855-920f-a0ca78c3ff38.png">

In Artifact Hub, the official status means that the publisher owns the software deployed by a package. If we consider the example of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the official status the publisher should be the owner of the Consul software (HashiCorp in this case), not just the chart.

The official status can be granted at the repository or package level. When it is granted for a repository, all packages available on it will display the official badge, so all packages in the repository must be official. If only some of the packages in your repository are official, please list them in the Official packages field when submitting the official status request.

Before applying for this status, please make sure your repository complies with the following requirements:

The repository has already obtained the [Verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
All official packages available in the repository provide a README.md file with some documentation that can be displayed on Artifact Hub.
Once you have verified that the requirements are met, please file an issue [using this template](https://github.com/artifacthub/hub/issues/new?assignees=&labels=official+status+request&template=official-status-request.md&title=%5BOFFICIAL%5D+Your+repository+or+project+name) to apply.

See:
https://artifacthub.io/docs/topics/repositories/#official-status

**Comment by OrlinVasilev** [comment]
https://github.com/artifacthub/hub/issues/2970

**Comment by OrlinVasilev** [comment]
![image](https://user-images.githubusercontent.com/7236111/230599869-fa135982-b89c-43ba-8fe0-8e4d97a5ab0c.png)
Done :)
