### ISSUE TITLE
Registry component has downtime in HA mode with "Recreate" update strategy

### ISSUE THREAD

**Issue by hauke-d** [goharbor/harbor-helm#1469]
We are running a HA deployment with 2 registry replicas and an `updateStrategy.type` of `Recreate` (which we need for the stateful components). Even though our registry replicas are stateless without volumes, both of them are taken down at the same time when we apply updates due to the `Recreate` option. So we have downtime whenever there are changes, although we would like to provide an HA service.

Opened #1455 as a fix proposal, so the strategy can be overridden for each component.

**Comment by zyyw** [comment]
why do we have to assign `Recreate` for stateful components, such as `database` and `redis`?

**Comment by zyyw** [comment]
As your env doesn't support `ReadWriteMany`, the update strategy should be set as `Recreate`.

**Comment by cfiehe** [comment]
@zyyw
What about making the global update strategy configurable in order to make it possible to set `maxSurge` and `maxUnavailable` for the rollingUpdate strategy?

**Comment by MrMarkW** [comment]
@zyyw I am experiencing a similar issue. I have a mixed AWS EKS environment: JobService with PVC EBS (ReadWriteOnce) and Registry with S3 (ReadWriteMany).  

Using the updateStrategy.type: Recreate global causes the Registry to not be HA. 

A way to make this passive would be to keep the global, but if updateStrategy is set at the component level, use it vs the global.

```
updateStrategy:
  type: RollingUpdate
jobservice:
  updateStrategy:
    type: Recreate
```

**Comment by cfiehe** [comment]
@MrMarkW I am completely with you. Our deployment scenario is nearly identical. We also use an S3 as storage backend. I have already implemented what you, me and others need: Having a global default combined with the capability to define an update strategy individually for a specific deployment. Unfortunately, the pull request was rejected: https://github.com/goharbor/harbor-helm/pull/1524/files.

**Comment by Maltazar** [comment]
this is still need for us also

**Comment by 98jan** [comment]
also needed here, without this feature, I have issues running harbor on environments with only 3 nodes and harbor runs on every node.

For now used a patch to set maxSurge with FluxCD to 0. Better would be to have this feature in the helm chart directly.
