### ISSUE TITLE
Chart `1.12.0` (Harbor `2.8.0`) is missing in https://helm.goharbor.io/index.yaml

### ISSUE THREAD

**Issue by aureq** [goharbor/harbor-helm#1478]
I noticed version [`1.12.0`](https://github.com/goharbor/harbor-helm/releases/tag/v1.12.0) of this helm Chart has been released. However, after refreshing my local helm cache, I can't see the new release (`helm search repo -l harbor`).

Looking at https://helm.goharbor.io/index.yaml and it seems the Chart repository hasn't been updated. Maybe an github action didn't run?

**Comment by aureq** [comment]
Seems related to https://github.com/goharbor/harbor-helm/issues/1418

**Comment by aureq** [comment]
Thanks @zyyw 

Maybe as a suggestion, it would be great to publish the GitHub release when such PRs are merged.
I was confused to get the release notification but the repo not being updated yet.

Thank you

**Comment by zyyw** [comment]
Thank you for the suggestion. We will revise our release process in the future to publish the GitHub releases after such PRs are merged.

**Comment by aureq** [comment]
Thank you. I'll close this issue. Great work.
