### ISSUE TITLE
Github GHCR as proxy cache missing in helm chart

### ISSUE THREAD

**Issue by AndreasPelzer** [goharbor/harbor-helm#1489]
**Expected behavior and actual behavior:**
Harbor provides [Github GHCR as proxy cache](https://github.com/goharbor/harbor/pull/16834). However, the [helm chart does not](https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-cm.yaml#L51).
Error message in Harbor when setting up a project with Github GHCR as proxy: 
> bad request: "unsupported registry type github-ghcr"

**Steps to reproduce the problem:**
- setup a ghcr.io registry
- try to create a new project with ghcr as proxy cache

**Versions:**
- harbor versions: >=[2.6.0]

**Additional information:**
See also https://github.com/goharbor/harbor/issues/17527 .
Suggestion: it might be sufficient to align [the helm chart](https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-cm.yaml#L51) with [harbor](https://github.com/goharbor/harbor/blob/bf6389e6c824a01cf6cda1ee63a0fd2d26e3b798/make/photon/prepare/templates/core/env.jinja#L42) regarding PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE, i.e. from
`PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: "docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay,docker-registry,jfrog-artifactory"`
to
`PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: "docker-hub,harbor,azure-acr,aws-ecr,google-gcr,quay,docker-registry,github-ghcr,jfrog-artifactory"`

**Comment by jc01rho** [comment]
+1
