### ISSUE TITLE
Chart Museum URL is not configurable

### ISSUE THREAD

**Issue by darend** [goharbor/harbor-helm#149]
When installing the chart it should be possible to set the `CHART_URL` for chart museum. This allows the registry to return absolute URLs instead of relative ones. This is required when integrating with tools that expect absolute, such as Spinnaker.

This Configmap entry needs to be templatized:
https://github.com/goharbor/harbor-helm/blob/1.0.0/templates/chartmuseum/chartmuseum-cm.yaml#L25

Related to https://github.com/goharbor/harbor/issues/6572

**Comment by ywk253100** [comment]
#150 is reverted by https://github.com/goharbor/harbor-helm/pull/165, let's reopen the issue.

**Comment by Jean-PhilippeGouin** [comment]
Hi,

Do you know when this issue will be resolved?
And why the patch has been reverted?

Thanks!

**Comment by ywk253100** [comment]
Fixed by https://github.com/goharbor/harbor-helm/pull/267
