### ISSUE TITLE
Add imagePullSecrets and namespaces to helm template

### ISSUE THREAD

**Issue by jimangel** [goharbor/harbor-helm#152]
You can see the example below for imagePullSecrets and the same could be done for namespaces.

```
spec:
      {{- if .Values.image.pullSecret -}}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
```

This will help companies deploy harbor using helm + private internal repository and/or scope it to a namespace.

**Comment by ywk253100** [comment]
Any interests to contribute this part?

**Comment by jimangel** [comment]
I can own this, I am busy for the next 2 weeks but should have time after to complete.. Any thoughts on moving the repo into the "official" helm charts like we discussed?

**Comment by ywk253100** [comment]
@jimangel That's ok. 
And I comment on the #67 about publishing Harbor chart to a public chart repository.

**Comment by Syleron** [comment]
any progress on namespaces?
