### ISSUE TITLE
Unauthorized access error when pushing image to Harbor

### ISSUE THREAD

**Issue by VascoBotelho** [goharbor/harbor-helm#1520]
Hey, I'm new to Harbor and I have a fresh Harbor installation using Helm in my Kubernetes Cluster, the following is the command I used to install Harbor.

`helm install harbor harbor/harbor --set expose.type=ingress --set expose.ingress.hosts.core=harbor.domain.com --set externalURL=https://harbor.domain.com --set harborAdminPassword=admin -n harbor --create-namespace`.

After the installation, I logged into the Harbor with no problems, change the password, and created a new project named test, then
I logged into the registry using `docker login harbor.domain.com -u admin -p password` with success, but when I tried to push an image `docker image push harbor.domain.com/test/image:latest` I got the following:
`unauthorized: unauthorized to access repository: test/image, action: push: unauthorized to access repository: test/image, action: push`.

> harbor version: v2.8.2-d4c34dcc
> docker engine version: 23.0.6
> k3s version: v1.26.4

**Comment by zyyw** [comment]
@VascoBotelho can you please try to create the test directory first and then `docker push harbor.domain.com/test/image:latest` next?
Please let us know whether this still persists.

**Comment by zyyw** [comment]
@VascoBotelho by `change the password`, how do you change the admin password?
It should be changed via the Harbor Portal.
<img width="352" alt="Screenshot 2023-06-14 at 16 25 50" src="https://github.com/goharbor/harbor-helm/assets/6709992/600295eb-ed2b-4ec9-8688-538fde0eb31b">

Tried the following steps and cannot reproduce the problem mentioned in this issue:
1. Created a kind cluster k8s version 1.25.1 & installed nginx-ingress v1.5.1
2. git clone the harbor-helm code and check out to the v1.12.2 tag (harbor 2.8.2) 
3. deploy harbor using harbor-helm 
```
helm install harbor-ingress-20230614 --set persistence.enabled=false,externalURL=https://harbor.1.2.3.4.nip.io,expose.ingress.hosts.core=harbor.1.2.3.4.nip.io,imagePullSecrets[0].name=dockerhub-cred  .
```
4. change the admin password via the Harbor Portal
5. create a `test` project in Harbor portal
6. docker login harbor.1.2.3.4.nip.io -> success
7. docker push `harbor.1.2.3.4.nip.io/test/nginx:1.13.12` -> success
8. docker image push `harbor.1.2.3.4.nip.io/test/redis:latest` -> success

**Comment by VascoBotelho** [comment]
@zyyw Yes, I changed the password through the Harbor Portal, one thing I didn't mention is that I'm using k3s with docker runtime, so when I do `helm install harbor harbor/harbor ...` the cluster deploys docker containers to run the Harbor application.

**Comment by VascoBotelho** [comment]
Hey @zyyw, I recently picked this up again, and I discovered it has something to do with CloudFlare that I'm using for the domain. I'm still having the same problem and haven't found a solution, I did find this on [StackOverflow](https://stackoverflow.com/questions/75904283/harbor-configure-http-using-cloudflare), but it didn't work for me.

if you or anyone reading knows a solution, I would appreciate,
thank you

**Comment by sunflower-lmt** [comment]
@VascoBotelho  Setting the registry.relativeurls property to true fix this issue

**Comment by VascoBotelho** [comment]
> @VascoBotelho Setting the registry.relativeurls property to true fix this issue

This was the answer to my issue, thank you @sunflower-lmt
