### ISSUE TITLE
Silent upgrade to postgres14 in :dev-image

### ISSUE THREAD

**Issue by Brice187** [goharbor/harbor-helm#1526]
I ran into a weird issue:

The Kubernetes-Node which held the harbor-database-0 pod restarted tonight and the pod got scheduled on another node. 

Because of the pull policy `IfNotPresent`, the Pod was scheduled on another Node which held a longhorn-replica of the database-pv. Because the `:dev`-image was cached, no new image was pulled. But because of a prior "silent" upgrade to Postgres14, the *pg13-data* folder in the PV was empty and eventually got recreated. In the end, I had an empty database.

The solution is to temporaly change the pullpolicy to always or pull the images manually on the nodes. 

In the future, you should just stick to a stable image-tag.

Just fyi :)

**Comment by Brice187** [comment]
Just for documentation

**Comment by zyyw** [comment]
@Brice187 , to use a fixed version, I would suggest you install harbor-helm with a release version (1.12.2) instead from using the master branch.
