### ISSUE TITLE
Override namespace via values

### ISSUE THREAD

**Issue by morozovcookie** [goharbor/harbor-helm#1529]
Hello! I would like to purpose to add a `namespaceOverride` variable to the `values.yaml`. 

In my case I am use a single big chart where I set up all components as dependencies. By default all chart will be installed in `{{ .Release.Namespace }}`, but I want to control it behavior.

**Comment by zyyw** [comment]
Hi @morozovcookie you can use `--namespace` in helm 2, or use `--namespace` and `--create-namespace` in helm 3 to manage the namespace. 
Reference:
* https://stackoverflow.com/a/65751410

**Comment by morozovcookie** [comment]
No, i can not use this options. It is works only if I will be install only harbor chart. 

But I need to install a chart which contains harbor as dependency. In this case, with your manifests, it will be installed in the single namespace, that will be provided through command line options as you described earlier.

But I want to control this behavior. I have a single chart with some dependencies. I want to have an options to put each dependency in the separate namespace. This feature is available in [cert-manager](https://github.com/cert-manager/cert-manager), [happroxy charts](https://github.com/haproxytech/helm-charts) and [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).
