### ISSUE TITLE
jobserver Service keeps restarting,The lack of the certificate /etc/core/private_key.pem？

### ISSUE THREAD

**Issue by GounGG** [goharbor/harbor-helm#154]
error log:
```
2019-02-12T07:58:25Z [ERROR] [options.go:38]: failed to read private key open /etc/core/private_key.pem: no such file or directory
panic: load configurations error: missing logger config of job service


goroutine 1 [running]:
main.main()
	/go/src/github.com/goharbor/harbor/src/jobservice/main.go:45 +0x29d
```
Where can I find this certificate??

**Comment by ywk253100** [comment]
Are you using the chart to install Harbor? What is the version are you using? How do you config it?

**Comment by GounGG** [comment]
> Are you using the chart to install Harbor? What is the version are you using? How do you config it?

yes,i'm using char,the installed version is :  
```shell
$ helm list
hub            	1       	Tue Nov 20 09:33:06 2018	DEPLOYED	harbor-dev      	hub
```
Only the configuration of data persistence has been modified.

**Comment by ywk253100** [comment]
Do not use the chart on the master branch as said here https://github.com/goharbor/harbor-helm#helm-chart-for-harbor, it is under development. Use the stable version instead.

**Comment by GounGG** [comment]
> Do not use the chart on the master branch as said here https://github.com/goharbor/harbor-helm#helm-chart-for-harbor, it is under development. Use the stable version instead.

Thank
