### ISSUE TITLE
Harbor core configuration managed by helm's triggered Job

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [goharbor/harbor-helm#1544]
Harbor chart is making a great work in terms of setting up the service, but in my opinion it lacks the ability to initialize the service configuration.

From an application standpoint, I can solve this in 3 ways:
1. Configure it manually after installation
2. Set the environment variable CONFIG_OVERWRITE_JSON with required values (e.g. with Kustomize patch)
3. Run an API request to adjust the configuration.

Option no. 3 IMO could be implemented with Helm job template with helm triggers and fill this gap.

Option no. 2 was discussed and eventually rejected ( #1021 )
Additionally, it isn't perfect because setting the mentioned variable makes Harbor unwilling to get any configuration changes made by API request. It is making, i.e., automated backups harder as the service cannot be set to ReadOnly with an API request.

I could provide a PR with such configuration Job as I'm going to make it for our internal Harbor deployments.

But what do you think?

**Comment by zyyw** [comment]
Hi @tomaszkrzyzanowski , we have this [PR](https://github.com/goharbor/harbor-helm/pull/1147) merged in. The `CONFIG_OVERWRITE_JSON` will be available in harbor-helm 1.13.0 (Harbor oss 2.9.0) in the near future.

**Comment by tomaszkrzyzanowski** [comment]
Sounds cool, there is still a little issue with switching the app to ReadOnly mode while the env is set, but I will ask about this in Harbor main repo issue. The docs are suggesting the backup should be made in RO mode but when the env is set, the core is rejecting the requests trying to change the service mode to RO.
