### ISSUE TITLE
helm templates currently do not support limits.cpu,limits.memory,requests.cpu,requests.memory

### ISSUE THREAD

**Issue by jimangel** [goharbor/harbor-helm#155]
I am happy to PR this functionality in, but does anyone know the recommended settings or minimum requirements for each component?

**Comment by ywk253100** [comment]
@jimangel There is a configuration item `resources` for each components in `values.yaml`, it contains `requests` but no `limits` and I find that the configuration doesn't apply to some components, such as `core`. 

It'll be appreciated if you can contribute the `limits` part and I think these configuration can be commented by default.

**Comment by ywk253100** [comment]
@jimangel  The PR #172 is closed automatically when we fixing #48, you need to re-do the works in the PR and commit them again if you would like, sorry for that.
