### ISSUE TITLE
Unable to configure updateStrategy per service

### ISSUE THREAD

**Issue by mac-chaffee** [goharbor/harbor-helm#1552]
The helm chart has one `updateStrategy` value which applies to both the jobservice and the registry. I have a use-case where I want the updateStrategy for the jobservice to stay as "Recreate" while the registry uses "RollingUpdate".

I've been running the registry for a while now using 2 replicas and a ReadWriteMany volume with no issues. This is possible because my volumes are NFS-based which I've configured to guarantee the read-after-write consistency that the registry requires: https://github.com/distribution/distribution/issues/1176

But I'm not sure how the jobservice would react to having two replicas, so I left that as a single replica which needs the "Recreate" strategy due to mounting a ReadWriteOnce PVC. So it would be nice to be able to configure these updateStrategies independently. 

Thoughts? How would you prefer a migration to work? Just remove the top-level `updateStrategy` or treat it as a fall-back if `registry/jobservice.updateStrategy` isn't set?

**Comment by zyyw** [comment]
Similar topic issue:
* https://github.com/goharbor/harbor-helm/issues/1469
