### ISSUE TITLE
YAML error with trace attributes

### ISSUE THREAD

**Issue by Tearix** [goharbor/harbor-helm#1556]
Using default values with enabled tracing with any attributes:
```
trace:
  enabled: true
  attributes:
    application: harbor
```

Leads to:

```Error: YAML parse error on harbor/templates/core/core-cm.yaml: error converting YAML to JSON: yaml: line 53: did not find expected key```

Render with --debug shows `TRACE_ATTRIBUTES: "{"application":"harbor"}"`

Looks likes there is problem with qoutes at [_helpers.tpl#L477](https://github.com/goharbor/harbor-helm/blob/master/templates/_helpers.tpl#L477)
```
  {{- if .Values.trace.attributes }}
  TRACE_ATTRIBUTES: "{{ .Values.trace.attributes | toJson }}"
  {{- end }}
```

Possible WA - single qoutes `TRACE_ATTRIBUTES: '{{ .Values.trace.attributes | toJson }}'`

**Comment by zyyw** [comment]
Thanks for contributing to harbor-helm!
Can you it with `TRACE_ATTRIBUTES: '{{ .Values.trace.attributes | toJson }}'` and submit a PR if it works?
Thanks

**Comment by zyyw** [comment]
@Tearix

**Comment by Tearix** [comment]
@zyyw check please
