### ISSUE TITLE
`1.13.0` Helm Chart Removed

### ISSUE THREAD

**Issue by ChrisJBurns** [goharbor/harbor-helm#1592]
We have deployed version `1.13.0` of the Harbor Helm Chart which was accompanying Harbor `2.9.0` but now the Helm Chart has been removed? 

We know this because our Renovate Bot detected a new version of the Chart as shown in the image below. But ever since it's been merged, the Chart has been removed from the Harbor Helm repo.

![image](https://github.com/goharbor/harbor-helm/assets/29541485/7d7d0beb-0eb4-4fe2-8693-070417fdb9bb)

**Comment by jakeforge** [comment]
Looks like harbor itself removed 2.9.0 which is the version helm 1.13.0 had.  https://github.com/goharbor/harbor/releases/

**Comment by viceice** [comment]
It's back, so helm chart v1.13 should be published again

**Comment by ChrisJBurns** [comment]
Does seem like it's available yet https://github.com/goharbor/harbor-helm/releases/tag/v1.13.0

**Comment by nbjohnson** [comment]
Yeah I also dont see the new helm chart, would be great to be able to get it back to start testing 2.9

**Comment by ChrisJBurns** [comment]
If the 2.9.0 got removed, I'm hoping that the no new code was introduced? As this would be quite a major problem if true

**Comment by jakeforge** [comment]
Looks like it's back now.

**Comment by zyyw** [comment]
Thank you all for your concern of harbor-helm 1.13.0 (Harbor oss 2.9.0). 
There was an license issue in original release of Harbor oss v2.9.0. We revoked the original release of Harbor oss v2.9.0 and its corresponding release of harbor-helm. Now, the Harbor oss v2.9.0 is re-published and harbor-helm 1.13.0 also re-published. 
There is no major change between the original release of harbor-helm 1.13.0 and the new release 1.13.0 except for this PR:
* https://github.com/goharbor/harbor-helm/pull/1585
