### ISSUE TITLE
Incompatibility with AWS NLB + nginx ingress in EKS

### ISSUE THREAD

**Issue by NicoForce** [goharbor/harbor-helm#1598]
Greetings,

I deployed harbor to my cluster; however, with an nginx ingress combined with NLB, I'm unable to push any images.

If I create a port forward to the core service, or to the registry directly, pushing images works fast and without issues.

However, when using the ingress external hostname to push an image, it's very slow and ultimately the command gets stuck and never finishes, and there's no error message.

If anybody has seen this scenario before, any suggestion is accepted!

**Comment by zyyw** [comment]
Do you got a chance to try ALB?
* https://github.com/goharbor/harbor-helm/blob/main/values.yaml#L36

**Comment by antoineco** [comment]
Amazon NLB is a [layer 4 load balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html); it doesn't know about the HTTP protocol (layer 7) and therefore doesn't know what backend to route requests to based on the URL path.
For a container registry, URLs with the `/v2/` prefix must be routed to the [OCI registry](https://github.com/distribution/distribution) that ships with Harbor, whereas (most) other requests are to be routed to the Harbor core.

That also means that the [Ingress object](https://github.com/goharbor/harbor-helm/blob/v1.13.0/templates/ingress/ingress.yaml) distributed with this Helm chart cannot be backed by an NLB alone, it requires another Ingress controller behind it, such as [ingress-nginx](https://github.com/kubernetes/ingress-nginx). Then you need to forward traffic from the NLB to that Ingress controller's NodePort, not to Harbor's.

---

In case you don't have an Ingress controller deployed in your cluster, you can serve Harbor behind a statically configured NGINX [using this Helm chart](https://github.com/goharbor/harbor-helm/blob/86dd759ac03e9c781c25a6c0d71ec8d95368fb32/values.yaml#L1-L4):

```yaml
# values.yaml
expose:
  type: nodePort  # instead of the default "ingress" value
```

This will generate a Service of type NodePort inside your namespace. After that, you need to forward traffic from the NLB to that NodePort, not to Harbor's.

**Comment by antoineco** [comment]
For this you need either:
- a _public_ ALB (exposed to the internet)
- [VPC peering](https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html)

Both topics are very distant from the original discussion about the Harbor Helm chart.

**Comment by NicoForce** [comment]
> (...) such as [ingress-nginx](https://github.com/kubernetes/ingress-nginx) (NLB _does not support Ingress_).

Ingress Nginx does support work with NLB, I've been using it as such for a few years by now, and most applications work without the need for ALB.

> Amazon NLB is a [layer 4 load balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html); it doesn't know about the HTTP protocol (layer 7) and therefore doesn't know what backend to route requests to based on the URL path.

Yes, but nginx is the layer 7 in the scenario, and is in charge of sending traffic over to the right app. See [this guide from aws](https://aws.amazon.com/blogs/opensource/network-load-balancer-nginx-ingress-controller-eks/), more specifically, the `service.beta.kubernetes.io/aws-load-balancer-type: nlb` annotation in [this script](https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/aws/deploy.yaml).

**Comment by antoineco** [comment]
@NicoForce you are twisting my words and quoting things out of context. I didn't say that ingress-nginx couldn't work _with_ NLB, I said that NLB and ingress-nginx had to be deployed together:

> the Ingress object distributed with this Helm chart cannot be backed **by an NLB alone**, it requires an Ingress controller behind it, **such as ingress-nginx**

**Comment by NicoForce** [comment]
My bad, but the gist of this ticket is that Harbor doesn't work when deployed with a working Nginx Ingress + NLB. Only worked for me with the ALB ingress.

I'll update the description on the initial comment to avoid confusion.

**Comment by antoineco** [comment]
I'm running Harbor behind NLB -> ingress-nginx inside EKS, let me know if I can provide any further information.

A few things I had to pay attention to:
- All Ingress objects that serve `/v2` need the annotation `nginx.ingress.kubernetes.io/proxy-body-size: "0"`, because image blobs are likely to overflow the default value. The Helm chart does it by default on its own Ingress, but maybe you are using a custom Ingress object like I do.
- The AWS Load Balancer Controller expects VPC networks to be tagged with `kubernetes.io/role/elb` for [subnet discovery]( https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/subnet_discovery/). Maybe your NLB's listeners ended up with stale targets because the subnets your Kubernetes nodes are deployed to don't have that tag. In any case, the controller should report issues via API events on the associated Service (`kubectl describe service ...`).

**Comment by NicoForce** [comment]
Regarding those points you mentioned, NLB + nginx ingress is already working for multiple applications and services (linkerd, flagger, prometheus stack, longhorn, nexus, etc.), only harbor was not working as expected.

Also I checked that the harbor helm chart does add `nginx.ingress.kubernetes.io/proxy-body-size: "0"` and that annotation ended in the final ingress (it was not being overwritten).

I'll go over testing again, but I'm pretty sure it just does not work with NLB + ingress nginx, at least in my setup.

**Comment by NicoForce** [comment]
I didn't get to test the issue again, as I don't have a necessity to change at the moment, this might change in the near future thanks to AWS new costs for Ipv4.

Will close for now, thanks for the help so far.
