### ISSUE TITLE
Using harbor helm chart as subchart

### ISSUE THREAD

**Issue by manang** [goharbor/harbor-helm#1601]
Hi,
I'm trying to use the harbor chart as subchart, I changed the main Chart.yaml to the following version:
`apiVersion: v2

name: harbor

version: 1.0.0

dependencies:
  - name: harbor
    version: 1.13.0
    repository: https://helm.goharbor.io`

After I launch the dependency build:
`helm dependency build  `
And after the install command:
`helm install harbor harbor/ \
    --namespace harbor \
    --create-namespace`

The problem is that I obtain the following error:
`Error: INSTALLATION FAILED: no Secret with the name "harbor-core" found`

Do you know how I can correct this issue?
Thanks a lot
Angelo

**Comment by zyyw** [comment]
hi @manang, could you please explain how do you use harbor-helm as a sub-chart?
Maybe you should just use harbor-helm to install Harbor without using it as a "sub-chart".

**Comment by manang** [comment]
Hi,
i needed to include it in argocd environment.
My error was that the values.yaml needed a level more, it has to start with "harbor:".
Thanks a lot for your answer
