### ISSUE TITLE
logging configuration

### ISSUE THREAD

**Issue by neottil** [goharbor/harbor-helm#1608]
In helm installation there isn't possibility to configure logging. It would be great to standardize the logs of the various modules and have the ability to log to json format files.
[https://github.com/goharbor/harbor-helm/discussions/1604](opened discussion)

**Comment by zyyw** [comment]
maybe you wanna take a look at this:
* https://github.com/goharbor/harbor-helm/blob/main/values.yaml#L333-L334

**Comment by neottil** [comment]
I've seen this. But it's only the log level. The log formats of the various modules are different, and aren't in json.
In my opinion it's good idea standarize the log format in all modules, maybe in json. This would allow (in an organised architecture) logs to be conveniently collected and transported through tools such as fluenbit
