### ISSUE TITLE
fix: varying checksum

### ISSUE THREAD

**Issue by jjangga0214** [goharbor/harbor-helm#1609]
checksum(annotation) is automatically changed every time even when it should not.

For example, `checksum/secret` changes when a value regardless of it changes.

I think it should be fixed.

**Comment by tobiwanobi** [comment]
This is still not working for me when deploying the 1.14.0 helm chart with ArgoCD v2.9.3

Everytime I commit anything to my repo these values get updated and a new replicaset is created.
