### ISSUE TITLE
Packed 1.11.3 chart missing fixes

### ISSUE THREAD

**Issue by Tearix** [goharbor/harbor-helm#1611]
There is no [fix](https://github.com/goharbor/harbor-helm/pull/1589) in released chart:
```
helm pull --repo https://helm.goharbor.io harbor --version=1.11.3 --untar && cat harbor/templates/_helpers.tpl | grep TRACE_ATTRIBUTES
  TRACE_ATTRIBUTES: "{{ .Values.trace.attributes | toJson }}"
```

Present at tag [v1.11.3](https://github.com/goharbor/harbor-helm/blob/v1.11.3/templates/_helpers.tpl#L576)

**Comment by zyyw** [comment]
Thanks @Tearix . We may delete the current harbor-helm 1.11.3 from https://artifacthub.io/packages/helm/harbor/harbor and then push a new packed 1.11.3 to the artifacthub.io

**Comment by Tearix** [comment]
Thanks!
```
helm pull --repo https://helm.goharbor.io harbor --version=1.11.3 --untar && cat harbor/templates/_helpers.tpl | grep TRACE_ATTRIBUTES
  TRACE_ATTRIBUTES: {{ .Values.trace.attributes | toJson | squote }}
```
