### ISSUE TITLE
Integrate Cosign to the Helm Chart

### ISSUE THREAD

**Issue by Freydiere** [goharbor/harbor-helm#1615]
It is my understanding that you chose to deprecate the use of Notary (deletion of the templates and the corresponding values in the last release, decision to deprecate Notary since Harbor v2.6). 

Are you going to release a new version of the Helm Chart integrating Cosign instead or should I develop the template myself?

Thank you very much!

**Comment by Kajot-dev** [comment]
What do you mean by cosign integration? You can use cosign now, without special integrations by first pushing your image and the signing the image with `cosign sign YOUR_IMAGE`.
You can verify i with `cosign verify` (either via *public key* or *expected certificate issuer and certificate subject*)

Do you mean a feature that would allow, for example to upload allowed public keys into the project and only allow deploying images which are signed with such key? Even so, that would be a feature of the harbor itself, not the helm chart.

**Comment by zyyw** [comment]
As @Kajot-dev suggest, users can use `cosign` CLI to interact with Harbor without special integrations.
