### ISSUE TITLE
Getting a error redirect address when accessing Harbor over HTTP

### ISSUE THREAD

**Issue by blpwa** [goharbor/harbor-helm#1616]
![image](https://github.com/goharbor/harbor-helm/assets/144432485/6cd91dc1-8059-48f0-9364-37300e8b2f72)
use the https port is ok
use the http port is errot

**Comment by zyyw** [comment]
@blpwa could you please share with us how you configured the `values.yaml` file? Maybe share a copy of it with sensitive info deducted.

**Comment by zyyw** [comment]
The reason for this issue might be related to this config:
* https://github.com/goharbor/harbor-helm/blob/main/templates/nginx/configmap-https.yaml#L184

here it redirect to https without specifying a port (using default 443)

**Comment by blpwa** [comment]
> @blpwa could you please share with us how you configured the `values.yaml` file? Maybe share a copy of it with sensitive info deducted.

I deploy Harbor using the following configuration

helm install --set expose.type=nodePort,expose.tls.auto.commonName=harbor,\
persistence.persistentVolumeClaim.registry.storageClass=nfs-storage,\
persistence.persistentVolumeClaim.jobservice.jobLog.storageClass=nfs-storage,\
persistence.persistentVolumeClaim.database.storageClass=nfs-storage,\
persistence.persistentVolumeClaim.redis.storageClass=nfs-storage,\
persistence.persistentVolumeClaim.trivy.storageClass=nfs-storage,\
externalURL=https://192.168.56.102:30003 \
harbor harbor/harbor

**Comment by blpwa** [comment]
> The reason for this issue might be related to this config:
> 
> * https://github.com/goharbor/harbor-helm/blob/main/templates/nginx/configmap-https.yaml#L184
> 
> here it redirect to https without specifying a port (using default 443)

I try to modify the redirect address to `{{ .Values.externalURL }}$request_uri`, and then redeploy, access via http can be redirected to https, is this correct?
