### ISSUE TITLE
does harbor use  db postgres in postgresql?

### ISSUE THREAD

**Issue by yifanyou** [goharbor/harbor-helm#162]
I find there are some tables in postgres.public. don't know they come from.
![image](https://user-images.githubusercontent.com/8372481/53006238-cb663c80-346f-11e9-9399-9b89dccde48a.png)

**Comment by ywk253100** [comment]
It's used by Clair service.

**Comment by yifanyou** [comment]
> It's used by Clair service.

I want to migrate harbor dbs to other places, can I only migrate registry, notaryserver,notarysigner?

**Comment by yifanyou** [comment]
I saw values.yaml in harbor 0.3.2,   clairDatabase default value is clair.   So, if  install harbor 0.3.2, i can migrate db postgres.public to db clair.public?

**Comment by ywk253100** [comment]
Are you using the external database? Why do you need to migrate the table from postgres to others?

**Comment by yifanyou** [comment]
> Are you using the external database? Why do you need to migrate the table from postgres to others?

yes, i use aliyun rds plsql 10.  when i migrate postgres.public to rds by aliyun dts, some errors happen caused by custom types.

**Comment by reasonerjt** [comment]
Closing as we recommend using Trivy as default scanner and clair will be removed from default installation.
