### ISSUE TITLE
core-secret always generate TLS keys even when disabled

### ISSUE THREAD

**Issue by Gigigotrek** [goharbor/harbor-helm#1629]
In [core-secret.yaml](https://github.com/goharbor/harbor-helm/blob/1.12.0/templates/core/core-secret.yaml), some keys are randomly generated even when are disabled.

By default [internalTLS is disabled](https://github.com/goharbor/harbor-helm/blob/main/values.yaml#L108-L110)
```
internalTLS:
  # If internal TLS enabled
  enabled: false
```

But the [tls.key](https://github.com/goharbor/harbor-helm/blob/main/templates/core/core-secret.yaml#L15) and [tls.crt](https://github.com/goharbor/harbor-helm/blob/main/templates/core/core-secret.yaml#L16) keys are created anyway

```
  {{- if not .Values.core.secretName }}
  {{- $ca := genCA "harbor-token-ca" 365 }}
  tls.key: {{ .Values.core.tokenKey | default $ca.Key | b64enc | quote }}
  tls.crt: {{ .Values.core.tokenCert | default $ca.Cert | b64enc | quote }}
  {{- end }}
```

**Comment by zyyw** [comment]
https://github.com/goharbor/harbor-helm/blob/96428e03ea28c7eeb7e02454ac7f38295e3b98af/templates/core/core-secret.yaml#L15-L16
has nothing to do with internalTLS, it is used for encrypt/decrypt token generated by the token service.
internalTLS is certs/keys are here:
* https://github.com/goharbor/harbor-helm/blob/main/templates/internal/auto-tls.yaml
