### ISSUE TITLE
CORE_SECRET can not be passed from external secret

### ISSUE THREAD

**Issue by Gigigotrek** [goharbor/harbor-helm#1630]
core-secret.yaml forces to pass the CORE_SECRET in raw from values file or generate it randomly.

`secret: {{ .Values.core.secret | default (randAlphaNum 16) | b64enc | quote }}`

We propose to use the same approach than _secretKey_ or _HARBOR_ADMIN_PASSWORD_

```
  {{- if not .Values.existingSecretCoreSecret }}
  secret: {{ .Values.core-secret | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
```

**Comment by zyyw** [comment]
Thanks for bring this up. Can you rise a PR for this?

**Comment by zyyw** [comment]
this PR might resolves this issue:
* https://github.com/goharbor/harbor-helm/pull/1373
