### ISSUE TITLE
Enable serviceAnnotations for portal service

### ISSUE THREAD

**Issue by viktordebulat** [goharbor/harbor-helm#1637]
I'm using Harbor with internal TLS but exposing portal to Internet is a bit tricky as I'm using Traefik Servers Transport to support self-signed CA and need to add serverstransport annotation to Portal service. But it is not possible with current helm chart version.

**Problem:** Lack of portal.serviceAnnotations value in helm chart.

**Comment by drkwng** [comment]
Faced the same problem. Any chances to see that in upcoming releases?

**Comment by zyyw** [comment]
@viktordebulat could you please share with us your use case in details?

Harbor is exposed either via nginx or ingress. Is adding the `serviceAnnotation` for portal service enough? Because Harbor portal also send API requests to the core service as well.

**Comment by viktordebulat** [comment]
@zyyw Recent traefik implementation inside our cluster won't work with self-signed CA. So, I'm adding [serversTransports Traefik](https://doc.traefik.io/traefik/routing/services/#serverstransport_1) to Portal service. For that, I need to annotate Portal service like this ```traefik.ingress.kubernetes.io/service.serverstransport: harbor-harbor-portal@kubernetescrd```

As I mentioned above, currently I annotate that service with kyverno policy but it would be easier to do it just via helm chart values.
