### ISSUE TITLE
Custom LDAP CA

### ISSUE THREAD

**Issue by krishau99** [goharbor/harbor-helm#1653]
Hi!

I need the option to add a custom CA to create a secure LDAP connection. I can't find any way to add this in the current helm-chart, is it possible to add an option to do this?

**Comment by zyyw** [comment]
Hi @krishau99 , could you please have a try on the following config:
https://github.com/goharbor/harbor-helm/blob/aa2569d9a8547719958181d2e59b5b3f630e7e6a/values.yaml#L367-L369
