### ISSUE TITLE
The helm chart is lagging behind the main project's release cycle

### ISSUE THREAD

**Issue by mstavrev** [goharbor/harbor-helm#1667]
The main project of harbor had already released version 2.10.0 - https://github.com/goharbor/harbor/releases/tag/v2.10.0 - about four days ago. The helm chart is still not updated to let users that are deploying via helm to update deployments to the newer version.

We either need a more tight integration between the two projects, or merge them into a single one.

**Comment by zyyw** [comment]
Please expect 1~2 weeks delay of harbor-helm behind [harbor-oss](https://github.com/goharbor/harbor)
