### ISSUE TITLE
Split ingresses for Docker endpoint and portal/others

### ISSUE THREAD

**Issue by marevers** [goharbor/harbor-helm#1672]
I would like to use two different ingress controllers for Harbor:

1) an ingress controller with a public load balancer for the Docker endpoint
2) an ingress controller with a private load balancer for the Harbor portal / other endpoints

This is so that we can use Harbor as a public repository with authentication reachable over the internet, but keep the portal and any APIs that don't need to be exposed to the outside internal only.

Right now the Helm chart generates a single Ingress object bound to a single ingress class, so that is not possible.
Would it be possible to add this option to the chart?

**Comment by Vad1mo** [comment]
If we get https://github.com/goharbor/harbor-helm/pull/1073 across the line, then you could set up your ingress as you like.

**Comment by marevers** [comment]
Got it, thank you. For now I think I will just use cluster IP for the expose type and work around it by providing my own ingress definitions in parallel to the chart.
