### ISSUE TITLE
Persistent volume claim size defaults

### ISSUE THREAD

**Issue by yakbulut** [goharbor/harbor-helm#169]
Hi all,

In version `1.0.0` of the chart the following values are set as defaults:

```
persistentVolumeClaim.jobservice.size=1Gi
persistentVolumeClaim.database.size=1Gi
persistentVolumeClaim.redis.size=1Gi
```
What happens when/if these volumes are filled up ? Are these LIFO caches ? Does the product lock up ? And if so what are the workarounds when this happens ?

**Comment by ywk253100** [comment]
This should be handled by your Kubernetes: https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Comment by yakbulut** [comment]
@ywk253100 Thanks for the reply, that sounds like a great feature but I believe that's not going to work for me on Vsphere. See the supported type of volumes at https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims
and the discussion at https://github.com/vmware/kubernetes/issues/168#issuecomment-451730840

Can you please provide more information around how you came to the defaults of `1Gi` ? I am trying to figure out a safe set of defaults when expanding the volume is not possible.

**Comment by ywk253100** [comment]
The storage of `jobservice` is used to store job log, and the logs will be swept periodically. 
The session and job queue are store in `Redis`, and the data will be removed after them are useless. 
So I think `1G` for `jobservice` and `Redis`is enough.

For database, every pull/push/delete operations will generate an audit log record: https://github.com/goharbor/harbor/blob/master/make/migrations/postgresql/0001_initial_schema.up.sql#L134 in database. It will grow up quickly if there are many such operations in you system. You can estimate the size of volume used by database according to your system.
