### ISSUE TITLE
Provide "Registry GC" function to help registry's GC

### ISSUE THREAD

**Issue by jeremyxu2010** [goharbor/harbor-helm#17]
refer to [Deleting repositories](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md#deleting-repositories), why do i have to shut down the harbor for this operation of registry's garbage collection(GC)?

I suggest you can improve as follows:
1. Put a "Registry GC" Button on the harbor's administrator UI
2. Once the system administrator clicks this button, a prompt box will pop up to show the upcoming GC operation
3. If the system administrator clicks the confirmation button, then continue
4. temporarily disable push image globally
5. Execute this garbage-collect python script
6. After the above script is executed, enable push image globally

**Comment by reasonerjt** [comment]
We started working on online GC in 1.6 and hopefully i will be shipped in 1.7,
though the process is not exactly the same as your described.

Please see:
https://github.com/goharbor/harbor/issues/4949

Additionally, this repo is for helm chart of Harbor only, please open issue to 
https://github.com/goharbor/harbor
in future if you have a question or feature request.
