### ISSUE TITLE
child process was terminated by signal 7: Bus error

### ISSUE THREAD

**Issue by rookiesince** [goharbor/harbor-helm#1701]
helm install  harbor 
version：harbor-1.14.0
[root@k8s-master harbor]# kubectl logs  harbor-database-0  -n harbor
Defaulted container "database" out of: database, data-migrator (init), data-permissions-ensurer (init)
init DB, DB version:14
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /var/lib/postgresql/data/pgdata/pg14 ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... UTC
creating configuration files ... ok
child process was terminated by signal 7: Bus error
initdb: removing data directory "/var/lib/postgresql/data/pgdata/pg14"
running bootstrap script ...

**Comment by zyyw** [comment]
There is a known issue of setting database password https://github.com/goharbor/harbor-helm/issues/1674. Not sure if this issue is related or not.

Hi @rookiesince , would you please try the same config on harbor v2.9.2 (harbor-helm v1.13.2) to see if the same error persists?

**Comment by wy65701436** [comment]
More hints at here: https://www.crunchydata.com/blog/huge-pages-and-postgres-in-containers

**Comment by AllKai** [comment]
I also encountered the same problem
