### ISSUE TITLE
issue while pulling image : no such host

### ISSUE THREAD

**Issue by nirupbbnk** [goharbor/harbor-helm#1716]
when I try to pull image I am getting error Error response from daemon: Get "https://harbor.nutrikorr.com/v2/": dial tcp: lookup harbor.nutrikorr.com on 172.19.192.1:53: no such host

but portal is working fine at https://harbor.nutrikorr.com

I am using nginx ingress

**Comment by zyyw** [comment]
@nirupbbnk Have you tried to configure `externalURL:https://harbor.nutrikorr.com/`?

**Comment by zyyw** [comment]
also `172.19.192.1:53: no such host` looks like that the network where you pull image cannot resolve DNS name.
