### ISSUE TITLE
chart 1.14.0 broken

### ISSUE THREAD

**Issue by itssven** [goharbor/harbor-helm#1721]
There is a bug in chart 1.14.0 which is not in git branch 1.14.0

git: https://github.com/goharbor/harbor-helm/blob/1.14.0/templates/_helpers.tpl#L101
```
{{- .Values.database.internal.password | default (index $existingSecret.data "POSTGRES_PASSWORD" | b64dec) -}}
```

chart: 
- helm pull harbor/harbor --version 1.14.0 --untar
- file harbor/templates/_helpers.tpl
```
{{- .Values.database.internal.password | default (index $existingSecret.data "POSTGRES_PASSWORD") | b64dec -}}
```

The difference is the place of ) in the default function parameter list which should be after b64dec. By installing or upgrading the release and setting `.Values.database.internal.password` the database password is first decoded from plain text and then encoded, which leads to secrets showing the plain text password and an unexpected value in the pods.

Please build a new chart version reflecting the git state eg. as 1.14.1

**Comment by sharkymcdongles** [comment]
sloppy :'(

**Comment by Simbud-7** [comment]
Hi.

Indeed, new chart must be deployed with the fix (parenthesis).

Thanks :)

**Comment by zyyw** [comment]
sorry for this troubling issue. It is a dup of this one:
* https://github.com/goharbor/harbor-helm/issues/1692#issuecomment-1946113860
