### ISSUE TITLE
I need a lifecycle setting for the harbor core container, any thoughts on adding it to the chart?

### ISSUE THREAD

**Issue by derekcha** [goharbor/harbor-helm#1722]
I was getting a 504 or EOF error when rolling while using harbor.
Pods don't seem to be cleaned up gracefully when terminated (possibly due to my having harbor after AWS LB) 
So I tested by randomly setting a prestop(sleep 60) lifecycle for the container in harbor core and no errors occurred.
I would like to be able to set lifecycle on chart as well, what do you think?

**Comment by zyyw** [comment]
Could you please elaborate and clarify the problem, the actual behavior, the expected behavior, and your proposed solution?

**Comment by derekcha** [comment]
@zyyw 
Hi first of all thanks for the reply.
To explain the problem situation, I'm using harbor with helm installed, and I did a helm upgarde because I needed to make some changes, but then a developer using harbor reported the following error.
```
  Warning  Failed                  13s (x2 over 32s)  kubelet                  Failed to pull image "harbor-domain/harbor-project/image:tag": rpc error: code = Unknown desc = failed to pull and unpack image "harbor-domain/harbor-project/image:tag": failed to resolve reference "harbor-domain/harbor-project/image:tag": failed to do request: Head "harbor-domain/harbor-project/image:tag": EOF
  Warning  Failed                  13s (x2 over 32s)  kubelet                  Error: ErrImagePull
```
So I did some digging and found that the harbor core pod was not rolling out gracefully.
I tried randomly adding the following configuration to harbor-core for graceful shutdown, and no more errors occurred.
```
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 60"] 
```
I registered this issue because it would be nice if the lifecycle settings of the container were added to the helm chart itself.
Maybe I should fix it myself and raise the PR?

**Comment by derekcha** [comment]
@zyyw 
Check plz.
