### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by vodanet** [goharbor/harbor-helm#1755]
Hi,

I have an RKE2 cluster with Traefik.
Helm 3.14.2 is installed.

kubectl version
Client version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.12+rke2r1
Chart version: 1.14.2

User name: admin
Password: Harbor12345

I want to install the latest version, which also works.
I have not changed the default password and name.
But when I try to log in via the GUI, I always get the message that the password is incorrect.

Even when I want to register a new user, confusing messages appear.
If I specify testuser for the user name, for example, the message still appears: "Must not contain any special characters and should be shorter than 255 characters.". If I use "test@user.com" as an email, for example, the message appears: "The email address will only be used to reset the password.
Email should be a valid email address such as name@example.com."

Where do these errors come from?
I also tested it with different browsers.

Greetings,
Daniel

**Comment by kastl-ars** [comment]
I had similar issues. In my case I could solve this by setting the `externalURL` to the correct value.

(I am only using http:// for testing currently, but the externalURL was set to httpS://...)

**Comment by vodanet** [comment]
@kastl-ars 
Sorry for the very late reply. There were a few other challenges first.
But what you described was exactly the problem. When the routes matched, LOGIN worked immediately.

THANK YOU!!!
