### ISSUE TITLE
app.conf is actually an app.ini file

### ISSUE THREAD

**Issue by boris-smidt-klarrio** [goharbor/harbor-helm#1770]
https://github.com/goharbor/harbor-helm/blob/f547605c75badb6675810327cc4809b3ec4202a8/templates/core/core-cm.yaml#L8
It seems that the config file used in this helm chart isn't using the 'correct' extension and it actually contains a .ini .

**Comment by Vad1mo** [comment]
wow you are right, never knew that 

https://github.com/goharbor/harbor/blob/main/src/core/controllers/base.go#L160

**Comment by zyyw** [comment]
If we run `sudo ./prepare --with-trivy`, it outputs:
```
prepare base dir is set to /home/ubuntu/temp/harbor
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Generated configuration file: /config/core/app.conf <------------ please check here
Generated configuration file: /config/registry/config.yml
Generated configuration file: /config/registryctl/env
Generated configuration file: /config/registryctl/config.yml
Generated configuration file: /config/db/env
Generated configuration file: /config/jobservice/env
Generated configuration file: /config/jobservice/config.yml
loaded secret from file: /data/secret/keys/secretkey
Generated configuration file: /config/trivy-adapter/env
Generated configuration file: /compose_location/docker-compose.yml
Clean up the input dir
```

**Comment by MinerYang** [comment]
Per beego doc https://github.com/beego/beedoc/blob/master/en-US/mvc/controller/config.md#default-configurations-parsing
And https://github.com/beego/beego/blob/76343e4422710373ed4838e7262c4d54524e3b94/core/config/ini.go#L56
the appConfig will be loaded correctly regardless the file name is `app.conf` or `app.ini`  as long as the adapter is `ini`  **which explicitly specified in the func**

**Comment by boris-smidt-klarrio** [comment]
I made the suggestion of renaming the file to improve the syntax highlighting and better linting in the configmap to a `.ini` file.

**Comment by zyyw** [comment]
This `app.conf` is a auto-generated file and should be transparent to the end users. BTW, to keep it consistent with the Harbor oss, it might be better keep it as it is.
