### ISSUE TITLE
InternalCertificate Renewal Job

### ISSUE THREAD

**Issue by shan100github** [goharbor/harbor-helm#1775]
## Issue
After a year of harbor deployment, internal TLS expired & pods started failing

## Solution
It will be nicer if we have a job to renew all internal TLS certs can be regenerated.

I look forward to other suggestions and opinions.

**Comment by Kajot-dev** [comment]
There was #1713 which could solve this but it got stale and was untested

**Comment by shan100github** [comment]
yeah, something similar to that.
At present, I have used "helm template" to generate TLS certs and replace them in the environment. It made Harbor environment usable.

**Comment by zyyw** [comment]
Alternatively, it might be a better idea for users to set `internalTLS.certSource` to be `manual` or `secret` with a given formalized certs configuring a specified expiration time in their production environment.
