### ISSUE TITLE
How to change registry token expiration time ?

### ISSUE THREAD

**Issue by zdenekvicar** [goharbor/harbor-helm#178]
Hello,
I am running harbor in kubernetes cluster (harbor 1.6.0), and I am not able to find out how I can change token expiration time, which is set by default to 30 minutes. Since I need to push images through very slow connections, I would need to increase this.

I did find the option to change this in harbor.cfg ( based on https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md#optional-parameters and parameter `token_expiration`) but that counts only to non-k8s installation I guess.
Is this option configurable also for harbor running in Kubernetes?

Thanks,
Zdenek

**Comment by ywk253100** [comment]
Login as system admin, and you can change it on the portal.

**Comment by zdenekvicar** [comment]
Thanks a lot, I was so much looking for any more complex answer that I completely overlooked it in the admin settings. Shame on me 😉

**Comment by tedmiston** [comment]
@ywk253100 In general, is it possible to use a `harbor.cfg` (or now `harbor.yml`) together with the Harbor Helm chart?  I'm trying to find a way to programmatically override fields mentioned in the Installation Guide such as `harbor_admin_password` but not finding anything analogous in `values.yaml` or the chart docs.  I'm wondering if I'm missing it or if it is not possible?

**Comment by zdenekvicar** [comment]
Maybe I did not fully understood your question @tedmiston but at least harbor admin password is editable in values.yml file 

https://github.com/goharbor/harbor-helm/blob/1.1.0/values.yaml#L230

If I really did not fully catch your question, could you please be more specific? Maybe I could assist you 🙂

**Comment by tedmiston** [comment]
@zdenekvicar Thank you, and yes, of course, I found that one in `values.yml` (but as camelcase) just after posting my comment.  My question is, in general: Is there a corresponding value in `values.yml` for every one in `harbor.yml`?  Or is there some way to use both config files in the Helm install?

For example, in `harbor.yml`, I see configuration variables like `rotate_count` and `rotate_size` nested under `log`, but in `values.yaml`, I see just `logLevel`.

[`harbor.yml`](https://github.com/goharbor/harbor/blob/b98ca7bf0b66615e881f9d5946d8f82968b1985b/make/harbor.yml#L71-L82) (comments removed):

```
log:
  level: info
  rotate_count: 50
  rotate_size: 200M
  location: /var/log/harbor
```

[`values.yaml`](https://github.com/goharbor/harbor-helm/blob/58a4c1052a78ad764d1182d6898aac1ea1e6d57b/values.yaml#L243):

```
logLevel: debug
```
