### ISSUE TITLE
Not create audit log 

### ISSUE THREAD

**Issue by sias32** [goharbor/harbor-helm#1782]
When deploying harbor helm v1.15.0, an error appears in the harbor-core logs

```log
2024-06-25T13:23:04Z [ERROR] [/pkg/audit/forward.go:44]: failed to create audit log, error dial tcp: missing address
```

Everything seems to be working, task logs are created, but this error makes me nervous

Can you tell me what it depends on? What does it require?

**Comment by MinerYang** [comment]
Ignore this if you are not using `Audit Log Forward Syslog Endpoint`

**Comment by sias32** [comment]
okay
