### ISSUE TITLE
Incorrect generation of harbor-core URL in part of jobservice

### ISSUE THREAD

**Issue by Tonkari** [goharbor/harbor-helm#1790]
# Summary
Jobservice logs show that some calls from hook_agent go to an incorrect harbor-core URL

# Environment
We are using this chart to deploy harbor 2.10.2 (chart version 1.14.2) with internal TLS enabled, certSource is secret and the secrets are managed by cert-manager. This means our services all listen exclusively on port 443

# Problem
When troubleshooting an unrelated issue with the jobservice we noticed some errors in the pod logs that contain failed requests to "http://harbor-core:80", when all other requests from the pod go to the correct URL of "https://harbor-core:443"

# Log messages
```
# failed call
2024-07-11T07:57:13Z [ERROR] [/jobservice/hook/hook_agent.go:159]: Retry: still failed after all retries: Post "http://harbor-core:80/service/notifications/tasks/xxx": context deadline exceeded (Client.Timeout exceeded while awaiting headers), evt=status change: job=xxxxxxxxxxxxxxxxxxxxxxxx@1720656000, status=Success, revision=1720655940->http://harbor-core:80/service/notifications/tasks/xxx

# working call from same pod
2024-07-11T08:00:00Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: https://harbor-core:443/api/v2.0/internalconfig
```

I don't know if it's a configuration error in this chart of if it's hardcoded in the docker image itself - I would appreciate any help or direction. I also don't know what functions of harbor are impaired here or what earlier versions are affected.

**Comment by zyyw** [comment]
@Tonkari thanks for reporting this issue. Could you please share with us when the `# failed call` occurs, what kind of webhook event was triggered, for example image scan, replication.

@chlins could you please help to take a look on this? Thanks

**Comment by chlins** [comment]
@Tonkari If you initially used port 80 and later switched to 443, there might be some old tasks that send requests to the old address. Please try restarting the harbor core and jobservice containers, and check their environment variables for `CORE_URL` related configurations.

**Comment by Tonkari** [comment]
Hi, thanks for the investigation,

We were indeed using port 80 initially, but that was many years and versions ago. In the meantime all pods have been updated and restarted multiple times (we are running everything with at least 3 replicas), and a manual restart of jobservice did not get rid of the error. 
How can I identify the job that triggers the notification? We are not running any replication between other registries but everything else should be configured (GC, scans with built-in trivy, retention mostly). It always calls the same URL as well http://harbor-core:80/service/notifications/tasks/186, not multiple different ones.
