### ISSUE TITLE
v1.15.0：failed to migrate the database

### ISSUE THREAD

**Issue by durant0819** [goharbor/harbor-helm#1797]
Dear，
I met a problem and  spent a lot of time but couldn't solve it ， the process like below:

1.  Down load  harbor-1.15.0.tgz  and ungzip it.

2.  use cmd:    **helm install harbor .** 

3.  Then the problem occur: 

I know when the db was initalizing,  the pods core and jobservice would be not ok until the db's work is down：
![image](https://github.com/user-attachments/assets/96e39f41-9280-41cf-be4e-08e9bb06aa15)

when the db was ok,  the last 2 pods were in 0/1 running status:
![image](https://github.com/user-attachments/assets/5b0d8404-6c47-42f7-8b0c-e1e2e8e17eed)

I checked the db's logs, it seemslike normal:
![image](https://github.com/user-attachments/assets/0b7433f7-0a0f-4812-9439-c78f6f9b44fa)

but when I checked  the **core pod**'s logs, there was an error: 
![image](https://github.com/user-attachments/assets/868eab87-ca46-4c98-adb2-fcfff51003a0)

I didn't know whether it was the network's problem or others,  I felt when it run:
`1/u initial_schema (4m10.426207141s)`
it cost about 4min, what is this process meaning, should I download the offline pkg to prevent it download online? 
Thanks for your support~

**Comment by zyyw** [comment]
It seems that the database pod does not working properly. I found a related issue here:
* https://github.com/goharbor/harbor/issues/15109
