### ISSUE TITLE
redis password is available as plain text in the config map

### ISSUE THREAD

**Issue by muralisankar32** [goharbor/harbor-helm#1803]
Redis password is available as plain text in the config map which is not recommended. It would be better to read it from the secret instead of configmap.

**Comment by MinerYang** [comment]
Hi @muralisankar32 ,

This is an upstream limitation. We need to set up Redis client from url for several components like harbor-core, harbor-trivy-adapter etc. and set plain text of redis password for distribution registry `config.yml`.

So we can not encrypt only Redis password from harbor-helm

Best,
Miner
