### ISSUE TITLE
 v1.15.0 upgrade failed

### ISSUE THREAD

**Issue by dyvol777** [goharbor/harbor-helm#1806]
After upgrade to v1.15.0 chart database changed postgresql from 14 to 15 version. So harbor start with clear database, without projects, users etc.

Solution: add migration job or add documentation with warning

**Comment by zyyw** [comment]
That's odd. Are you using external database or internal database? Please also make sure to upgrade within `N-2` version.

**Comment by zyyw** [comment]
Could you please share us with the log of database pod?
