### ISSUE TITLE
FEATURE: Add support for layerinfo caching configuration

### ISSUE THREAD

**Issue by iseyer** [goharbor/harbor-helm#1807]
Distribution(all versions, [going back to 9 years ago](https://github.com/distribution/distribution/commit/919d972e652bd256196b56a03d9769c375bffefd)) supports 3 options for layerinfo caching: `redis`, `inmemory`, and `disabled` (by not being set to either redis or inmemory).

Currently, however, harbor is [hardcoded to redis](https://github.com/goharbor/harbor-helm/blob/main/templates/registry/registry-cm.yaml#L158). 

Expose this option to the harbor helm chart, to allow for configurations where redis is not available to the registry.

**Comment by zyyw** [comment]
Thank you for contributing to Harbor! 
I am thinking whether we should make this configurable in the upstream (goharbor/harbor) first, then we can discuss about enabling this configuration in harbor-helm.

**Comment by iseyer** [comment]
Out of curiosity - what would that look like? Seems like distribution handles this natively with no change to harbor itself. At what other levels would you want layer caching?

**Comment by zyyw** [comment]
By upstream, I was thinking about configuring `harbor.yml` in `goharbor/harbor` so that it can be configurable not only in harbor-helm but also in harbor offline-installer (docker-compose).

Also Harbor GC relies on redis as well:
* https://github.com/goharbor/harbor/blob/main/src/jobservice/job/impl/gc/garbage_collection.go#L494

**Comment by iseyer** [comment]
In that case - do you think it is worth supporting anything _but_ redis for layer caching? If Redis is a hard requirement and it should stay that way, this PR & issue can be trashed

**Comment by MinerYang** [comment]
Will close per above discussion.
