### ISSUE TITLE
Redis error: ERR AUTH <password> called without any password configured in Harbor v1.15.1 (registry container logs)

### ISSUE THREAD

**Issue by charger251** [goharbor/harbor-helm#1829]
#### **Description**

We are encountering an issue in Harbor v1.15.1 where the **registry container** logs the following error related to Redis authentication, even though no password is set for Redis and Sentinel:

```bash
level=error msg="redis: error connecting: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?" 
go.version=go1.22.6 
instance.id=73b0384e-4cc8-4956-8ee5-09fb5a624471 
redis.connect.duration=1.083452ms 
service=registry 
version=v2.8.3.m
```

### **Details:**
- **Harbor Version**: v1.15.1
- **Redis Configuration**: No password set for Redis and Sentinel.
- **Components**:
  - `core`: Working without errors.
  - `jobservice`: Working without errors.
  - `redis`: No password is configured.
  - `registry`: Logs the Redis authentication error described above.

Despite the Redis authentication error in the **registry container logs**, the core and jobservice components are operating without issues. It seems the **registry** service is attempting to authenticate with Redis, even though no password is configured.

#### **Steps to Reproduce**:
1. Deploy Harbor v1.15.1 using the official Helm chart.
2. Ensure that Redis and Sentinel are configured **without any passwords**.
3. Check the logs of the **registry container** for Redis authentication errors.

#### **Expected Behavior**:
The registry should connect to Redis without attempting authentication if no password is configured.

#### **Observed Behavior**:
The registry container logs an authentication error when trying to connect to Redis, even though no password is set.

#### **Environment**:
- **Harbor version**: v1.15.1
- **Redis version**: Bundled with Harbor Helm chart v1.15.1
- **Kubernetes version**: v1.24.x
- **Helm version**: v3.x

#### **Additional Context**:
While the **core** and **jobservice** components are not affected, the **registry** component consistently logs Redis authentication errors. This suggests that the registry service is attempting to authenticate with Redis, even though authentication is not required due to the absence of a password.

Please provide guidance on whether this is a configuration issue or a bug in the registry service when interacting with Redis.

---

### **Tags**:
- `bug`
- `redis`
- `auth`
- `registry`
- `v1.15.1`

**Comment by reasonerjt** [comment]
This is the behavior of the distribution code.
Let's double check if this is a known issue.
