### ISSUE TITLE
Trivy Scanner Fails to Ping - Invalid Character in Response (harbor & trivy in different namespaces)

### ISSUE THREAD

**Issue by micheleietri** [goharbor/harbor-helm#1831]
I am encountering an issue when attempting to add a new scanner to Harbor. The Trivy server instance is deployed in a separate namespace from the Harbor chart.

![image](https://github.com/user-attachments/assets/0facfefd-7a97-4152-aecc-e0298847443d)

Steps to Reproduce:

    Install Trivy server in a dedicated namespace (e.g., trivy-system).
    Deploy Harbor chart in another namespace (e.g., harbor).
    Within the Harbor UI, attempt to add a new scanner.

Expected Behavior:

The scanner should be successfully added after providing the necessary details.

Actual Behavior:

The attempt to add a scanner fails with the following error logs:

2024-09-27T07:20:25Z [ERROR] [/controller/scanner/base_controller.go:322][error="v1 client: get metadata: general response handler: invalid character 'p' after top-level value" requestID="d3fe6d5424372cc9221c58bea8473de9"]: failed to ping scanner
2024-09-27T07:20:25Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"scanner controller: ping: v1 client: get metadata: general response handler: invalid character 'p' after top-level value"}]}

Additional Information:

    I have verified that the Trivy CLI works successfully when running test commands from within the same namespace as Harbor.
    Harbor and Trivy versions (if applicable):
        Harbor: [insert version]
        Trivy: [insert version]

Possible Causes:

    Communication issue between Harbor and Trivy due to different namespaces.
    Corrupted data received during the ping request.

Request for Assistance:

I would appreciate any guidance on how to troubleshoot this issue and successfully add the Trivy scanner to Harbor.

Additional Notes:

    The provided stack trace can be helpful for developers to identify the specific location of the error.
    Feel free to add any further details or observations related to the issue.

By following this format, you create a clear and concise issue report on GitHub that effectively communicates the problem and provides relevant information for developers to diagnose and resolve it.

**Comment by reasonerjt** [comment]
When Harbor core tries to "ping" the scanner, it calls an API `GET  ${scanner_host_and_ip}/api/v1/metadata`

you may use `kubectl debug` to setup a pod and curl this API to see what was returned.

Is it possible that the way you deploy Harbor and trivy may impact the networking?

**Comment by micheleietri** [comment]
the issue seems to be that my trivy installation isn't serving that endpoint.
