### ISSUE TITLE
Upgrade chart 1.15.0 from 1.14.0

### ISSUE THREAD

**Issue by s4ndalHat** [goharbor/harbor-helm#1870]
Hello, 

I'm trying to upgrade our harbor instance to the next version. 
But during this upgrade, the migration job always fail like outputting some assembly output.

As it is for a client workload, i immediately rollback to keep the instance running.
Does anybody encounter this issue ? Thank you.

**Comment by MinerYang** [comment]
More contexts like failed logs or error msg may help us better triage the issue

**Comment by s4ndalHat** [comment]
I have already rollbacked, 
I will post logs on my next test, thanks

**Comment by MinerYang** [comment]
Sure, then we will close this issue for now. Please feel free to reopen this issue if you still have the same problem.
