### ISSUE TITLE
Using chart v1.15.2 only update jobservice to 2.11.2

### ISSUE THREAD

**Issue by gu1ll0me** [goharbor/harbor-helm#1882]
Should registry, core and portal services be upgraded too ? Thanks !

![image](https://github.com/user-attachments/assets/988c4799-4d05-4675-b092-1adf761343c0)

**Comment by reasonerjt** [comment]
@gu1ll0me 

Where did you get this chart?

All images have been bumped up in values.yaml in v1.15.x:
https://github.com/goharbor/harbor-helm/blob/1.15.0/values.yaml

**Comment by gu1ll0me** [comment]
I got it from `https://helm.goharbor.io` on December 2 before this [commit](https://github.com/goharbor/harbor-helm/commit/d218b4d0118c28caabc67b7d2c87292aace8fef1) that solve this issue.

Thanks.
