### ISSUE TITLE
 [ERROR] [context.go:86]: Job context initialization error: http error: code 404, message <!DOCTYPE HTML>

### ISSUE THREAD

**Issue by jacobishao** [goharbor/harbor-helm#191]
![image](https://user-images.githubusercontent.com/8140244/54529239-457bd980-49ba-11e9-995e-1ad11d98f435.png)

**Comment by jacobishao** [comment]
![image](https://user-images.githubusercontent.com/8140244/54530902-013f0800-49bf-11e9-90ea-c28683edfd7d.png)
healthcheck fail

**Comment by ywk253100** [comment]
Are you using the latest `dev` images? Try to set the `imagePullPolicy ` to `Always`

**Comment by jacobishao** [comment]
still has the problem
![image](https://user-images.githubusercontent.com/8140244/54591153-99db9380-4a64-11e9-85a4-dc5d164e98e5.png)

**Comment by ywk253100** [comment]
Please use the stable version
