### ISSUE TITLE
TLS_CERT and TLS_KEY are unspecified in Chartmuseum configmap

### ISSUE THREAD

**Issue by protochron** [goharbor/harbor-helm#192]
The values for `TLS_CERT` and `TLS_KEY` in the Chartmuseum configmap are null, which means that generating the ConfigMap and trying to apply it using `helm template` fails since the ConfigMap is invalid.

The fix is straightforward: set the values to `""`, which I'll do in a PR. I'm not sure if there's a reason for these values to even be present though since I don't see where you can ever specify values for these keys.

**Comment by ruzickap** [comment]
I do have the same problem:

```
$ helm install --wait --name harbor --namespace harbor-system harbor/harbor --version 1.1.0 \
  --set expose.ingress.hosts.core=core.mylabs.dev \
  --set expose.ingress.hosts.notary=notary.mylabs.dev \
  --set expose.tls.secretName=ingress-cert-staging \
  --set externalURL=https://core.mylabs.dev \
  --set harborAdminPassword=admin123

Error: validation failed: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.CONTEXT_PATH, unknown object type "nil" in ConfigMap.data.TLS_CERT, unknown object type "nil" in ConfigMap.data.TLS_KEY]
```

```bash
$ helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

You can easily reproduce it:

```bash
$ cd /tmp/
$ git clone https://github.com/goharbor/harbor-helm.git
$ cd harbor-helm

$ helm template --name harbor --namespace harbor-system . \
  --set expose.ingress.hosts.core=core.mylabs.dev \
  --set expose.ingress.hosts.notary=notary.mylabs.dev \
  --set expose.tls.secretName=ingress-cert-staging \
  --set externalURL=https://core.mylabs.dev \
  --set harborAdminPassword=admin123 \
> /tmp/delete

$ kubectl apply -f /tmp/delete

secret/harbor-harbor-chartmuseum unchanged
secret/harbor-harbor-core configured
secret/harbor-harbor-database unchanged
secret/harbor-harbor-jobservice configured
secret/harbor-harbor-registry configured
error: error validating "/tmp/delete": error validating data: [unknown object type "nil" in ConfigMap.data.CONTEXT_PATH, unknown object type "nil" in ConfigMap.data.TLS_CERT, unknown object type "nil" in ConfigMap.data.TLS_KEY]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by ruzickap** [comment]
Thank you...

Is there a chance to release new version of helm charts which include this fix?

Without the fix above you can not use the latest "stable" helm chart (1.1.0) and you can not install Harbor 1.8.0 with this command:

```bash
helm install --name my-release harbor/harbor
```

It means the helm chart version 1.1.0 can not be used :-(

**Comment by ywk253100** [comment]
@ruzickap The error is caused by the new change introduced in helm v2.14.0 https://github.com/helm/helm/issues/5750. The guys are still discussing whether release a new version of helm to disable the validation or just validate the new manifests. 

And whether we release a new Harbor version depends on the discuss result.

For now you can work around the issue either downgrade your helm to v2.13.1 or just checkout the Harbor chart from Github directly and install it.

**Comment by ruzickap** [comment]
Ok... I understand...

Thank you.

**Comment by andresmgot** [comment]
I just found the same issue. Any update here?

**Comment by ywk253100** [comment]
@andresmgot Refer to the workaround mentioned here https://github.com/goharbor/harbor-helm/issues/192#issuecomment-495151700 for now. We'll release a new Harbor chart including the fix when the Harbor 1.8.1 come out.

**Comment by andresmgot** [comment]
:+1: My workaround was to clone this repo, manually delete the lines from the ConfigMap that cause the error and install it from the local directory (just because I want to use Helm v1.14 for other projects). Thanks for the update!

**Comment by solidnerd** [comment]
Hey @ruzickap,
if you use the latest helm (2.14.1+)  it will work again. I tested it with your commands and this version.

**Comment by ruzickap** [comment]
Thank you. The latest Helm version is working fine :-)
