### ISSUE TITLE
Wrong type for value; expected string; got chartutil.Values

### ISSUE THREAD

**Issue by Nickuru** [goharbor/harbor-helm#201]
After last commit if i trying to use 
`helm github install --repo https://github.com/goharbor/harbor-helm.git --ref master`
I get an error:

> Error: render error in "harbor/templates/registry/registry-secret.yaml": template: harbor/templates/registry/registry-secret.yaml:10:70: executing "harbor/templates/registry/registry-secret.yaml" at <b64enc>: wrong type for value; expected string; got chartutil.Values

_Do not pay attention to "helm github", its just plugin for deploy_

**Comment by xuesea** [comment]
I got the same issue
