### ISSUE TITLE
Helm chart references dev tag by default

### ISSUE THREAD

**Issue by jw-s** [goharbor/harbor-helm#21]
As the title states, is this intended behaviour? Seems very misleading and also there are currently no other tags available if I wanted to override.

**Comment by reasonerjt** [comment]
This is intended we consider the `master` brach as dev branch.

We'll create a new branch to point to the v1.6 images.

**Comment by jw-s** [comment]
@reasonerjt Any update on this?

**Comment by reasonerjt** [comment]
We have to first release v1.6 and push the images to internet then we'll branch the repo to point to the `v1.6.0` images.  ETA within this week.

**Comment by ywk253100** [comment]
@jw-s Please use the chart on branch 0.3.0 which is using Harbor 1.6.0 images.
