### ISSUE TITLE
Use version number tags and leverage Chart.yaml semantic versioning for increased stability

### ISSUE THREAD

**Issue by jimangel** [goharbor/harbor-helm#213]
I ran into an issue recently where my helm charts required newer images than my private repository contained (both tagged "dev"). Since the tags matched, it deployed then crashed.

Looking more at the tags, I see some version number tags are getting updated while dev is not. This might be ok, but I have no way to know.

https://hub.docker.com/r/goharbor/harbor-adminserver/tags has “dev” as a 2mo old image, but newer releases are published for v1.7.5 (9 days ago).

https://hub.docker.com/r/goharbor/harbor-db/tags has a “dev” tag updated 4 hours ago

In addition to the confusing tags that risk stability, if you import this helm chart into artifactory (another chart museum - kind of funny), you cannot use `helm fetch <repo>/harbor` because the version in https://github.com/goharbor/harbor-helm/blob/master/Chart.yaml#L2 is not [SemVer](https://semver.org/) which is [required](https://github.com/helm/helm/blob/master/docs/chart_best_practices/conventions.md#version-numbers) by helm repos. 

My suggestion:

- [ ] Update charts to use version number tags instead of :dev for consistency / stability.
- [ ] When there is a new "stable" release, update the charts with `sed 's\oldversion\newversion\g'`
- [ ] Update the Chart.yaml version to comply with helm SemVer requirements. It does not need to match the version of the images, it can be used to track major changes in the chart (such as a breaking change like we saw with the notary ingress update). This would also increase stability.

**Comment by ywk253100** [comment]
The component `adminserver` is removed, so its `dev` image isn't updated anymore.
The Harbor chart on master branch which references the `dev` images is under development, it is unstable, you should use the stable version whose version is in `SemVer` format.
