### ISSUE TITLE
docker login

### ISSUE THREAD

**Issue by KevinHaselhoff** [goharbor/harbor-helm#217]
Hello,

I recently installed harbor via the Helm Chart. All went well, services are created, ingress created, pods are all up and running. I'm also able to login to the UI. I created a project and installed the harbor-ca on my computer. When I try to ```docker login```, I get a error message saying: 

```
Error response from daemon: Get https://harbor.kubernetes.khnobbi.xyz/v2/: Get https://harbor.kubernetes.khnobbi.xyz/service/token?account=admin&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I suspect that the colon at service=harbor-registry gets set somehow. I wasn't able to figure out where I went wrong, could somebody please advice.

Thanks in advance.

Best, Kevin

**Comment by ywk253100** [comment]
The colon is not part of the `service=harbor-registry`. Seems it's related with your network, can you curl https://harbor.kubernetes.khnobbi.xyz/service/token successfully?

**Comment by tedmiston** [comment]
I'm also experiencing the client timeout error above on a vanilla install of `harbor-helm` locally on Docker for Mac.  I can log in to the default admin account fine in the web app and have configured my Docker daemon to support the insecure registry, but `docker login` fails.

```
(⎈ |docker-desktop:default)$ docker login https://localhost:30003
Username: admin
Password:
Error response from daemon: Get http://localhost:30003/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

I've also attempted doing the login with `http` and no protocol.  I'm using an `expose.type` of `nodePort` and `expose.tls.enabled` set to `true` with `expose.tls.commonName` set to `localhost`.

@ywk253100 Can you give any additional suggestions here?

**Comment by fshadid96** [comment]
Hey, 

were you able to figure out this issue? I am running into the same error
