### ISSUE TITLE
[v1.0.1 ] can't find file ca.crt  in "/etc/core/ca" 

### ISSUE THREAD

**Issue by siriuswinds** [goharbor/harbor-helm#219]
[v1.0.1 ] can't find ca.crt file in "/etc/core/ca"

**Comment by lizhongit** [comment]
@siriuswinds Are you resolve this? I have the issue same you

**Comment by siriuswinds** [comment]
in your values.yaml, let
 
secretName: ""
notarySecretName: ""

maybe help

**Comment by siriuswinds** [comment]
> @siriuswinds Are you resolve this? I have the issue same you

in your values.yaml, let

secretName: ""
notarySecretName: ""

maybe help

**Comment by lizhongit** [comment]
@siriuswinds But I wanna use own TLS certificate, if not fill the fields that the certificate was auto generate by harbor. I don't want this.

**Comment by siriuswinds** [comment]
> @siriuswinds But I wanna use own TLS certificate, if not fill the fields that the certificate was auto generate by harbor. I don't want this.

you can modify your ingress after install, edit harbor-harbor-ingress and use your own cert

**Comment by lizhongit** [comment]
@siriuswinds It's a good way, I'll try it out.

**Comment by lizhongit** [comment]
@siriuswinds I saw the harbor auto generate secret of TLS 

```shell
 kubectl describe secret -n harbor harbor-harbor-ingress
Name:         harbor-harbor-ingress
Namespace:    harbor
Labels:       app=harbor
              chart=harbor
              heritage=Tiller
              release=harbor
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
ca.crt:   1086 bytes
tls.crt:  1168 bytes
tls.key:  1679 bytes
```

I create secret command is `kubectl create secret tls tls-secret --cert=tls.pem --key=tls.key` after I describe it only tow file is  `tls.crt` and `tls.key`, missing the `ca.crt`

How can I create a TLS secret contain `ca.crt` file?

**Comment by siriuswinds** [comment]
@lizhongit 
why you need a ca.crt ? 
i don't have a ca.crt too and it works ok.

**Comment by lizhongit** [comment]
@siriuswinds 
In other words it works around for me now by your way, thanks a million. 
I just thinking about k8s TLS secret. Why harbor's TLS contain `ca.crt` but I not, It's a so strange for me.

**Comment by siriuswinds** [comment]
@lizhongit 
perhaps you can gotit from the yaml，you can create the secret containing ca.crt in data part

kubectl get secret harbor-harbor-ingress -n harbor -o yaml

**Comment by lizhongit** [comment]
Yeah, I can leaning from Chart of Harbor,
My Traefik has been configured global TLS by Let's Encript,
All the https access works well a long time ago,
I remove TLS part of Ingress harbor-harbor-ingress after I installed Harbor from Helm and it auto using global default TLS and works for me
