### ISSUE TITLE
need to split replication/core to different pods. 

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor-helm#222]
Currently replication/core is in the same pod, but replication will access the core through service IP, in some k8s deployment (like PKS), the hairpin mode is not enable which doesn't allow service within pod to access service IP backend by the same pod.

**Comment by ywk253100** [comment]
@renmaosheng Currently, the replication and core are in the same process, splitting them into two processes is our next step, maybe it can be completed in Harbor 1.9, it depends on our plan.

We cannot fix this just in chart, so I'm removing the `targer/1.8.0` label.

**Comment by reasonerjt** [comment]
@ywk253100 let's make sure there's a release note in the chart release.

**Comment by ywk253100** [comment]
Fixed.
