### ISSUE TITLE
Harbor helm upgrade fails due to volume multi attach error on multiple workers

### ISSUE THREAD

**Issue by yakbulut** [goharbor/harbor-helm#224]
Hi all,

We are running into an issue where upgrading harbor chart from 1.0.0 to 1.0.0 causes upgrade to break as JobService and Registry pods are stuck in ContainerCreate. Looking into kubectl describe reveals these have failed due to not being able to mount the volume.`Multi-Attach error for volume "pvc-xxx" Volume is already used by pod(s)`

Essentially, what happens is that during an upgrade if these pods are scheduled to start on different workers, new pods are unable to mount the volumes due to RWO access. We are unable to change this to RWM as it is not supported by vSphere cloud provider.

I have found the workaround to be manually setting the replica to 0 to terminate registry and jobservice and then patch it back to 1 right after upgrade. However, this is less than ideal.

Repro steps:
1. Get a kubernetes cluster with multiple workers
2. Helm install harbor 1.0.0
3. Helm upgrade harbor using the same values with --force and --recreate-pods
4. Registry and JobService are stuck at ContainerCreate

What is the solution for this issue ? Does harbor chart only work with RWM access on in a multi worker setup ?

Thanks,

**Comment by Benjvfr** [comment]
Hi,

Same problem again concerning the upgrade from Helm Chart v1.2.1 to v1.2.2.

Do you know how to that ?

Thanks.

**Comment by ywk253100** [comment]
Fixed
