### ISSUE TITLE
rancher cannot create catalog from private helm-chart catallog which from harbor？

### ISSUE THREAD

**Issue by bobo200128** [goharbor/harbor-helm#227]
harbor 1.7.5
sudo ./install.sh --with-notary --with-clair --with-chartmuseum

rancher 2.2.1

http://.../chartrepo/helm

problem:
in rancher,create catalog failed.the log is

Helm template failed. Error: stat template-dir: no such file or directory : exit status 1

Desired solution：
can create catalog from private helm chart

helm server can resolve the problem.
But I think there are better ways

**Comment by reasonerjt** [comment]
Closing the issue.

Seems you are using the offline installer which is based on docker-compose.
This has nothing to do with helm chart.
