### ISSUE TITLE
custom ingress path needed

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor-helm#238]
Hi,

In my case, I don't have several domain name, I have only one.
And I have several tools as well as harbor.
I guess many user in corporate are same as me.

so, basically I can't install harbor using this chart.
In my case, I need to change 

1. expose.ingress.hosts.core and expose.ingress.notary will be same.
2. ingress path :
portal : /  ->  /harbor (or user wanted)
core : /api/  -> /harbor/api or /harbor-api
core : /service/  -> /harbor/service or /harbor-service
...
notary : /  ->  /notary

like this.

please improve so I can install and use harbor!

Thanks.

below is copied from another issue.
```
Name:             my-harbor-test-harbor-ingress
Namespace:        default
Address:
Default backend:  default-http-backend:80 (10.24.2.7:8080)
TLS:
  my-harbor-test-harbor-ingress terminates core.sdjkf.ml
  my-harbor-test-harbor-ingress terminates registry.sdjkf.ml
Rules:
  Host               Path  Backends
  ----               ----  --------
  core.sdjkf.ml
                     /             my-harbor-test-harbor-portal:80 (<none>)
                     /api/         my-harbor-test-harbor-core:80 (<none>)
                     /service/     my-harbor-test-harbor-core:80 (<none>)
                     /v2/          my-harbor-test-harbor-core:80 (<none>)
                     /chartrepo/   my-harbor-test-harbor-core:80 (<none>)
                     /c/           my-harbor-test-harbor-core:80 (<none>)
  registry.sdjkf.ml
                     /   my-harbor-test-harbor-notary-server:4443 (<none>)
Annotations:
  ingress.kubernetes.io/ssl-redirect:           true
  nginx.ingress.kubernetes.io/proxy-body-size:  0
  nginx.ingress.kubernetes.io/ssl-redirect:     true
  ingress.kubernetes.io/proxy-body-size:        0
```

**Comment by Hokwang** [comment]
@ywk253100 @reasonerjt 
Guys, I need your attention and effort. Many thanks in advanced.

**Comment by ywk253100** [comment]
@Hokwang The docker client can only communicate with `/v2` API, not `/prefix/v2`, so we cannot just add some prefix at the path.

**Comment by Hokwang** [comment]
@ywk253100 Thanks for your comment,
if only /v2 is your concern, how about
portal : /  ->  /harbor (what user want)
core : /v2  -> /v2

I guess I can handle this way when I will not use /v2 path for other tool.
I think the important thing is do not use ingress path itself (like "/" )
and do not restrict domain address. (you should have special domain address for harbor(docker-registry). 

even if /api or others should be fixed, I can use it.
core : /api  ->  /harbor-api ( I want ) 
but 
/api is not changable, /api is ok.

and I found other tool (artifactory) 's example for using simillar way.
please refer [https://medium.com/@jainishshah17/kubernetes-nginx-ingress-with-artifactory-on-gke-e6781d4ab5e8](https://medium.com/@jainishshah17/kubernetes-nginx-ingress-with-artifactory-on-gke-e6781d4ab5e8)

this need ingress annotations rewrite ^/(v2)  /some/address/docker/null/v2/
I think we can handle /some/address/docker/null 

```
docker pull alpine
docker tag alpine my.tool.com/docker/alpine
docker push my.tool.com/docker/alpine
```
works well.


Conclusion,
my.tool.com/harbor  for ui(portal)
and docker command is
```
docker login -u user my.tool.com/harbor
docker push my.tool.com/harbor/project/alpine
```

**Comment by ywk253100** [comment]
`my.tool.com/harbor` doesn't work for docker.

And for the `target-rewrite`, the annotation doesn't work for all the ingress controllers: #210.

**Comment by Hokwang** [comment]
OK. I will close this case.

**Comment by Hokwang** [comment]
@xaleeks I want to hear your answer. could you look around this issue, please?

I think all app in kubernetes should support multiple instance (deployment) not using multiple domain.
So I mean that below case is supported.
If someone wants to deploy instance per subpath in one single domain, this should be possible.
www.company.com/harbor-prod
www.company.com/harbor-stage
www.company.com/harbor-dev

I think @ywk253100 said it is technically impossible, by the way I don't know why it is not possible and I just wonder is it real? (so sad for my poor tech level)
