### ISSUE TITLE
LoadBalancer sends wrong health checks

### ISSUE THREAD

**Issue by akranga** [goharbor/harbor-helm#246]
Nginx service setup 80 and 443 ports. Where http request to 80 port returns 301/2 to 443. Kubernetes takes first port see: [source code](https://github.com/kubernetes/cloud-provider-aws/blob/8f6e1e3d2cfa20a0deac088b9c4022d433500369/pkg/cloudprovider/providers/aws/aws.go#L3606) to setup healthcheck. This results in contradiction to aws [docs](https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-classic-health-checks/)

Happy to make a PR.

**Comment by ywk253100** [comment]
I didn't quite understand the issue. Could you describe it more detail?

**Comment by akranga** [comment]
Here are some details

**Steps to reproduce**:
1. Reproducible with Kubernetes v1.14 and aws cloud provider enabled
2. Install Harbor using helm chart with SSL enabled and nginx LoadBalancer
3. Open your browser and navigate to the URL (https) of the generated LoadBalancer
4. See empty page

**What have happened**:
1. Open AWS console and navigate to the EC2 >> Load Balansers
2. See healthy nodes: `OutOfService` error
3. Navigate to the health check: see that health check has been installed pointing to the `http` port
4. Use `curl --verbose` option to ping `http` port of the `nginx` service (harbor) and see http redirect  response code
5. Open trouble shoot manual from AWS [here](https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-classic-health-checks/). See that AWS Load Balancer health checks does not tolerate as healthy http redirect result code

**Why this have happened**:
1. Load balancer healthchecks has been managed by Kubernetes. 
1. Open code for Kubernetes aws cloud provider [here](https://github.com/kubernetes/cloud-provider-aws/blob/8f6e1e3d2cfa20a0deac088b9c4022d433500369/pkg/cloudprovider/providers/aws/aws.go#L3606)
2. See that in this case  takes first suitable port of the node to install a health check (and this is correct from Kubernetes point of view)

**What should be done**:
1. Easiest way to fix this is to declare https port before any other port. Then health check will return a result code `200`
2. Another option is to implement `/healthz` document for nginx that should return OK 200 and not redirection. However please note, helm chart must ensure that health check has type: `http` or `https`

**Comment by reasonerjt** [comment]
This seems to be related to the ambiguity in the `tls.enabled` when the `expose.type` is loadbalancer.
