### ISSUE TITLE
[Contribution proposal] Providing a SideCar container utility for External DB (GKE?)

### ISSUE THREAD

**Issue by ghost** [goharbor/harbor-helm#247]
Hello,

For my company, I'm trying to setup Harbor using your chart (v1.1.0), deployed in a GKE, using a Google SQL (postgre) instance as the Database.

By default, Google Cloud suggests to use the Public DB IP, which makes no sense when the SQL Instance as well as the Harbor services are internal to GKE.
Alternatives include:
 - Using private IP for the SQL Instance (Beta version for our Infra-as-code tools)
 - Using a sidecar Container (we're already using this method for other services).

We thought that using a sidecar container to proxify the access to the database would be an appropriate solution, and already have a patch for this internally.

Our internal patch is currently only handling external database, on the premise that it should be configured in the "database" block of the values.yml file from the chart.

It could be changed if you (as a project handling team) have a preferred alternative.
Would you be interested in such a contribution ?

**Comment by ywk253100** [comment]
I didn't quite understand what your issue is. Why can't you use the private IP? What the sidecar container is used for? If using a sidecar container, is the IP of database private or public?

**Comment by DavidPineauScality** [comment]
Hello @ywk253100

First point would be that the SQL Proxy (sidecar container) is advised by Google to reach out to the Google SQL database from a GKE cluster. It provides multiple bonuses, such as End-to-End encryption of the communications with the Google SQL database, and only requires the instance name and port (no IP, private or public), as documented here: https://cloud.google.com/sql/docs/mysql/connect-external-app?hl=en_US#proxy . Then, the container which requires access to the database connects locally to the port exposed by this SQL Proxy sidecar container (127.0.0.1:5432), and provides the usual authentication information.

Second point is that using the Private IP relies on beta features of our infra-as-code tool (Terraform + google-cloud providers) which is used for the setup of the infrastructure before deploying Harbor.
As much as possible, we want to rely on stable APIs and refrain from using beta features.

I hope this makes the context clearer. Please ask anything you need if part of it is still unclear to you.

**Comment by DavidPineauScality** [comment]
@ywk253100 Are you interested in this proposal ? As we have a PullRequest open, we'd gladly iterate on that until we reach something satisfactory for you.

If not, we'll handle this in our infra with a kind of internal patch, and close both Issue and PR.

**Comment by wu105** [comment]
We have a similar issue that might be addressed by adding a health check sidecar to the notary server pod:
On GKE, if we use the GCE ingress/loadbalancer, the notary root url must respond with 200 for the loadbalancer to consider it ready.  Alternatively, we could add a http readiness probe on the pod using a non-root path.  None of these would work as all the notary urls will respond 401 to the unauthenticated probing from the loadbalancer.  

This health check situation is documented at https://cloud.google.com/kubernetes-engine/docs/concepts/ingress

The readiness sidecar could respond to an unused health check path properly and forwarding everything else to the notary server.  

A best solution would be for the notary server to add an unauthenticated health check path but we are talking about helm charts here.

**Comment by Eric-Fontana-Bose** [comment]
I have solved this problem by using Kustomize and injecting and initContainer which creates the database tables in my RDS hosted postgres.

**Comment by reasonerjt** [comment]
Closing the issue as the submitter of OP seems to be removed.
