### ISSUE TITLE
Installation fails with validation failed

### ISSUE THREAD

**Issue by tantweiler** [goharbor/harbor-helm#250]
Hi all!

I tried to install the latest chart version 1.1.0. The installation fails with the following error message:
```
Error: validation failed: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.CONTEXT_PATH, unknown object type "nil" in ConfigMap.data.TLS_CERT, unknown object type "nil" in ConfigMap.data.TLS_KEY]

Any idea would be great. Thanks!

**Comment by ywk253100** [comment]
It's a known issue, please refer to the comment https://github.com/goharbor/harbor-helm/issues/192#issuecomment-495151700 to workaround it for now.

**Comment by tantweiler** [comment]
Helm version 2.14.1 fixes this isssue!
