### ISSUE TITLE
db logs: LOG:  could not create IPv6 socket: Address family not supported by protocol

### ISSUE THREAD

**Issue by lizhongit** [goharbor/harbor-helm#253]
Env:

Helm Client: v2.13.1
Helm Server: v2.13.1
K8s: v1.14.0
OS: CoreOS
Docker: 18.06.3-ce
Go: 1.10.8

I wanted install harbor on my k8s cluster, But my cluster cannot support IPv6, I got the logs from my pod of harbor-harbor-database-0 

```shell
LOG:  could not create IPv6 socket: Address family not supported by protocol
```

I can’t figure it out how to changing database listening config on `values.yaml` file

Is there a way to change postgresql config to listening via IPv4 address?

**Comment by lukasmrtvy** [comment]
It also does not work with external database ( Azure PostgreSQL ).

harbor-clair:
```
{"Event":"pgsql: could not open database: pq: Server is not configured to allow ipv6 connections.","Level":"fatal","Location":"main.go:97","Time":"2020-03-26 12:54:16.867673"}
```

**Comment by reasonerjt** [comment]
Thanks @lukasmrtvy 
@lizhongit if the problem remains please open a new issue.
