### ISSUE TITLE
StatefulSet options for Deployments with PVC (chartmuseum for instance)

### ISSUE THREAD

**Issue by mumrau** [goharbor/harbor-helm#260]
Hello,

As stated in #7 , a few components moved to Deployment from StatefulSet because they were stateless, at least at the time.
Unfortunately, a few things changed and some of the components now can be persistent, (I say can, because for example chartmuseum can be used with various cloud storage backends) and they use PVC which are most likely in ReadWriteOnce.
Thus, when you apply a change, another ReplicaSet gets spawned, and since it cannot mount the volume cause it is already mounted on the old ReplicaSet, we're stucked. The old one isn't deleted because the new one cannot reach a ready state.
My possible fix would simply be to give the choice in between SS and Dpl for some components.

Could somebody brigthen me about this?

**Comment by ywk253100** [comment]
@mumrau As we discussed in https://github.com/goharbor/harbor-helm/pull/410, the `jobservice`, `chartmuseum` and `registry` are both Deployment rather than StatefulSet.
And a new PR https://github.com/goharbor/harbor-helm/pull/470 is submitted to fix the upgrade issue, closing this one.
