### ISSUE TITLE
error validating data: unknown object type "nil" in ConfigMap.data.CONTEXT_PATH

### ISSUE THREAD

**Issue by An0nymous0** [goharbor/harbor-helm#269]
![image](https://user-images.githubusercontent.com/6836030/59958785-8b2acf80-94de-11e9-82e9-f0dae27d35e3.png)

**Comment by ywk253100** [comment]
@An0nymous0 Please use helm 2.14.1+ according to https://github.com/helm/helm/issues/5750

**Comment by RoyRimjhim** [comment]
Hello Team, We are facing this issue in the newly released v3 as well but not in the beta version v3.0.0-beta.4. Kindly help with the resolution.

**Comment by ywk253100** [comment]
What is the version of Harbor chart you are using? I think we have fixed it in the patch releases
