### ISSUE TITLE
Can not show images on harbor

### ISSUE THREAD

**Issue by leowucn** [goharbor/harbor-helm#283]
I installed harbor through helm-harbor which version is v1.1.0. 

My problem is that I can `docker login` succeed on terminal, and successfully `docker push` images, but there is no image showing in harbor web page, there is no any image there.

I checked the log of the container `registry` of pod `harbor-registry` which constantly generate the following information, I don't know if this has some relationship with my problem.
![Snipaste_2019-07-06_00-48-42](https://user-images.githubusercontent.com/16133390/60735945-d7b6e600-9f87-11e9-9986-197b623294f0.jpg)

Is there any one can help me? Thanks.

**Comment by ywk253100** [comment]
Could you package all logs of harbor-core and upload them?

**Comment by leowucn** [comment]
I solved the problem. The reason is I have a wrong configuration for "externalURL" in "values.yaml"
