### ISSUE TITLE
Unable to login via docker cli to Harbor deployed behind Traefik

### ISSUE THREAD

**Issue by nick-lehmann** [goharbor/harbor-helm#287]
I have a harbor deployment running on an on-premise Kubernetes cluster. Traefik works as the reverse proxy and ingress controller, and manages a wildcard certificate for my whole domain (`nicklehmann.sh`). Deploying went fine and the web UI works nicely. 

However, when I try to login into the registry with the docker cli, I get the following error message:

```
> docker login https://hub.nicklehmann.sh/
Username: admin
Password: ***
Error response from daemon: Get https://hub.nicklehmann.sh/v2/: x509: certificate signed by unknown authority
```

I then downloaded the registry certificate for `library` and marked it as trusted with this command (on Manjaro):

```
> trust anchor ca.crt
```

After restarting the docker service, the error still persists.

**Comment by stephenmoloney** [comment]
See here 

https://github.com/goharbor/harbor/blob/b55f4036798a3ac88c45498cfdb6587f4c4d35d4/docs/configure_https.md#troubleshooting

Number 2
