### ISSUE TITLE
Any plans to run as nonRoot? (PSP / Security Contexts)

### ISSUE THREAD

**Issue by jimangel** [goharbor/harbor-helm#288]
After enabling PSP's our harbor deployments fail due to them requiring root (or inability to validate a nonRoot UID). What is the need / requirement to run containers elevated? Is there a recommended PSP policy to apply to allow them to run without restricting too much?

I found this 26 day old related PR: https://github.com/goharbor/harbor-helm/pull/266

For now, we can allow an exception for this deployment, but I would really like to avoid that.

**Comment by voor** [comment]
Awesome, really glad you found that PR.  Additionally, there's a bit of work that needs to happen to Harbor itself to run fully as non-root.  The entrypoints for the Docker files will need to either be migrated to init containers, or re-architected since they're hitting some `sudo` commands:
https://github.com/goharbor/harbor/issues/8300

**Comment by voor** [comment]
Related to https://github.com/goharbor/harbor-helm/issues/53
Suggest `initContainers` as an alternative, which is a similar approach that `stable/postgresql` takes to allow turning off in the event of high security environments.

**Comment by TheAifam5** [comment]
I wonder why the harbor team decided to build everything on root & sudo :D

**Comment by voor** [comment]
> I wonder why the harbor team decided to build everything on root & sudo :D

This most likely has to do with some of the systems Harbor runs on (it doesn't *just* run on Kubernetes), and the lack of mechanisms those systems may have to do certain `chmod` or `chown` operations on mounted volumes.

**Comment by verwilst** [comment]
I think Harbor 1.9 fixes most of the issues here, running the containers as non-root. Am I correct?

**Comment by funkypenguin** [comment]
I'm running Harbor 1.9, and can confirm the issue still exists:

```
root@cn1:/tmp/ansible.5OZFrvtemp# kubectl get pods -n harbor
NAME                                           READY   STATUS                            RESTARTS   AGE
harbor-harbor-chartmuseum-5c78bf65f6-gq29q     1/2     CreateContainerConfigError        0          106s
harbor-harbor-clair-79f798b8f7-8nfmq           1/2     CreateContainerConfigError        0          106s
harbor-harbor-core-5dbf868b65-xxrmm            0/2     ContainerCreating                 0          106s
harbor-harbor-database-0                       0/2     Init:CreateContainerConfigError   0          106s
harbor-harbor-jobservice-c9844999-5mrhl        1/2     CreateContainerConfigError        0          106s
harbor-harbor-notary-server-7554dfc9b6-98db9   1/2     CreateContainerConfigError        0          106s
harbor-harbor-notary-signer-5948595cfd-7rkpb   1/2     CreateContainerConfigError        0          106s
harbor-harbor-portal-66b448f6db-cx2dh          1/2     CreateContainerConfigError        0          106s
harbor-harbor-redis-0                          1/2     CreateContainerConfigError        0          106s
harbor-harbor-registry-579cd8fd4d-xt9kr        1/3     CreateContainerConfigError        0          106s
root@cn1:/tmp/ansible.5OZFrvtemp# kubectl get serviceaccount -n harbor
NAME      SECRETS   AGE
default   1         2m37s
root@cn1:/tmp/ansible.5OZFrvtemp#
```

**Comment by voor** [comment]
What version of kubernetes is that?

**Comment by verwilst** [comment]
The version isn't really important imo, it's just whether PodSecurityPolicies are enabled. Maybe a `kubectl describe` of one of the CreateContainerConfigErrored container might be beneficial?

**Comment by Jude188** [comment]
Having a similar issue I believe perhaps. Harbor trying and failing to chown a bunch of PVC directories.

**Comment by amimof** [comment]
Having the same issue, running harbor 2.2 on Kubernetes 1.16.7 with PodSecurityPolicy enabled. The [container image](https://hub.docker.com/layers/goharbor/harbor-jobservice/v1.10.2/images/sha256-ffae3c00e373c9bf88cfeb8afc177c0d98382ff3345fbca88b0816ceed7ed7ff?context=explore) is built using the `USER harbor` directive. Which is not optimal, should be a numeric value.

**Comment by funkypenguin** [comment]
FWIW, I've switched over to the [Bitnami charts/images](https://github.com/bitnami/charts/tree/master/bitnami/harbor), which are able to run as non-root 👍

**Comment by reasonerjt** [comment]
I'll have to check how bitnami is building the images for harbor.

**Comment by ywk253100** [comment]
Let's use https://github.com/goharbor/harbor-helm/issues/756 to track the work of psp.
