### ISSUE TITLE
Harbor in K8s update 1.6.0 -> 1.8.1. (0.3.0 -> 1.1.1.)

### ISSUE THREAD

**Issue by zdenekvicar** [goharbor/harbor-helm#296]
Hello all,
I would like to ask you if anyone of you does have experiences with updating Harbor 1.6.0 to 1.8.1. in Kubernetes. My version 1.6.0 was deployed using heavy updated Helm chart v0.3.0 ... and using `helm upgrade release-name --force .` as recommended [here](https://github.com/goharbor/harbor-helm/blob/master/docs/Upgrade.md) is not an option for me (I am not using helm to install Harbor - just generating manifests from it).

Now I am in a situation where Harbor is running, UI says version 1.8.1 ... but I have DB from version 1.6.0.

At the very least, it has some problems with translations in English in UI -> see picture.

However, I suspect also other issues, as below result does not look good either:

```
registry=> select * from alembic_version;
 version_num 
-------------
 1.6.0
(1 row)
```

So my main question is, is there any guide how to perform the DB upgrade/migration (whatever is needed) manually, not by using `helm upgrade` ?

![image](https://user-images.githubusercontent.com/41696960/61641119-d7fcf400-ac9e-11e9-9afa-52fc04a8b9c4.png)

**Comment by ywk253100** [comment]
The database schema is upgraded automatically. To fix the issue you got in UI, you can try to clear the cache of browser and refresh the page.

**Comment by zdenekvicar** [comment]
@ywk253100  thanks, seems it helped :) 

however i noted the alembic version in DB keeps on 1.6.0 value even though I've tried to install clean Harbor on 1.8.1 version ... was this table deprecated somehow, so its not updated with never versions ?

**Comment by ywk253100** [comment]
Yes, it's deprecated. We use `schema_migrations` currently instead.

**Comment by zdenekvicar** [comment]
Thanks a lot, closing Issue now 😉👍🏻
