### ISSUE TITLE
Docker Distribution offers configuration support for Middleware, harbor-helm should too.

### ISSUE THREAD

**Issue by jkjell** [goharbor/harbor-helm#304]
We'd like to use the options documented [here](https://github.com/docker/distribution/blob/master/docs/configuration.md#middleware) to offer a registry that uses CloudFront.

**Comment by ywk253100** [comment]
Fixed by #305.

**Comment by dbarranco** [comment]
Hello @jkjell @ywk253100, sorry for bumping again this topic.

I've been taking a look at the Harbor distribution configuration and I haven't found anything at all in the Internet.

At the moment, I have a setup in which:

- Harbor runs in an EKS cluster
- Harbor is configured against S3 to upload its manifests/blobs
- Harbor has the Cloudfront configuration

The whole setup works fine, I don't see any error log at all, but I don't see how this setup is working at all.
Have you been able to configure this setup successfully? Are there any docs or resources I could follow to test this?

Thanks in advance!
