### ISSUE TITLE
clusterIP expose type should allow annotations

### ISSUE THREAD

**Issue by tluimes** [goharbor/harbor-helm#307]
I would like to add annotations to the harbor service when using the `clusterIP` `expose.type`. Similar to the loadbalancer and ingress types.

**Comment by titou10titou10** [comment]
+1
This is required if we want OpenShift to generate a certificate for the nginx service, and connect it to a "route" of kynd "reencrypt"
Annotation "service.alpha.openshift.io/serving-cert-secret-name"

**Comment by reasonerjt** [comment]
I think this is do-able @ywk253100
