### ISSUE TITLE
Basic Auth for Chart Museum is hardcoded

### ISSUE THREAD

**Issue by juan131** [goharbor/harbor-helm#317]
The environment variable **BASIC_AUTH_USER** is hardcoded to `chart_controller` at the ConfigMap below:

https://github.com/goharbor/harbor-helm/blob/master/templates/chartmuseum/chartmuseum-cm.yaml#L13

Is there any reason for that? I assume that `harbor-core` uses that authentication user by default. However, I think this parameter should be configurable both in **Chartmuseum** and **Core** components.

I also noticed the **BASIC_AUTH_PASS** environment variable is set reusing the secret used on Core component to set **CORE_SECRET**. Check the links below:

https://github.com/goharbor/harbor-helm/blob/master/templates/chartmuseum/chartmuseum-dpl.yaml#L58
https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-dpl.yaml#L53

Is there any reason for this? Shouldn't this basic authentication setup for **Chartmuseum** be independent?

**Comment by ywk253100** [comment]
Users shouldn't access the chartmuseum directly, they should call the APIs provided by Harbor. The credential is used only for authentication between the Harbor internal components.
Is there any special reason that we need to expose the credential to users?

**Comment by juan131** [comment]
Hi @ywk253100 

I agree, there's no reason to expose the credentials... but why hardcode it? 

Even if those credentials are used by internal components to communicate, why not allowing to choose to use any other user? I might want to use a different username (instead of `chart_controller`) for security reasons (avoiding common/default names for admin credentials).

**Comment by reasonerjt** [comment]
@juan131 

You can do it by updating the chart, but I don't think we want to add extra parameters in `values.yaml` for user to set.

Considering it is internal, we may use other authn mechanism or not requiring auth at all

**Comment by reasonerjt** [comment]
Considering the inactivity of this issue.
I'm closing as a won't fix
