### ISSUE TITLE
Robot Accounts Unable to Authenticate when .core.secretName is Changed

### ISSUE THREAD

**Issue by KISStian** [goharbor/harbor-helm#326]
We were using the default Harbor cert/key, but decided to use a custom cert instead.  However, when we populated .core.secretName so that it uses the custom cert, we noticed that the robot accounts were unable to authenticate.  To resolve the issue, we reverted to using the default provided by Harbor.  Should .core.secretName be immutable and not change between releases/deployments?

**Comment by reasonerjt** [comment]
@KISStian  I think that's a valid concern, we'll investigate if there's a way that helm bypass the updating of some resource during update.

**Comment by ywk253100** [comment]
I don't think helm has the ability to keep some properties immutable, that should be guaranteed by users
