### ISSUE TITLE
最新版本貌似helm无法安装成功

### ISSUE THREAD

**Issue by duiniwukenaihe** [goharbor/harbor-helm#327]
部署了一套新的环境，但是数据库database 会偶发出现权限问题。harbor-portal ，job也会出现各种异常，前段时间同样部署是没有问题的。登录dockerhub发现helm默认dev镜像有更新。选择v1.8.2 v1.8.2-dev版本无异常

**Comment by ywk253100** [comment]
It's a known issue and the fixing #324 is in progress.

**Comment by duiniwukenaihe** [comment]
ok ,values.yaml中tag能否修改下用稳定版标识？一般其他项目规范点都采用个唯一标识呢，dev这样的一般小白搭建确实容易懵，打扰大佬了

**Comment by ywk253100** [comment]
The master branch is under development and unstable, follow the guide https://github.com/goharbor/harbor-helm#installation to install the stable one
