### ISSUE TITLE
Configuration option for registry mirroring

### ISSUE THREAD

**Issue by jbialy** [goharbor/harbor-helm#333]
Are there plans to allow a configuration option that allow using Harbor to mirror another registry?

https://github.com/goharbor/harbor/blob/master/contrib/Configure_mirror.md

**Comment by ywk253100** [comment]
Issue your requirement in https://github.com/goharbor/harbor/issues repository, this repository is only used for Harbor helm chart.

For mirror, you can refer to https://github.com/goharbor/harbor/issues/8082 and https://github.com/goharbor/harbor/issues/6894
