### ISSUE TITLE
Add ECR endpoint

### ISSUE THREAD

**Issue by mlewiarz** [goharbor/harbor-helm#342]
Hi, is there instruction how to add ECR endpoint to Harbor? 
I tried on dev images, tried my personal credentials and gernerated by 'aws ecr login'

Thanks,
Marcin

**Comment by bitsf** [comment]
Use your AK not password, and be sure you have Storage permission.

![image](https://user-images.githubusercontent.com/188115/64667096-30749480-d48b-11e9-93c0-b5178d489977.png)

**Comment by bitsf** [comment]
And next time, please submit such issue to harbor repo, not harbor-helm
