### ISSUE TITLE
fail to push images with traefik as ingress

### ISSUE THREAD

**Issue by Jean-PhilippeGouin** [goharbor/harbor-helm#345]
Hi ,

**Description** : 
I cannot push to harbor using traefik as ingress controller in AWS.
Login works fine and pull too.
When i try to push it keep retrying and finish by a EOF.
With strace enable, the error come from a Unavailable Ressource.

**Environment** : 
I use a NLB with ssl termination and traefik redirect all 80 in 443.

**Resolution** 
By adding in the **registry** config.yaml configmap the following line it resolves the issue : 
```
http :
  relativeurls: true
```

Unfortunately this value in not accessible from the values.yaml.

It could be great to have this available for configuration.

**Comment by ywk253100** [comment]
There is a PR https://github.com/goharbor/harbor-helm/pull/271 to make it available in `values.yaml`

**Comment by ywk253100** [comment]
PR #271 is merged.

**Comment by 3ks** [comment]
Thanks, It's work!
