### ISSUE TITLE
Separate core and notary ingresses

### ISSUE THREAD

**Issue by StianOvrevage** [goharbor/harbor-helm#349]
Currently it seems only one ingress is created for both hostnames.

I think this causes issues with cert-manager and nginx-ingress already running in the cluster. With HTTP-01 challenge cert-manager can only issue certificate for 1 hostname at a time. However, with this ingress setup nginx-ingress requires both names to be in the same certificate.

I see no reason these could not be split into two separate independent ingress objects allowing cert-manager and nginx-ingress to work automatically.

Sidenote: I debugged this as a authentication problem for a long while since the dashboard said "Invalid username and password" no matter what. It turns out the login request failed client-side because of invalid certificate (even though I accepted it when browsing to it). A more helpful error message on the client when the login request is blocked would be helpful :)

**Comment by heww** [comment]
Closed by #575
