### ISSUE TITLE
livenessprobe and readnessprobe for jobservice

### ISSUE THREAD

**Issue by starzha** [goharbor/harbor-helm#35]
Hi,

Any suggestion on livenessprobe and readnessprobe commands for jobservice?

Thanks,
yzha

**Comment by ywk253100** [comment]
You can use `/api/v1/stats` https://github.com/goharbor/harbor/blob/master/src/jobservice/api/router.go#L73.
Are you adding probes to all components? Will you contribute this part back to the upstream?

**Comment by starzha** [comment]
@ywk253100 Thanks, i tried the command in the pod of jobservice, but requires authorization.
What else need i to do?

curl http://localhost:8080/api/v1/stats
{"code":10014,"message":"Unauthorized","details":"header 'Authorization' missing"}

Once i finish the probes, i wil contribute back for sure.

Thanks,
yzha

**Comment by ywk253100** [comment]
@starzha Hi, any updates on the probe works?

**Comment by ywk253100** [comment]
PR #78 opened for probes.
