### ISSUE TITLE
Incorrect input validation errors on harbor user creation

### ISSUE THREAD

**Issue by jacob-ward** [goharbor/harbor-helm#350]
I'm having a couple of issues with Harbor portal:
1. I cant create a new user due to input validation errors on the username and email fields
2. I cant log in with the default harbor admin account

For example the username **dave** is rejected, and the email address **dave@example.com** is rejected for being invalid.

Having looked at the HTML for the user creation modal in the chrome developer tool I can not see any issues, the input validation is there, and I am not breaking any rules as far as i can tell.

I have tested this on chrome and firefox and the behaviour is consistent.

The harbor instance is deployed on a kubernetes cluster and is exposed through ingress, using haproxy ingress controller. I am using a browser extension to supply the correct 'host' value.

I deployed this yesterday with dev tags on all components and imagePullPolicy set to Always

values.yaml below:
`expose:
  type: ingress
  tls:
    enabled: true
    secretName: ""
    notarySecretName: ""
    commonName: ""
  ingress:
    hosts:
      core: core.harbor
      notary: notary.harbor
    controller: default
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  clusterIP:
    name: harbor
    ports:
      httpPort: 80
      httpsPort: 443
      notaryPort: 4443
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002
      https:
        port: 443
        nodePort: 30003
      notary:
        port: 4443
        nodePort: 30004
  loadBalancer:
    name: harbor
    IP: ""
    ports:
      httpPort: 80
      httpsPort: 443
      notaryPort: 4443
    annotations: {}
    sourceRanges: []

externalURL: https://portal.harbor

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-claim
      storageClass: slow
      subPath: registry
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      existingClaim: harbor-claim
      storageClass: slow
      subPath: chartmuseum
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      existingClaim: harbor-claim
      storageClass: slow
      subPath: jobservice
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
  imageChartStorage:
    disableredirect: false
    type: filesystem
    filesystem:
      rootdirectory: /storage
    azure:
      accountname: accountname
      accountkey: base64encodedaccountkey
      container: containername
    gcs:
      bucket: bucketname
      encodedkey: base64-encoded-json-key-file
    s3:
      region: us-west-1
      bucket: bucketname
    swift:
      authurl: https://storage.myprovider.com/v3/auth
      username: username
      password: password
      container: containername
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      region: regionname
      bucket: bucketname

imagePullPolicy: Always

imagePullSecrets:

logLevel: debug
harborAdminPassword: "Harbor12345"
secretKey: "not-a-secure-key"

proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
  components:
    - core
    - jobservice
    - clair

nginx:
  image:
    repository: goharbor/nginx-photon
    tag: dev
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

portal:
  image:
    repository: goharbor/harbor-portal
    tag: dev
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

core:
  image:
    repository: goharbor/harbor-core
    tag: dev
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""
  secretName: ""

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: dev
  replicas: 1
  maxJobWorkers: 10
  jobLogger: file
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""

registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: dev
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: dev
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: ""
  middleware:
    enabled: false
    type: cloudFront
    cloudFront:
      baseurl: example.cloudfront.net
      keypairid: KEYPAIRID
      duration: 3000s
      ipfilteredby: none
      privateKeySecret: "my-secret"

chartmuseum:
  enabled: true
  absoluteUrl: false
  image:
    repository: goharbor/chartmuseum-photon
    tag: dev
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

clair:
  enabled: true
  image:
    repository: goharbor/clair-photon
    tag: dev
  replicas: 1
  updatersInterval: 12
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

notary:
  enabled: true
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: dev
    replicas: 1
  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: dev
    replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secretName: ""

database:
  type: external
  internal:
    image:
      repository: goharbor/harbor-db
      tag: dev
    password: "changeit"
    nodeSelector: {}
    tolerations: []
    affinity: {}
  external:
    host: 172.16.112.84
    port: 5432
    username: ******
    password: ******
    coreDatabase: registry
    clairDatabase: clair
    notaryServerDatabase: notary_server
    notarySignerDatabase: notary_signer
    sslmode: "disable"
  maxIdleConns: 50
  maxOpenConns: 100
  podAnnotations: {}

redis:
  type: external
  internal:
    image:
      repository: goharbor/redis-photon
      tag: dev
    nodeSelector: {}
    tolerations: []
    affinity: {}
  external:
    host: 172.16.112.122
    port: 6379
    coreDatabaseIndex: 0
    jobserviceDatabaseIndex: 1
    registryDatabaseIndex: 2
    chartmuseumDatabaseIndex: 3
    password: ""
  podAnnotations: {}
`

**Comment by ywk253100** [comment]
Could you try to install the stable version rather than the `dev`? And did the error reported by frontend or backend? Could you provide the logs of `core`?
