### ISSUE TITLE
failed to initialize database: file does not exist

### ISSUE THREAD

**Issue by NanXuejiao** [goharbor/harbor-helm#354]
**version**
tag v1.1.2
**problem**
```
2019-09-16T14:02:03Z [ERROR] [/common/config/manager.go:192]: failed to get key admiral_url, error: the configure value is not set
2019-09-16T14:02:03Z [ERROR] [/common/config/manager.go:192]: failed to get key admiral_url, error: the configure value is not set
2019-09-16T14:02:03Z [INFO] [/core/config/config.go:143]: initializing the project manager based on local database...
2019-09-16T14:02:03Z [INFO] [/core/main.go:96]: configurations initialization completed
2019-09-16T14:02:03Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-maxim-harbor-database port-5432 databse-registry sslmode-"disable"
[ORM]2019/09/16 14:02:03 Detect DB timezone: UCT open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
2019-09-16T14:02:03Z [INFO] [/common/dao/base.go:89]: Register database completed
2019-09-16T14:02:03Z [INFO] [/common/dao/pgsql.go:107]: Upgrading schema for pgsql ...
2019-09-16T14:02:03Z [ERROR] [/common/dao/pgsql.go:112]: Failed to upgrade schema, error: "file does not exist"
2019-09-16T14:02:03Z [FATAL] [/core/main.go:103]: failed to initialize database: file does not exist
```
**value.yaml**
```
externalURL: http://xxx.xxx
```
What's wrong?

**Comment by NanXuejiao** [comment]
I added `ADMIRAL_URL: "NA"` to core-cm.yaml, and this fix `[ERROR] [/common/config/manager.go:192]: failed to get key admiral_url, error: the configure value is not set
`
But I still got `[ERROR] [/common/dao/pgsql.go:112]: Failed to upgrade schema, error: "file does not exist"`

How to fix this?

**Comment by ywk253100** [comment]
Is it a fresh install? 
Could you run the following commands to check the schema version stored in database?

Run bash in database container, replace the pod name with yours:
```
kubectl exec -it harbor-harbor-database-0 bash
```
Connect to the postgres:
```
psql -U postgres -d registry
```
Check the schema version:
```
select * from schema_migrations;
```

**Comment by NanXuejiao** [comment]
I installed harbor earlier, and it worked well for a few days, but some harbor pods restarted recently, then occurred error. And I can't fix that so delete and re-install harbor.

Result of above command you provide:
```
root [ / ]# psql -U postgres -d registry
psql (9.6.14)
Type "help" for help.

registry=# select * from schema_migrations;
 version | dirty
---------+-------
      10 | f
(1 row)
```

**Comment by ywk253100** [comment]
You should remove all the PVCs before re-installing

**Comment by NanXuejiao** [comment]
I tried to delete PVC harbor used after deleting harbor by helm just now, then created the PVC，and installed harbor again.
I get the same error `Failed to upgrade schema, error: "file does not exist"`

BTW, I use k8s local pv to store harbor data, and my pv has old data.

**Comment by NanXuejiao** [comment]
`Failed to upgrade schema, error: "file does not exist"`
This mean upgrading harbor but can't find file? What file is there need?

**Comment by mumrau** [comment]
I'm facing similar issues, on my end I have:
```Registering database: type-PostgreSQL host-gcn-harbor-harbor-database port-5432 databse-registry sslmode-"disable"```
I think there is a typo on `databse-registry`, an `a` is missing obviously, this might be the cause.

**Comment by reasonerjt** [comment]
For chart issue please open it on
https://github.com/goharbor/harbor-helm

**Comment by mumrau** [comment]
I hardly believe this is related to a chart issue.

Le ven. 20 sept. 2019 à 05:03, Daniel Jiang <notifications@github.com> a
écrit :

**Comment by NanXuejiao** [comment]
I try to set `schema_migrations` `dirty`=false.
```
root [ / ]# psql -U postgres -d registry
psql (9.6.14)
Type "help" for help.
registry=# update schema_migrations set dirty = false;
```

Other pods telnet 10.96.192.185 5432 is ok, but `core` pod can not connect to `database`.
`core` log:
```
[ERROR] [/common/utils/utils.go:101]: failed to connect to tcp://harbor-harbor-database:5432, retry after 2 seconds :dial tcp 10.96.192.185:5432: i/o timeout
```

`database` log:
```
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  invalid length of startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
```

**Comment by NanXuejiao** [comment]
> I'm facing similar issues, on my end I have:
> `Registering database: type-PostgreSQL host-gcn-harbor-harbor-database port-5432 databse-registry sslmode-"disable"`
> I think there is a typo on `databse-registry`, an `a` is missing obviously, this might be the cause.
> 
> EDIT: output of above command:
> 
> ```
> psql (9.6.14)
> Type "help" for help.
> 
> registry=# select * from schema_migrations
> registry-# ;
>  version | dirty 
> ---------+-------
>       11 | f
> (1 row)
> ```
> 
> PS: mine is not a fresh install, but I strongly desire upgrade path with helm to function.
> 
> On the database log side, I get `LOG: incomplete startup packet` every time `core` tries to start up.

The same with @mumrau

**Comment by ywk253100** [comment]
The root cause for the error `file does not exist` is that you guys use `dev` images or try to downgrade the installation.
@NanXuejiao The version `10` is the schema version of Harbor 1.9(Harbor helm 1.2.0), but you are trying to install Harbor helm 1.1.2(Harbor 1.8.2) whose schema version is `5`.

@mumrau The version `11` is the current schema version on master branch, you shouldn't use the images built from master branch, those images are unstable
