### ISSUE TITLE
High Availability Documentation

### ISSUE THREAD

**Issue by mark007** [goharbor/harbor-helm#368]
Hi,

I am very interested in the high availability features in this project. I have been reading the High Availability guide below and it is very good. However I am not able to see from the current documentation what high availability really means here. Mainly I'm wondering in the event of certain failures while the system is in use. So even when there are 2 instances of each service, when an ongoing use case is running, and the 1 instance that this use case is running on goes down, how does the system ensure the user is not effected.

Is this supported, or in this case is the system able to retry (if its an internal call thats failing), or is the user expected to retry (if its a northbound, external service thats failing).

I am wondering if some of this could be described in the existing documentation so it is clear what happens to ongoing use cases, in the event of failures.

https://github.com/goharbor/harbor-helm/blob/master/docs/High%20Availability.md

Regards,
Mark

**Comment by ywk253100** [comment]
The current ongoing request has to retry. The HA solution makes sure that the following requests aren't effected by the failure of one instance.
