### ISSUE TITLE
harbor-portal is missing in noproxy harbor-core configmap

### ISSUE THREAD

**Issue by HaveFun83** [goharbor/harbor-helm#390]
Hi thanks for your hard work to make this project so awesome.

We use harbor behind a proxy and still see harbor-portal requests within our proxy log form the harbor-core pod.
I added the harbor-portal to the harbor-core configmap here: https://github.com/goharbor/harbor-helm/blob/0e0bb5872af1f2ffc5c7b97184bbcbf0b1d9ed29/templates/core/core-cm.yaml#L57

but i think the harbor-portal should also added to the template file here:
https://github.com/goharbor/harbor-helm/blob/0e0bb5872af1f2ffc5c7b97184bbcbf0b1d9ed29/templates/_helpers.tpl#L284

any suggestion?

**Comment by ywk253100** [comment]
@HaveFun83 Yes, you are correct. Any interest to submit a PR to fix it?
