### ISSUE TITLE
nginx not work

### ISSUE THREAD

**Issue by myeveryheart** [goharbor/harbor-helm#406]
I can't open portal through web: 192.168.1.100:30002

helm install harbor/harbor --name harbor --version 1.2.1 -f harbor-config.yaml

and harbor-config.yaml is 

expose:
  type: nodePort
  tls:
    enabled: false
externalURL: http://192.168.1.100:30002

[root@localhost bin]# kubectl get pods
NAME                                           READY   STATUS             RESTARTS   AGE
harbor-harbor-chartmuseum-676d6b5cd4-m5p7t     2/2     Running            0          12m
harbor-harbor-clair-7b5c45f5f4-6qzfb           2/2     Running            4          12m
harbor-harbor-core-f54b545bf-fgpmn             2/2     Running            4          12m
harbor-harbor-database-0                       2/2     Running            0          12m
harbor-harbor-jobservice-65b77c586-5hwd4       2/2     Running            2          12m
harbor-harbor-nginx-6dbd5b6666-jhjrq           1/2     CrashLoopBackOff   7          12m
harbor-harbor-notary-server-c798c64c4-gf6w9    2/2     Running            2          12m
harbor-harbor-notary-signer-7f74c946db-5bm22   2/2     Running            2          12m
harbor-harbor-portal-64bc45998-f2rfb           2/2     Running            0          12m
harbor-harbor-redis-0                          2/2     Running            0          12m
harbor-harbor-registry-c875c5648-mrhfr         3/3     Running            0          12m
jaeger-agent-n78jm                             2/2     Running            0          4h51m
jaeger-collector-665b959b4b-2p8vp              2/2     Running            4          4h51m
jaeger-elasticsearch-client-98c7b4bf9-6ckf9    2/2     Running            0          4h51m
jaeger-elasticsearch-client-98c7b4bf9-xkdvv    2/2     Running            0          4h51m
jaeger-elasticsearch-data-0                    2/2     Running            0          4h51m
jaeger-elasticsearch-data-1                    2/2     Running            0          4h49m
jaeger-elasticsearch-master-0                  2/2     Running            0          4h51m
jaeger-elasticsearch-master-1                  2/2     Running            0          4h49m
jaeger-elasticsearch-master-2                  2/2     Running            0          4h49m
jaeger-query-7dcbdcf9b5-xz7dz                  3/3     Running            4          4h51m
jenkins-65bf695c9d-4z7qw                       2/2     Running            0          26h
loki-0                                         2/2     Running            7          33h
loki-promtail-llpm6                            2/2     Running            15         33h
nfs-client-provisioner-55fdc7df7d-6jzgn        2/2     Running            1          26h
[root@localhost bin]# kubectl describe pod harbor-harbor-nginx-6dbd5b6666-jhjrq
Name:           harbor-harbor-nginx-6dbd5b6666-jhjrq
Namespace:      default
Priority:       0
Node:           localhost.localdomain/192.168.1.100
Start Time:     Fri, 18 Oct 2019 20:59:02 +0800
Labels:         app=harbor
                chart=harbor
                component=nginx
                heritage=Tiller
                pod-template-hash=6dbd5b6666
                release=harbor
Annotations:    checksum/configmap: 29e019bc7d497d8d2fbf12860797c9e9fa67a892b628bc3fed58a219cd22f4a4
                sidecar.istio.io/status:
                  {"version":"2696c96840179bdcd8f86ed60a643396f0cb250f56458b46a7fc667e6c75ef7f","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:         Running
IP:             10.244.0.69
Controlled By:  ReplicaSet/harbor-harbor-nginx-6dbd5b6666
Init Containers:
  istio-init:
    Container ID:  docker://7e8f8fbd47884d709b154a5e0c6e18da69898cb83fe994333db2f3b6f99decf6
    Image:         docker.io/istio/proxy_init:1.3.3
    Image ID:      docker-pullable://istio/proxy_init@sha256:9b6c40ef8e5ff220a67b9cac6e5d9a8ad885a92fbcbbd02936dfb668a06ea409
    Port:          <none>
    Host Port:     <none>
    Args:
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      *
      -d
      15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 18 Oct 2019 20:59:11 +0800
      Finished:     Fri, 18 Oct 2019 20:59:13 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-v7pmg (ro)
Containers:
  nginx:
    Container ID:   docker://83b5e7c845ce54bba58d7f50da82e309bf5dfa46b486a8e73af80732bf1baace
    Image:          goharbor/nginx-photon:v1.9.0
    Image ID:       docker-pullable://goharbor/nginx-photon@sha256:968130655bbfef99f0bf9e20b9c0ce31766f5c4c3f726f2455b286be78a04ad4
    Ports:          8080/TCP, 8443/TCP, 4443/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 18 Oct 2019 21:07:43 +0800
      Finished:     Fri, 18 Oct 2019 21:08:10 +0800
    Ready:          False
    Restart Count:  7
    Liveness:       http-get http://:8080/ delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/ delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/nginx/nginx.conf from config (rw,path="nginx.conf")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-v7pmg (ro)
  istio-proxy:
    Container ID:  docker://320fe9b537d280587ded281c5a4719cbf23c4566d958b4ef351d6251e7cdecc4
    Image:         docker.io/istio/proxyv2:1.3.3
    Image ID:      docker-pullable://istio/proxyv2@sha256:ba3471a9749893afe80f7d8f11119bf0148ffe0f4eaf3f9da66bb27076a8c2a6
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      harbor.$(POD_NAMESPACE)
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15010
      --zipkinAddress
      zipkin.istio-system:9411
      --dnsRefreshRate
      300s
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      NONE
      --statusPort
      15020
      --applicationPorts
      8080,8443,4443
    State:          Running
      Started:      Fri, 18 Oct 2019 21:00:39 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                          harbor-harbor-nginx-6dbd5b6666-jhjrq (v1:metadata.name)
      ISTIO_META_POD_PORTS:              [
                                             {"containerPort":8080,"protocol":"TCP"}
                                             ,{"containerPort":8443,"protocol":"TCP"}
                                             ,{"containerPort":4443,"protocol":"TCP"}
                                         ]
      ISTIO_META_CLUSTER_ID:             Kubernetes
      POD_NAMESPACE:                     default (v1:metadata.namespace)
      INSTANCE_IP:                        (v1:status.podIP)
      SERVICE_ACCOUNT:                    (v1:spec.serviceAccountName)
      ISTIO_META_POD_NAME:               harbor-harbor-nginx-6dbd5b6666-jhjrq (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:       default (v1:metadata.namespace)
      SDS_ENABLED:                       false
      ISTIO_META_INTERCEPTION_MODE:      REDIRECT
      ISTIO_META_INCLUDE_INBOUND_PORTS:  8080,8443,4443
      ISTIO_METAJSON_ANNOTATIONS:        {"checksum/configmap":"29e019bc7d497d8d2fbf12860797c9e9fa67a892b628bc3fed58a219cd22f4a4"}
                                         
      ISTIO_METAJSON_LABELS:             {"app":"harbor","chart":"harbor","component":"nginx","heritage":"Tiller","pod-template-hash":"6dbd5b6666","release":"harbor"}
                                         
      ISTIO_META_WORKLOAD_NAME:          harbor-harbor-nginx
      ISTIO_META_OWNER:                  kubernetes://api/apps/v1/namespaces/default/deployments/harbor-harbor-nginx
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-v7pmg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      harbor-harbor-nginx
    Optional:  false
  default-token-v7pmg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-v7pmg
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.default
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                     From                            Message
  ----     ------     ----                    ----                            -------
  Normal   Scheduled  12m                     default-scheduler               Successfully assigned default/harbor-harbor-nginx-6dbd5b6666-jhjrq to localhost.localdomain
  Normal   Pulled     12m                     kubelet, localhost.localdomain  Container image "docker.io/istio/proxy_init:1.3.3" already present on machine
  Normal   Created    12m                     kubelet, localhost.localdomain  Created container istio-init
  Normal   Started    12m                     kubelet, localhost.localdomain  Started container istio-init
  Normal   Pulling    12m                     kubelet, localhost.localdomain  Pulling image "goharbor/nginx-photon:v1.9.0"
  Normal   Pulled     10m                     kubelet, localhost.localdomain  Successfully pulled image "goharbor/nginx-photon:v1.9.0"
  Normal   Pulled     10m                     kubelet, localhost.localdomain  Container image "docker.io/istio/proxyv2:1.3.3" already present on machine
  Normal   Started    10m                     kubelet, localhost.localdomain  Started container istio-proxy
  Normal   Created    10m                     kubelet, localhost.localdomain  Created container istio-proxy
  Warning  Unhealthy  10m                     kubelet, localhost.localdomain  Liveness probe failed: Get http://10.244.0.69:8080/: dial tcp 10.244.0.69:8080: connect: connection refused
  Warning  Unhealthy  10m                     kubelet, localhost.localdomain  Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Killing    10m                     kubelet, localhost.localdomain  Container nginx failed liveness probe, will be restarted
  Normal   Pulled     10m                     kubelet, localhost.localdomain  Container image "goharbor/nginx-photon:v1.9.0" already present on machine
  Normal   Created    10m (x2 over 10m)       kubelet, localhost.localdomain  Created container nginx
  Normal   Started    10m (x2 over 10m)       kubelet, localhost.localdomain  Started container nginx
  Warning  Unhealthy  10m (x5 over 10m)       kubelet, localhost.localdomain  Readiness probe failed: HTTP probe failed with statuscode: 404
  Warning  Unhealthy  7m21s (x16 over 10m)    kubelet, localhost.localdomain  Liveness probe failed: HTTP probe failed with statuscode: 404
  Warning  BackOff    2m20s (x26 over 8m31s)  kubelet, localhost.localdomain  Back-off restarting failed container

[root@localhost bin]# helm status harbor
LAST DEPLOYED: Fri Oct 18 20:58:58 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                       DATA  AGE
harbor-harbor-chartmuseum  23    16m
harbor-harbor-core         40    16m
harbor-harbor-jobservice   1     16m
harbor-harbor-nginx        1     16m
harbor-harbor-registry     2     16m

==> v1/Deployment
NAME                         READY  UP-TO-DATE  AVAILABLE  AGE
harbor-harbor-chartmuseum    1/1    1           1          16m
harbor-harbor-clair          1/1    1           1          16m
harbor-harbor-core           1/1    1           1          16m
harbor-harbor-jobservice     1/1    1           1          16m
harbor-harbor-notary-server  1/1    1           1          16m
harbor-harbor-notary-signer  1/1    1           1          16m
harbor-harbor-portal         1/1    1           1          16m
harbor-harbor-registry       1/1    1           1          16m

==> v1/Pod(related)
NAME                                          READY  STATUS            RESTARTS  AGE
harbor-harbor-chartmuseum-676d6b5cd4-m5p7t    2/2    Running           0         16m
harbor-harbor-clair-7b5c45f5f4-6qzfb          2/2    Running           4         16m
harbor-harbor-core-f54b545bf-fgpmn            2/2    Running           4         16m
harbor-harbor-database-0                      2/2    Running           0         16m
harbor-harbor-jobservice-65b77c586-5hwd4      2/2    Running           2         16m
harbor-harbor-nginx-6dbd5b6666-jhjrq          1/2    CrashLoopBackOff  9         16m
harbor-harbor-notary-server-c798c64c4-gf6w9   2/2    Running           2         16m
harbor-harbor-notary-signer-7f74c946db-5bm22  2/2    Running           2         16m
harbor-harbor-portal-64bc45998-f2rfb          2/2    Running           0         16m
harbor-harbor-redis-0                         2/2    Running           0         16m
harbor-harbor-registry-c875c5648-mrhfr        3/3    Running           0         16m

==> v1/Secret
NAME                         TYPE    DATA  AGE
harbor-harbor-chartmuseum    Opaque  1     16m
harbor-harbor-clair          Opaque  1     16m
harbor-harbor-core           Opaque  7     16m
harbor-harbor-database       Opaque  1     16m
harbor-harbor-jobservice     Opaque  1     16m
harbor-harbor-notary-server  Opaque  5     16m
harbor-harbor-registry       Opaque  2     16m

==> v1/Service
NAME                         TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)                      AGE
harbor                       NodePort   10.108.55.202   <none>       80:30002/TCP,4443:30004/TCP  16m
harbor-harbor-chartmuseum    ClusterIP  10.106.214.222  <none>       80/TCP                       16m
harbor-harbor-clair          ClusterIP  10.100.255.127  <none>       6060/TCP,6061/TCP            16m
harbor-harbor-core           ClusterIP  10.99.153.82    <none>       80/TCP                       16m
harbor-harbor-database       ClusterIP  10.104.188.187  <none>       5432/TCP                     16m
harbor-harbor-jobservice     ClusterIP  10.100.145.217  <none>       80/TCP                       16m
harbor-harbor-notary-server  ClusterIP  10.98.110.48    <none>       4443/TCP                     16m
harbor-harbor-notary-signer  ClusterIP  10.96.232.202   <none>       7899/TCP                     16m
harbor-harbor-portal         ClusterIP  10.108.51.175   <none>       80/TCP                       16m
harbor-harbor-redis          ClusterIP  10.96.166.88    <none>       6379/TCP                     16m
harbor-harbor-registry       ClusterIP  10.105.122.246  <none>       5000/TCP,8080/TCP            16m

==> v1/StatefulSet
NAME                    READY  AGE
harbor-harbor-database  1/1    16m
harbor-harbor-redis     1/1    16m

==> v1beta1/Deployment
NAME                 READY  UP-TO-DATE  AVAILABLE  AGE
harbor-harbor-nginx  0/1    1           0          16m

NOTES:
Please wait for several minutes for Harbor deployment to complete.
Then you should be able to visit the Harbor portal at http://192.168.1.100:30002.
For more details, please visit https://github.com/goharbor/harbor.

**Comment by Pradyumnakashyap** [comment]
Try using HTTPS with the port:30003 , i had the same issue got fixed by updating the external url to HTTPS://<node-ip>:30003 [if you are using the same configuration as above]

**Comment by reasonerjt** [comment]
@Pradyumnakashyap 

Thanks!

Closing this issue.
