### ISSUE TITLE
accessMode ReadWriteOnce blocks upgrade because of mount already mounted

### ISSUE THREAD

**Issue by roflmao** [goharbor/harbor-helm#408]
Harbor 1.9.1 from Helm.

ReadWriteOnce with default strategy RollingUpdate blocks upgrade since the volume is already mounted.

I fixed it locally with changing the deployment to:

```
  strategy:
    type: Recreate
```

**Comment by tlvenn** [comment]
@ywk253100 any chance we can add strategy.type value for all the deployments that are using a pvc ? The default value should probably be `Recreate` as I expect the vast majority of users will have only `RWO` pvc outside of the box.

**Comment by tlvenn** [comment]
This [PR](https://github.com/goharbor/harbor-helm/pull/366) would solve the issue.
@ywk253100 can you please review it ? Thanks

**Comment by ywk253100** [comment]
Fixed
