### ISSUE TITLE
[Migration 0.3.0(v1.6.0) -> 1.2.0(v1.9.0)/1.2.1(v1.9.1)] Database migration fails

### ISSUE THREAD

**Issue by pierredadt** [goharbor/harbor-helm#411]
Trying to migrate to migrate from v1.6.0 to v1.9.0 don't work because of some database issues.

**Context:**  
Docker engine: `docker-18.6.3`
Old Harbor version: `1.6.0`
New Harbor version: `1.9.0`
Harbor-Helm 1.2.0 config: https://gist.github.com/pierredadt/76cbbe7a36230f741e6eef4ab301cb7e#file-values-yaml

**What I did:**
I tried to migrate my Harbor stack following the doc at https://github.com/goharbor/harbor-helm/blob/1.2.0/docs/Upgrade.md.  
Following the few info I found in related issues, I updated the probes timeout to 30s and added an `initialDelaySeconds` of 300s for the core livenessProbe to try and avoid some early schema update on the database.  
The strategy was to keep my PVs and PVCs, reference them in the new version `values.yaml`, and count on the database migration system to handle the job. 

**What happened:**
When upgrading the chart with the given command, with the provided context and values, the database migration fails.

Core logs: 
```
[INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
[ERROR] [/common/dao/pgsql.go:124]: Failed to upgrade schema, error: "migration failed in line 0:/* add table for CVE whitelist */\nCREATE TABLE cve_whitelist\n(\n...
(...)
ALTER TABLE replication_task ADD COLUMN status_revision int DEFAULT 0;
DELETE FROM project_metadata WHERE deleted = TRUE;
ALTER TABLE project_metadata DROP COLUMN deleted; (details: pq: relation "replication_task" does not exist)

# Core crashes, respawns, and tries to migrate again
(...)
[INFO] [/common/dao/base.go:89]: Register database completed
[INFO] [/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
[ERROR] [/common/dao/pgsql.go:124]: Failed to upgrade schema, error: "Dirty database version 10. Fix and force version."
[FATAL] [/core/main.go:180]: failed to initialize database: Dirty database version 10. Fix and force version.
```

Database logs:
```
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
ERROR:  relation "replication_task" does not exist
STATEMENT:  /* add table for CVE whitelist */
(...)
	ALTER TABLE project_metadata DROP COLUMN deleted;

# Core crashes, respawns, and tries to migrate again
(...)
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
```

**What was expected:**
The migration works.

Do you have any idea how to handle the error found ? I suppose the `Dirty database version 10` is caused by the first failure, but do you know why the first migration failed ?

**Comment by pierredadt** [comment]
Just so you know, 
I updated the chart to v1.2.1 to use the latest modifications on probes, nginx headers and images, and the behavior, errors and logs are exactly the same when trying to migrate from 0.3.0.
But this time there is no errors when installing from scratch.

The thing is I need to migrate old images (some are not built from any CI).
Should I just abandon, make a fresh 1.2.1/v1.9.1 install, and automate pulls from my old harbor/push to the new ?

**Comment by reasonerjt** [comment]
@pierredadt 
The error was probably due to a incomplete migration happened earlier, which made the data in the PVC in consistent.

If you backed up the data, you can restore and retry the upgrade, otherwise, you may have to do a fresh install.
