### ISSUE TITLE
installation failed in clair

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor-helm#419]
hi  all:
when i install harbor with helm it shows ：
Error: render error in "harbor/templates/clair/clair-dpl.yaml": template: harbor/templates/clair/clair-dpl.yaml:32:25: executing "harbor/templates/clair/clair-dpl.yaml" at <.Values.clair.clair.image.repository>: nil pointer evaluating interface {}.image

what cause it?

**Comment by ywk253100** [comment]
@sinycn Please make sure the Harbor chart and images are both the latest ones if you are using the dev version.
