### ISSUE TITLE
chown: '/var/lib/registry' to '10000:10000': Operation not permitted

### ISSUE THREAD

**Issue by wzcwts521** [goharbor/harbor-helm#424]
harbor registry v1.9.1 installation by helm
kubernetes version v1.13.5

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

kubectl logs my-harbor-harbor-registry-688ff6f4b4-cx6xs registry 
chown: '/var/lib/registry' to '10000:10000': Operation not permitted

Does any experience the same issue?
Thanks

**Comment by yang-xixi** [comment]
If you are using NFS mount as PV, it's probably due to root_squash.
Add server option `no_root_squash` to the export line and do `exportfs -ra` to re-export.

**Comment by wzcwts521** [comment]
Thanks @yang-xixi 
Yes. I was using the NFS as a PV. I have a doubt that it is a root_squash issue.   
Deployed harbor registry again with --set persistence.enabled=false, I still see the issue. 

any other ideas?

Thanks

**Comment by wzcwts521** [comment]
I've deployed harbor in a local minikube. The issue could be something outside of the harbor registry.
