### ISSUE TITLE
install harbor by helm, the port 80 return 404

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-helm#433]
test with harbor-helm 1.2.0

install with command "helm install . --name mine --set persistence.enabled=false --set externalURL=https://harbor.10.192.202.98.xip.io --set expose.ingress.hosts.core=harbor.10.192.202.98.xip.io"

when browser http://harbor.10.192.202.98.xip.io, it will return 404 error.
we should 301 redirect to https://harbor.10.192.202.98.xip.io, or not listen on 80 at all.

**Comment by reasonerjt** [comment]
seems related to #312
