### ISSUE TITLE
Helm config option to install harbor as a pull-through registry mirror

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor-helm#446]
Helm config option to install harbor as a pull-through registry mirror.
Harbor config does allow installing harbor as a pull-through registry mirror but that's not exposed in harbor's helm chart values.yaml.

**Comment by ywk253100** [comment]
Harbor doesn't support to configure as a pull-through registry mirror yet.

**Comment by bjethwan** [comment]
@ywk253100 Thanks !
I was actually confused since I saw this document: https://github.com/goharbor/harbor/blob/master/contrib/Configure_mirror.md

**Comment by ywk253100** [comment]
The doc is already out of date, and the solution it provides is just adding mirror setting for registry and most of Harbor features will not work. If you want just mirror, you can use docker registry directly.

I'm closing this issue.
