### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by DarkRider1768** [goharbor/harbor-helm#450]
Hey,

I'm trying to get Harbor up and running on a Rancher managed Kubernetes cluster. We have it running MetalLB via BGP for load balancing. I've tried to get Harbor up via following the instructions in the YAML file but there is nothing in there for setting the External URL for services behind an L4 load balancer. Any help getting this configured and running would be appreciated.

We've tried:

- Setting it to the DNS A record assigned to the IP address of the service.
- Setting it to the IP address of the service.
- Leaving the configuration for it blank.
- Deploying the service with the default option.

```
2019-11-25T22:27:17Z [INFO] [/replication/adapter/native/adapter.go:44]: the factory for adapter docker-registry registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/harbor/adapter.go:42]: the factory for adapter harbor registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/googlegcr/adapter.go:31]: the factory for adapter google-gcr registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/awsecr/adapter.go:49]: the factory for adapter aws-ecr registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/aliacr/adapter.go:28]: the factory for adapter ali-acr registered
2019-11-25T22:27:17Z [INFO] [/replication/adapter/helmhub/adapter.go:31]: the factory for adapter helm-hub registered
2019-11-25T22:27:17Z [INFO] [/core/controllers/base.go:290]: Config path: /etc/core/app.conf
2019-11-25T22:27:17Z [INFO] [/core/main.go:169]: initializing configurations...
2019-11-25T22:27:17Z [INFO] [/core/config/config.go:98]: key path: /etc/core/key
2019-11-25T22:27:17Z [INFO] [/core/config/config.go:71]: init secret store
2019-11-25T22:27:17Z [INFO] [/core/config/config.go:74]: init project manager based on deploy mode
2019-11-25T22:27:17Z [INFO] [/core/config/config.go:143]: initializing the project manager based on local database...
2019-11-25T22:27:17Z [INFO] [/core/main.go:173]: configurations initialization completed

panic: runtime error: index out of range
goroutine 1 [running]:
github.com/goharbor/harbor/src/core/config.ExtURL(0x16bcba0, 0xc000481ec0, 0x18e51d6, 0x8)
/harbor/src/core/config/config.go:255 +0x152
github.com/goharbor/harbor/src/core/service/token.InitCreators()
/harbor/src/core/service/token/creator.go:53 +0x17c
main.main()
/harbor/src/core/main.go:174 +0x1e2
```

**Comment by ywk253100** [comment]
The `ExternalURL` is the URL users use when accessing Harbor, so in your case it should be the URL of your L4 load balancer.

**Comment by DarkRider1768** [comment]
So if metallb assigned it an address, 192.168.240.130, I should be able to
set it to either an A record pointing to that IP or the IP itself?

I ask because I've tried both and have had no success with either. I can
access the nginx instance that the chart spins up, at the address assigned
by the chart but core and job services are failing to spin up. This is
preventing me from getting to the login page and using the service.

**Comment by ywk253100** [comment]
What's the `expose.type` you set?

**Comment by DarkRider1768** [comment]
Expose.type is set to Load Balancer.

**Comment by ywk253100** [comment]
`Setting it to the DNS A record assigned to the IP address of the service` should work. If you set like this, some pods cannot startup, right? If so, we should check the reason why the pods failed to startup

**Comment by DarkRider1768** [comment]
Set an A record in DNS for harbor in zone k.node to point to 192.168.240.130. Set the ExtURL to harbor.k.node and it fails to start with the above error.

**Comment by ywk253100** [comment]
Double check the configuration item, did it contain the protocol `https://` part?

**Comment by DarkRider1768** [comment]
Yes, it definitely had the https:// portion.

**Comment by ywk253100** [comment]
@DarkRider1768 The error should be related with the missing `https://`, the fix has been merged into master https://github.com/goharbor/harbor/pull/10031
If you can confirm that your `ExternalURL` contains `https://` part, could you show me the configmap of core(replace the `harbor-harbor-core` with yours): 
```shell
kubectl describe cm harbor-harbor-core
```

**Comment by vamp911** [comment]
I'm having the exact same problem with deploying Harbor on to a Rancher controlled cluster using helm. I'm also using MetalLB as my service ingress (type: LoadBalancer). My ExternalURL also contains "https://".

Here's my core config map:

$ kubectl describe cm harbor-harbor-core -n harbor
Name:         harbor-harbor-core
Namespace:    harbor
Labels:       app=harbor
              chart=harbor
              heritage=Tiller
              io.cattle.field/appId=harbor
              release=harbor
Annotations:  <none>

Data
====
NOTARY_URL:
----
http://harbor-harbor-notary-server:4443
_REDIS_URL:
----
harbor-harbor-redis:6379,100,
ADMIRAL_URL:
----
NA
CHART_CACHE_DRIVER:
----
redis
CLAIR_DB_HOST:
----
co01kbecdb01v.tse.int
POSTGRESQL_MAX_IDLE_CONNS:
----
50
REGISTRY_URL:
----
http://harbor-harbor-registry:5000
PORTAL_URL:
----
http://harbor-harbor-portal
REGISTRY_STORAGE_PROVIDER_NAME:
----
filesystem
TOKEN_SERVICE_URL:
----
http://harbor-harbor-core/service/token
CLAIR_DB_SSLMODE:
----
disable
HTTPS_PROXY:
----

HTTP_PROXY:
----

CLAIR_DB_PORT:
----
5432
POSTGRESQL_MAX_OPEN_CONNS:
----
100
POSTGRESQL_USERNAME:
----
xxxxxx
WITH_CLAIR:
----
true
WITH_NOTARY:
----
true
app.conf:
----
appname = Harbor
runmode = dev
enablegzip = true

[dev]
httpport = 8080

CLAIR_HEALTH_CHECK_SERVER_URL:
----
http://harbor-harbor-clair:6061
JOBSERVICE_URL:
----
http://harbor-harbor-jobservice
REGISTRYCTL_URL:
----
http://harbor-harbor-registry:8080
POSTGRESQL_HOST:
----
co01kbecdb01v.tse.int
POSTGRESQL_PORT:
----
5432
POSTGRESQL_SSLMODE:
----
disable
SYNC_REGISTRY:
----
false
CFG_EXPIRATION:
----
5
CLAIR_URL:
----
http://harbor-harbor-clair:6060
CORE_URL:
----
http://harbor-harbor-core
LOG_LEVEL:
----
info
POSTGRESQL_DATABASE:
----
registry
WITH_CHARTMUSEUM:
----
true
CLAIR_DB:
----
clair
CONFIG_PATH:
----
/etc/core/app.conf
EXT_ENDPOINT:
----
172.17.237.241
NO_PROXY:
----
harbor-harbor-core,harbor-harbor-jobservice,harbor-harbor-database,harbor-harbor-chartmuseum,harbor-harbor-clair,harbor-harbor-notary-server,harbor-harbor-notary-signer,harbor-harbor-registry,127.0.0.1,localhost,.local,.internal
_REDIS_URL_REG:
----
redis://harbor-harbor-redis:6379/2
CHART_REPOSITORY_URL:
----
http://harbor-harbor-chartmuseum
CLAIR_DB_USERNAME:
----
harbor
DATABASE_TYPE:
----
postgresql
Events:  <none>

**Comment by reasonerjt** [comment]
@vamp911 
This shows the EXT_ENDPOINT  does NOT have the `https://`

```
EXT_ENDPOINT:
----
172.17.237.241
```

as @ywk253100  mentioned there has been a fix merged recently, please double check with latest build.
