### ISSUE TITLE
Support configuring security context

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor-helm#456]
Currently, the containers in Harbor run as specific user(user ID 10000 or 999), and the user cannot be changed because some directives such as https://github.com/goharbor/harbor/blob/release-1.10.0/make/photon/registry/Dockerfile#L9. This prevents the supporting for configuring`runAsUser`. 
For other security context directives https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies, we need more test to verify they can work as expected.

There is already a PR https://github.com/goharbor/harbor-helm/pull/266 from community for the security context supporting

**Comment by NickHes** [comment]
@ywk253100 Any plans to support this in the future? With Kubernetes 1.24 reaching EOL and clusters migrating to 1.25 with the new policies I suspect the need for this will grow. Currently we cannot run Harbor with the new policies enabled. If you are open for PR's for this we could most certainly take a look.
