### ISSUE TITLE
Automation test enhancement

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor-helm#457]
- [ ] Setup a simple K8s in travis CI and run some basic test cases
- [ ] Run more pipelines for different configurations in nightly testing
  - Use PV instead of cloud storage
  - Expose service via node port
  - Upgrade

**Comment by scottrigby** [comment]
Hi again 👋 Would you be interested in using the latest and greatest Helm GitHub Actions for chart testing and releasing? Demo here: https://github.com/helm/charts-repo-actions-demo If so and if I miss this issue comment notifications, hit me up on Slack 😄 I'm happy to help

**Comment by ywk253100** [comment]
Done
