### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by CasperNaudts** [goharbor/harbor-helm#458]
After setting up my harbor regestry on my k8s cluster with my godaddy wildcart tls certificate. I get this error "x509: certificate signed by unknown authority". I started looking arround and tried directly connecting to the regestrie but got the same error.

Is there any way to fix this issue with harbor so I don't need to copy the certificate to my local mashine so it functions like any other online registrie.

PS: I am running the harbor enviroment behind ingress as is default in the chart.

**Comment by ywk253100** [comment]
@CasperNaudts I don't think this is related with Harbor.
You need to make sure the certificate is trusted by your OS

**Comment by sunlianqiang** [comment]
> After setting up my harbor regestry on my k8s cluster with my godaddy wildcart tls certificate. I get this error "x509: certificate signed by unknown authority". I started looking arround and tried directly connecting to the regestrie but got the same error.
> 
> Is there any way to fix this issue with harbor so I don't need to copy the certificate to my local mashine so it functions like any other online registrie.
> 
> PS: I am running the harbor enviroment behind ingress as is default in the chart.

met the same issue several days ago, when I want to visit harbor in docker.
install ca-certification in docker slove the problem.

**Comment by catchups** [comment]
If you are using a private certificate, install the certificate under "/etc/docker/certs.d"

**Comment by rncortes1990** [comment]
@catchups How can I do that, could you bring some documentation?

**Comment by reasonerjt** [comment]
@rncortes1990 
https://docs.docker.com/engine/security/certificates/

As @ywk253100 pointed out establishing trust when you use self-signed cert is out of the scope of this helm chart, I'm closing this issue.
