### ISSUE TITLE
[bug] random string for XSRFKey causes core deployment update every time helm upgrade is run

### ISSUE THREAD

**Issue by paulczar** [goharbor/harbor-helm#459]
There's a random string in the core configmap that causes the configmap to change every time `helm ugprade` is run.  This creates the undesirable effect of the core deployment always changing and thus  creating a new replicaset and new pods.   It also messes with anything using a `helm diff` in a gitops type workflow as it sees a change when there really shouldn't be one.

The offending commit is in Pull Request #431 

```
    EnableXSRF = true
    XSRFKey = {{ randAlphaNum 40 }}
    XSRFExpire = 3600
```

should be the following with a new value in the values.yaml `core.xsrfKey`.   you could possibly do something a bit cleaner, but this is verbose to show the working.

```
    EnableXSRF = true
    {{- if core.xsrfKey }}
    XSRFKey = {{ core.xsrfKey }}
    {{- else }}
    XSRFKey = {{ randAlphaNum 40 }}
    {{- end }}
    XSRFExpire = 3600
```

**Comment by xaleeks** [comment]
please look into this @ywk253100
