### ISSUE TITLE
cannot login as ldap user

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [goharbor/harbor-helm#467]
good day
i'm setup harbor today from helm (last version) and can successfully login to ui using admin login/password, after that i setup LDAP auth module and try to authorize as domain user but i receive 401 on /api/users/current

versions of pods:
chartmuseum: goharbor/chartmuseum-photon:v0.9.0-v1.9.3
clair: goharbor/clair-photon:v2.1.0-v1.9.3
core: goharbor/harbor-core:v1.9.3
database: goharbor/harbor-db:v1.9.3
jobservice: goharbor/harbor-jobservice:v1.9.3
notary-server: goharbor/notary-server-photon:v0.6.1-v1.9.3
notary-signer: goharbor/notary-signer-photon:v0.6.1-v1.9.3
portal: goharbor/harbor-portal:v1.9.3
redis: goharbor/redis-photon:v1.9.3
registry: goharbor/harbor-registryctl:v1.9.3

my environment:
os: ubuntu 18.04.3
k8s: 1.16.0

harbor exposed as ingress (i use nginx ingress controller) without tls

after i enter login and password and click on login button i can see several requests:
/c/login  - 200, success,
/api/users/current - 401, unauthorized

when i try to use incorrect credential then i reseive error on login as expected and can see message 'invalid user name or password'

i can't find any clue in logs

**UPDATE**
i found very strange find. i try to restart pods and i can login with ldap user without any problems.  but after some times (i switch to another task and return back after several hours) i can't signup again!  all pods works correctly without errors..

**Comment by ywk253100** [comment]
Could you try to check the logs of redis pod when you get the error again?

**Comment by anatoly-kryzhanovsky** [comment]
ok, i will monitor service and provide logs from redis

**Comment by anatoly-kryzhanovsky** [comment]
ok, it's repeat again
i found some problem, but i haven't enough time before new year to investigate deeper.
logs from redis pod:

```
746:C 13 Dec 10:35:11.081 # Failed opening the RDB file dump.rdb (in server root dir /var/lib/redis) for saving: Permission denied
1:M 13 Dec 10:35:11.180 # Background saving error
```

and there is HUGE such items in logs

and one more - i found that jobservice pods restart many times - 621 times for 3 days but there is no errors in logs and now it is in CrashLoopBackOff state

> 
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/native/adapter.go:44]: the factory for adapter docker-registry registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/harbor/adapter.go:42]: the factory for adapter harbor registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/googlegcr/adapter.go:31]: the factory for adapter google-gcr registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/awsecr/adapter.go:49]: the factory for adapter aws-ecr registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/aliacr/adapter.go:28]: the factory for adapter ali-acr registered
> 2019-12-13T10:38:37Z [INFO] [/replication/adapter/helmhub/adapter.go:31]: the factory for adapter helm-hub registered
> 2019-12-13T10:38:37Z [INFO] [/common/config/store/driver/rest.go:24]: get configuration from url: http://harbox-harbor-core/api/internal/configurations
> 2019-12-13T10:38:37Z [DEBUG] [/jobservice/logger/sweeper_controller.go:89]: Sweeper *sweeper.FileSweeper is under working
> 2019-12-13T10:38:37Z [INFO] [/jobservice/logger/sweeper_controller.go:97]: 0 outdated log entries are sweepped by sweeper *sweeper.FileSweeper
> 2019-12-13T10:38:37Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-harbox-harbor-database port-5432 databse-registry sslmode-"disable"
> 2019-12-13T10:38:37Z [INFO] [/common/dao/base.go:89]: Register database completed
> 2019-12-13T10:38:37Z [INFO] [/jobservice/migration/manager.go:111]: No migration needed
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *sample.Job with name DEMO
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *gc.GarbageCollector with name IMAGE_GC
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *replication.Scheduler with name IMAGE_REPLICATE
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *notification.WebhookJob with name WEBHOOK
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *scan.ClairJob with name IMAGE_SCAN
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *scan.All with name IMAGE_SCAN_ALL
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *replication.Replication with name REPLICATION
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *retention.Job with name RETENTION
> 2019-12-13T10:38:37Z [INFO] [/jobservice/worker/cworker/c_worker.go:419]: Register job *scheduler.PeriodicJob with name SCHEDULER

**Comment by anatoly-kryzhanovsky** [comment]
ok, i solve problem - the issue is in permission to folder for redis storage

**Comment by not-happy** [comment]
@anatoly-kryzhanovsky hello, how did you solve it, i need help

**Comment by anatoly-kryzhanovsky** [comment]
In my case issue linked with permissions for refis data directory-after i
fixed permissions all works fine

вт, 7 янв. 2020 г., 13:41 not-happy <notifications@github.com>:
