### ISSUE TITLE
what kind of a Redis is recommended?

### ISSUE THREAD

**Issue by tirelibirefe** [goharbor/harbor-helm#475]
Hello;
Could you please explain what kind of a Redis is recommended?

"As the Redis client used by Harbor's upstream projects doesn't support Sentinel, Harbor can only work with a single entry point Redis. You can refer to this guide to setup a HAProxy before the Redis to expose a single entry point."

Reference link goes "HAProxy and Redis Sentinel" but at the same time documentations says "Redis Sentinel is not supported.

What kind of a  Redis is recommended? Is there proper reference link for recommended Redis configuration which is both high available and without Sentinel?

**Comment by ninjaslothx** [comment]
Hey @tirelibirefe there is a redis-ha helm chart with a haproxy option that might do what you need.
https://github.com/helm/charts/tree/master/stable/redis-ha
It's disabled by default but you can enable it by setting the value to true.
> haproxy.enabled / Enables HAProxy LoadBalancing/Proxy

Then you should be able to point your harbor config at the haproxy service that is setup.

**Comment by tirelibirefe** [comment]
@ninjaslothx I tried what you advised and it worked; thanks!
