### ISSUE TITLE
Unable to log in as admin user

### ISSUE THREAD

**Issue by silborynirmata** [goharbor/harbor-helm#492]
If I do a simple "helm install harbor harbor/harbor" install I'm unable to log in as admin with the default password.  If I install with "helm install harbor harbor/harbor --set  harborAdminPassword=foofoo" that doesn't work either.   Even though I see the password is set.
```
ssilbory@tower2:~$ kubectl get secrets -o yaml |grep -i admin
    HARBOR_ADMIN_PASSWORD: Zm9vZm9v
ssilbory@tower2:~$ echo "Zm9vZm9v"| base64 --decode
foofoossilbory@tower2:~$ 
```

I don't see anything in the logs that give me a clue to the issue.

```
10.0.1.1 - - [16/Jan/2020:20:46:49 +0000] "POST /c/userExists HTTP/1.1" 405 559 "http://35.236.59.30/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
10.0.0.41 - - [16/Jan/2020:20:46:52 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:46:53 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:46:55 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.0.41 - - [16/Jan/2020:20:47:02 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:47:03 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:47:05 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:47:06 +0000] "POST /c/userExists HTTP/1.1" 405 559 "http://35.236.59.30/harbor/sign-in?redirect_url=%2Fharbor%2Fprojects" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
10.0.0.41 - - [16/Jan/2020:20:47:12 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:47:13 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:47:15 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.0.41 - - [16/Jan/2020:20:47:22 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:47:23 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:47:25 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.0.41 - - [16/Jan/2020:20:47:32 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:47:33 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:47:35 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.0.41 - - [16/Jan/2020:20:47:42 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:47:43 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:47:45 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.0.41 - - [16/Jan/2020:20:47:52 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:47:53 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:47:55 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.0.41 - - [16/Jan/2020:20:48:02 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:48:03 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:48:05 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.0.41 - - [16/Jan/2020:20:48:12 +0000] "GET / HTTP/1.1" 200 718 "-" "Go-http-client/1.1"
10.0.1.1 - - [16/Jan/2020:20:48:13 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
10.0.1.1 - - [16/Jan/2020:20:48:15 +0000] "GET / HTTP/1.1" 200 718 "-" "kube-probe/1.13+"
````

**Comment by silborynirmata** [comment]
Also, I'm unable to create a user.

![Screenshot from 2020-01-16 12-51-43](https://user-images.githubusercontent.com/49996154/72562041-607bdc00-385f-11ea-84bc-51a322e6890b.png)

**Comment by Hokwang** [comment]
In my case, sometimes admin can't login, and sometimes can login.. weired..

**Comment by nvpnathan** [comment]
I've also reproduced this in my environment.

**Comment by silborynirmata** [comment]
The issue seems to occur when I'm using nodeport or cluster ip.  If I use a load balancer to connect (metallb) I don't see any issues.

**Comment by ywk253100** [comment]
According to the log `POST /c/userExists HTTP/1.1" 405`, this is the reason why you cannot login on web UI.

The request `POST /c/userExists` should be sent to pod `core`, but in your cases, seems it is sent to pod`portal`.

This may be caused by different match patterns for different ingress controllers: if the `/c/userExists` cannot be matched by `/c/` https://github.com/goharbor/harbor-helm/blob/1.3.0/templates/ingress/ingress.yaml#L24, it will be handled by `portal` https://github.com/goharbor/harbor-helm/blob/1.3.0/templates/ingress/ingress.yaml#L19

Could you guys confirm if this is your case? and provide the Harbor chart version and what the ingress controller that you are using.

**Comment by silborynirmata** [comment]
I'm only able to reproduce this issue now by using the IP address of the pod harbor-portal.  I think I had trouble when I was using nodeport (or clusterip?), but since I switched to a load balancer (metallb) it works fine with v1.2.4.

**Comment by silborynirmata** [comment]
PS- I don't have an ingress controller configured on this cluster.

**Comment by rsoika** [comment]
@silborynirmata : could you give a short example what you mean with "...I switched to a load balancer)"
Can you show your helm install command?

**Comment by osaffer** [comment]
Hi,

I did an installation with helm.
But I cannot docker login with admin user, but only with the user defined in values file, eg : harbor_registry_user.

What is the configuration to be able to connect with users created in harbor UI ?
Of course I can log in in WebUI with newly created users, or with admin harbor user. but with docker, no.

I use istio ingress to access the Web UI, and it works also with docker login, but not with admin user.
I can login and push image , BUT in UI, I cannot the repository supposed to be created.

Thank you

**Comment by hrodrig** [comment]
Hi,

same issues: can't login with admin and Harbor12345 and can't register as new user...

helm install harbor harbor/harbor \
  --set expose.type=ClusterIp \
  --set expose.tls.enabled=false \
  --set persistence.persistentVolumeClaim.registry.size=60Gi \
  --set persistence.persistentVolumeClaim.chartmuseum.size=20Gi \
  --set externalURL=https://myharbor.myweb.info \
  --set harborAdminPassword=MyPassw0rd

Kubernetes cluster running in a single node with Traefik as Ingress Controller...

How could I change user password inside postgres pod ?

Thank you in advance ;)

**Comment by byliuyang** [comment]
In case you are not able to login into harbor when exposing the service through ClusterIP, please make sure you are exposing both the portal & the api correctly:

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`harbor.example.com`)
      services:
        - kind: Service
          name: harbor-harbor-portal
          namespace: harbor
          port: 80
          scheme: http
    - kind: Rule
      match: Host(`harbor.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/service`) || PathPrefix(`/v2`) || PathPrefix(`/chartrepo`) || PathPrefix(`/c`))
      services:
        - kind: Service
          name: harbor-harbor-core
          namespace: harbor
          port: 80
          scheme: http
  tls:
    secretName: example-cert

**Comment by B3DTech** [comment]
This is still an issue.  Deployed via Helm, using nginx Ingress, cluster IP.  When entering username/password set in the values, I get "Invalid user name or password".  I can see the x-harbor-csrf-token in the header.  In the browser console, I see: Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.  Followed by a 401: Unauthorized.  

The core pod shows:

```
2021-08-05T17:59:33Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /c/login

2021-08-05T17:59:33Z [DEBUG] [/server/middleware/security/unauthorized.go:28][requestID="08fe5d60443cce0ad9252eec77fc294f"]: an unauthorized security context generated for request POST /c/login

2021-08-05T17:59:33Z [DEBUG] [/core/auth/authenticator.go:147]: Current AUTH_MODE is db_auth

2021-08-05T17:59:33Z [DEBUG] [/core/auth/authenticator.go:160]: Login failed, locking admin, and sleep for 1.5s

2021-08-05T17:59:35Z [ERROR] [/core/controllers/base.go:105]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Invalid credentials'
```

Seems like everything is working, but the username/password is wrong in the database?  I updated the helm deployment with a new password, still didn't help.

**Comment by B3DTech** [comment]
I had to manually change the password directly in database to get this to work.

**Comment by CracKOl** [comment]
I had the same pb so i kept ClusterIP setup and created the ingress for nginx controller : 

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor
  namespace: harbor
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/24
spec:
  rules:
  - host: your-adress.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-release-harbor-portal
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: my-release-harbor-core
            port:
              number: 80
      - path: /service
        pathType: Prefix
        backend:
          service:
            name: my-release-harbor-core
            port:
              number: 80
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: my-release-harbor-core
            port:
              number: 80
      - path: /chartrepo
        pathType: Prefix
        backend:
          service:
            name: my-release-harbor-core
            port:
              number: 80
      - path: /c
        pathType: Prefix
        backend:
          service:
            name: my-release-harbor-core
            port:
              number: 80
  tls:
    - secretName: my-tls
      hosts:
        - your-adress.com
  ingressClassName: nginx
`

**Comment by sid-hbm** [comment]
please reopen this issue which has not been fixed, and without login, you can just throw away Harbor. This is a very serious issue that need to be fixed.

**Comment by sid-hbm** [comment]
This issue is real and needs to be fixed urgently. Very easy to reproduce. In my case, I am running microk8s kubernetes on a multipass VM (on a Mac): Install Harbor with the following helm commands: helm repo add harbor https://helm.goharbor.io
   helm repo update
   helm upgrade --install --force harbor harbor/harbor -n harbor --create-namespace=true --set expose.tls.enabled=false \
            --set expose.tls.ingress.hosts.core=harbor.my --set expose.tls.trace.enabled=false \
            --set externalURL=http://harbor.my        and have an IngressRoute for the domain harbor.my to access the portal:           apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-route
  namespace: harbor
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`harbor.my`) || PathPrefix(`/harbor`)
      kind: Rule
      services:
        - name: harbor-portal
          port: 80
    - kind: Rule
      match: Host(`harbor.my`) && PathPrefix(`/c/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.my`) && PathPrefix(`/api/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.my`) && PathPrefix(`/service/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.my`) && PathPrefix(`/v2/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-registry
          namespace: harbor
          port: 5000
    - kind: Rule
      match: Host(`harbor.my`) && PathPrefix(`/chartrepo/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
    - kind: Rule
      match: Host(`harbor.my`) && PathPrefix(`/account/`)
      priority: 10
      services:
        - kind: Service
          name: harbor-core
          namespace: harbor
          port: 80
and then map harbor.my in your /etc/hosts to point to the IP address of the VM where microk8s kubernetes cluster is installed (or use dnsmasq with a rule that any domain ending with ".my" should be forwarded to the IP address of the VM). In my case, I have Traefik installed as a DaemonSet and acting as the main Ingress controller for my cluster (meaning any request coming to the IP address of the VM, it will be handled by Traefik).

**Comment by bsdis** [comment]
I agree - this is a serious issue and needs attention. Its very easy to reproduce.
Just download the online installer ( wget https://github.com/goharbor/harbor/releases/download/v2.12.1/harbor-online-installer-v2.12.1.tgz ) set up http only (ie comment out https lines from config) and install with trivy.
When trying to login, core log shows

2025-01-04T08:57:55Z [WARNING] [/core/auth/authenticator.go:158]: Login failed, locking admin, and sleep for 1.5s
2025-01-04T08:57:57Z [ERROR] [/core/controllers/base.go:101]: Error occurred in UserLogin: Failed to authenticate user, due to error 'Invalid credentials'

and its not possible to log in

**Comment by hAislt** [comment]
Why has this been closed? I am also facing this issue.
I verified that the password is correct and created a separate ingress with all needed paths.

**Comment by dongtd212** [comment]
> In case anybody else runs into this problem when deploying with default values from the helm chart, there may be an issue with the CSRF header in the login request when behind a reverse proxy (i.e. Traefik). You can see this by upgrading and setting the log level to debug (helm upgrade local-harbor harbor/harbor --set logLevel=debug) and watching the core pod logs (kubectl logs -n ops ops-harbor-core-f449dbcf4-69tjx -f). To fix, set the externalURL to use http instead of https per this comment: [goharbor/harbor#12676 (comment)](https://github.com/goharbor/harbor/issues/12676#issuecomment-817804095)

work like a charm, thank you @solidDoWant

**Comment by f3k-freek** [comment]
Hi, thanks for the great work on Harbor!

This issue shouldn’t be closed — users should be able to deploy the Helm chart successfully without needing to discover and apply this workaround from a GitHub thread.

I believe this could be solved by removing the protocol from `externalURL` and adding it dynamically in the Helm chart based on the TLS settings.

### Example
```yaml
externalURL: core.harbor.domain
internalTLS.enabled: true
expose.tls.enabled: true
```

To avoid breaking changes, the chart could check for the presence of `http://` or `https://` in `externalURL`, and only prepend the protocol if not already present.

I’d be happy to create a PR for this if desired.

This would help avoid confusion and improve the default deployment experience. Thanks again!

**Comment by behniafb** [comment]
> Hi, thanks for the great work on Harbor!
> 
> This issue shouldn’t be closed — users should be able to deploy the Helm chart successfully without needing to discover and apply this workaround from a GitHub thread.
> 
> I believe this could be solved by removing the protocol from `externalURL` and adding it dynamically in the Helm chart based on the TLS settings.
> 
> ### Example
> externalURL: core.harbor.domain
> internalTLS.enabled: false  # Would prepend http:// for internal communication
> expose.tls.enabled: true    # Would prepend https:// for external exposure
> To avoid breaking changes, the chart could check for the presence of `http://` or `https://` in `externalURL`, and only prepend the protocol if not already present.
> 
> I’d be happy to create a PR for this if desired.
> 
> This would help avoid confusion and improve the default deployment experience. Thanks again!

Thanks to your hint, I could solve my issue too, which was a little different from yours:

Because I used "NodePort" type access, I needed to also mention the nodePort in the externalURL, so it was something like this:
`externalURL: http://ip_of_node:nodeport_of_harbor_nginx`

**Comment by f3k-freek** [comment]
> Because I used "NodePort" type access, I needed to also mention the nodePort in the externalURL, so it was something like this: `externalURL: http://ip_of_node:nodeport_of_harbor_nginx`

Thank you very much for the addition. I have added it to my suggestion.
