### ISSUE TITLE
wrong logLevel

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor-helm#494]
Hello.

your comment is wrong.

```
# debug, info, warning, error or fatal
```
https://github.com/goharbor/harbor-helm/blob/8f4000deac0fba16a9277d48b4ecea7c9bea250b/values.yaml#L249

warning is wrong. warn is right.
I experienced crashloopback...

Thanks,

**Comment by evanstucker-hates-2fa** [comment]
I can confirm that using "warning" leads to this error in the registry pod:
```
$ k logs harbor-harbor-registry-c9984597f-h98jg registry
Appending internal tls trust CA to ca-bundle ...
find: /etc/harbor/ssl: No such file or directory
Internal tls trust CA appending is Done.
configuration error: error parsing /etc/registry/config.yml: Invalid loglevel warning Must be one of [error, warn, info, debug]

Usage: 
  registry serve <config> [flags]
Flags:
  -h, --help=false: help for serve


Additional help topics:

```

**Comment by evanstucker-hates-2fa** [comment]
Confirmed that changing "warning" to "warn" ensures that all pods start successfully. Created https://github.com/goharbor/harbor-helm/pull/712

**Comment by ywk253100** [comment]
The log level configured in `values.yaml` is shared by all Harbor components. The `warning` works as expected for other components except `registry`, so the PR https://github.com/goharbor/harbor-helm/pull/704 converts it to `warning` .
