### ISSUE TITLE
Proxy Configurations: Missing support for Registry and Chartmuseum components

### ISSUE THREAD

**Issue by Manny2014** [goharbor/harbor-helm#498]
In order to properly route all AWS traffic through a proxy, registry and chartmuseum should be included as part of components which can have the HTTP(S)_PROXY configurations/environment variables.

 Files to change:

1. templates/registry/registry-dpl.yaml
   a. CHANGE:

>         {{- if has "registry" .Values.proxy.components }} 
>         - name: HTTP_PROXY
>           value: "{{ .Values.proxy.httpProxy }}"
>         - name: HTTPS_PROXY
>           value: "{{ .Values.proxy.httpsProxy }}"
>         - name: NO_PROXY
>           value: "{{ template "harbor.noProxy" . }}"
>         {{- end }}

2. templates/chartmuseum/chartmuseum-dpl.yaml
    a. CHANGE:

>           {{- if has "chartmuseum" .Values.proxy.components }}
>           - name: HTTP_PROXY
>             value: "{{ .Values.proxy.httpProxy }}"
>           - name: HTTPS_PROXY
>             value: "{{ .Values.proxy.httpsProxy }}"
>           - name: NO_PROXY
>             value: "{{ template "harbor.noProxy" . }}"
>           {{- end }}

**Comment by ywk253100** [comment]
Fixed by #499, thanks @Manny2014
