### ISSUE TITLE
the auto generated service name is too long

### ISSUE THREAD

**Issue by fhchina** [goharbor/harbor-helm#5]
Failed to provision volume with StorageClass "gfs": failed to create volume: failed to create endpoint/service default/glusterfs-dynamic-adminserver-config-harbor-harbor-adminserver-0: error creating service: Service "glusterfs-dynamic-adminserver-config-harbor-harbor-adminserver-0" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-adminserver-config-harbor-harbor-adminserver-0": must be no more than 63 characters

**Comment by lanmingle** [comment]
赞同，同时也觉得不喜欢提供自动生成绑定的 PVC 模板，希望通过参数设置已存在的和子路径值，只好自己新建个分支进行维护。

**Comment by reasonerjt** [comment]
@lanmingle 
```
希望通过参数设置已存在的和子路径值
```
能具体解释下这个场景吗？

**Comment by lanmingle** [comment]
@reasonerjt 现在在官方的 chart 库中有很多提供外置存在的 pvc 用来绑定，以及一些可选的子路径，并不是所有人都有外置的云存储，比如我想在本地裸机上整测试环境的，就一块硬盘，为了好管理这些存储的目录，就会规划，比如 /opt/app/harbor/xX-data（各种使用的组件），搭建支持的存储很麻烦，一般情况下没啥条件的都会用 NFS 作存储，我就是其中一个。

**Comment by ywk253100** [comment]
The `adminserver` doesn't need PVC any more, closing this issue.
