### ISSUE TITLE
Harbor in K8s update 1.6.0 -> 1.10.0 (0.3.0 -> 1.3.0)

### ISSUE THREAD

**Issue by zdenekvicar** [goharbor/harbor-helm#500]
Hello all,
I would like to ask you if anyone of you does have any experience with updating Harbor 1.6.0 to 1.10.0 in Kubernetes.

I am not really sure if one step upgrade (directly to v1.10.0) is really supported (in onpremise Harbor installation it is not as far as I found in documentation), however K8s version might be slightly different.

Due to my company needs, I am using modified manifests from harbor-helm v0.3.0 ... therefore I cannot really use the helm upgrade feature here. My plan is to use harbor-helm v1.10.0 to generate 'template' manifests, then update them according our needs. Question is, will this work ? Or do I really need to perform 4 separate upgrades (generate manifests via helm, update them to our company needs, apply, ...) to move to 1.10.0 from 1.6.0 ?

What is preferable option to perform such upgrade ?
1. step by step
  - v1.6.0 -> v1.7.* -> v1.8.* -> v1.9.* -> v1.10.0 
2. one step
 - v1.6.0 -> v1.10.0

**Comment by oscarlofwenhamn** [comment]
If possible, one option could be to set up a parallel instance and use the Replications functionality to migrate all images. That is what we are in the process of doing, instead of having to migrate databases. The only obvious downsides I've found is the migration of users and robot accounts, but since we are using oidc authentication it isn't a big hassle making new accounts, and robot accounts already need to be replaced on a regular basis so the workflow is already in place for that.

**Comment by zdenekvicar** [comment]
@oscarlofwenhamn  Problem is with replication of other data -> see my question here https://github.com/goharbor/harbor/issues/9994

Current replication will not help you with LDAP settings, user privileges, etc. ... 

My current plan (once the time allows) is to try direct update from v1.6.0 -> v1.10.0 as theoretically it should work ... I can update & share results here once I have them

**Comment by reasonerjt** [comment]
1.6.0 -> 1.10.0 may work but it is not tested

Normally only upgrade from 2 minor versions lower is tested.

@zdenekvicar please let us know if you succeeded or not.

**Comment by zdenekvicar** [comment]
@reasonerjt I am sorry I totally forgot about this topic 🙂

Upgrade from 1.6 directly to 1.10 was running just fine, it is approx 1month since I switched all (currenty 13) our instances to 1.10 and all works just fine. Only issue I had is with quotas, but this seems to be related to some damaged files in out storage rather than the upgrade itself.

To sum it up -> it is perfecty doable and it works 👍🏻

**Comment by oscarlofwenhamn** [comment]
@zdenekvicar If it works as expected, is it possible to close this Issue or du you have further questions?

**Comment by zdenekvicar** [comment]
@oscarlofwenhamn I will close it 😉
