### ISSUE TITLE
Add option on values for priority class

### ISSUE THREAD

**Issue by connorearl** [goharbor/harbor-helm#505]
I don't see any support for setting a priority class for harbor. It would be great to be able to set that so I can set a higher priority for harbor to ensure harbor doesn't get evicted first. I need to still pull images if something gets rescheduled if resources are tight.

**Comment by reasonerjt** [comment]
@connorearl 
Could you provide more information about `priority class`

I also don't understand in what case Harbor will be evicted.

**Comment by connorearl** [comment]
I run in a resource limited bare metal cluster where priority classes are quite important to ensure I have certain pods running if I am low on resources. I can set less important pods a higher priority so they get scheduled first if not everything can be scheduled. This important for harbor to maintain high availability. For example:

Let's say I have 3 namespaces, one for harbor, one for my production environment of a microservices application and one for a staging environment. My cluster only has enough resources to support the above applications, if a node goes down some pods can't be scheduled. (obviously not ideal, but just to illustrate the point)

If I have a node go down, with priority classes I can set the production environment and harbor pods from the failed node to be scheduled over the staging environment, and be able to keep production up, as harbor will be there to pull images from if they need to be pulled for production. Staging pods that can't be scheduled from the old node will be left pending.

Without priority classes harbor may be left pending over the staging pods from the failed nodes, and I won't be able to pull images for any of the production pods from the failed node.


In addition, I also use the descheduler with evicts based on priority class to rebalance nodes. I'd rather evict staging pods over harbor in this case too, even though the bit of harbor downtime isn't as catastrophic as the example above. 

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
https://github.com/kubernetes-sigs/descheduler

**Comment by brettmorien** [comment]
Hi folks. I'd like to add a scenario here where priority class would be extremely helpful.

We are charged with helping other teams in our org with Kubernetes clusters, and we include Harbor in that environment for read-through caching images. We automate the process of K8 upgrades (ie, 1.18 -> 1.19) which requires draining and cycling nodes. When Harbor is evicted, priority class would make it much easier for us to assure that there is a running Harbor instance in the uncertain time when workloads are rescheduled and the cluster autoscaler starts adding nodes again.

Regardless of the actual scenario, it's a pretty common need to have control over workload scheduling. Along with taints/tolerations, priority class is a helpful tool. It shouldn't be terribly disruptive to add a passthrough for priority class into the deployments.
