### ISSUE TITLE
How to access harbour after deploying to k8s

### ISSUE THREAD

**Issue by leeadh** [goharbor/harbor-helm#51]
hi all, 

how do we access the habor after we have deployed to k8s?

sorry for this question. M just wondering how do we access? I tried changing the webportal service to nodeport but the portal tells me that there is an error. Unknown errors have occurred. Please try again later.

Any help?

**Comment by ywk253100** [comment]
The Harbor chart only supports ingress currently, and a pull request #14 is in progress to support `NodePort`.
