### ISSUE TITLE
https://helm.goharbor.io/index.yaml inaccessible

### ISSUE THREAD

**Issue by titou10titou10** [goharbor/harbor-helm#512]
It seems the site https://helm.goharbor.io is broken since a few days:

    helm version
    version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

    helm repo list
    NAME    URL
    harbor  https://helm.goharbor.io

    helm repo update
    Hang tight while we grab the latest from your chart repositories...
     ...Unable to get an update from the "harbor" chart repository (https://helm.goharbor.io):
                Get https://helm.goharbor.io/index.yaml: read tcp 172.xx.x.xxx:33826->178.128.239.221:443: read: connection reset by peer

**Comment by ywk253100** [comment]
I tried in my env, it works well:
```
yinw-a01:cnab-to-oci yinw$ helm repo add harbor https://helm.goharbor.io
"harbor" has been added to your repositories
yinw-a01:cnab-to-oci yinw$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "nginx" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
```
Seems it is related with your env

**Comment by titou10titou10** [comment]
@ywk253100  what version of helm are you using?

The result of removing adding helm harbor repo in my case with helm 3.1.0 :

        helm repo remove harbor
        "harbor" has been removed from your repositories

        helm repo add harbor https://helm.goharbor.io
        Error: looks like "https://helm.goharbor.io" is not a valid chart repository or cannot be reached: Get https://helm.goharbor.io/index.yaml: read tcp 172.xx.x.xxx:38846->178.128.239.221:443: read: connection reset by peer

        ping helm.goharbor.io
        PING helm.goharbor.io (178.128.239.221) 56(84) bytes of data.
        64 bytes from 178.128.239.221 (178.128.239.221): icmp_seq=1 ttl=51 time=9.73 ms

**Comment by ywk253100** [comment]
Tried with both helm 2 and 3:
```
yinw-a01:cnab-to-oci yinw$ helm repo add harbor https://helm.goharbor.io
"harbor" has been added to your repositories
yinw-a01:cnab-to-oci yinw$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "nginx" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
yinw-a01:cnab-to-oci yinw$ helm3 repo add harbor https://helm.goharbor.io
"harbor" has been added to your repositories
yinw-a01:cnab-to-oci yinw$ helm3 repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "harbor" chart repository
Update Complete. ⎈ Happy Helming!⎈
yinw-a01:cnab-to-oci yinw$ helm3 version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
yinw-a01:cnab-to-oci yinw$ helm version -c
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**Comment by titou10titou10** [comment]
@ywk253100, I tried it for the Nth  time and it "magically" (?) worked...

    helm repo add harbor https://helm.goharbor.io
    "harbor" has been added to your repositories

Weird.
anyway, closing this.
