### ISSUE TITLE
upgrade ingress but core, database and registry  were all recreated

### ISSUE THREAD

**Issue by sunlianqiang** [goharbor/harbor-helm#521]
every time I upgrade the helm, most pods will recreate. 
For example, I just upgrade the ingress, but core, database and registry were recreated.

**Comment by ywk253100** [comment]
Currently, there are some attributes which are generated automatically, which means the values are different for every deployment. 
This is the reason why the pods are recreated even though you don't change them.

So you can set these attributes by your self with solid values to avoid the pod creating.

**Comment by sunlianqiang** [comment]
thank you, problems sloved. @ywk253100
