### ISSUE TITLE
harbor-core:dev updated, but looks like has bug

### ISSUE THREAD

**Issue by zerone12** [goharbor/harbor-helm#522]
I provisioned harbor using helm chart with values.yaml describes 'core' image tag as 'dev'.
After upgrade chart, I can't login web app.

below is core pod log
<pre>
2020/02/28 07:19:29.386 [D] [transaction.go:71]  |   10.203.7.246| 404 |    557.689µs|   match| GET      /api/v2.0/systeminfo   r:/api/v2.0/*
2020/02/28 07:19:29.409 [D] [transaction.go:71]  |   10.203.7.246| 404 |    502.672µs|   match| GET      /api/v2.0/users/current   r:/api/v2.0/*
2020/02/28 07:19:29.425 [D] [transaction.go:71]  |   10.203.7.246| 404 |      417.2µs|   match| GET      /api/v2.0/users/current   r:/api/v2.0/*
2020/02/28 07:19:29.477 [D] [transaction.go:71]  |   10.203.7.246| 404 |    467.191µs|   match| GET      /api/v2.0/systeminfo   r:/api/v2.0/*
</pre>

<pre>
2020/02/28 07:23:18.042 [D] [transaction.go:71]  |   10.203.7.246| 404 |    624.114µs|   match| GET      /api/v2.0/users/current   r:/api/v2.0/*
</pre>

/api/ path is redirected to itself(core pod) by ingress.
So I can't understand why 404 Not Found error has occurred. 

I realized harbor-core:dev image has been updated just few hours ago by visiting docker hub.
So is there any bug on updated 'dev' tag image?

**Comment by ywk253100** [comment]
The `dev` images are built from the unstable branch which is under heavy development. Please use the release build instead
