### ISSUE TITLE
Invalid trivy docker image

### ISSUE THREAD

**Issue by bclermont** [goharbor/harbor-helm#524]
[In this commit](https://github.com/goharbor/harbor-helm/commit/cf0591ddd71da4fce9533165151a2ecbdf88df67#diff-ba05023d0f1b5d4b64b6cad4cf9a7ecdR461) support for trivy was added, but it refers to a docker image that don't exists.

**Comment by bclermont** [comment]
@danielpacak FYI

**Comment by danielpacak** [comment]
> [In this commit](https://github.com/goharbor/harbor-helm/commit/cf0591ddd71da4fce9533165151a2ecbdf88df67#diff-ba05023d0f1b5d4b64b6cad4cf9a7ecdR461) support for trivy was added, but it refers to a docker image that don't exists.

Hi @bclermont and thank you for reporting this. I'm aware of the fact that the Docker image is not available yet. We'll publish it soon. As a workaround please disable Trivy (`trivy.enabled=false`) if you use this Helm chart from the master branch. /cc @heww @steven-zou

**Comment by danielpacak** [comment]
@bclermont The image can be pulled from DockerHub now. Could you try and close the issue if it works for you:

```
docker pull goharbor/trivy-adapter-photon:dev
```
