### ISSUE TITLE
Run images as non-root

### ISSUE THREAD

**Issue by mmack** [goharbor/harbor-helm#53]
We're not allowed to run images as root on our k8s cluster. Docker best practice is to not use root images. 

Is the root user really required?

Max

**Comment by reasonerjt** [comment]
Which image? @mmack

**Comment by reasonerjt** [comment]
The reason `sudo` is used, is a easy way to solve some permission issue, `chmod` has to be called as some directories are mounted from docker host.

**Comment by mmack** [comment]
Which are the directories that are mounted from docker host? Is that really necessary?

**Comment by reasonerjt** [comment]
This has been fixed in Harbor v1.9+ closing.
