### ISSUE TITLE
Help understanding the architecture

### ISSUE THREAD

**Issue by jwlai** [goharbor/harbor-helm#54]
Hi I was looking for some additional help in deploying Harbor via Helm. I'm getting hung up on the values that set up the Ingress, Ingress Controller(NGINX). Mainly it is the externalURL that the values.yaml takes in. 
I'm unsure of what to put into the externalURL and how to get that to be publicly accessible (as well as the registry available). I've only done loadbalanced services so ingress is new to me. Can someone point me in the right direction? I.e. what would the externalURL be? (a domain name? NGINX IP? The worker node IP that the pod//service is on?) 

Thanks.

**Comment by ywk253100** [comment]
I think you should understand how the ingress works first. About this, you can refer to the guide of Kubernetes. 
The `externalURL` should be set as `protocol://host:port`, the `host` is the value of `ingress.hosts.core` and the `port` is the port that ingress controller listening on.
