### ISSUE TITLE
current helm chart broken

### ISSUE THREAD

**Issue by h4wkmoon** [goharbor/harbor-helm#548]
Hi, 
the current version 1.3.1 includes core probe using /api/ping, which does not work anymore.
The files in the git repo include core probe with /api/v2.0/ping, which works.

When do you plan on release a new working chart, plz ?

**Comment by lzaldivarkt** [comment]
Also, for some reason, if you install from scratch the current version, the login doesn't work :(

**Comment by h4wkmoon** [comment]
It seems that the v2 "dev" tag is not production ready yet. Hence, the term "dev".
I manage to install a working Harbor using the current helm chart and specifying the correct v1 tag for each component. I had to look at the docker hub page of each of them to find the correct "non-prod" tag.

**Comment by ywk253100** [comment]
@h4wkmoon Please follow the guide to install the released version of Harbor chart(using the chart repository): https://github.com/goharbor/harbor-helm#add-helm-repository

@lzaldivarkt Please open another issue for your problem and it's better to provide logs

**Comment by h4wkmoon** [comment]
My bad.
The solution was to use : 
`helm show values harbor/harbor --version 1.3.1`
to get the default values
instead of the values.yml file from the master branch.

You mention that on your page.

I learned something.
