### ISSUE TITLE
NFS的权限

### ISSUE THREAD

**Issue by shayulei** [goharbor/harbor-helm#55]
harbor 1.6.0 
goharbor/harbor-db:dev
用NFS为harbor提供存储，POD无法更改权限
harbor-database
harbor-chartmuseum
harbor-registry
都报
chown: changing ownership of 'X/X/X/X/X/X/X': Operation not permitted
怀疑是镜像做的有问题，因水平有限，不能继续分析，也有可能是误报，不知道有没有用NFS给harbor提供存储的，又用helm安装的朋友。

**Comment by lanmingle** [comment]
这是 docker 基础挂载问题，与其他无关，使用 nfs 类似（你可以这样理解）docker 本地挂载，注意 docker 本地挂载会创建相关的目录（nfs挂载还可能不会创建，17.03的版本试过会出现这样的情况），但是创建的目录权限是 root ,然而容器上运行的非 root 用户，这时候会出现权限不足，所以需在本地（nfs）先创建目录并授权，或者在 dockerfile 进入点，以 root 授权（非内核上控制的目录和文件）。

临时不建议使用 nfs 来玩 k8s 的存储，开发环境还可以玩一下，实际问题很多的，比如删除文件的延迟，会导致很多问题，可以考虑自己搭建 ceph 文件存储系统。
