### ISSUE TITLE
HELM install - pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by itsecforu** [goharbor/harbor-helm#559]
Hello folks!

My issue:

- Centos 7
- Kubernetes 1.15

steps:

1. helm repo add harbor https://helm.goharbor.io
2. helm install --name harbor harbor/harbor 

than i got erro on my pods: 

``pod has unbound immediate PersistentVolumeClaims (repeated 7 times)``

listing:

```  kubectl get pv

NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                        

STORAGECLASS       REASON   AGE

consul-2                                   10Gi       RWO            Retain           Bound       default/consul-3             
manual                      71d

consul-3                                   10Gi       RWO            Retain           Bound       default/vol-postgres         manual                      71d

consul-data                                1Gi        RWO            Retain           Available                                local-storage               126d

consul-l                                   10Gi       RWO            Retain           Released    default/consul-2             manual                      71d

data-consul-0                              10Gi       RWO            Retain           Bound       default/data-

consul-0        manual                      119d

data-consul-1                              10Gi       RWO            Retain           Bound       default/data-

consul-1        manual                      119d

data-consul-2                              10Gi       RWO            Retain           Bound       default/data-

consul-2        manual                      119d

data-consul-pv0                            10Gi       RWO            Recycle          Available   default/data-

consul-pvc0     manual                      119d

data-consul-pv1                            10Gi       RWO            Recycle          Available   default/data-

consul-pvc0     manual                      7d21h

minio-pv-volume                            15Gi       RWO            Retain           Bound       default/minio-pv-

claim       manual                      154d

my-local-pv                                500Gi      RWO            Retain           Available                                my-

local-storage            2d

my-local-pv2                               500Gi      RWO            Retain           Available                                

my-local-storage            2d

my-local-pv3                               500Gi      RWO            Retain           Available                                

my-local-storage            2d

postgres-volume                            10Gi       RWO            Retain           Bound       default/consul-1             

manual                      105d

pv-volume10                                10Gi       RWX            Retain           Bound       sonar/sonar-temp-

pv-claim                                105d

pv-volume7                                 10Gi       RWX            Retain           Bound       sonar/sonar-ext-pv-
claim                                 105d

pv-volume8                                 10Gi       RWX            Retain           Bound       sonar/sonar-data-pv-claim                                105d


pv-volume9                                 10Gi       RWX            Retain           Bound       sonar/pg-pv-claim                                        105d

pv0                                        10Gi       RWO            Retain           Available                                default                     126d

pv1                                        10Gi       RWO            Retain           Available                                default                     126d

pv2                                        10Gi       RWO            Retain           Bound       default/vault-pv-claim       default                     126d
pvc-b2cd2c8a-e7bb-4ea4-ac05-521f29966ce8   1000Mi     RWO            Delete           Bound       default/test-data            my-storage                  143d

sonarqube-volume                           10Gi       RWO            Retain           Bound       

sonarqube/sonar-postgresql   manual                      105d

test-pv-volume                             1Gi        RWO            Retain           Available                                slow                        8d

vol-mobsf                                  10Gi       RWO            Retain           Bound       default/vol-mobsf            manual                      65d

vol-mobsf2                                 10Gi       RWO            Retain           Bound       ingress-nginx/vol-

mobsf2     manual                      51d

vol-nginx-log                              10Gi       RWO            Retain           Bound       default/vol-nginx-log        manual                      65d

vol-postgres                               10Gi       RWO            Retain           Available                                manual                      65d
![2](https://user-images.githubusercontent.com/38696837/78886095-55070e00-7a66-11ea-9148-b9c6fcbdd81e.png)
```

PVC:

`` kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                        STORAGECLASS       REASON   AGE
consul-2                                   10Gi       RWO            Retain           Bound       default/consul-3             manual                      71d
consul-3                                   10Gi       RWO            Retain           Bound       default/vol-postgres         manual                      71d
consul-data                                1Gi        RWO            Retain           Available                                local-storage               126d
consul-l                                   10Gi       RWO            Retain           Released    default/consul-2             manual                      71d
data-consul-0                              10Gi       RWO            Retain           Bound       default/data-consul-0        manual                      119d
data-consul-1                              10Gi       RWO            Retain           Bound       default/data-consul-1        manual                      119d
data-consul-2                              10Gi       RWO            Retain           Bound       default/data-consul-2        manual                      119d
data-consul-pv0                            10Gi       RWO            Recycle          Available   default/data-consul-pvc0     manual                      119d
data-consul-pv1                            10Gi       RWO            Recycle          Available   default/data-consul-pvc0     manual                      7d21h
minio-pv-volume                            15Gi       RWO            Retain           Bound       default/minio-pv-claim       manual                      154d
my-local-pv                                500Gi      RWO            Retain           Available                                my-local-storage            2d
my-local-pv2                               500Gi      RWO            Retain           Available                                my-local-storage            2d
my-local-pv3                               500Gi      RWO            Retain           Available                                my-local-storage            2d
postgres-volume                            10Gi       RWO            Retain           Bound       default/consul-1             manual                      105d
pv-volume10                                10Gi       RWX            Retain           Bound       sonar/sonar-temp-pv-claim                                105d
pv-volume7                                 10Gi       RWX            Retain           Bound       sonar/sonar-ext-pv-claim                                 105d
pv-volume8                                 10Gi       RWX            Retain           Bound       sonar/sonar-data-pv-claim                                105d
pv-volume9                                 10Gi       RWX            Retain           Bound       sonar/pg-pv-claim                                        105d
pv0                                        10Gi       RWO            Retain           Available                                default                     126d
pv1                                        10Gi       RWO            Retain           Available                                default                     126d
pv2                                        10Gi       RWO            Retain           Bound       default/vault-pv-claim       default                     126d
pvc-b2cd2c8a-e7bb-4ea4-ac05-521f29966ce8   1000Mi     RWO            Delete           Bound       default/test-data            my-storage                  143d
sonarqube-volume                           10Gi       RWO            Retain           Bound       sonarqube/sonar-postgresql   manual                      105d
test-pv-volume                             1Gi        RWO            Retain           Available                                slow                        8d
vol-mobsf                                  10Gi       RWO            Retain           Bound       default/vol-mobsf            manual                      65d
vol-mobsf2                                 10Gi       RWO            Retain           Bound       ingress-nginx/vol-mobsf2     manual                      51d
vol-nginx-log                              10Gi       RWO            Retain           Bound       default/vol-nginx-log        manual                      65d
vol-postgres                               10Gi       RWO            Retain           Available                                manual                      65d
``

Plz tell me how to make correct PV for solution 🙏

![2](https://user-images.githubusercontent.com/38696837/78885892-035e8380-7a66-11ea-8805-dae48431c216.png)
![1](https://user-images.githubusercontent.com/38696837/78885896-03f71a00-7a66-11ea-906e-d8797d9a1e5f.png)

**Comment by itsecforu** [comment]
![2](https://user-images.githubusercontent.com/38696837/78886122-63552a00-7a66-11ea-8675-6931f81f6d39.png)

**Comment by reasonerjt** [comment]
do you have a default storage class set in your cluster?

**Comment by itsecforu** [comment]
> 
> 
> do you have a default storage class set in your cluster?

``kubectl get storageclass
NAME            PROVISIONER                    AGE
ceph-rbd        ceph.com/rbd                   169d
fast-rbd        ceph.com/rbd                   146d
general         ceph.com/rbd                   169d
local-storage   kubernetes.io/no-provisioner   127d
my-storage      rook.io/block                  143d``

**Comment by itsecforu** [comment]
no ideas ? :-(

**Comment by dunxiii** [comment]
Run `kubectl get storageclasses.storage.k8s.io` and see if any has `(default)` by it's name. Otherwise you must define the storageclass in the values file.

**Comment by itsecforu** [comment]
Wow thx for feedback!
```
 kubectl get storageclasses.storage.k8s.io
NAME            PROVISIONER                    AGE
ceph-rbd        ceph.com/rbd                   175d
fast-rbd        ceph.com/rbd                   152d
general         ceph.com/rbd                   175d
local-storage   kubernetes.io/no-provisioner   133d
my-storage      rook.io/block                  150d
```
Seems as i dont have this one. 
What if you add this class? and do not restart the assembly with the new "values" file?
Is it possible?

**Comment by itsecforu** [comment]
I added **local-storage** on ``storageclass section.``

next  I try 

``helm upgrade -f ./values.yaml harbor harbor/harbor
UPGRADE FAILED
Error: PersistentVolumeClaim "harbor-harbor-chartmuseum" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims && PersistentVolumeClaim "harbor-harbor-jobservice" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims && PersistentVolumeClaim "harbor-harbor-registry" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims && StatefulSet.apps "harbor-harbor-database" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && StatefulSet.apps "harbor-harbor-redis" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Error: UPGRADE FAILED: PersistentVolumeClaim "harbor-harbor-chartmuseum" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims && PersistentVolumeClaim "harbor-harbor-jobservice" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims && PersistentVolumeClaim "harbor-harbor-registry" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims && StatefulSet.apps "harbor-harbor-database" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden && StatefulSet.apps "harbor-harbor-redis" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden``

**Comment by djpbessems** [comment]
You should follow the steps in this article to actually set a default storageclass:
https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

**Comment by CodingSpiderFox** [comment]
@djpbessems how can I set a default storage class if the list of storage classes available is completely empty "No resources found"

**Comment by djpbessems** [comment]
> 
> 
> @djpbessems how can I set a default storage class if the list of storage classes available is completely empty "No resources found"

**Short answer:**  
You can't.

**Long answer:**  
Read this to actually understand the topic: https://kubernetes.io/docs/concepts/storage/storage-classes/
Pick a provisioner and set it up.

**Comment by nicolasery** [comment]
Hi, I don't know if I'm the good issue but before I deployed the helm chart I created a PV with unique storageClass on my NFS for each pod, then I defined the storageClass for for each PVC in the chart values.yml, they all works with persitence ofc except for database PVC, I have to let the default chart value = local-path storageClass by default or I'm stuck with the same issue
I really need the keep database persistent

`  Warning  FailedScheduling  7m31s                  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  7m31s                  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         7m28s                  default-scheduler  Successfully assigned system/harbor-harbor-database-0 to master-1
  Normal   Pulling           7m23s                  kubelet            Pulling image "goharbor/harbor-db:v2.2.0"
  Normal   Pulled            3m34s                  kubelet            Successfully pulled image "goharbor/harbor-db:v2.2.0" in 3m49.038577438s
  Normal   Created           3m34s                  kubelet            Created container data-migrator
  Normal   Started           3m34s                  kubelet            Started container data-migrator
  Warning  Unhealthy         3m15s (x2 over 3m25s)  kubelet            Readiness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "10.42.0.43" and accepting
           TCP/IP connections on port 5432?
`

the default PV database
pvc-17943039-f6e4-47d5-8e3a-b5f043a2676c   1Gi        RWO            Delete           Bound       system/database-data-harbor-harbor-database-0   local-path                      15m

**Comment by nicolasery** [comment]
ok sorry, I think its just my NFS permissions that are wrong, I'll test it
