### ISSUE TITLE
How to access the registry use cli

### ISSUE THREAD

**Issue by cuijxin** [goharbor/harbor-helm#56]
大家好，

       当我部署完Harbor之后，因为我修改了harbor-ui的服务的spec.type为NodePort，
       所以我可以通过hostIP+port的方式在浏览器里访问harbor-ui。
       但是当我想登录registry时，遇到了一个错误，
        我在命令行执行：“docker login core.harbor.domain”时，
         报错“Error response from daemon: Get https://core.harbor.domain/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)”。
     这里我需要怎么来配置我的harbor服务来让我可以通过命令行来登录它，并且上传我的镜像呢？

**Comment by ywk253100** [comment]
配置`values.yaml`中的`externalURL `为你外部可访问的URL

**Comment by fshadid96** [comment]
Hey, 

by any chance were you able to figure out this issue?
