### ISSUE TITLE
(external database) - failed to initialize database: register db Ping `default`, pq: database "registry" does not exist

### ISSUE THREAD

**Issue by cparadal** [goharbor/harbor-helm#564]
Hi,

I'm trying to install Harbor (Helm chart) with a setup of external components: RDS (Postgres), Elasticache (Redis) and S3 storage.

Upon chart install, multiple pods, including the core one, fail with the below error:

```
port-5432 databse-registry sslmode-"disable"
[ORM]2020/04/15 08:45:56 register db Ping `default`, pq: database "registry" does not exist
2020-04-15T08:45:56Z [FATAL] [/core/main.go:188]: failed to initialize database: register db Ping `default`, pq: database "registry" does not exist
```

It doesn't seem to be an issue with the RDS instance itself (or connectivity to it) as the pods come up with no issues after I manually create the registry, clair, notarysigner and notaryserver databases myself.

As I understand, those databases should be created on Harbor initialization.
Is there any way of making it work without having to manually create the databases, which is obviously not scalable?

Thanks.

Harbor Helm chart version: 1.3.1
Kubernetes version: 1.15.4

**Comment by pard68** [comment]
Having the same issue. The bitnami chart has an init container it uses to create the needed databases. Looks like, if you use an internal db it uses the goharbor/harbor-db image which looks to be getting, what I can only assume, is the fresh database:
https://hub.docker.com/layers/goharbor/harbor-db/dev/images/sha256-65b7eb0ea1cda5482c65bc276a7d646bdb6d09e83dea886b94381c79da9011ba?context=explore

**Comment by pard68** [comment]
Poking around and this [issue](https://github.com/goharbor/harbor/issues/12251) helped me solve the problem, but still it'd be nice if this could just be thrown into an init container.

**Comment by reasonerjt** [comment]
@pard68 is correct the external DB has to have a database called `registry`:
https://github.com/goharbor/harbor/blob/master/make/photon/db/initial-registry.sql#L2
