### ISSUE TITLE
Release 1.3.2 contains helm binary which makes release to big for deployment.

### ISSUE THREAD

**Issue by dunxiii** [goharbor/harbor-helm#568]
Hi.

In the latest 1.3.2 release the helm binary (45MB) was included in the tgz file so when deploying with helm following error occurs:
`Error: create: failed to create: Request entity too large: limit is 3145728`

By simply re-release without the binary it should behave normal again.

**Comment by thamaraiselvam** [comment]
Yes it happens for me as well.

**Comment by heww** [comment]
Closed for the 1.3.2 was re-released.
