### ISSUE TITLE
Harbor Helm 1.3.2 - Failed to install app harbor. Error: UPGRADE FAILED: grpc: received message larger than max (45969392 vs. 20971520)

### ISSUE THREAD

**Issue by gknepper** [goharbor/harbor-helm#569]
Error happening in a brand new installation and during a upgrade:

Failed to install app harbor. Error: UPGRADE FAILED: grpc: received message larger than max (45969392 vs. 20971520)

**Comment by gameiro83** [comment]
Same thing happen to me too, the issue must related to the https://github.com/goharbor/harbor-helm/issues/568

**Comment by heww** [comment]
1.3.2 was re-released and it is 34.6 KB now.
