### ISSUE TITLE
Not able to push the image to the Registry - Docker push (retrying) 

### ISSUE THREAD

**Issue by Pradyumnakashyap** [goharbor/harbor-helm#578]
Installed Harbor with Helm on Kubernetes (on EC2-AWS - Development env)
All pods are fine and able to login with UI and create projects, When i try to push images after a successful docker login, keeps on retrying and fails (Docker logs says - time="2020-04-15T16:19:05.287199445Z" level=error msg="Upload failed, retrying: received unexpected HTTP status: 500 Internal Server Error"
cross verified other similar issues, No problem with storage as I am using file system (local) to store the images.
Please help.
(As advised opening issue here under harbor-helm)

**Comment by Pradyumnakashyap** [comment]
@reasonerjt  @ywk253100  Please help on the same.

**Comment by Pradyumnakashyap** [comment]
A 500 error is a catch all and could be anything, So Please kindly help with the same at the earliest.
@reasonerjt  @ywk253100 @heww

**Comment by Pradyumnakashyap** [comment]
Never mind ! Fixed it myself. 
Inside the registry container the permissions did not allow write changes to /storage (as it was owned by 999) 
a simple 'chmod 777' did the trick ! 
-may be a pod file with security context allowing such changes can avoid such issues.

**Comment by yzz-ihep** [comment]
What is the password of sudo?

**Comment by Pradyumnakashyap** [comment]
> What is the password of sudo?

You will have to use a "docker exec -u" command with username admin and log into the Registry container and make the changes.

**Comment by yzz-ihep** [comment]
> > What is the password of sudo?
> 
> You will have to use a "docker exec -u" command with username admin and log into the Registry container and make the changes.

Thanks!!!!

**Comment by invy** [comment]
I have similar problem. I'm trying to configure Harbor in HA cluster.

I've specified FSGID for nfs provisioner (this one: https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/intro.md ) to be 10000 (which is specified in securityContext for the registry pod), but it returns with error code 500. However uploading happens and layers are written inside of the /storage.
I suppose there is still some other problem, maybe with other pods?...
