### ISSUE TITLE
Support for harbor 2.0

### ISSUE THREAD

**Issue by tvvignesh** [goharbor/harbor-helm#584]
Hi. Requesting upgrade of this helm chart to v2.0. While I tried modifying the image versions along with a few other things in this helm chart, it fails because of the breaking change in the api.

It gives `2020/05/13 20:22:46.609 [D] [middleware.go:52] | ::1| 404 | 2.026509ms| nomatch| GET /api/ping` so harbor-core for instance is still trying to ping `/api` when it should ping `/api/v2`

Tried modifying the URLs wherever I could find it but still the issue persists.

**UPDATE:** Cleaned up everything, did it again and it worked. Only nginx fails now. Looking into it. Keeping this issue open till its fixed.

**UPDATE:** I removed Nginx completely from the Helm chart and used the Istio config as given here: https://github.com/goharbor/harbor-helm/issues/77#issuecomment-627841527 and it worked for htpasswd authentication but did not for others. Did not spend time debugging Nginx (It seems to be failing healthchecks since I am running within Istio - related https://github.com/goharbor/harbor-helm/issues/576 and https://github.com/goharbor/harbor-helm/issues/406)

Thanks.

**Comment by lnattrass** [comment]
I'm surprised that the Harbor 2.0 release didn't include a helm chart...

**Comment by jkroepke** [comment]
@ywk253100 @heww @danielpacak 

Is something blocking? Can we help?

**Comment by reasonerjt** [comment]
Hi, the code is in master now, a release will be tagged after verification

**Comment by cafeliker** [comment]
Is there any target date to release the chart for harbor 2.0?

**Comment by jessehu** [comment]
The harbor helm chart for harbor 2.0 is released: https://github.com/goharbor/harbor-helm/releases/tag/v1.4.0

**Comment by tvvignesh** [comment]
@jessehu Great to hear that! Will try it out right away. You may close this issue if you want. Will report back if I find any issues. Thanks.
