### ISSUE TITLE
Image tags in 1.4.0 are defined as dev

### ISSUE THREAD

**Issue by klinux** [goharbor/harbor-helm#592]
The release 1.4.0, the values of image tag is **dev**, I think this is a mistake, or is correct tag?

Thank you

**Comment by heww** [comment]
I just check that the image tags used by harbor-helm 1.4.0 are `v2.0.0`. 

You should to install harbor-helm 1.4.0 through the repo. Please try

``` bash
helm repo add harbor https://helm.goharbor.io
helm repo update
helm install my-release harbor/harbor
```

The image tags in master branch are always `dev`.

**Comment by klinux** [comment]
You are saying that images here https://github.com/goharbor/harbor-helm/releases/tag/v1.4.0 is always dev  tag?

And now I download the file again and all  tags have v2.0.0 version!

Thank you

**Comment by heww** [comment]
I mean image tags in this file https://github.com/goharbor/harbor-helm/blob/master/values.yaml will be always `dev`.
