### ISSUE TITLE
Trivy not getting the proxy settings from helm chart

### ISSUE THREAD

**Issue by gknepper** [goharbor/harbor-helm#595]
Trivy not getting the proxy settings from helm, Although Clair is getting as expected all the following values: **http_proxy,https_proxy and no_proxy.** 

Also the installation doesn't allow the manual environment variable mapping for Trivy.

Unfortunately resulting in a error then using Trivy due the restriction on update the vulnerability DB.

Thanks

**Comment by phisco** [comment]
same issue here 👍
