### ISSUE TITLE
There is no way to use an "existingClaim" for trivy persistence

### ISSUE THREAD

**Issue by titou10titou10** [goharbor/harbor-helm#598]
There is a place in`values.yaml`to let trivy use an existing PVC (`existingClaim`) but it is not used in the StatefulSet 

Values.yaml: 

    persistence:
      persistentVolumeClaim:
        trivy:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 5Gi

trivy-sts.yaml:

    {{- $trivyPVC := .Values.persistence.persistentVolumeClaim.trivy }}

    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ $trivyPVC.accessMode | quote }}
        {{- if $trivyPVC.storageClass }}
        {{- if (eq "-" $trivyPVC.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ $trivyPVC.storageClass }}"
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ $trivyPVC.size | quote }}

[EDITED]
~~This part of sts should be conditionnal of`"$trivyPVC.existingClaim"` and a`"volume"`with a`"persistentVolumeClaim"`clause added in the spec, as it is done in [database-ss](https://github.com/goharbor/harbor-helm/blob/master/templates/database/database-ss.yaml)~~

As trivy is deployed as a StatefulSet, and its uses the PVC for cache management, IMHO the "fix" is to simply remove the`persistence.persistentVolumeClaim.trivy. existingClaim`key from`values.yaml

**Comment by alex1989hu** [comment]
I have just found that issue, I am happy that you also met 🏅

**Comment by heww** [comment]
Closed by #602
