### ISSUE TITLE
Use default Certificate from Ingress Controller not possible

### ISSUE THREAD

**Issue by splattner** [goharbor/harbor-helm#600]
Currently its not possible to not set a secretName for the ingress resources as its automaticly generated when the value for secretName is empty (https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L19). I use a default certificate on our Nginx ingress controller (https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate) and therefore don't want to set a secretName and it also should not be generated

**Comment by reasonerjt** [comment]
@splattner 
It's tricky to design the chart to support different dependencies in the env.

As for now please edit the template to workaround, we may consider changing this part but it's not a very high priority.

**Comment by ywk253100** [comment]
Harbor chart supports this use case now by specifying the `expose.tls.certSource` as `none` https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L21

**Comment by abdennour** [comment]
@ywk253100  what about the other values ? like `expose.ingress.annotations` ? 
what will be the values of `expose.ingress.annotations`  when `expose.ingress.annotations` is `none` ?
