### ISSUE TITLE
compatibility for registry schema1

### ISSUE THREAD

**Issue by secret104278** [goharbor/harbor-helm#605]
There should be an option to enable schema1 compatibility in https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-cm.yaml

When compatiblity is not set, you may encounter
```
docker push registry.example.com/test:test
The push refers to repository [registry.example.com/test:test]
79d155105598: Layer already exists
fb34596dd97c: Layer already exists
e4cbd5becbe1: Layer already exists
00598e9193e9: Layer already exists
16542a8fc3be: Layer already exists
6597da2e2e52: Layer already exists
977183d4e999: Layer already exists
c8be1b8f4d60: Layer already exists
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the registry.example.com registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
received unexpected HTTP status: 500 Internal Server Error
```

Harbor default is enable.
https://github.com/goharbor/harbor/blob/b747fdb68da86c7108807ab6bf6da6e6a617209a/make/photon/prepare/templates/registry/config.yml.jinja#L42

**Comment by reasonerjt** [comment]
@secret104278
The `DEPRECATION NOTICE` was printed by docker and probably has nothing to do with the 500 error.

Could you let us know what version are you using?  Could you check the log in core pod to see what's wrong?

**Comment by lassegaardsholt** [comment]
Would it be possible to create a new release with this in? :)
