### ISSUE TITLE
Provide a way to add extra CAs to ca-bundle.crt in harbor core component

### ISSUE THREAD

**Issue by titou10titou10** [goharbor/harbor-helm#608]
When creating a remote "registry endoint" in Harbor to a registry that is accessible with a certificate that is signed by a corporate CA, there is no options except to uncheck the "verify remote cert" box to validate that everything is OK. Harbor executes a "https get" to the remote address, this check uses the CAs held in the`/etc/pki/tls/certs/ca-bundle.crt`file deployed in the container

The Helm chart should provide a way for the "core" component of Harbor to either (in order of preference):
- provide`ConfigMaps` with extra CAs that would be added to the`/etc/pki/tls/certs/ca-bundle.crt` in the container (With an init container?)
- replace the whole`/etc/pki/tls/certs/ca-bundle.crt`file with a version that contains the corporate CAs held in a`ConfigMap` via a "volume mount" in the container
- define our own`initContainers`to perform any action, including the one described above

(this is related to https://github.com/goharbor/harbor/issues/10086)

**Comment by heww** [comment]
Closed by #601
