### ISSUE TITLE
Unable to configure externalUrl when using LoadBalancer type Service

### ISSUE THREAD

**Issue by Purushotham233** [goharbor/harbor-helm#618]
Harbor-helm chart verison: 1.4.0
Kubernetes version: 1.17.4

Kubernetes cluster is on our private cloud. We use LoadBalancer type Service to create ELB via our custom cloud controller manager.

When we use LoadBalance type Service, ELP IP wont be available upfront. So not able to provide the value to externalUrl parameter in values.yaml. Are we supposed to use DomainName for externalUrl always? 

Could you advise how do we use the helm chart in our scenario.

**Comment by reasonerjt** [comment]
For now.  
You should use Domain name for LB.
