### ISSUE TITLE
ingress的问题

### ISSUE THREAD

**Issue by shayulei** [goharbor/harbor-helm#62]
在3个月前的老版本中，我使用以下命令
helm install . --debug --name my-harbor --namespace harbor --set externalDomain=harbor.aa.com.cn
就能在WEB中使用harbor.aa.com.cn访问harbor的web，但在新版中使用
helm install . --debug --name my-harbor --namespace harbor --set externalURL=http://harbor.aa.com.cn -f ./values1.yaml
却无法使用harbor.aa.com.cn打开网页，使用kubectl get in -n harbor 查看，发现hosts还是老的域名

**Comment by ywk253100** [comment]
需要同时设置`externalURL`和`ingress. hosts `

**Comment by lanmingle** [comment]
需要同时设置externalURL和ingress. hosts
