### ISSUE TITLE
docker push "unauthorized: unauthorized to access repository"

### ISSUE THREAD

**Issue by czysl** [goharbor/harbor-helm#622]
no problem with login in the webpage 
but when i use docker push , errors are reported as follows：

kubectl  logs harbor-harbor-registry-57bfc699dc-5rltg -c registry

```
level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="blob unknown" err.detail=sha256:e5c3f8c317dc30af45021092a3d76f16ba7aa1ee5f18fec742c8
err.message="blob unknown to registry" go.version=go1.13.8 http.request.host=harbor.xxxx.com http.request.id=b3571a86-4f22-4a50-8a94-faada8ecb1c9 http.request.method=HEAD http.request.remoteaddr=100.120.136.132 http.request.uri="/v2/java/blobs/sha256:e5c3f8c317dc30af45021092a3d76f16ba7aa1ee5f18fec742c84d49608185" 
http.request.useragent="docker/1.13.1 go/go1.10.3 kernel/3.10.0-957.21.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=101.296901ms http.response.status=404 http.response.written=157
```

kubectl logs core 
```
2020/06/13 09:57:36.085 [D] [middleware.go:52]  |100.120.136.154| 401 |    313.027µs|   match| GET      /v2/   r:/v2/*
2020/06/13 09:57:36.118 [D] [middleware.go:52]  |100.120.136.131| 200 |   11.93295ms|   match| GET      /service/token   r:/service/token
2020/06/13 09:57:36.286 [D] [transaction.go:62]  |100.120.136.178| 202 | 160.409383ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.328 [D] [transaction.go:62]  |100.120.136.138| 202 | 188.481362ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.342 [D] [transaction.go:62]  |100.120.136.182| 202 | 202.364465ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.345 [D] [transaction.go:62]  |100.120.136.179| 404 | 205.740173ms|   match| HEAD     /v2/blobs/sha256:4f2f2375eda7fcb98cd22858eb3008c610add3f9d1e993ccec0d32b5b0d9c825   r:/v2/*
2020/06/13 09:57:36.349 [D] [transaction.go:62]  |100.120.136.145| 202 | 209.668532ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.452 [D] [transaction.go:62]  |100.120.136.152| 401 |   1.209912ms|   match| PATCH    /v2/blobs/uploads/5170600c-d46d-4b76-86c5-1d7bc79eabc9   r:/v2/*/blobs/uploads/:session_id
2020/06/13 09:57:36.484 [D] [transaction.go:62]  |100.120.136.133| 401 |   1.219599ms|   match| PATCH    /v2/blobs/uploads/be57d342-c5bf-4c35-8c88-9a166b631480   r:/v2/*/blobs/uploads/:session_id
2020/06/13 09:57:36.722 [D] [transaction.go:62]  |100.120.136.145| 202 | 192.321321ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.741 [D] [transaction.go:62]  |100.120.136.160| 404 | 197.076354ms|   match| HEAD     /v2/blobs/sha256:31d57ef7a684bffc0decadb0c268cf3c9b582271caab5565148ed4a87d7c4167   r:/v2/*
2020/06/13 09:57:36.741 [D] [transaction.go:62]  |100.120.136.128| 404 | 197.135027ms|   match| HEAD     /v2/blobs/sha256:72744d0a318b0788001cc4f5f83c6847ba4b753307fadd046b508bbc41eb9e29   r:/v2/*
2020/06/13 09:57:36.745 [D] [transaction.go:62]  |100.120.136.131| 404 | 200.352867ms|   match| HEAD     /v2/blobs/sha256:a587a86c9dcb9df6584180042becf21e36ecd8b460a761711227b4b06889a005   r:/v2/*
2020/06/13 09:57:36.752 [D] [transaction.go:62]  |100.120.136.140| 404 | 210.081026ms|   match| HEAD     /v2/blobs/sha256:a2a7264255929d31586b2389e52c0939bdd2f627b72e6aca55ff169108589524   r:/v2/*
2020/06/13 09:57:36.937 [D] [transaction.go:62]  |100.120.136.168| 202 | 173.178379ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.943 [D] [transaction.go:62]  |100.120.136.165| 202 | 190.924888ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.955 [D] [transaction.go:62]  |100.120.136.138| 404 | 211.485291ms|   match| HEAD     /v2/blobs/sha256:e5c3f8c317dc30af45021092a3d76f16ba7aa1ee5f18fec742c84d4960818580   r:/v2/*
2020/06/13 09:57:36.955 [D] [transaction.go:62]  |100.120.136.146| 202 | 198.077608ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:36.977 [D] [transaction.go:62]  |100.120.136.186| 202 | 213.108651ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:37.094 [D] [transaction.go:62]  |100.120.136.176| 404 | 138.915005ms|   match| HEAD     /v2/blobs/sha256:bc9ab73e5b14b9fbd3687a4d8c1f1360533d6ee9ffc3f5ecc6630794b40257b7   r:/v2/*
2020/06/13 09:57:37.094 [D] [transaction.go:62]  |100.120.136.153| 404 | 141.423019ms|   match| HEAD     /v2/blobs/sha256:193a6306c92af328dbd41bbbd3200a2c90802624cccfe5725223324428110d7f   r:/v2/*
2020/06/13 09:57:37.170 [D] [transaction.go:62]  |100.120.136.166| 202 | 198.390364ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:37.211 [D] [transaction.go:62]  |100.120.136.138| 202 |  98.095592ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
2020/06/13 09:57:37.213 [D] [transaction.go:62]  |100.120.136.148| 202 |  99.860469ms|   match| POST     /v2/blobs/uploads/   r:/v2/*/blobs/uploads
```

anyone has the same trouble?

**Comment by hasonhai** [comment]
sometimes I had it also.
which helm chart and harbor version are you using?
which storage backend are you using for registry?

**Comment by reasonerjt** [comment]
This may be a known issue on the distribution side.  There may be some inconsistency in the storage.

@czysl please clarify what storage backend you are using.

When you try to push again what happens?

**Comment by AviorAlong** [comment]
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.870 #033[1;44m[D]#033[0m [middleware.go:52]  |   10.28.252.31|#033[97;43m 401 #033[0m|    401.273µs|   match|#033[97;44m GET     #033[0m /v2/   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.892 #033[1;44m[D]#033[0m [middleware.go:52]  |   10.28.252.31|#033[97;42m 200 #033[0m|  15.255505ms|   match|#033[97;44m GET     #033[0m /service/token   r:/service/token
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.923 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|  24.680046ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:7867af19f69cb8ed796a87f10bb0b25f6d928ab402a2e39a6ccb99eb0fd42408   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.923 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|  26.395595ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:33699d7df21edc5ded5b679bc283e5890ed92c5bf20e53b48edcd9096c8a5962   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.924 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|  25.011822ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:6fa330d99257255a758c41e3e851d516834c151853b8c4df3dcc22d45fc58822   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.924 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|  25.066079ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:923705ffa8f8217d98152f2bd87298401ee7d1d7b641925e500d0b77155e3be6   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.925 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|  28.409566ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:48582f1cafc0714fd44ddb5781dd70df9d9ac2496f8a68ca92c7de2fe82ca7f2   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|   2.887801ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|   3.094882ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|   3.439631ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|   3.567404ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.934 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|    2.99761ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.957 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|   17.05438ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:81fc1918191541a2ffb6ed1cd8386ef8302aea1b0613ebc768a00e76c1f34bb9   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.957 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|  18.903445ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:a8f58c4fcca04f9622e97db77618075b618c24a58cce6c6860ca54c9a887745b   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.958 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|    17.7828ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:82851092453815ec861754ded7101fcfa3b648d09a0818ced17ea80478f179a3   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.960 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 404 #033[0m|  19.115734ms|   match|#033[97;45m HEAD    #033[0m /v2/library/zm-node/blobs/sha256:ee49ee6a23d1c7e6b8b574c905dcd4a53efb869a539a957d3e47bc3698f01dc8   r:/v2/*
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.965 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|   2.250491ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.966 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|   2.390865ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.966 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|   3.458107ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads
Jul  3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.968 #033[1;44m[D]#033[0m [transaction.go:62]  |   10.28.252.31|#033[97;43m 401 #033[0m|    2.52717ms|   match|#033[97;46m POST    #033[0m /v2/library/zm-node/blobs/uploads/   r:/v2/*/blobs/uploads

![image](https://user-images.githubusercontent.com/18592408/86471411-e76e3380-bd6f-11ea-9041-d46b55180d5b.png)

**Comment by AviorAlong** [comment]
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.870 #33[1;44m[D]#33[0m [middleware.go:52] | 10.28.252.31|#33[97;43m 401 #33[0m| 401.273µs| match|#33[97;44m GET #33[0m /v2/ r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.892 #33[1;44m[D]#33[0m [middleware.go:52] | 10.28.252.31|#33[97;42m 200 #33[0m| 15.255505ms| match|#33[97;44m GET #33[0m /service/token r:/service/token
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.923 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 24.680046ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:7867af19f69cb8ed796a87f10bb0b25f6d928ab402a2e39a6ccb99eb0fd42408 r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.923 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 26.395595ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:33699d7df21edc5ded5b679bc283e5890ed92c5bf20e53b48edcd9096c8a5962 r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.924 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 25.011822ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:6fa330d99257255a758c41e3e851d516834c151853b8c4df3dcc22d45fc58822 r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.924 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 25.066079ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:923705ffa8f8217d98152f2bd87298401ee7d1d7b641925e500d0b77155e3be6 r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.925 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 28.409566ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:48582f1cafc0714fd44ddb5781dd70df9d9ac2496f8a68ca92c7de2fe82ca7f2 r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 2.887801ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 3.094882ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 3.439631ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.933 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 3.567404ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.934 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 2.99761ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.957 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 17.05438ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:81fc1918191541a2ffb6ed1cd8386ef8302aea1b0613ebc768a00e76c1f34bb9 r:/v2/_
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.957 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 18.903445ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:a8f58c4fcca04f9622e97db77618075b618c24a58cce6c6860ca54c9a887745b r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.958 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 17.7828ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:82851092453815ec861754ded7101fcfa3b648d09a0818ced17ea80478f179a3 r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.960 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 404 #33[0m| 19.115734ms| match|#33[97;45m HEAD #33[0m /v2/library/zm-node/blobs/sha256:ee49ee6a23d1c7e6b8b574c905dcd4a53efb869a539a957d3e47bc3698f01dc8 r:/v2/*
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.965 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 2.250491ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.966 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 2.390865ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads
> Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.966 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 3.458107ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads Jul 3 20:57:10 192.168.32.1 core[16136]: 2020/07/03 12:57:10.968 #33[1;44m[D]#33[0m [transaction.go:62] | 10.28.252.31|#33[97;43m 401 #33[0m| 2.52717ms| match|#33[97;46m POST #33[0m /v2/library/zm-node/blobs/uploads/ r:/v2/_/blobs/uploads
> 
> ![image](https://user-images.githubusercontent.com/18592408/86471411-e76e3380-bd6f-11ea-9041-d46b55180d5b.png)

The push refers to repository [10.81.87.34/library/zm-node]
0ddfc92678f1: Preparing 
937b32faacbc: Preparing 
f81e2504e954: Preparing 
bc17cd405095: Preparing 
ee854067fbbd: Preparing 
740ffea5d5c3: Waiting 
eac9ead92b24: Waiting 
23bca356262f: Waiting 
8354d5896557: Waiting 
unauthorized: unauthorized to access repository: library/zm-node, action: push: unauthorized to access repository: library/zm-node, action: push

**Comment by aloisiobilck** [comment]
I have the same issue

`persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: "ebs-sc-retain"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    disableredirect: false
    type: s3
    s3:
      region: eu-central-1
      bucket: harbor-artifacts-objectstore
      accesskey: accesskey
      secretkey: secretkey`

**Comment by czysl** [comment]
already solve it with add one line  in the reigstry-configmap:
    http:
      relativeurls: false
      addr: :5000
        host: https://harbor.xxx.com.cn     #####ADD THE LINE
      # set via environment variable
      # secret: placeholder
