### ISSUE TITLE
configmap.yaml under /harbor/templates/portal was named to comfigmap.yaml erroneously

### ISSUE THREAD

**Issue by zhangrui153169** [goharbor/harbor-helm#625]
When I did "helm pull harbor/harbor" and "tar -xzvf harbor-1.4.0.tgz" , I found _configmap.yaml_ under /harbor/templates/portal was named to _comfigmap.yaml_ erroneously。

**Comment by reasonerjt** [comment]
Thanks this looks like a typo, we'll fix it.

**Comment by reasonerjt** [comment]
Fixed.
