### ISSUE TITLE
CrashLoopBackOff registryctl

### ISSUE THREAD

**Issue by SvenC56** [goharbor/harbor-helm#626]
Hey I launched the helm chart (v3) yesterday and everything is working fine. However the registryctl is getting a CrashLoopBackOff loop. The registry is running fine.

```
ls: /harbor_cust_cert: No such file or directory
2020-06-16T06:47:47Z [ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:open : no such file or directory
2020-06-16T06:47:47Z [FATAL] [/registryctl/main.go:78]: Failed to load configurations with error: open : no such file or directory
```

helm config 

```yaml
registry:
  # set the service account to be used, default if left empty
  serviceAccountName: ""
  registry:
    image:
      repository: goharbor/registry-photon
      tag: dev
    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: dev

    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
```

**Comment by SysdigDan** [comment]
Seeing the same issue.

**Comment by ywk253100** [comment]
Please follow the guide https://github.com/goharbor/harbor-helm#add-helm-repository to install the stable version of Harbor chart.

The `dev` images are the development version, we cannot guarantee they work as expected.

**Comment by SvenC56** [comment]
I used the `values.yaml` file which contains the `dev` tag. Not using this `dev` tag everything is working again. 

Thank you.

**Comment by fl-max** [comment]
I'm seeing this issue return with `v1.4.2` of the chart and `v2.1.0` of Harbor (goharbor/harbor-registryctl:v2.1.0).

**Comment by AnavMahajan** [comment]
failed to load storage driver, err:open .

Same error for me also with v1.4.2 of the chart and v2.1.0 of Harbor (goharbor/harbor-registryctl:v2.1.0)
Any Fix for this ?

**Comment by ywk253100** [comment]
@fl-max @AnavMahajan Please refer to https://github.com/goharbor/harbor-helm/issues/747

**Comment by AnavMahajan** [comment]
Thanks a ton @ywk253100

It is working as expected 👍

As Suggested, I have updated the Harbor chart 1.5.0 for OSS and used Harbor 2.1.0
