### ISSUE TITLE
Replace "extensions/v1beta1" to use "networking.k8s.io/v1beta1" on Ingress Template to support Kubernetes v1.16

### ISSUE THREAD

**Issue by ramrodo** [goharbor/harbor-helm#628]
This issue is different from this one:

- [migrate to use apps/v1 for support kubernetes 1.16 #403](https://github.com/goharbor/harbor-helm/issues/403)

Because that issue does not consider **extensions/v1beta1** API deprecated usage found here:

1. https://github.com/goharbor/harbor-helm/blob/v1.4.0/templates/ingress/ingress.yaml#L28
2. https://github.com/goharbor/harbor-helm/blob/master/templates/ingress/ingress.yaml#L91

This `apiVersion` should be replaced for `networking.k8s.io/v1beta1` as described [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) to support Kubernetes v1.16.

Actually I didn't identify a specific issue that breaks the functionality of this Chart, but that API version should be replaced for full support Kubernetes v1.16.

**Comment by reasonerjt** [comment]
@ramrodo please update the pr as suggested in the comment and we can resolve this issue.

**Comment by ramrodo** [comment]
Sure! Sorry for the delay. Let me update it today.
