### ISSUE TITLE
PVC's for internal DB and redis not deleted when uninstalling

### ISSUE THREAD

**Issue by jsuchome** [goharbor/harbor-helm#633]
Setting persistence.resourcePolicy to empty value in the chart should mean that PVC's are deleted during a helm delete operation.
However PVC's for DB and redis are not deleted, although they are created by harbor chart (they are marked as type: internal

This kubernetes issue might be related: https://github.com/kubernetes/kubernetes/issues/55045

**Comment by jsuchome** [comment]
Hm, additionally to the discussion in upstream kubernetes, there's a discussion about it in helm, maybe offering some extra option in the future: https://github.com/helm/helm/issues/5156

However neither of these solution is near. Also, it is not (as I originally assumed) a bug in the helm chart itself. One thing that could be done on helm chart level is update the comment around resourcePolicy option so that it will state explicitly that the automatic deletion does not apply to database and redis components.

**Comment by MinerYang** [comment]
Close by merged
