### ISSUE TITLE
Jobservice GC invalid redis URL scheme

### ISSUE THREAD

**Issue by theSuess** [goharbor/harbor-helm#65]
When trying to perform GC, the jobservice produces the following log:
```
2018-10-23T07:41:04Z [INFO] the readonly request has been sent successfully
2018-10-23T07:41:04Z [INFO] start to run gc in job.
2018-10-23T07:41:04Z [ERROR] [job_logger.go:82]: failed to connect to redis invalid redis URL scheme: 
2018-10-23T07:41:04Z [INFO] the readonly request has been sent successfully
```
My generated configmap looks like this:
```.yaml
protocol: "http"
port: 8080
worker_pool:
  workers: 50
  backend: "redis"
  redis_pool:
    redis_url: "harbor-redis:6379/1"
    namespace: "harbor_job_service_namespace"
logger:
  path: "/var/log/jobs"
  level: "DEBUG"
  archive_period: 14
admin_server: "http://harbor-adminserver"
```
It seems like the redis url is empty. Is there maybe somewhere else the redis_url must be specified?

**Comment by ywk253100** [comment]
Are you using the latest code of Harbor chart?

**Comment by theSuess** [comment]
I've rewritten the chart to an openshift template 1:1 so it should be the latest version. Sorry if it's caused by my rewrite and therefore not really your issue. Just wanted to know if this kind of problem has occurred at any time before.

**Comment by theSuess** [comment]
Thanks, I seemed to have missed this. This fixes the issue
