### ISSUE TITLE
Dose ingress.host.core and externalURL support multi domain？

### ISSUE THREAD

**Issue by hwdef** [goharbor/harbor-helm#650]
I want to use multi domains to access harbor. 

I found [ingress-nginx server-alias](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#server-alias) is support this. Dose harbor-helm support it ?

How should I modify value.yaml?

**Comment by dntosas** [comment]
got same question ^^ +1

**Comment by hwdef** [comment]
@dntosas 
I don't know if harbor supports, so I create a [issue](https://github.com/goharbor/harbor/issues/12396) in harbor. 
We can keep following it
