### ISSUE TITLE
Habror 2.0.1 pushed on release branch 1.4 but not yet published on Harbor Helm Hub

### ISSUE THREAD

**Issue by dntosas** [goharbor/harbor-helm#651]
Hello people!

We got a commit in https://github.com/goharbor/harbor-helm/tree/1.4.0 which bumps Harbor to `2.0.1` but not a release of the Helm Chart v1.4.1 so we can use it from upstream.

Are any plans to do so?

**Comment by reasonerjt** [comment]
It will be pushed, after verifications.

**Comment by ywk253100** [comment]
Closing as 1.4.1 is already released
