### ISSUE TITLE
Harbor Core LOG_LEVEL not taking effect via Helm chart

### ISSUE THREAD

**Issue by DandyDeveloper** [goharbor/harbor-helm#652]
I feel like I'm being stupid here but it looks to me like the default Harbor chart isn't correctly deploying the log_level as `info` in the default.

I see we're setting `LOG_LEVEL` with the following:

```
  LOG_LEVEL: "{{ .Values.logLevel }}"
```

Then bringing this in as a env var. However, I see that my environment is still printing a substantial amount of debug logs. 

Is there another way to get the core log level to a more appropriate `info`?

**Comment by reasonerjt** [comment]
@DandyDeveloper 

I think it is correct that the log level on `harbor-core` is controlled by env var.

Could you please elaborate what were the messages you think were `debug` level?

**Comment by ywk253100** [comment]
Closing as inavtivity
