### ISSUE TITLE
Is the chart available at some public repository / museum?

### ISSUE THREAD

**Issue by smnbbrv** [goharbor/harbor-helm#67]
Hi guys,

is the chart available at some of the public chart repositories (something like https://github.com/helm/charts / kubernetes-charts-incubator.storage.googleapis.com or charts.bitnami.com/bitnami) or the only option to use it is to manually install?

Copying the chart is also OK, but it is so much more user-friendly to have the already published chart...

**Comment by ywk253100** [comment]
No other public chart repositories currently.

**Comment by smnbbrv** [comment]
Why is it closed? As for me it is an issue

**Comment by ywk253100** [comment]
@smnbbrv Let's keep it open to track the work and welcome contribution.

**Comment by jimangel** [comment]
@ywk253100 @smnbbrv - I would be happy to move this chart to https://github.com/helm/charts but I think it would be an issue to have 2 separate charts (https://github.com/goharbor/harbor-helm and helm/charts) that are "supported."

Is the harbor community / team open to moving the charts completely to helm/charts?

This repo could be shut down and redirected to the the helm chart. We should still be able to allow the same maintainers access to contribute there instead.

**Comment by draeron** [comment]
i would suggest publishing the chart to the new helm hub repository

https://hub.helm.sh/

**Comment by jimangel** [comment]
> i would suggest publishing the chart to the new helm hub repository

I agree. If you look at the actual integration with [helm hub](https://github.com/helm/hub/blob/master/config/repo-values.yaml) it's based on chart repositories vs strait up "single" charts. If I were to integrate harbor-helm with https://github.com/helm/charts it would automatically be pulled into helm hub via the first line:
```
    # Helm hosted repositories
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
```

pinging @ywk253100 - do I have approval to move forward?

**Comment by ywk253100** [comment]
@jimangel Thanks for your suggestion. I know nothing about the contribution flow on helm/charts so I need to do some invetigation first and will discuss here later.

**Comment by ywk253100** [comment]
@jimangel I agree with @draeron to add Harbor chart to helm hub. In this way, we can keep everything the same with before. 
As helm hub needs a chart repository, we can leverage the capability of goharbor.github.io to make it a chart repository just like https://github.com/helm/hub/pull/50 did.

**Comment by ywk253100** [comment]
@kfox1111 Let's use this issue to track moving Harbor chart to one public repository.
@jimangel @kfox1111 Do you guys have any interests to do the work?

**Comment by kfox1111** [comment]
Yeah, I can help with that.

I've automated the packaging/release/integration with travis for a few other projects. I see a trivis file in the harbor repo.

So, I think we need 3 things to get it set up:
1. could we get travis setup for this repo?
2. we need a new repo for storing the packages/repo index.
3. an account token loaded into travis for git pushing to the new repo.

**Comment by paulczar** [comment]
There's a tool we're working on in the helm community called [chart-releaser](https://github.com/helm/chart-releaser) that utilizes github releases and github pages to host helm repos in github.  I would recommend using that for this project as it keeps things very simple.

**Comment by kfox1111** [comment]
I'm unfamiliar with that tool. @paulczar, if you want to do the implementation with chart-releaser, go for it. Seems like a good tool.

**Comment by ywk253100** [comment]
Closing this issue as the Harbor chart has been published to helm hub.
