### ISSUE TITLE
registryctl container gets unneeded arguments on start

### ISSUE THREAD

**Issue by jsuchome** [goharbor/harbor-helm#679]
Helm chart passes to registryctl container the same argument as to registry container:
https://github.com/goharbor/harbor-helm/blob/1.4.0/templates/registry/registry-dpl.yaml#L160

(args: ["serve", "/etc/registry/config.yml"])

However, it's unnecessary registryctl does not use any arguments. It seems obvious this is an copy-paste error.

**Comment by jsuchome** [comment]
See https://github.com/goharbor/harbor-helm/pull/665 for a fix

**Comment by reasonerjt** [comment]
Closing as #665 has been merged.
