### ISSUE TITLE
Use DB container for init container

### ISSUE THREAD

**Issue by jsuchome** [goharbor/harbor-helm#681]
There's no need to need extra busybox container for the database "change-permission-of-directory"  init container. Well, there would be one - init container needs to run as root so that it actually can change the permissions.

However this could be achieved by `runAsUser: 0` securityContext and then it's possible to use the same DB container for init container, overriding the fact that normally it would be run as postges user.

What's more: this way the init container already knows UID:GID of postgres user and group and so there's no need to provide explicit UID:GID numbers in the helm chart, instead, it's possible to do `chown -R postgres:postgres /var/lib/postgresql/data`

See https://github.com/goharbor/harbor-helm/pull/667 for a fix

**Comment by reasonerjt** [comment]
closing this as #667 is merged.
