### ISSUE TITLE
harbor-core seems in a bad state after upgrading

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor-helm#686]
Please see https://github.com/goharbor/harbor/issues/12645 which had a response from goharbor that suggested this is  a helm chart issue.

**Comment by reasonerjt** [comment]
The original chart version is a bit old (1.2.x) 

And the override values may not be sufficient for a successful upgrade.

I suggest you go through the values and manually insert the values into the values.yaml of v1.4.x, then use that values.yaml for upgrade.
