### ISSUE TITLE
Configure Garbage Collection scheduling in helm chart

### ISSUE THREAD

**Issue by Kevin-Bannier** [goharbor/harbor-helm#694]
Hello,

To my knowledge, there is no way to configure a GC schedule in helm chart. So in my case, I need to use web interface or API after the harbor startup to configure GC.
It would be nice to configure a GC schedule in helm chart, with the option `Allow garbage collection on untagged artifacts`, instead of configure it after startup

**Comment by ywk253100** [comment]
Yes, you have to call the API to configure the GC, it cannot be set via Harbor chart
