### ISSUE TITLE
Notary server URL

### ISSUE THREAD

**Issue by CYBERBUGJR** [goharbor/harbor-helm#695]
Hello,

I've installed a fresh version of Harbor v 2.0.2 on my Kubernetes cluster. 
I would like to use Notary to sign my images before i push them on the registry but my docker client doesn't seem to like the fact that notary is served on an other URL than my registry.
I checked the doc about setting up notary for client but i looks like it had been made on compose not on  kube. The notary address is the same as the registry. In my case, i've got harbor.mydomain.com and notary.mydomain.com.
If you have any ideas/tricks ?

Thanks for help.

**Comment by dkulchinsky** [comment]
@CYBERBUGJR you can instruct Docker that the trust server is at a different endpoint:
```
export DOCKER_CONTENT_TRUST_SERVER=https://<notary.domain>[:port]
```

**Comment by CYBERBUGJR** [comment]
Thank you for your reply, it works fine
