### ISSUE TITLE
Add harbor-exporter in the Chart

### ISSUE THREAD

**Issue by c4po** [goharbor/harbor-helm#707]
Can we add the [prometheus exporter](https://github.com/c4po/harbor_exporter) to the chart?

**Comment by ywk253100** [comment]
It's in our roadmap

**Comment by dntosas** [comment]
> It's in our roadmap

@ywk253100 its on `harbor` roadmap as a project or on the `harbor-helm` chart roadmap? if it is on the roadmap for the chart, maybe we can help with that ^^ cc @c4po

**Comment by reasonerjt** [comment]
In Harbor OSS v2.2.0 (consumed by chart v1.6.0) 

There will be a solution for integration with prometheus, as fir the way to expose that on chart, @ninjadq can provide more details

**Comment by ywk253100** [comment]
PR https://github.com/goharbor/harbor-helm/pull/818 merged, closing this issue
