### ISSUE TITLE
Documentation doesn't mention setting ssl annotations in expose.ingress.annotations

### ISSUE THREAD

**Issue by user-name-is-taken** [goharbor/harbor-helm#717]
To turn TLS off, the documentation mentions setting `expose.tls.enabled=false`, but you also have to set `expose.ingress.annotations.ingress.kubernetes.io/ssl-redirect: "false"` and `expose.ingress.annotations.nginx.ingress.kubernetes.io/ssl-redirect: "false"`

**Comment by aureq** [comment]
To follow up on @user-name-is-taken comment, the documentation should cover the following 3 scenarios.

1. the user is using SSL/TLS and so values should be set to `true`
2. the user is not using SSL/TLS at all and so values should be set to `false`
3. the user is using a SSL/TLS termination endpoint that's in front of the ingress and so `expose.tls.enabled` should be `false` while `expose.ingress.annotations.ingress.kubernetes.io/ssl-redirect` and/or `expose.ingress.annotations.nginx.ingress.kubernetes.io/ssl-redirect` should be set to `true`.

As a side note, I'm in the 3rd scenario and it works perfectly fine with the values I provided for that scenario.
