### ISSUE TITLE
Harbor portal login error, Status Code: 403 Forbidden

### ISSUE THREAD

**Issue by jacky68147527** [goharbor/harbor-helm#724]
Status Code: 403 Forbidden.
Reponse {"errors":[{"code":"FORBIDDEN","message":"CSRF token invalid"}]}

Helm install harbor parameters: 
`helm install odp-harbor  --set expose.type='loadBalancer'  --set persistence.enabled=false --set expose.tls.enabled=false  --set externalURL='' harbor/harbor`

All k8s resources of harbor are running.

Please help me where is the problem. thanks~

**Comment by phuongleeo** [comment]
```
Format: protocol://domain[:port]. Usually:

if expose the service via Ingress, the domain should be the value of expose.ingress.hosts.core
if expose the service via ClusterIP, the domain should be the value of expose.clusterIP.name
if expose the service via NodePort, the domain should be the IP address of one Kubernetes node
if expose the service via LoadBalancer, set the domain as your own domain name and add a CNAME record to map the domain name to the one you got from the cloud provider
```
did you try to set your domain to externalURL? or try removing `externalURL` ?

**Comment by jacky68147527** [comment]
@phuongleeo Thank you, when i set externalURL to my own domain name, it's worked!

**Comment by worming004** [comment]
For any readers, ensure to use the same protocol than externalURL. I've setted up https in the variable, and encountered the problem because I was using http on my browser. Using the same protocol make it works
