### ISSUE TITLE
Where are projects stored?

### ISSUE THREAD

**Issue by itsecforu** [goharbor/harbor-helm#728]
Hello!
After some problems in the cluster, I restored the tool to work. All users, settings remained unchanged. Only projects are missing. Now I see that these projects remain on the same node and on the mounted volume under the registry. Tell me how to restore them?

**Comment by ywk253100** [comment]
Could you open the issue on the OSS Harbor repo https://github.com/goharbor/harbor/issues?
This isn't related with Harbor chart, I'm closing it
