### ISSUE TITLE
Chart for Harbor v2.1.0

### ISSUE THREAD

**Issue by jkroepke** [goharbor/harbor-helm#736]
Hi!

Please provide a Chart version for Harbor release v2.1.0.

https://github.com/goharbor/harbor/releases/tag/v2.1.0

Thanks.

https://github.com/goharbor/harbor-helm/pull/735

**Comment by ywk253100** [comment]
We are doing some internal end to end testing for the Harbor chart 1.5.0(OSS Harbor 2.1.0), once it is done the chart will be released.

**Comment by ywk253100** [comment]
The chart 1.5.0 is released, closing this issue

**Comment by jkroepke** [comment]
Thanks!
