### ISSUE TITLE
registry_config property missing in v1.4.2

### ISSUE THREAD

**Issue by fl-max** [goharbor/harbor-helm#742]
The `registry_config` property is missing from v1.4.2 of this Helm Chart (See [here](https://github.com/goharbor/harbor-helm/blob/v1.4.2/templates/registry/registry-cm.yaml#L183)). It was [committed](https://github.com/goharbor/harbor-helm/commit/ee8e41d7d8da9fb9db783975b8a86e739316f82a) in July and in the [master branch](https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-cm.yaml#L224) but seems to not have made it into the v1.4.x release.

This will cause a config [issue](https://github.com/goharbor/harbor/issues/13120) with v2.1.0 of registryctl. May be related to [#736](https://github.com/goharbor/harbor-helm/issues/736). Is the Helm Chart tightly coupled to the App version?

**Comment by ywk253100** [comment]
@fl-max Yes, please use the release version of Harbor chart which is coupled to a specific OSS Harbor version. 
The chart for Harbor 2.1.0 will be available once we finishing the end to end testing, let's track it in https://github.com/goharbor/harbor-helm/issues/736.

Closing this issue

**Comment by fl-max** [comment]
It is working with `v1.5.0` of the chart. It may be worth noting that `v1.5.0` has breaking changes, specifically:
* `expose.tls.secretName` -> `expose.tls.certSource` + `expose.tls.secret.secretName`
* `core.livenessProbe.initialDelaySeconds` -> removed
  * `core.startupProbe.initialDelaySeconds` was added but this is still an alpha feature and not enabled by default
* `database.internal.initContainerImage` -> removed
* `redis.external.host` + `redis.external.port` -> `redis.external.addr`
