### ISSUE TITLE
internal redis as deployment instead statefulset

### ISSUE THREAD

**Issue by kfirfer** [goharbor/harbor-helm#746]
Hello
In my opinion internal redis could be deployment instead statefulset if there is no persistent-volume attached to him

What do you think ?

**Comment by ywk253100** [comment]
In most cases, the statefulset is the correct choice for Redis. 
Is there any reason why you want deployment rather than statefulset?

**Comment by kfirfer** [comment]
I dont have specific scenario in mind 

But its sounds best practice to use deployment over statefulset when the pods is epthermal

**Comment by DandyDeveloper** [comment]
Redis is a stateful component that uses the volume (WAL) to keep track of things when an unexpected restart of the process has occurred. 

If you restart Redis without a PVC attached, you'll lose all the keys you had. 

@kfirfer All pods in Kubernetes are ephemeral. However, state is still managed by the underlying service running within those pods. That is why Redis is a Statefulset.

**Comment by kfirfer** [comment]
@DandyDeveloper 
Redis can persist , or as a cache layer. or both.
but when you want setup redis as a cache service , uses only RAM (for highest throughput), you don't need statefulset object.

**Comment by DandyDeveloper** [comment]
@ywk253100 Even then, Redis will still want to use a WAL for persisting that cache through restarts. 

Yes you could have it the way you describe, in which case the chart could be adjusted to specifically enable/disable persistence on the STS (Rather then moving to a Deployment).

But even then, I'm not sure why you'd want that over having persistence?

**Comment by kfirfer** [comment]
In my schenario I'm using other solutions for persistency , such as mysql & mongodb , And Im using redis only as a fast ram cache , when the pod is restarted, I don't mind about the loss of data

**Comment by DandyDeveloper** [comment]
@kfirfer Right, but what's the issue with having it? It sounds like you're asking for a solution to a non-issue.

**Comment by kfirfer** [comment]
Sorry , might be missunderstanding , didnt meant theres an issue , it's only proposal ;-)

**Comment by Kilz78** [comment]
@ywk253100 , Hello, I would like to set the HA for Harbor because it will be used for our production. 
But with Redis as a statefulset, How can we set it ? 

If redis is down, harbor is down;
