### ISSUE TITLE
CrashLoopBackOff registryctl issue with new harbor version 2.1.0 and helm chart version 1.4.2

### ISSUE THREAD

**Issue by AnavMahajan** [goharbor/harbor-helm#747]
CrashLoopBackOff registryctl 
 [ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:open : no such file or directory

**Comment by ywk253100** [comment]
Please use the Harbor chart 1.5.0 for OSS Harbor 2.1.0 instead

**Comment by AnavMahajan** [comment]
Thanks a ton @ywk253100 

It is working as expected 👍 

As Suggested, I have updated the Harbor chart 1.5.0 for OSS and used Harbor 2.1.0

**Comment by AnavMahajan** [comment]
Thanks a ton @ywk253100 

It is working as expected 👍 

As Suggested, I have updated the Harbor chart 1.5.0 for OSS and used Harbor 2.1.0

**Comment by AnavMahajan** [comment]
> Please use the Harbor chart 1.5.0 for OSS Harbor 2.1.0 instead

Thanks a ton @ywk253100 

It is working as expected 👍 

As Suggested, I have updated the Harbor chart 1.5.0 for OSS and used Harbor 2.1.0
