### ISSUE TITLE
Harbor 2.1.0 : Vulnerability Settings in Proxy Cache Projects not working

### ISSUE THREAD

**Issue by AnavMahajan** [goharbor/harbor-helm#748]
Selected the Prevent vulnerable images from running checkbox to prevent vulnerable images under the **proxy cache**  project from being pulled.

But still i am able to pull the images from **proxy cache** project besides having high vulnerabilities which shouldn't be the case.

![image](https://user-images.githubusercontent.com/53244136/94033512-6077a700-fe04-11ea-9651-d6da5fad0c62.png)

![image](https://user-images.githubusercontent.com/53244136/94033932-c95f1f00-fe04-11ea-8b63-97ec5bb1e4d4.png)
 
![image](https://user-images.githubusercontent.com/53244136/94034035-e09e0c80-fe04-11ea-9023-b1a41d359aa4.png)

**Expected Behaviour** : Harbor Should restrict the pull from proxy cache project in case of Vul

**Comment by AnavMahajan** [comment]
Any Update on this. This can be a important feature as we can restrict the CICD build based on the scan's result.

**Comment by ywk253100** [comment]
Could you open the issue on the OSS Harbor repo https://github.com/goharbor/harbor/issues?
This isn't related with Harbor chart, I'm closing it
