### ISSUE TITLE
Problems with OIDC groups

### ISSUE THREAD

**Issue by gabrilabs75** [goharbor/harbor-helm#751]
Hi all! 
I'm trying to configure OIDC groups in my harbor configuration but it seems not working properly. I try to create a group ("test-group" for example) with the same definition on my OIDC providers (keycloak) and join via keycloak some users to this group. I've created new project "test-prj" and I've assigned the permission to view this project @ group above. 
When I logged in with a user belonging to "test-group" I didn't see the project expected "test-prj". 
Any suggestions? 
Thanks in advance

**Comment by gabrilabs75** [comment]
I've seen that similar issue was closed

https://github.com/goharbor/harbor/issues/10419#issuecomment-590165308

But I don't undestand what kind of value I have to insert as "Token Claim Name" in Keycloak client configuation.

**Comment by gabrilabs75** [comment]
Hi all,
I think i solved it long ago passing the default "Token Claim Name"

Regards,
Gabriele

**Comment by panteparak** [comment]
__

> Hi all, I think i solved it long ago passing the default "Token Claim Name"
> 
> Regards, Gabriele

How did you solve this. can you walkthrough the steps?
