### ISSUE TITLE
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "startupProbe" in io.k8s.api.core.v1.Container

### ISSUE THREAD

**Issue by ksdeepak93** [goharbor/harbor-helm#754]
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "startupProbe" in io.k8s.api.core.v1.Container

If Kubernetes is returning the error, this is likely due to startupProbe not being a valid field in Kubernetes v1.14 (the version of my AKS instance).
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#container-v1-core
It looks like it was added in Kubernetes v1.16. 

kube: 1.15: eks

Could we get some help

**Comment by ywk253100** [comment]
The Kubernetes cluster 1.16+ is needed for Harbor chart currently as mentioned in the README https://github.com/goharbor/harbor-helm#prerequisites

**Comment by ksdeepak93** [comment]
Above worked with upgrade to 1.16
Forgot to mention here.

**Comment by jkroepke** [comment]
startupProbe could be disabled now.

https://github.com/goharbor/harbor-helm/pull/781
