### ISSUE TITLE
harbor behind Proxy: problem

### ISSUE THREAD

**Issue by osaffer** [goharbor/harbor-helm#755]
Hi,

The kubernetes Cluster is running behind a corporate proxy.
Harbor was installed inside the kubernetes through HELM.
To access harbor, I configured istio, and I can access istio through TLS. 
I can docker login , and push the image.

But , the repository is not visible in the project inside harbor. 
I can see the push worked : https://my-hostname/v2/_catalog

in log of registry pod, I have the following error looping : 

evel=warning msg="httpSink{http://harbor-core/service/notifications} encountered too many errors, backing off" 
time="2020-09-30T14:28:45.543033316Z" level=error msg="retryingsink: error writing events: httpSink{http://harbor-core/service/notifications}: response status 404 Not Found unaccepted, retrying" 
time="2020-09-30T14:28:45.543056877Z" level=warning msg="httpSink{http://harbor-core/service/notifications} encountered too many errors, backing off" 

in core pod:

nomatch| POST     /service/notifications
2020-09-30T14:29:17Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id e312a6b4-32a0-4201-b07c-6e4aa250c06c to the logger for the request POST /service/notifications
2020-09-30T14:29:17Z [DEBUG] [/server/middleware/security/unauthorized.go:29][requestID="e312a6b4-32a0-4201-b07c-6e4aa250c06c"]: an unauthorized security context generated for request POST /service/notifications

in notary pod :+1: 
020/09/30 13:56:57 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.26.46.239:7899: connect: connection refused"; Reconnecting to {harbor-notary-signer:7899 <nil>}

in notary-signer:
Server.Serve failed to complete security handshake from "172.20.1.1:47164":

Maybe someone has experienced a harbor installation behind proxy ?

Thanks for your help

**Comment by btsken** [comment]
I got the same issue

**Comment by osaffer** [comment]
I decided to not enable the notary

But I have still : 

level=error msg="retryingsink: error writing events: httpSink{http://harbor-core/service/notifications}: response status 404 Not Found unaccepted, retrying"

Which ingress do you use ?

I think one moment, I gonna to stop the deployment on Kubernetes, documentation is not clear.

I dont understand also why the docker user is the one defined in values file, and wwhy I cannot use the user created in Harbor UI.

**Comment by btsken** [comment]
I use istio too.

**Comment by osaffer** [comment]
[harbor_istio.yaml.txt](https://github.com/goharbor/harbor-helm/files/5346005/harbor_istio.yaml.txt)
This is my configuratio, may I see yours ?

**Comment by ywk253100** [comment]
@osaffer Please use the latest version of the harbor chart

**Comment by danielzhanghl** [comment]
i got strange error when deploy harbor with istio, if the gateway is listen on 443, then everything is fine, like portal/ docker cli push and pull image,

but if I use anther gateway port, like 30006, the portal is fine, docker cli login is fine, but push image will fail, the cli still want to reach 443 port. is anyone use other port than 443 successfully ?

**Comment by danielzhanghl** [comment]
like below error:

 docker login https://ctl-1-harbor.com:30006/ -u admin -p  24zC
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded


docker   push  ctl-1-harbor.com:30006/library/ms:1.0
The push refers to repository [ctl-1-harbor.com:30006/library/ms]
f072c1b71989: Pushing [==================================================>]  4.362MB/4.362MB
90f767bdc025: Retrying in 5 seconds
342e4668db2a: Retrying in 1 second
706f1d220052: Retrying in 5 seconds
2c30600325be: Retrying in 5 seconds
df64d3292fd6: Waiting
dial tcp 1.5.4.9:**443**: connect: connection refused

**Comment by ninjadq** [comment]
@danielzhanghl  did you configured the external URL to https://ctl-1-harbor.com:30006/ ?

**Comment by danielzhanghl** [comment]
yes, I did, the docker login is fine, and portal is fine, but push failure, very strange...

**Comment by danielzhanghl** [comment]
it seems some error in my nginx configuration...
