### ISSUE TITLE
How to configuration LDAP / SMTP in chart

### ISSUE THREAD

**Issue by gprossliner** [goharbor/harbor-helm#757]
Hi Everyone,

I'm looking for a way to specify the configuration values for LDAP / SMPT. I don't see any explicit parameter (like ldap_base_dn for example) listed in Values.yaml, nor I find an "extraConfigurationOptions" parameter, which allows to to pass any additional configuration setting.

Can anyone tell me, if there is really no way to specify additional configuration settings by using the Helm Chart.

Thanks

**Comment by sharkymcdongles** [comment]
Currently it seems not doable. Only option I imagine is to use the bitnaml chart that uses an external database or use an external database here that has a patch as a posthook to set the values.

**Comment by nedhanks** [comment]
We set up ldap in the ui "Administration -> Configuration".

**Comment by sharkymcdongles** [comment]
I think he wants it as part of deployment in values file.

**Comment by gprossliner** [comment]
Hi folks! First it seems that it's even not possible to provide the configuration when using Manifests only. The related Configuration-Settings are stored in the Database, and not fetched from files. So one would need to provision this manually, or by using the api. Can you confirm this?

**Comment by reasonerjt** [comment]
@gprossliner 
Correct, you need to call the API to make update in configuration regarding LDAP/SMTP.

**Comment by sharkymcdongles** [comment]
Yes this is why I said the only way to do it is with a posthook in the helm
chart or custom built images.

**Comment by reasonerjt** [comment]
Closing as we have clarified issue and there's no more actions to take.

**Comment by abdennour** [comment]
#977  #978
