### ISSUE TITLE
ChartMuseum times out - 500 error on list charts

### ISSUE THREAD

**Issue by jonhatallasf** [goharbor/harbor-helm#758]
```harbor-alpha-harbor-core-55f97cb956-h7sgv core 2020-10-08T18:24:04Z [ERROR] [/server/error/error.go:53]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"fail to list charts: get content failed: send request GET /api/docker/charts failed: Get http://harbor-alpha-harbor-chartmuseum/api/docker/charts: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}]}```

This happens on most pages in the UI.  This failure cases a 30s lag in the UI - making it unusable
```harbor-alpha-harbor-core-55f97cb956-6c864 core 2020/10/08 18:24:04.530 [D] [middleware.go:52]  |    10.43.3.200| 500 | 30.00553635s|   match| GET      /api/chartrepo/docker/charts   r:/api/chartrepo/:repo/charts```

**Comment by ywk253100** [comment]
How many charts in the `docker` repository?

**Comment by jonhatallasf** [comment]
0 charts in the docker repository
50 or so in the charts repository

**Comment by ywk253100** [comment]
Seems there is some issues in the communication between the `core` and `chartmuseum` in your env

**Comment by jonhatallasf** [comment]
@ywk253100 Is there a way to address this or maybe provide more information that could help solve this??

My chartmuseum installation is rather simple, and has no deviation from the normal installation (outside of using s3)

**Comment by ywk253100** [comment]
You can try to curl the API inside the `core` container

BTW, the chartmuseum may be deprecated in the future release and instead users can push charts into the registry as OCI artifact. Helm v2 has already support that
