### ISSUE TITLE
core server alway error

### ISSUE THREAD

**Issue by hawking-lab** [goharbor/harbor-helm#759]
2020-10-10T04:04:16Z [INFO] [/core/main.go:162]: initializing configurations...

2020-10-10T04:04:16Z [INFO] [/core/config/config.go:84]: key path: /etc/core/key

2020-10-10T04:04:16Z [INFO] [/core/config/config.go:61]: init secret store

2020-10-10T04:04:16Z [INFO] [/core/config/config.go:64]: init project manager

2020-10-10T04:04:16Z [INFO] [/core/config/config.go:96]: initializing the project manager based on local database...

2020-10-10T04:04:16Z [INFO] [/core/main.go:164]: configurations initialization completed

2020-10-10T04:04:16Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-harbor-harbor-database port-5432 database-registry sslmode-"disable"

2020-10-10T04:04:16Z [INFO] [/common/dao/base.go:70]: Register database completed

2020-10-10T04:04:16Z [FATAL] [/core/main.go:174]: failed to migrate: please upgrade to version 1.10 first

**Comment by ywk253100** [comment]
`2020-10-10T04:04:16Z [FATAL] [/core/main.go:174]: failed to migrate: please upgrade to version 1.10 first`
As the log said, you need to upgrade to OSS Harbor 1.10(Harbor chart 1.3.0)

**Comment by InfluencerNGZK** [comment]
I am using kubernetes 1.16.2 to deploy harbor v2.1.0, found the sam error.
```sh
2020-10-10T04:04:16Z [FATAL] [/core/main.go:174]: failed to migrate: please upgrade to version 1.10 first
```
Switch to harbor v1.10.0 fixed my issue.
I am curious why can`t I deploy harbor v2.1.0 via k8s 1.16.2.

**Comment by InfluencerNGZK** [comment]
> I am using kubernetes 1.16.2 to deploy harbor v2.1.0, found the same error in the logs of `harbor-core`.
> 
> ```shell
> 2020-10-16T14:51:15Z [FATAL] [/core/main.go:174]: failed to migrate: please upgrade to version 1.10 first
> ```
> 
> Switch to harbor v1.10.0 fixed my issue.
> I am curious why can`t I deploy harbor v2.1.0 via k8s 1.16.2.

Disable trivy fixed

**Comment by kasim457** [comment]
> 
> 
> > I am using kubernetes 1.16.2 to deploy harbor v2.1.0, found the same error in the logs of `harbor-core`.
> > ```shell
> > 2020-10-16T14:51:15Z [FATAL] [/core/main.go:174]: failed to migrate: please upgrade to version 1.10 first
> > ```
> > 
> > 
> > Switch to harbor v1.10.0 fixed my issue.
> > I am curious why can`t I deploy harbor v2.1.0 via k8s 1.16.2.
> 
> Disable trivy fixed

@InfluencerNGZK ,  I also experienced same error message in our setup.  How did you fix this error?

**Comment by InfluencerNGZK** [comment]
> > > I am using kubernetes 1.16.2 to deploy harbor v2.1.0, found the same error in the logs of `harbor-core`.
> > > ```shell
> > > 2020-10-16T14:51:15Z [FATAL] [/core/main.go:174]: failed to migrate: please upgrade to version 1.10 first
> > > ```
> > > 
> > > 
> > > Switch to harbor v1.10.0 fixed my issue.
> > > I am curious why can`t I deploy harbor v2.1.0 via k8s 1.16.2.
> > 
> > 
> > Disable trivy fixed
> 
> @InfluencerNGZK , I also experienced same error message in our setup. How did you fix this error?

What kind of persistent storage you are using? In my situation it seems to be the problem of  `harbor-portal` pod. After I change the persistent storage for database, things went well.
You can also delete and then pull all the harbor images again before deploying.
Hope it works : )

**Comment by kasim457** [comment]
We are using rook-ceph for persistent storage. what did you change for `harbor-portal`

**Comment by InfluencerNGZK** [comment]
Since I am using [csi-nfs](https://github.com/kubernetes-csi/csi-driver-nfs), I just create the NFS deployment and service for `harbor-portal` which mentioned in [existing-claim](https://github.com/goharbor/harbor-helm#configure-the-way-how-to-persistent-data).

**Comment by huoyingdk** [comment]
This guide covers upgrade and migration to version 2.3.0. This guide only covers migration from v1.10.x and later to the current version. If you are upgrading from an earlier version, refer to the migration guide in the release-1.10.0 branch to upgrade to v1.10.x first, then follow this guide to perform the migration to this version.
