### ISSUE TITLE
deploy harbor helm failed 

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor-helm#775]
when i deploy harbor in k8s it shows:
cdc-harbor-harbor-chartmuseum-66f48b5499-vjbcn     1/1     Running             0          102m
cdc-harbor-harbor-clair-775f476ffb-n8z22           2/2     Running             5          102m
cdc-harbor-harbor-core-6d974b869d-x9p86            1/1     Running             2          102m
cdc-harbor-harbor-database-0                       1/1     Running             0          102m
cdc-harbor-harbor-jobservice-654cdc8fdd-vn2k2      1/1     Running             1          102m
cdc-harbor-harbor-nginx-6c7996bd99-8svv6           0/1     CrashLoopBackOff    25         102m
cdc-harbor-harbor-notary-server-66f4864979-v8b87   1/1     Running             3          102m
cdc-harbor-harbor-notary-signer-554d6f958b-tpkrc   1/1     Running             3          102m
cdc-harbor-harbor-portal-d799b95b5-zfvxd           1/1     Running             0          102m
cdc-harbor-harbor-redis-0                          1/1     Running             0          102m
cdc-harbor-harbor-registry-7b447846c4-bbmvx        0/2     ContainerCreating   0          102m
cdc-harbor-harbor-trivy-0                          1/1     Running             0          102m

when check cdc-harbor-harbor-nginx-6c7996bd99-8svv6 pod   the error message shows:

2020/10/28 07:10:25 [emerg] 1#0: cannot load certificate "/etc/nginx/cert/tls.crt": BIO_new_file() failed (SSL: error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:filename(libz.so): libz.so: cannot open shared object file: No such file or directory error:25070067:DSO support routines:DSO_load:could not load the shared library error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/cert/tls.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/nginx/cert/tls.crt": BIO_new_file() failed (SSL: error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:filename(libz.so): libz.so: cannot open shared object file: No such file or directory error:25070067:DSO support routines:DSO_load:could not load the shared library error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/cert/tls.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by alsoxavi** [comment]
Could you solve this issue? I'm having the same one right now =(
