### ISSUE TITLE
Harbor API not accessible with ingress-nginx 0.41.0

### ISSUE THREAD

**Issue by stefannica** [goharbor/harbor-helm#783]
The ingress-nginx 0.41.0 version released yesterday makes the harbor API inaccessible. For example, the UI login yields an `Invalid user name or password` error, with no relevant logs in the Harbor core component. Contacting the API directly returns 404 errors.

Note that the UI is still accessible through the ingress, it's just the URL paths leading to other components that are not.

**Comment by stefannica** [comment]
Looking at the [ingress-nginx changelog](https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md), support for the `Prefix` pathType was introduced in 0.41.0: https://github.com/kubernetes/ingress-nginx/pull/6389/. This probably changes the `ImplementationSpecific` default for ingress-nginx to act the same as `Prefix`, as covered in the [kubernetes ingress path types documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types). 

The paths that Harbor sets up for the ingress all have a trailing `/`, which do not really conform to the default `Prefix` ingress-nginx `pathType` specification. Removing those trailing `/` fixes the problem.

**Comment by stefannica** [comment]
One could also argue that this is a backwards-incompatible change introduced with ingress-nginx 0.41.0. However, the ingress paths set up by Harbor should still be modified to conform to [the kubernetes ingress `pathType` specification](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types).

**Comment by dirien** [comment]
hi @stefannica, i can confirm this. Ran yesterday in the same problem between the release of ingress-nginx. So one cluster worked, the other two not! 

made me crazy !

Thanks for your fix and meanwhile i delete the trailing / by hand

**Comment by hamid-elaosta** [comment]
I was just hit by this issue after switching Ingress Controller to NGINX Ingress Controller v0.41.0. For now the solution seems to be to remove the trailing slash from all `path` values in the Harbor ingress (except the lone slash).

**Comment by WebSpider** [comment]
@hamid-elaosta That did it for me too, many thanks! In my first deployment, my admin password didnt seem to work. It turned out I was impacted by this bug.

**Comment by dirkmueller** [comment]
@ywk253100 please also consider backporting that to older helm versions.. it is a pretty  universal problem..

**Comment by jonathantransb** [comment]
I face this error again. The changes from this [commit](https://github.com/goharbor/harbor-helm/commit/42da4e56d19f6d9ba3456b54719dfe75bbfd0023) add the trailing slash to `path`.

**Comment by anibali** [comment]
https://github.com/goharbor/harbor-helm/commit/42da4e56d19f6d9ba3456b54719dfe75bbfd0023 does indeed appear to undo the fix in https://github.com/goharbor/harbor-helm/pull/811. @ywk253100 could you possible comment on this? I am getting 404s when I try to use `/api/` and am wondering if this is the cause.

**Comment by anibali** [comment]
Ah, I was just using the wrong path---it seems like `/api/v2.0/` is what I want, not `/api/`. Sorry for the noise.
