### ISSUE TITLE
Harbor data base pods failed with Bus Error

### ISSUE THREAD

**Issue by tongtongxiaopeng1979** [goharbor/harbor-helm#785]
Harbor Helm Chart: v1.5.1
With huge paged enabled, harbor data base not work with error log:
Bus error               (core dumped) "/usr/bin/postgres" --boot -x0 -F -c max_connections=100 -c shared_buffers=1000 -c dynamic_shared_memory_type=none < "/dev/null" > "/de │

if disable huge page, the issue disappear

BTW: is it possible to configure harbor postgres's hugepage as "off" rather than "try"

**Comment by dageita** [comment]
How to disable huge page config?

**Comment by lijianfeng1993** [comment]
https://github.com/docker-library/postgres/issues/451#issuecomment-871109581

**Comment by leonseng** [comment]
Is there an option to disable hugepage in Harbor database? @ywk253100  @reasonerjt

**Comment by Sycrosity** [comment]
Is there any update on this? I'm stuck in a slight cycle in which i need to create a new image on harbor to run postgresql with hugepages disabled but can't start the harbor registry to upload it due to not having the image... Running k8s on talos linux 1.4.0.
