### ISSUE TITLE
Accessing HarborUI using NodePort indefinitely says "Loading"  

### ISSUE THREAD

**Issue by danishsh** [goharbor/harbor-helm#79]
I have deployed harbor from master branch with service type as NodePort

helm install --name harb-imagerepo . -f values.yaml 
with following changes to values.yaml

externalURL: https://xxx.domain/harbor           --- running External LoadBalancer( HA Proxy) with ssl termination on it.
ingress enabled: false
service.type: NodePort
secretKey: sixteen-digit-key
nginx.tls.enabled:false
Rest everything as default
PVC are getting provisioned using underlying Ceph cluster. There are no 
below are more details
Cluster Info:
![k8s-cluster-details](https://user-images.githubusercontent.com/7964116/48054385-971f8680-e1c6-11e8-95e2-6d3856cfe323.PNG)

List of all pods in running state
![image](https://user-images.githubusercontent.com/7964116/48054494-d77f0480-e1c6-11e8-92bd-cf6689abe93b.png)

List of Service 
![image](https://user-images.githubusercontent.com/7964116/48054552-0006fe80-e1c7-11e8-9e70-04935b803d15.png)

Result of curl

$ curl 10.xxx.1xx.1xx:30002
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>VMware</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico?v=2">
<link rel="stylesheet" href="styles.0a97e5c7dae15939bfca.css"></head>

<body>
    <harbor-app>
        <div class="spinner spinner-lg app-loading">
            **Loading...**
        </div>
    </harbor-app>
<script type="text/javascript" src="runtime.a66f828dca56eeb90e02.js"></script><script type="text/javascript" src="scripts.70b8b612aef2adc60282.js"></script><script type="text/javascript" src="main.e08f87e1596c0c50af39.js"></script></body>

</html>

**Comment by ywk253100** [comment]
Could you open the debug tool of the browser and check that what the page is pending on?

**Comment by danishsh** [comment]
@ywk253100 : 
console of browser says
Failed to load resource: the server responded with a status of 404 (Not Found) runtime.a66f828dca56eeb90e02.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found) main.e08f87e1596c0c50af39.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found) scripts.70b8b612aef2adc60282.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found) main.e08f87e1596c0c50af39.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found) favicon.ico?v=2:1 
Failed to load resource: the server responded with a status of 404 (Not Found) styles.0a97e5c7dae15939bfca.css:1

**Comment by ywk253100** [comment]
Did you install Harbor before? Can you try to clear the cache of the browser and retry again?

**Comment by danishsh** [comment]
@ywk253100 :  yes, I did install and uninstalled harbor many times by now :( 
But Perhaps nothing to do with browser, as curl also give same "Loading" response.
However, i did clean cache of browser and retried...but of no help.

**Comment by danishsh** [comment]
@ywk253100 : I have narrowed down to this observation.
when externalURL is set without path like https://abc.example.com/, the application is accesible from browser and works fine , however if externalURL  is path based like https://abc.example.com/harbor , the context are not prefixed to the resources like csss, js, favicon resulting in 404 error.

**Comment by ywk253100** [comment]
What is the subpath `harbor` in `externalURL ` used for? Did you set up a proxy before Harbor?

**Comment by danishsh** [comment]
@ywk253100 : yes, I have used HA Proxy external LoadBalancer infront of K8s cluster and using NodePort of services. Here harbor is the subpath in externalURL

**Comment by ywk253100** [comment]
Did you configure the proxy to rewrite `https://abc.example.com/harbor` to the URL of Harbor deployed inside Kubernetes? If you did, the path of web resources should not contain `harbor`.

**Comment by danishsh** [comment]
@ywk253100 : Thanks for your input.
However, my requirement is like this 
1. Set External URL as https://abc.example.com/harbor
2. Hence, Resources should be available with /harbor
3. User should be able to visit home/login page of harbor with URL https://abc.example.com/harbor. so, perhaps, no need for proxy to rewrite the url.
Please confirm if harbor supports above requirement?
As per my observation it doesn't seems to work

**Comment by ywk253100** [comment]
No, Harbor doesn't support that.

**Comment by ywk253100** [comment]
Closing this issue, feel free to reopen it.

**Comment by wmullen0** [comment]
> @ywk253100 : Thanks for your input.
> However, my requirement is like this
> 
> 1. Set External URL as https://abc.example.com/harbor
> 2. Hence, Resources should be available with /harbor
> 3. User should be able to visit home/login page of harbor with URL https://abc.example.com/harbor. so, perhaps, no need for proxy to rewrite the url.
>    Please confirm if harbor supports above requirement?
>    As per my observation it doesn't seems to work

Did you find a solution? I am seeing this issue too.
