### ISSUE TITLE
Log rotation options

### ISSUE THREAD

**Issue by khrd** [goharbor/harbor-helm#792]
Hi. As you can see in this picture,
A large amount of pull logs are generated daily in the event log, 
and I'm afraid that these logs will squeeze the disk in the future.

![eventlogs](https://user-images.githubusercontent.com/28554407/99035007-f5f01580-25c1-11eb-8216-08b101362078.png)

The harbor itself has a log rotation setting,
But is there a way to set up log rotation if I installed it using Helm?

## environment

My chart version is here.

```
$ helm list
NAME  	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART       	APP VERSION
harbor	harbor   	1       	2020-04-24 18:19:23.818561 +0900 JST	deployed	harbor-1.3.2	1.10.2
```

**Comment by ywk253100** [comment]
The OSS Harbor installed by docker-compose contains a `log` container to  collect and rotate the logs. 
For the Harbor installed by helm, the log collection and rotate should be the capability of k8s platform, so you can configure it in the cluster level

**Comment by khrd** [comment]
Thank you for your reply.

As you said, I confirmed that there is a container called `harbor-log` in docker-compose.
And in the helm, Harbor’s event log seems to be recorded in postgres.

ex) access_log table:
```
registry=# select * from access_log;
 log_id | username  | project_id | repo_name   | repo_tag | guid | operation |          op_time
--------+-----------+------------+-------------+----------+------+-----------+----------------------------
  22051 | anonymous |         18 | **********  | *******  |      | pull      | 2020-11-13 05:36:23.183554
  22076 | anonymous |         18 | **********  | *******  |      | pull      | 2020-11-13 07:06:25.169161
  22118 | anonymous |         18 | **********  | *******  |      | pull      | 2020-11-13 09:37:02.302444
  22132 | anonymous |         18 | **********  | *******  |      | pull      | 2020-11-13 10:28:30.84112
  22212 | anonymous |         18 | **********  | *******  |      | pull      | 2020-11-13 15:19:21.290987
```

So I'd like to create a cronjob resource to manage the postgres records.
Thanks for the advice :)

**Comment by ywk253100** [comment]
@khrd Sorry for the misunderstanding. The log you said is the access/audit log.
For OSS Harbor the log rotate is for the application logs not the access/audit log.

Currently, there is no rotate for the access/audit log for Harbor installed by both docker-compose and helm chart, but this requirement is already in our planning, see https://github.com/goharbor/harbor/issues/13523 for more detail.

Let's use https://github.com/goharbor/harbor/issues/13523 to track the requirement, and I'm closing this one. Thanks
