### ISSUE TITLE
error: a container name must be specified for pod harbor-set-release-harbor-registry-655bf59586-44w28, choose one of: [registry registryctl]

### ISSUE THREAD

**Issue by gaokechen** [goharbor/harbor-helm#793]
### The registry uses the default configuration, find error: a container name must be specified for pod harbor-set-release-harbor-registry-655bf59586-44w28, choose one of: [registry registryctl] 
![image](https://user-images.githubusercontent.com/32739652/99355688-bab45600-28e3-11eb-9c2d-8feb34bef9cf.png)

### I tried to modify the registerctl name in the registry-dpl.yaml file to registry, and a duplicate name error occurred
![image](https://user-images.githubusercontent.com/32739652/99355882-0e26a400-28e4-11eb-8296-efd20ca4c1b6.png)

![image](https://user-images.githubusercontent.com/32739652/99355413-32ce4c00-28e3-11eb-9267-0c2d460b1e4c.png)

**Comment by ywk253100** [comment]
Check the option `--container`

**Comment by fshadid96** [comment]
@gaokechen were you able to figure this out? 

@ywk253100  what do you mean by the --container option
