### ISSUE TITLE
Can't add internal repository

### ISSUE THREAD

**Issue by itsecforu** [goharbor/harbor-helm#798]
Hello!

Seems like i got DNS problem with adding repo.

`2020-11-20T08:49:08Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://ip-address/docker: Get "https://ip/v2/": dial tcp: lookup : no such host
`
![harbor1](https://user-images.githubusercontent.com/38696837/99947092-7f54d400-2d88-11eb-9833-688c6823e646.png)

So which configmap do I need to edit and how to add /etc/hosts?

I cant get root access into pods and cant edit configs manually :-(

**Comment by itsecforu** [comment]
anybody? :-(

**Comment by ywk253100** [comment]
Please refer to the guide here https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/ to add host alias

**Comment by itsecforu** [comment]
> Please refer to the guide here https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/ to add host alias

thx but anyway doesnt work

**Comment by itsecforu** [comment]
I added host_aliases to deplyments Core and Registry, but it still doesnt work :-(

**Comment by itsecforu** [comment]
no ideas? :-(
