### ISSUE TITLE
Question: upgrade path from 1.3.2/1.10.2

### ISSUE THREAD

**Issue by cebidhem** [goharbor/harbor-helm#816]
Hey there,

We are running Harbor `1.10.2` with the harbor-helm `1.3.2`, and I wonder what should be the upgrade path to go to the latest.
Should we do `1.3.2` -> `1.4.0`, then `1.4.0` -> `1.5.2` ? Or can we go directly from `1.3.2` to `1.5.2` ?

The other question is about Harbor itself. I mean we'll backup our PostgreSQL db first, but does the upgrade with the chart will do the necessary updates in db introduced by harbor `2.0.0` or is there something we should do outside of the `helm upgrade` ?

Thanks for your help !

**Comment by reasonerjt** [comment]
`harbor-core` will handle the schema migration of `harbor-db`

The `--override` was not tested in this path, but if you make sure the values.yaml in new version carries all the values in the old one correctly, the upgrade should work.

But make sure you backup your data before you do the upgrade.
