### ISSUE TITLE
redis password is in ConfigMap as part of URL

### ISSUE THREAD

**Issue by chulkilee** [goharbor/harbor-helm#824]
This helm chart puts the redis URL several places (see the below) in ConfigMap. If a config may include any credentials, it would be better to use Secret, not ConfigMap.

Examples:

https://github.com/goharbor/harbor-helm/blob/v1.5.2/templates/jobservice/jobservice-cm.yaml#L21

https://github.com/goharbor/harbor-helm/blob/v1.5.2/templates/core/core-cm.yaml#L42

**Comment by reasonerjt** [comment]
Are you suggesting we store the config.yml in a secret?

**Comment by PKizzle** [comment]
That sounds like a good solution. Another alternative is to dynamically load the redis credentials from environment variables and patch the yaml files on startup.

**Comment by nbjohnson** [comment]
Any update on this? I would like to see harbor secure the redis password and not leak it in some configmaps to improve the security posture

**Comment by muralisankar32** [comment]
any update on this issue.. having redis password in the configmap is a security issue.
