### ISSUE TITLE
failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts

### ISSUE THREAD

**Issue by prudhvigodithi** [goharbor/harbor-helm#833]
Hello, I'm using harbor installed with helm chart version: 1.5.3, appVersion: 2.1.3.
The core pod logs continuously throw the following error 

`2021-01-12T22:27:24Z [WARNING] [/server/middleware/security/idtoken.go:45][requestID="002e1311-8905-4761-b52b-40b97b27c1b8"]: failed to verify token: oidc: malformed jwt: square/go-jose: compact JWS format must have three parts`

Tested docker login, image push, and help charts upload, everything works fine, do we have to worry about this warning message? or is related to any unverified acces_token using an external oidc provider?

Similar issue:
https://github.com/goharbor/harbor/issues/12261

**Comment by reasonerjt** [comment]
You can ignore that because the code always try to parse the ID token when Harbor is configured to authenticate via OIDC provider.  I think it will be mitigated in v2.2.  Need to double check.

**Comment by reasonerjt** [comment]
I believe this has been fixed by commit:
https://github.com/goharbor/harbor/commit/2dd499bacf56a8358de39db61fb9b8b3282a7a5a

Closing
