### ISSUE TITLE
Question: any way to discover and import all running charts in the K8S cluster?

### ISSUE THREAD

**Issue by strus38** [goharbor/harbor-helm#837]
Hi

It seems that you can only updload 'local' charts into Harbor. Is there any feature coming to automatically detect running charts in a K8S cluster and import them in Harbor automatically?

**Comment by ywk253100** [comment]
@strus38 Could you open an issue on Harbor repository https://github.com/goharbor/harbor as this repository only tracks the issues of harbor chart related?
BTW, you can add your requirement on https://github.com/goharbor/harbor/discussions, we are collecting the requirement for the next release
