### ISSUE TITLE
blob upload unknown

### ISSUE THREAD

**Issue by apannwitz** [goharbor/harbor-helm#839]
Hi,

I have installed latest harbor via helm (1.5.3) on a bare metal kubernetes cluster (3 master, 3 worker nodes). Eventhough I put a "registry.relativeurls=true" as helm parameter, I get from time to time an error "blob upload unknown" when pushing images to Harbor. This is how I installed harbor:

helm install harbor harbor/harbor -n harbor \
--create-namespace --namespace harbor \
--set externalURL=https://harbor.XXX.net \
--set expose.ingress.hosts.core=harbor.XXX.net \
--set expose.ingress.hosts.notary=harbor-notary.XXX.net \
--set expose.ingress.annotations."kubernetes\.io/ingress\.class"=private  \
--set expose.tls.certSource=secret \
--set expose.tls.secret.secretName=wildcard-XXX-net \
--set expose.tls.secret.notarySecretName=wildcard-XXX-net \
--set persistence.persistentVolumeClaim.registry.existingClaim=harbor-pv-claim-registry \
--set persistence.persistentVolumeClaim.jobservice.existingClaim=harbor-pv-claim-jobs   \
--set persistence.persistentVolumeClaim.chartmuseum.existingClaim=harbor-pv-claim-chartmuseum \
--set persistence.persistentVolumeClaim.database.existingClaim=harbor-pv-claim-database \
--set persistence.persistentVolumeClaim.redis.existingClaim=harbor-pv-claim-redis \
--set persistence.persistentVolumeClaim.trivy.existingClaim=harbor-pv-claim-trivy \
--set portal.replicas=3 \
--set core.replicas=3 \
--set jobservice.replicas=3 \
--set registry.replicas=3 \
--set registry.relativeurls=true \
--set chartmuseum.replicas=3 \
--set notary.server.replicas=3 \
--set notary.signer.replicas=3 \
--set metrics.enabled=true

Can anyone help me?

**Comment by apannwitz** [comment]
Noone any clue?

**Comment by ywk253100** [comment]
The `blob upload unknown` error comes from docker client? Is there any error log in the harbor components, such as `core` and `registry`?

**Comment by apannwitz** [comment]
Hi Wenkai Yin,
yes "blob upload unknow" occures from docker client. In "core" I get the following (maybe) interesting entries:

2021-01-28T16:53:23Z [ERROR] [/controller/event/handler/internal/artifact.go:96]: scan artifact library/bla@sha256:863f574c25f9f163d6caee0186ef7a94e53a9ce70dc6c9888576c621fdb6fc0e failed, error: a previous scan process is Running

2021-01-28T16:55:32Z [WARNING] [/core/systeminfo/imagestorage/filesystem/driver.go:51]: The path /data is not found, will return zero value of capacity

And in "registry" I have also errors with "blob unknown to registry"

time="2021-01-28T18:00:58.806550906Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code="404 unknown" err.detail=sha256:0fbb7ca63f43534ce8a63256b2116dcbed3b3499c27fa0213877db180feb9465 err.message="blob unknown to registry" go.version=go1.14.13 http.request.host=harbor-staging.XXX.net http.request.id=911aded5-c05d-43f2-ba85-cb57b368ba0c http.request.method=HEAD http.request.remoteaddr=10.244.4.0 http.request.uri="/v2/AAA/BBB/test5/nginx-data-api-staging/blobs/sha256:0fbb7ca63f43534ce8a63256b2116dcbed3b3499c27fa0213877db180feb9465" http.request.useragent="docker/19.03.13 go/go1.13.15 git-commit/4484c46d9d kernel/4.15.0-132-generic os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.14 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=128.445929ms http.response.status=404 http.response.written=157 vars.digest="sha256:0fbb7ca63f43534ce8a63256b2116dcbed3b3499c27fa0213877db180feb9465" vars.name="AAA/BBB/test5/nginx-data-api-staging"

**Comment by Goend** [comment]
me too ,
![image](https://user-images.githubusercontent.com/40394339/115704450-f9bc6b00-a39d-11eb-86f8-cc5d308fc9d8.png)

**Comment by Goend** [comment]
![image](https://user-images.githubusercontent.com/40394339/115704521-0ccf3b00-a39e-11eb-9ff9-3120295828d4.png)

**Comment by Goend** [comment]
![image](https://user-images.githubusercontent.com/40394339/115712580-861f5b80-a3a7-11eb-9bae-32e8e4635e9c.png)
,this is the permission status on container,and i login in,but cant's push image,i use the hostpath as the volume

**Comment by Goend** [comment]
nse.written=0
this is log

**Comment by Goend** [comment]
[22/Apr/2021:12:31:16 +0000] "POST /v2/aaaa/test/xx/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/19.03.13 go/go1.13.15 git-commit/4484c46d9d kernel/4.19.104-microsoft-standard os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.12 \\(linux\\))"
time="2021-04-22T12:31:16.533386205Z" level=info msg="response completed" go.version=go1.15.6 http.request.host=reg.changhong.com http.request.id=7c3b13d1-3197-46f5-9ce7-720e843b5449 http.request.method=POST http.request.remoteaddr=10.9.38.0 http.request.uri="/v2/aaaa/test/xx/blobs/uploads/" http.request.useragent="docker/19.03.13 go/go1.13.15 git-commit/4484c46d9d kernel/4.19.104-microsoft-standard os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.12 \(linux\))" http.response.duration=367.171282ms http.response.status=202 http.response.written=0
 this is log
