### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by lijialin-code** [goharbor/harbor-helm#841]
我在1.18版本的K8S集群部署harbor
但是在harbor容器部署的节点上拉取镜像有时候会出现超时问题，其他节点都是正常的，登录也会超时 报错如下
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry.ciecdev.com/v2/: net/http: TLS handshake timeout

**Comment by ywk253100** [comment]
Seems it's more related with the environment, could you try to debug the TLS handshake process with network tools to find out the root cause?
