### ISSUE TITLE
Harbor Stateful Components (Registry, Chartmuseum, Jobservice) should be moved to StatefulSets

### ISSUE THREAD

**Issue by DandyDeveloper** [goharbor/harbor-helm#843]
Right now, automation surrounding deployments of Harbor is a real pain because whenever an upgrade is performed against a persistent component (ChartMuseum, Jobservice or Registry) the components are stuck in a state of `ContainerCreating` because Kubernetes will not release the resource currently consuming the PV. 

```
harbor-harbor-chartmuseum-774fcbc4f-vrmhn      0/1     ContainerCreating   0          12m
harbor-harbor-chartmuseum-784dcd5bc8-ksjhg     1/1     Running             0          8d
harbor-harbor-jobservice-7db668d464-dx22k      0/1     ContainerCreating   0          12m
harbor-harbor-jobservice-8cb5c786d-2hvqb       1/1     Running             0          8d
harbor-harbor-registry-66d65bd8b-flhf9         0/2     ContainerCreating   0          12m
harbor-harbor-registry-8496dc979b-6rc2j        2/2     Running             0          8d
```

We should move the following component to `StatefulSets` so that they will appropriately support rolling updates during helm upgrades:

**Comment by DandyDeveloper** [comment]
One huge issue I see is retention of existing data should this update be done. I'm looking into making a PR for this.

**Comment by ywk253100** [comment]
Please refer to https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L330

**Comment by DandyDeveloper** [comment]
@ywk253100 That has literally nothing to do with the problem I am having and the suggestion I am making.

**Comment by DandyDeveloper** [comment]
We discussed in Slack and whilst I don't fully agree, there's a simple enough workaround already described in the chart for this scenario.

**Comment by Sajith-Kulathupara-Tjx** [comment]
@ywk253100 , @DandyDeveloper : I'm not able to get around with this issue unless I manually delete the running pod. How did you fix this using helm?

**Comment by sajithvasu** [comment]
@DandyDeveloper @ywk253100 : How did you fix this issue using helm? I cannot find any way unless I delete the pod manually
I'm using version 2.3.1
