### ISSUE TITLE
Kubernetes interrupts database migrations

### ISSUE THREAD

**Issue by cjnosal** [goharbor/harbor-helm#846]
When a new Harbor version includes a database schema migration, the core pod will not report as `ready` while the migration is running. Kubernetes will then restart the core pod, interrupting the migration. This causes harbor to mark the database schema as dirty in `schema_migrations` table, which prevents the restarted core pod from completing the migration without manual intervention.

My current manual workaround for upgrading with a schema change is:
1) scale `core` and `jobservice` (depends on core) replicas to 0
2) `helm upgrade` to update the deployments
3) use `kubectl edit` to remove the liveness/readiness probes from core's deployment spec, and scale to 1 replica
4) wait for db migration to complete (which sometimes includes data migrations where time correlates to db size)
5) `helm upgrade` to restore the core probes and desired core/jobservice replica counts

If schema migrations could be done in a way that doesn't cause kubernetes to interfere, these manual steps wouldn't be required. 

Kubernetes `Jobs` and `init containers` could be used to allow the migration to complete without flagging a pod as unhealthy https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-7-running-database-migrations/#using-kubernetes-jobs-and-init-containers

**Comment by ywk253100** [comment]
Set the `core.startupProbe.initialDelaySeconds` with a reasonable value to avoid `core` being killed by k8s: https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L414

Currently the database migration and core service are in the same process, if we can split them into two separated process, we may consider to use the `Job` or `init container` to do the work

**Comment by xtreme-conor-nosal** [comment]
For some migrations the time is proportional to the database size, and not known before we attempt the upgrade (e.g. upgrading from 1.x to 2.x the migration took over an hour), and making `initialDelaySeconds` especially large means all `helm upgrades` will be needlessly delayed.

**Comment by mmiller1** [comment]
I think a predeploy hook Job that mimics the core service template almost exactly minus liveness / readiness, perhaps with a different entry point (maybe a bash script that constantly checks liveness and readiness, then issues a SIGTERM to it's child procs once it's up) so it exits immediately after a full start sequence would solve this. This predeploy hook would add a bit of time to every deployment, as you would be waiting for a core service pod to spin up and down, but that seems fair given how critical database migrations are.
