### ISSUE TITLE
How to set up harbor time zone？

### ISSUE THREAD

**Issue by liudaze** [goharbor/harbor-helm#85]
How to set up harbor time zone to Asia/Shanghai？
I tried to set it in env, but it not work. 
` env:
  - name: TZ
    value: Asia/Shanghai`

**Comment by Jamlee** [comment]
how to resolve it ?

**Comment by YeonSeoMom** [comment]
I have the same problem.

**Comment by hqq-get** [comment]
I have the same problem.
