### ISSUE TITLE
Internal Postgres Container goes into Recovery mode when pushing big images 

### ISSUE THREAD

**Issue by fshadid96** [goharbor/harbor-helm#850]
Hi, 

I deployed Harbor on an OpenShift cluster using Helm chart. When I push an image for the first time (1.3 GB sized image) the Postgress went into a recovery mode. However, it works fine if I try to push the same image again since it mounts from pushed layers. 

`[USER@SERVER ~]$ docker push myharbor.com/PROJECT/REPO/el7:test
The push refers to repository [myharbor.com/PROJECT/REPO/el7:]
18dcc2b3d6cf: Pushing [==================================================>]  594.8MB
a4adab029ac9: Pushed
fab6c812f0c0: Pushed
f24adad3de25: Pushed
638da6d6f6dd: Pushing [==================================================>]  594.2MB
ef214e811995: Pushed
b7c7a774a3de: Pushing [==========>                                        ]  193.1MB/926.3MB
407dd1c44d81: Pushing [==================================================>]  107.3MB
43a60ce3bbaa: Pushed
a011264bddfe: Pushed
6df9ce342ddf: Pushed
997e5e402196: Pushing [==================================================>]  33.28kB
5bfa93ca97e5: Pushing [==================================================>]  10.24kB
0d15e9de5906: Retrying in 2 seconds
9f6d56caba9c: Retrying in 3 seconds
e49421bb1456: Retrying in 3 seconds
9d5bf33c0bfe: Waiting
cc01e22d5d0f: Waiting
unauthorized: pq: the database system is in recovery mode: pq: the database system is in recovery mode

[USER@SERVER ~]$ docker push myharbor.com/PROJECT/REPO/el7:test
The push refers to repository [myharbor.com/PROJECT/REPO/el7]
18dcc2b3d6cf: Pushed
a4adab029ac9: Layer already exists
fab6c812f0c0: Layer already exists
f24adad3de25: Layer already exists
638da6d6f6dd: Pushed
ef214e811995: Layer already exists
b7c7a774a3de: Pushed
407dd1c44d81: Pushed
43a60ce3bbaa: Layer already exists
a011264bddfe: Layer already exists
6df9ce342ddf: Layer already exists
997e5e402196: Pushed
5bfa93ca97e5: Pushed
0d15e9de5906: Pushed
9f6d56caba9c: Pushed
e49421bb1456: Pushed
9d5bf33c0bfe: Pushed
cc01e22d5d0f: Pushed
test: digest: sha256:7a769af0082ff58b8578c0d9845596244bdbe29ad21d739a596549fafb2e2812 size: 4094
`

database pods logs 

`LOG:  database system was interrupted; last known up at 2021-02-02 16:34:27 UTC
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 2/AAAB1280
LOG:  invalid record length at 2/AAAC4608: wanted 24, got 0
LOG:  redo done at 2/AAAC45E0
LOG:  last completed transaction was at log time 2021-02-02 16:36:14.133382+00
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  server process (PID 436315) was terminated by signal 9: Killed
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process

DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
LOG:  all server processes terminated; reinitializing
FATAL:  the database system is in recovery mode
LOG:  database system was interrupted; last known up at 2021-02-02 16:36:52 UTC
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
FATAL:  the database system is in recovery mode
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 2/AAAC4678
LOG:  invalid record length at 2/AAAD7218: wanted 24, got 0
LOG:  redo done at 2/AAAD71F0
LOG:  last completed transaction was at log time 2021-02-02 16:37:08.061689+00
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
`

**Comment by ywk253100** [comment]
Seems the database process is killed by someone?
```
LOG: server process (PID 436315) was terminated by signal 9: Killed
```

Could you try to install the same on other non-openshift env? We havn't test the chart against openshift

**Comment by fshadid96** [comment]
I was able to fix this issue by increasing the resources limit on the database. It works on openshift very well so far from what I see.

**Comment by jsonbruce** [comment]
> I was able to fix this issue by increasing the resources limit on the database. It works on openshift very well so far from what I see.

Thanks! Solved by adding resource limits.

```
2021-09-03 07:20:57.008 UTC [1] LOG: server process (PID 391) exited with exit code 141
2021-09-03 07:20:57.008 UTC [1] LOG: terminating any other active server processes
2021-09-03 07:20:57.009 UTC [369] WARNING: terminating connection because of crash of another server process
2021-09-03 07:20:57.009 UTC [369] DETAIL: The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-09-03 07:20:57.009 UTC [369] HINT: In a moment you should be able to reconnect to the database and repeat your command.
2021-09-03 07:20:57.010 UTC [398] WARNING: terminating connection because of crash of another server process
2021-09-03 07:20:57.010 UTC [398] DETAIL: The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-09-03 07:20:57.010 UTC [398] HINT: In a moment you should be able to reconnect to the database and repeat your command.
2021-09-03 07:20:57.129 UTC [396] WARNING: terminating connection because of crash of another server process
2021-09-03 07:20:57.129 UTC [396] DETAIL: The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-09-03 07:20:57.129 UTC [396] HINT: In a moment you should be able to reconnect to the database and repeat your command.
2021-09-03 07:20:57.479 UTC [376] WARNING: terminating connection because of crash of another server process
2021-09-03 07:20:57.479 UTC [376] DETAIL: The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-09-03 07:20:57.479 UTC [376] HINT: In a moment you should be able to reconnect to the database and repeat your command.
2021-09-03 07:20:57.481 UTC [397] WARNING: terminating connection because of crash of another server process
2021-09-03 07:20:57.481 UTC [397] DETAIL: The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-09-03 07:20:57.481 UTC [397] HINT: In a moment you should be able to reconnect to the database and repeat your command.
2021-09-03 07:20:58.446 UTC [1] LOG: all server processes terminated; reinitializing
2021-09-03 07:20:58.495 UTC [399] LOG: database system was interrupted; last known up at 2021-09-03 07:20:45 UTC
2021-09-03 07:20:59.919 UTC [400] FATAL: the database system is in recovery mode
2021-09-03 07:21:05.410 UTC [399] LOG: database system was not properly shut down; automatic recovery in progress
2021-09-03 07:21:05.426 UTC [399] LOG: invalid record length at 0/17EBA98: wanted 24, got 0
2021-09-03 07:21:05.426 UTC [399] LOG: redo is not required
2021-09-03 07:21:05.479 UTC [411] FATAL: the database system is in recovery mode
```

**Comment by rgulden** [comment]
> I was able to fix this issue by increasing the resources limit on the database. It works on openshift very well so far from what I see.

How high did you increase the resource limit?

**Comment by pleymor** [comment]
Hi!

I got the same error with this conf on my db service (in docker-compose.yml):

```yaml
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 400M
        reservations:
          cpus: "0.5"
          memory: 400M
```

I doubled cpus and memory and it worked:

```yaml
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 800M
        reservations:
          cpus: "1"
          memory: 800M
```
