### ISSUE TITLE
[metrics] Prometheus & Grafana Integrations

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor-helm#858]
Can we add a metrics.serviceMonitor , metrics.prometheusRule , metrics.dashboard ?

I still didnt test the master chart, but this seems a reasonable inclusing for the v2.2.0 update

**Comment by ywk253100** [comment]
You can configure the metrics in harbor chart 1.6.0(OSS Harbor v2.2.0): https://github.com/goharbor/harbor-helm/blob/master/values.yaml#L735

**Comment by dioguerra** [comment]
This is not the same thing that i said...

**Comment by dioguerra** [comment]
I said, among others also, to include a CM for harbor visualization
Installed by CM

https://stackoverflow.com/questions/55830850/how-to-import-custom-dashboards-to-grafana-using-helm

**Comment by reasonerjt** [comment]
IMO, that is out of the scope of this repo.
