### ISSUE TITLE
Failed to delete images via GC function within HTTP proxy

### ISSUE THREAD

**Issue by rikust** [goharbor/harbor-helm#861]
Using Harbor deployed via Helm to a K8s cluster.

```
Helm chart version: 1.5.3
Helm version: 2.1.3
```

While using Harbor deployed via Helm chart to K8s Cluster and running within HTTP proxy that we have to save images to external Object Storage Service, and unable to delete the images & repositories via GC function.

After viewing the source code that we found out Helm Chart had some bugs causing the HTTP Proxy didn't work properly while we tried to delete the images.

**Comment by ywk253100** [comment]
The fix is merged into master by https://github.com/goharbor/harbor-helm/pull/885 already
