### ISSUE TITLE
REGISTRY_HTPASSWD var triggers warning

### ISSUE THREAD

**Issue by Patricol** [goharbor/harbor-helm#866]
`REGISTRY_HTPASSWD` seems to be used to add a secret to the registry pod as a file; but it is also noticed by the registry container; which warns `Ignoring unrecognized environment variable REGISTRY_HTPASSWD`; which is a rather concerning message if it makes you think auth isn't being setup.

Can the variable name be changed?

**Comment by reasonerjt** [comment]
Thanks for reporting, we probably can store the `REGISTRY_HTPASSWD` in a separate secret, such that it won't be set as env var by `envFrom` in the deployment.
