### ISSUE TITLE
runAsUser and fsGroup must be overridable for OpenShift

### ISSUE THREAD

**Issue by djjudas21** [goharbor/harbor-helm#874]
When installing this chart on OpenShift 4.6, every pod has errors like this, because OpenShift has very specific requirements about uids, which are allocated per project (namespace).

```
Error creating: pods "harbor-harbor-notary-server-66657c8bd5-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{10000}: 10000 is not an allowed group spec.containers[0].securityContext.runAsUser: Invalid value: 10000: must be in the ranges: [1000630000, 1000639999]]
```

Therefore every reference to `runAsUser` and `fsGroup` in this chart needs to be referenced in `values.yaml` so OpenShift admins can override these values for their environments. Keeping the currently-hardcoded values as defaults would be fine.

**Comment by djjudas21** [comment]
I am working on a PR for this

**Comment by ywk253100** [comment]
The `runAsUser` and `fsGroup` may not be changed currently as there are some hardcoded user/group for the folders when building the images

**Comment by djjudas21** [comment]
Thanks @ywk253100, indeed I discovered this after I used a different value for `runAsUser` and `fsGroup`. As a workaround, I applied this SCC to allow use of the hard-coded values:
```
oc adm policy add-scc-to-user anyuid system:serviceaccount:harbor:default
```
