### ISSUE TITLE
Default registry.credentials.htpasswd causes confusion

### ISSUE THREAD

**Issue by BobyMCbobs** [goharbor/harbor-helm#875]
The chart has a default value for _registry.credentials.htpasswd_, this makes logging into the registry either impossible or just difficult. If this value is commented out, it means that any user can login to perform registry actions.

**Comment by ywk253100** [comment]
The item is configurable for security reason, users should override this item in production env.
Any suggestion to make it less confusion?

**Comment by BobyMCbobs** [comment]
> The item is configurable for security reason, users should override this item in production env.
> Any suggestion to make it less confusion?

@ywk253100, thanks for the reply.
I would suggest not having this field set in the default _values.yaml_, otherwise the registry is unable to be used

**Comment by reasonerjt** [comment]
@BobyMCbobs 
```
otherwise the registry is unable to be used
```
Could you elaborate why it's unable to be used?

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs
> 
> ```
> otherwise the registry is unable to be used
> ```
> 
> Could you elaborate why it's unable to be used?

Since _registry.credentials.htpasswd_ is set, the registry is configured by default to require a username and password which are unknown
