### ISSUE TITLE
Typo in templates/jobservice/jobservice-dpl.yaml

### ISSUE THREAD

**Issue by FriesPascal** [goharbor/harbor-helm#878]
The template `templates/jobservice/jobservice-dpl.yaml` has a typo in field `.spec.template.spec.volumes.[name = job-logs]`. The conditional refers to `.Values.jobservice.jobLogger` instead of `.Values.jobservice.jobLoggers`, which will always return false. As a result, with the default `values.yaml`, a PVC will be created for the Jobservice but not bound to. Easily fixed by adding an 's'.

**Comment by reasonerjt** [comment]
This should have been fixed by #870 #877

**Comment by fshadid96** [comment]
I am not sure what you suggested above actually work I am still running into the same issue 

`
jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.2.0
  replicas: 1
  # set the service account to be used, default if left empty
  serviceAccountName: ""
  maxJobWorkers: 10
  # The logger for jobs: "file", "database" or "stdout"
  jobLogger:
    - file
    # - database
    #- stdout
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}
  # Secret is used when job service communicates with other components.
  # If a secret key is not specified, Helm will generate one.
  # Must be a string of 16 chars.
  secret: ""
`


`Error: UPGRADE FAILED: template: harbor/templates/jobservice/jobservice-dpl.yaml:113:48: executing "harbor/templates/jobservice/jobservice-dpl.yaml" at <has "file" .Values.jobservice.jobLogger>: error calling has: Cannot find has on type string
`
