### ISSUE TITLE
harbor login stuck on the login page using chart 1.5.2 1.5.3 and 1.6.0

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor-helm#880]
After helm3 install, login on the harbor page stays on the login page.  
If the password is typed wrong, the login page would warn, but when the username/password is correct, it would simply stay there, with the login button disabled.  To get the button activated, we need to reload the page and fill in the id and password.
This is tested usign chrome, edge, and firefox.  

In chrome, the developer tool consol would display the following after clicking the LOG IN button:
`main.34cee70ac3f8ba62b6a9.js:1 GET https://harbor.va.avaya.com/api/v2.0/users/current 401`

When using chart 1.5.2, occasionally it would be ok. the 'admin' user and the its default password is used.

The above was observed on TKG 1.2 provisioned kubernetes cluster on vSphere.  Using nginx ingress while Contour is also installed.

**Comment by reasonerjt** [comment]
I would suggest you reach out to TKG developer via internal channel in vmw slack for help.

Please be kindly reminded this repo is for OSS chart, not vmw product integration.
