### ISSUE TITLE
Configure registries and projects from values.yaml

### ISSUE THREAD

**Issue by BobyMCbobs** [goharbor/harbor-helm#884]
I intend to use Harbor as proxy cache but need declarative configuration for sections such as:
- registries
- projects
- users

is this or can this be possible with the Helm chart?

**Comment by hh** [comment]
Conversation in slack as well: https://cloud-native.slack.com/archives/CC1E09J6S/p1615152094159700

@BobyMCbobs  and I are working up a prototype to provide a cross-cloud solution for the kubernetes community to distribute our container images and artifacts.

Currently k8s.gcr.io hosts most of the world`s k8s image downloads (from google) rather than a possibly local mirror or cache (ideally hosted by their provider).

**Comment by hh** [comment]
> What specific geolocation/redirection and other features might help us champion Harbor over other solutions?

Part of what we need is a chart or declarative way to deploy harbor.

> One idea is to setup registry.k8s.io or similar pointing to harbor instances around the world on various providers, populating and caching from our existing gcs buckets underlying gcr.io.

Ideally we could update the chart to configure the upstream registries, projects, users etc.

**Comment by hh** [comment]
Clarity from @reasonerjt https://cloud-native.slack.com/archives/CC1E09J6S/p1615171897164000?thread_ts=1615154063.163300&cid=CC1E09J6S :

> You have to create data objects via API after Harbor is up, currently there’s no plan to support declarative data population.

Some thought will need to go into how to use inject any registry, project, or user config via the API.

**Comment by dims** [comment]
cc @steven-zou  @wy65701436

**Comment by reasonerjt** [comment]
Thanks @hh  

For your requirement,  you can write a program to deploy Harbor and call the API after it is ready.
IMO we want to keep the scope of the chart to the deployment of a Harbor.

**Comment by matt-roz** [comment]
Can anyone point me into a direction where we can setup projects, users, project-members either via the `values.yaml` in the helm-chart or afterwards via CRDs?

**Comment by alexsorkin** [comment]
The proper implementation would be using operator, deploying the Harbor managed resources via Custom Resource definitions...
e.g: 
apiVersion: harbor.goharbor.com/v1alpha1
kind: UpstreamRepostory
spec:
  prefix: foo
  upstreamUrl: <foo.com>
  credential: <secretName>

or/and
apiVersion: harbor.goharbor.com/v1alpha1
kind: Project
spec:
  name: <bar>
  upstreamPrefixes:
  - "foo"

...etc..
