### ISSUE TITLE
It can't delete the chart whois version like '1.1.1-156982111-1614747412345'

### ISSUE THREAD

**Issue by bainilybi** [goharbor/harbor-helm#888]
If my chart version like 1.1.1-156982111-1614747412345
I can upload the chart to harbor.
But if I delete it, the chart record is still in the project.

**Comment by reasonerjt** [comment]
This repo is specifically for the Harbor helm chart, if this is not related to the chart itself, please open an issue in repo: goharbor/harbor

**Comment by bainilybi** [comment]
Thanks!
