### ISSUE TITLE
Trivy support ignore-policy

### ISSUE THREAD

**Issue by pja-kit** [goharbor/harbor-helm#890]
Would it be possible to enable support for supplying OPA vuln filter in the Trivy STS: https://github.com/aquasecurity/trivy#filter-the-vulnerabilities-by-open-policy-agent-policy

This could be implemented either by, specific parameters for ignore-policy like: trivy.vulnType or it could be implemented like making it possible for users to supply extra parameters and volumes/mounts to the trivy STS

**Comment by reasonerjt** [comment]
Thanks @pja-kit let's revisit it when it's supported on the trivy adapter?
