### ISSUE TITLE
Chart can't pass lint

### ISSUE THREAD

**Issue by KeepMasterBranch** [goharbor/harbor-helm#896]
I'm pretty sure this issue will be ignored as [nobody care about community here](https://github.com/goharbor/community/issues/132#issuecomment-699867397
) . I could fix this issue, but as all pull requests are ignored, it's a waste of time to contribute to harbor... so feel free to act as usual and ignore this issue

```
[ERROR] harbor/templates/jobservice/jobservice-dpl.yaml:113:48: executing "harbor/templates/jobservice/jobservice-dpl.yaml" at <has "file" .Values.jobservice.jobLogger>: error calling has: Cannot find has on type string
```

**Comment by reasonerjt** [comment]
@KeepMasterBranch 
Thanks for reporting, I think this has been fixed by #877 and #870 

Sorry for having been inactive, we try to go through the issues/PRs regularly.
