### ISSUE TITLE
internalTLS broken in 1.6.0 due to missing exporter template

### ISSUE THREAD

**Issue by bbockelm** [goharbor/harbor-helm#909]
The new exporter component for 1.6.0 breaks the use of `internalTLS` because of a reference to a template (`harbor.internalTLS.exporter.secretName`) that does not exist:

https://github.com/goharbor/harbor-helm/blob/v1.6.0/templates/exporter/exporter-dpl.yaml#L74

It looks like some copy/paste was missing?

**Comment by hasonhai** [comment]
This issue affected 1.6.1 also
