### ISSUE TITLE
Harbor DB has wrong permissions

### ISSUE THREAD

**Issue by tibers** [goharbor/harbor-helm#910]
May be related to https://github.com/goharbor/harbor-helm/issues/899
Definitely related to https://github.com/goharbor/harbor-helm/issues/444

The harbor DB is crashing out with a constant stream of:
```
2021-03-23 09:46:15.327 EDTFATAL: data directory "/var/lib/postgresql/data/pgdata" has group or world access
Error
2021-03-23 09:46:15.328 EDTDETAIL: Permissions should be u=rwx (0700).
```

**Comment by johann8384** [comment]
This seems to happen intermittently on our systems. If I uninstall and re-install it will be fine, but if I make changes it will fail. Sometimes it will fail on the initial install as well.

**Comment by tibers** [comment]
> This seems to happen intermittently on our systems. If I uninstall and re-install it will be fine, but if I make changes it will fail. Sometimes it will fail on the initial install as well.

That mirrors my experience. I've been playing with it and I can't get it to happen every time, but it does happen. 

I *thought* it might be something like GKE is saying the storage is ready but the storage isn't really ready, and so the initpod starts, makes the permissions changes, terminates, but those aren't actually applied to the storage. However I can't get it to happen reliably so I don't feel confident in writing a fix.

**Comment by ywk253100** [comment]
@tibers @johann8384 For the permission issue of database in Harbor chart 1.6.0, please refer to https://github.com/goharbor/harbor-helm/issues/876

Please upgrade your deployment to 1.6.1 once it releases

**Comment by tibers** [comment]
OK will reopen if this persists. Thanks!
