### ISSUE TITLE
External and Internal TLS Certs Expiration

### ISSUE THREAD

**Issue by fshadid96** [goharbor/harbor-helm#912]
Hello, 

I am working on deploying Harbor 2.2 (Helm chart 2.2) on Openshift 4.6

For external certs, we would like to use our letsencrypt certs, we store them in the router pod in the ingress-controller project. Harbor should pick them up from there as long as "expose.tls.certSource" is set to "none" right? 

Also, do the internal TLS certs generated by the chart ever expire? if they do, does the chart handle generating new certs/ rotation?

**Comment by ywk253100** [comment]
For the external certs, yes, it is
For the internal TLS certs, chart doesn't handle the expiration
