### ISSUE TITLE
cant docker login and push images

### ISSUE THREAD

**Issue by nicklv** [goharbor/harbor-helm#92]
![image](https://user-images.githubusercontent.com/5789960/48964688-29f25a80-efe8-11e8-9758-7d3700786565.png)
![image](https://user-images.githubusercontent.com/5789960/48964694-34acef80-efe8-11e8-916c-7bd5f664ed47.png)
it shows Error response from daemon: Get https://harbor.dev.com/v2/: unable to decode token response: invalid character '<' looking for beginning of value
int the pushing images logs,it show the same tips:
![image](https://user-images.githubusercontent.com/5789960/48964742-2c08e900-efe9-11e8-8eb4-d82250e03178.png)

**Comment by ywk253100** [comment]
Closing as inactivity, feel free to reopen it.
