### ISSUE TITLE
Login Credentials (default or from config) are not valid

### ISSUE THREAD

**Issue by tibeer** [goharbor/harbor-helm#925]
Hi there,

it seems that the login credentials for the helm chart are not working. The deployments come up flawless and i can open the harbor portal. But every username / password combination i enter is incorrect. Even the default ones (admin/Harbor12345) are not accepted. I run microk8s with dns and ingress enabled and did a clean install with `helm install harbor harbor/harbor` just to verify it. Has someone an idea what the issue is?

Kind regards

**Comment by ywk253100** [comment]
Could you open the debug console of your browser and check what's the response of the login API?

**Comment by tibeer** [comment]
Thanks for coming back to me. In the meanwhile i figured out, that the ingress from microk8s is the issue. I switched over to a different kubernetes edge distribution with nginx as an ingress controller.
