### ISSUE TITLE
Configuration for default login and password should be documented.

### ISSUE THREAD

**Issue by mianos** [goharbor/harbor-helm#926]
Maybe it is somewhere, I can't see but it seems over 20 of the 100 most recent issues are "installed with helm, can't log in".
I never got logged in with an exposed clusterIP so went back to the low end registry:2 again.
If someone can point me to a document, that would be great.

**Comment by ywk253100** [comment]
For the login issue, you should make sure all harbor pods are running as expected first.
After that, open your browser debug console and check the response of the login API and the logs of `core` pod
