### ISSUE TITLE
ldap bug in v2.2.1:  system auth_mode isn't ldap_auth

### ISSUE THREAD

**Issue by httaotao** [goharbor/harbor-helm#930]
I knew there were a issue [#14351](https://github.com/goharbor/harbor/pull/14351) ,but I found the problem is still in v2.2.1 .

when I change the Auth mode into LDAP, I couldn't test without saving. if I test ldap server without saving, there are some error showing :

```
2021-04-16T09:22:45Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"system auth_mode isn't ldap_auth, please check configuration"}]} 
```

**Comment by stonezdj** [comment]
yes, this issue fixed in 2.3.0 with PR: https://github.com/goharbor/harbor/pull/14351
