### ISSUE TITLE
S3 SSE key ID is hardcoded to aws:kms

### ISSUE THREAD

**Issue by luthar64** [goharbor/harbor-helm#931]
Reference: https://github.com/goharbor/harbor-helm/blob/80f97cf60b4efa47c06718f98616e699a364e321/templates/chartmuseum/chartmuseum-cm.yaml#L76

even though the helm chart allows parameter "storage.s3.keyid", it does not actually change the STORAGE_AMAZON_SSE configuration in `chartmuseum-cm.yaml`.

**Comment by failytaler** [comment]
We need encryption and would like this to be fixed..

**Comment by rogfut** [comment]
+1 for s3 encryption for chart museum
