### ISSUE TITLE
Not having the upstream version on clair delays bug reporting

### ISSUE THREAD

**Issue by wu105** [goharbor/harbor-helm#933]
This would be true for all the harbor components whose upstream versions are unknown when an obvious issue is suspected.  See https://github.com/goharbor/harbor/issues/14720 for example.

**Comment by reasonerjt** [comment]
It's in the `Makefile` :
https://github.com/goharbor/harbor/blob/release-2.0.0/Makefile#L102

I have opened another issue in Harbor repo to suggest we document the version s in releaese note:
https://github.com/goharbor/harbor/issues/14937
