### ISSUE TITLE
Default Helm Chart Storage Avail/Usage?

### ISSUE THREAD

**Issue by DanPhonovation** [goharbor/harbor-helm#937]
From a basic install of this helm chart, harbor seems to be reporting 16 GB used and a limit of 26 GB.

I'm confused 1) where it's getting 26GB from and 2) what 16GB is used on by default?

The chart says 5Gi for persistence.registry claims, I'm confused how much storage is actually available to me and therefore, what I need to change in the helm chart to get my desirable size.

Sorry if this is noob.

**Comment by ywk253100** [comment]
The storage statistic for Harbor chart deployment isn't accurate.
It only works for the Harbor instance that using local file to store images and deployed with docker-compose.

For other types of storage, there isn't an easy way for Harbor to get the storage information

**Comment by DanPhonovation** [comment]
How does one ascertain storage capacity (and if you're running out of it) - if there is no easy way to tell that?
