### ISSUE TITLE
values.yaml中commonName 应该配置什么 

### ISSUE THREAD

**Issue by JulyYin** [goharbor/harbor-helm#94]
Error: render error in "harbor/templates/nginx/secret.yaml": template: harbor/templates/nginx/secret.yaml:3:13: executing "harbor/templates/nginx/secret.yaml" at <genSignedCert .Value...>: error calling genSignedCert: error parsing ip: 
values.yaml中commonName 应该配置什么

**Comment by JulyYin** [comment]
![image](https://user-images.githubusercontent.com/8434933/49133837-7a392780-f31c-11e8-89b1-8067ea325c4d.png)

**Comment by ywk253100** [comment]
The `commonName` should be the IP of one of k8s nodes if you expose the service via `NodePort`. 
The size of `secretKey` should be 16.

**Comment by JulyYin** [comment]
Thanks
