### ISSUE TITLE
Frequent timeouts when using with ingress-nginx on AWS

### ISSUE THREAD

**Issue by austinorth** [goharbor/harbor-helm#945]
### Overview
I am currently hosting Harbor using this Helm chart for use with a CI system, and able to push and pull images most of the time; however, we are experiencing frequent timeout issues. The issues occur when we have pushed a test image to Harbor and then have k8s pull that image from Harbor for testing. Kubernetes itself fails to pull the image, and generates one of the following errors (IP redacted):
```
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
and
```
Get https://harbor.example.com/v2/library/myapp/manifests/6339603.b54: dial tcp [AWSloadbalancerIPaddress]:443: i/o timeout
```
So far I have tried the following to resolve:
- Running two replicas of each Harbor pod for HA
- Placing all Harbor pods on the same node
- Placing an ingress-nginx pod on the same node as Harbor
- Adding the following ingress-nginx annotations to Harbor ingress:
```
ingress.kubernetes.io/ssl-redirect: "true"
ingress.kubernetes.io/proxy-body-size: "0" 
kubernetes.io/ingress.class: nginx-internal
nginx.ingress.kubernetes.io/proxy-body-size: "0" 
nginx.ingress.kubernetes.io/proxy-buffering: "off"
nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
nginx.ingress.kubernetes.io/ssl-redirect: "true"
nginx.ingress.kubernetes.io/configuration-snippet: |
  proxy_set_header X-Forwarded-Proto $scheme;
```
None of this seems to have made any difference, and I am now considering hosting Harbor using `docker-compose` instead of this Helm chart because of this issue. But I would love to solve this so we can just host it in k8s like everything else. Below are additional details about the environment I'm running this in.

### Environment Details
**Harbor Image Version:** 2.2.1
**Harbor Chart Version:** 1.6.1
**Cloud:** AWS
**Kubernetes version:** 1.19.9
**Network:** weave-net
**ingress-nginx version:** 0.44.0 w/ NLB
**DNS:** NodeLocal DNS
**kube-proxy mode:** ipvs
**CI:** Jenkins w/ Kubernetes plugin
**Using Route53 for Harbor DNS address**

I will be working on hosting Harbor with `docker-compose` and also possibly trying to host it in a cluster without `ipvs` and NodeLocalDNS to see if those make any difference, but curious if anyone else has run into them and, if so, how you were able to mitigate them? Thanks!

**Comment by austinorth** [comment]
I set up a simple EC2 instance running Harbor with `docker-compose`, and we have not encountered any timeout errors since switching over to it, so I think we'll be running with that until I can find a way to run Harbor on k8s without timeouts. I am definitely interested in whether or not other folks have run into this error, though, and what you did to resolve it, so will leave issue open! Also, if anyone has had success hosting using alternative ingress solutions, would definitely be open to trying something like Istio or maybe even just simply hosting via NodePort.

**Comment by reasonerjt** [comment]
We have been using nginx ingress on k8s on bare-metal, and have not encountered such timeout.

So this happens particularly when you use nginx ingress controller on AWS? 
How do you setup the k8s and what's the version of ingress controller?

**Comment by austinorth** [comment]
@reasonerjt ingress-nginx is version `0.44.0`, installed using Helm chart version `3.25.0`. And yeah have not experienced this issue in other environments. I set up the cluster with kOps, and it's running on `m5.xlarge` instances. ingress-nginx is using an AWS NLB with proxy protocol v2 and cross-zone loadbalancing enabled, and we're able to access everything else that we have deployed with ingresses on the cluster without timeout issues.

**Comment by djcass44** [comment]
I'm having the same problem! I'm glad I'm not going insane.

Harbor version: 2.3.1
Kubernetes version: EKS 1.21 provisioned with Terraform running on `c4.2xlarge` nodes
Ingress NGINX: 0.49.0 w/ VPC-internal NLB

It seems to be totally random but it's crippling my CI/CD. I've tried every possible combination of settings for the NLB, NGINX and Kubernetes but nothing has fixed it.

I've noticed that it seems to happen more frequently when Kubernetes is pulling the image from Harbor on the same cluster. Could it potentially be a CNI problem? I've tried a number of different CNI configurations (both the `aws-vpc-cni` and others) but I'm running out of ideas.

**Comment by austinorth** [comment]
@djcass44 I'm running weave-net, rather than CNI networking, so might not be a CNI problem. One thing I've been meaning to try after reading [this](https://mrkaran.dev/posts/ndots-kubernetes/) is having the CI jobs connect with a FQDN, because I think it might be trying to search the local cluster DNS zones before traffic actually resolves to the Route53 record associated with Harbor. We've fully migrated away from running Harbor in k8s at this point, but if you still have that environment up and wouldn't mind giving FQDNs a shot, would definitely be interested in whether or not that improves performance!

**Comment by djcass44** [comment]
I had a chat with the EKS team via AWS Support and they revealed that this strange network behaviour can be caused by the way NLBs route traffic. Disabling "Client IP preservation" was the key recommendation and it has appeared to fix most of my problems. I am going to keep monitoring to be certain that this fixes it.

For reference, the documentation that AWS shared with me: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#loopback-timeout
