### ISSUE TITLE
helm upgrade: core Pod needs to be restarted before jobservice Pod on core Secret update

### ISSUE THREAD

**Issue by br0ziliy** [goharbor/harbor-helm#947]
There's an issue with this chart: jobservice is using core `Secret` 
to authenticate against core; during `helm upgrade`, auth secrets (if not set statically in the values.yaml) are
regenerated every time, which triggers `Secret` resource to be recreated and core and jobservice pods restarted. It seems like the order of resources regeneration is following:

1. helm recreates core Pod
2. helm recreates core Secret (with updated "secret" value to authenticate to core)
3. helm recreates jobservice Pod

This causes jobservice to use new "secret" to authenticate to core, while core 
does not know that the "secret" was updated (because `Secret` update happens /after/ the
Pod is started already) - and jobservice fails to authenticate to core and does
not start, which eventually leads to failed helm update.

Deleting core Pod while `helm update` is still running (so that core picks up 
new Secret / updated "secret" value) helps to finish update successfully.

**Comment by br0ziliy** [comment]
Setting static `.core.secret` in values.yaml helps with helm upgrades.

This behaviour either needs to be clarified in the docs/values.yaml file comments, or the chart fixed - though I'm not quite expert in Helm and not sure if it can actually be fixed on the chart level without breaking existing setups.

**Comment by reasonerjt** [comment]
core and jobservice both depends on the secret, os IMO the secret should be recreated first?  If it does not work this way it seems a bug in helm to me.

**Comment by br0ziliy** [comment]
The Secret gets recreated, the issue is that it seems it gets recreated /after/ core Pod is running already, and before jobservice is started. As far as I can tell, there's nothing in core Pod that re-reads the new Secret, thus jobservice is using new secret value, while core expect old one.

**Comment by reasonerjt** [comment]
I did see this issue once when I ran `helm upgrade` 

The notary -server pod reports erorr messages like:
```
{"level":"info","msg":"Using postgres backend","time":"2021-06-07T08:23:24Z"}
2021/06/07 08:23:24 Failed to dial harbor-test-harbor-notary-signer:7899: connection error: desc = "transport: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"harbor-notary-ca\")"; please retry.
{"level":"info","msg":"Starting Server","time":"2021-06-07T08:23:24Z"}
{"level":"info","msg":"Starting on :4443","time":"2021-06-07T08:23:24Z"}
{"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"harbor-notary-ca\\\")\"","time":"2021-06-07T08:23:34Z"}
{"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"harbor-notary-ca\\\")\"","time":"2021-06-07T08:23:44Z"}
{"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"harbor-notary-ca\\\")\"","time":"2021-06-07T08:23:54Z"}
{"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"harbor-notary-ca\\\")\"","time":"2021-06-07T08:24:04Z"}
```
Normally I would generate the secret, and reference it in the values.yaml.  
To fix the problem in your case maybe we can dynamicly generate a new secret name for the certificates each time the secret is created.
