### ISSUE TITLE
Harbor DB has wrong permissions

### ISSUE THREAD

**Issue by xiaozhi747** [goharbor/harbor-helm#958]
My harbor-helm version is 1.6.2, and the database pod startup log is as follows:
`Data page checksums are disabled.  `
`initdb: could not access directory "/var/lib/postgresql/data/pgdata": Permission denied`

data-permissions-ensurer init pod start log is as follows:
`chmod: changing permissions of '/var/lib/postgresql/data/pgdata': Operation not permitted`

ps: I upgraded from 1.6.1, it also has this problem, but I see that the issue means it has been resolved  #910

**Comment by maxisam** [comment]
I have the same issue. Why do you close it? Do you fix it?
