### ISSUE TITLE
Metrics port not exposed in core deployment

### ISSUE THREAD

**Issue by heww** [goharbor/harbor-helm#959]
When the metrics enabled in the core, the metrics port not exposed in its deployment.

https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-dpl.yaml#L97-L98

**Comment by steffenb91** [comment]
an ingress rule is also missing, pointing to the port the metrics get exposed to? for me, metrics are not available. i just enabled them in the values.yaml (the other configuration options are set to defaults).

**Comment by hrr888** [comment]
It is added to service https://github.com/goharbor/harbor-helm/blob/32e0df98a4718f074fc4fe3d39a89fc34c46defe/templates/core/core-svc.yaml#L15, so it must be added to pod.

**Comment by zyyw** [comment]
it's by design to use service monitor to fetch metrics data.
