### ISSUE TITLE
Pushing the image to Harbor failed. Docker Login failed

### ISSUE THREAD

**Issue by isFxh** [goharbor/harbor-helm#964]
I created a Harbor private project, and now I want to push my locally made image to the Harbor private repository. I have the following problem:
`Username: admin
Password:
Error response from daemon: Get https://localhost:30003/v2/: Get https://core.harbor.domain/service/token? account=admin&client_id=docker&offline_token=true&service=harbor-registry: Service Unavailable`
I checked Ingress, but there is no Ingress created
![image](https://user-images.githubusercontent.com/58544359/120877944-ce0ee080-c5eb-11eb-97ae-c6f7f3b5af27.png)

```shell
docker login core.harbor.domain # The following error occurs when using this command
```
Username: admin
Password: 
Error response from daemon: Get https://core.harbor.domain/v2/: Service Unavailable

**Comment by ywk253100** [comment]
Seems you didn't set the `externalURL`?
