### ISSUE TITLE
adjust log rotate

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor-helm#967]
Hi,

can we adjust log rotate config in helm chart?

I think this should be in v2.3.0 helm chart.

**Comment by ywk253100** [comment]
What does the `log rotate config` refer to?
The log isn't collected by any Harbor components when deploying with helm chart

**Comment by Hokwang** [comment]
@ywk253100 sorry for this,
then how to do log rotate when deploying with helm chart? 
could you let me know?

**Comment by LinAnt** [comment]
Depends on how you have deployed your kubernetes cluster, and not on the application itself.

https://www.magalix.com/blog/kubernetes-logging-101
