### ISSUE TITLE
Ingress version issue when deploying with ArgoCD

### ISSUE THREAD

**Issue by pburgisser** [goharbor/harbor-helm#970]
When deploying Harbor using ArgoCD on k8s cluster running version 1.18.0, the ingresses fail to be created as it doesn't understand `networking.k8s.io/v1`.

Troubleshooting shows that the `.Capabilities.KubeVersion.GitVersion` [1] always return 1.20.0 as ArgoCD doesn't know what k8s version is below.

[1] https://github.com/goharbor/harbor-helm/blob/81fb1ee3b804e94b63d3c32da60677d604172f8b/templates/ingress/ingress.yaml#L31-L37

**Comment by ywk253100** [comment]
Seems that it is more likely a bug/limitation of ArgoCD?

**Comment by pburgisser** [comment]
I think both :)

I'm trying to get more information from ArgoCD and see if I can enrich this issue.
