### ISSUE TITLE
[feature request] support configuring registry replication endpoints thru helm values

### ISSUE THREAD

**Issue by abdennour** [goharbor/harbor-helm#976]
As per the documentation(https://goharbor.io/docs/1.10/administration/configuring-replication/create-replication-endpoints/), we can replicate the images from a non Harbor repository.

Currently there are following options for provider:

- Alibaba ACR
- Artifact Hub
- Aws ECR
- Azure ACR
- Docker Hub
- Docker Registry
- DTR
- Github GHCR
- Gitlab
- Google GCR
- Harbor
- Helm Hub
- Huawei SWR
- JFrog Artifactory
- Quay
- Tencent TCR
- Docker Registry (in general for others like Nexus .. so on)

That would be great if `.Values.replicationEndpoints` can be supported

**Comment by ywk253100** [comment]
The configuration of Harbor chart is only used for the management of Harbor lifecycle. 
You should call the API to populate the replication endpoints data
