### ISSUE TITLE
Who has encountered this problem：error: a container name must be specified for pod harbor-harbor-registry-db5b54b56-kz9m7, choose one of: [registry registryctl]

### ISSUE THREAD

**Issue by luckydog85** [goharbor/harbor-helm#983]
error: a container name must be specified for pod harbor-harbor-registry-db5b54b56-kz9m7, choose one of: [registry registryctl]

![image](https://user-images.githubusercontent.com/10277372/123064499-e763b980-d440-11eb-8e14-0c33e5d3d1e0.png)
![image](https://user-images.githubusercontent.com/10277372/123064571-fa768980-d440-11eb-8ec5-d559449e28d3.png)

**Comment by ywk253100** [comment]
You should use the `-c` option to specify the container as the error said
