### ISSUE TITLE
Both nginx:s brake on clusters with IPv6 disabled

### ISSUE THREAD

**Issue by LinAnt** [goharbor/harbor-helm#985]
```
2021/06/24 11:10:15 [emerg] 1#0: socket() [::]:8443 failed (97: Unknown error)
nginx: [emerg] socket() [::]:8443 failed (97: Unknown error)
```

I suggest we add a bool for IPv6 support with the default being true.

I can shoot away a PR after work :+1:

**Comment by ninjadq** [comment]
are you set up Harbor on an IPv6-only env?

**Comment by LinAnt** [comment]
We have some workers with IPv6 disabled. That means if the nginx pod spawns on one of them workers it will fail to start up.

I started working on deprecating those machines in favor of machines with IPv6 Support

**Comment by heww** [comment]
Let's reopen this issue, we may need to fix this problem in the portal image.

**Comment by bitsf** [comment]
Is only portal imaged be affected? Is that mean it is some limitation of nginx?

**Comment by LinAnt** [comment]
It is not the images, the issue is in the configuration on the node. If you disable IPv6 on your node, nginx will not be able to listen on IPv6.

**Comment by alexeyatbluescape** [comment]
This issue is also preventing the use of this amazing chart in environments where IPv6 is disabled due to security requirements.
All that is needed is a flag to disable nginx IPv6 support that will not render `listen [::]:8080;` in nginx config files.

Is that a reasonable ask?

**Comment by danielbjornadal** [comment]
The helm chart have an option to disable ipv6, but it looks like it is not working. We experience the same error.

```
ipFamily:
  ipv6:
    enabled: false
```

**ipFamily.ipv6.enabled**
if ipv6 is enabled in cluster, all ipv6 related configs will set correspondly, but currently it only affected the nginx related components ｜ true

**Comment by alexeyatbluescape** [comment]
I think this was added 3 days ago: https://github.com/goharbor/harbor-helm/commit/089c923bf40e03c62e5ddf43c083a96894bb7266
Which is great! Have to test it out.

**Comment by alexeyatbluescape** [comment]
@danielbjornadal Looks like it's not published yet. We might have to wait for next release, its definitely not in 1.7.1

**Comment by aadrii** [comment]
Hi,
We are facing the same problem on our ipv4 only clusters...

Any idea of when the next release wiil be published ?

Thanks

**Comment by fredgate** [comment]
Warning: there is a typo in the configmap for nginx portal :
https://github.com/goharbor/harbor-helm/blob/master/templates/portal/configmap.yaml#L25

I created this pull request to fix it : https://github.com/goharbor/harbor-helm/pull/1061
