### ISSUE TITLE
Harbor DB fails to start due to file permissions after initial run

### ISSUE THREAD

**Issue by ryan-a-baker** [goharbor/harbor-helm#993]
I'm deploying a fresh instance of Harbor using the 1.7.0 version of the helm chart.  Everything works perfectly on initial deploy.  However, if you delete the PG13 database pod - it fails to restart due to file permissions:

```
NAME         	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
harbor          	default  	1       	2021-06-29 15:49:43.431721 -0500 CDT	deployed	harbor-1.7.0        	2.3.0
```

```
~ k logs -f harbor-harbor-database-0
no need to upgrade postgres, launch it.
2021-06-30 14:00:19.368 UTC [1] FATAL:  data directory "/var/lib/postgresql/data/pgdata/pg13" has invalid permissions
2021-06-30 14:00:19.368 UTC [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```

I was able to get it to start again by changing the chmod command on the init container from:

```
      - args:
        - -c
        - chmod 700 /var/lib/postgresql/data/pgdata || true
```

to

```
      - args:
        - -c
        - chmod 700 /var/lib/postgresql/data/pgdata/pg13 || true
```

I've never seen this before.  I wonder if it was introduced with pg13?  If I get time - I'll use a PG12 container and see if the path changed at all.

**Comment by alexremn** [comment]
The issue here is that there is missing -R (recursive) arg in the chmod command. Though, it chmod's only top-level folder, not recursively others.
Would prepare PR for this one.

**Comment by alexremn** [comment]
Done. Here is a PR: https://github.com/goharbor/harbor-helm/pull/996

**Comment by brtknr** [comment]
Same here

**Comment by brtknr** [comment]
> Done. Here is a PR: #996

Can confirm that this fix works.
